/-
Generated by validate.py.  Do not edit by hand.

This file recompiles the exact declaration bodies of the four checkpoint
modules and issues one #print axioms command for every source theorem or
lemma.  Recompilation in one file keeps private source names addressable.
-/
import IUTThreeClosures.AffineCatalogueWeightOverlap20260901
import IUTThreeClosures.IntegralOrderDecompositionObstruction
import IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901
import IUTThreeClosures.PellLucasAllOrderStaircase20260901
import IUTThreeClosures.PellOddKernelThirdOrderPacket20260901

/- BEGIN EXACT BODY: IUTThreeClosures/AffineSignedRayCanonicalCaps20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/

/-!
# Signed affine ray capacities and canonical arm energy

The mathematical proofs precede this module in
`research/ABC_AFFINE_SIGNED_RAY_CANONICAL_CAPS_2026_09_01.md`.

This file retains the strict large-label inequality in the ray-period
ledger.  It proves the linear capture squeeze, the signed non-arm cap, exact
capture and linear capacity on all three primitive arm-level directions, and
the optimal global conversion from shifted to unshifted cubic energy.  It
assumes no density theorem and proves no abc statement.
-/

namespace IUTThreeClosures
namespace AffineSignedRayCanonicalCaps20260901

open scoped BigOperators
open AffineTemplateEntropy20260901
open AffineAdaptiveCommonKernel20260901
open AffineCommonKernelTripleSelection20260901
open AffineCollinearPeriodEnergy20260901

/-! ## The exact period/span ledger -/

/-- Removing the first occurrence from an exact residue-class capacity
retains the complete period factor. -/
theorem shiftedCard_mul_period_le
    {card H T : ℕ} (hcard : card ≤ H / T + 1) :
    (card - 1) * T ≤ H := by
  have ha : card - 1 ≤ H / T := by
    apply Nat.sub_le_iff_le_add.mpr
    simpa [add_comm] using hcard
  calc
    (card - 1) * T ≤ (H / T) * T := Nat.mul_le_mul_right T ha
    _ ≤ H := Nat.div_mul_le_self H T

/-- The strict large-label inequality converts period capacity into a linear
bound by the direction capture.  This is the lossless arithmetic core of all
four signed direction branches. -/
theorem shiftedCard_mul_ambient_mul_scale_lt_capture
    {card H T capture D N L : ℕ}
    (hT : 0 < T)
    (hcard : card ≤ H / T + 1)
    (hspan : H * L ≤ N)
    (hfactor : T * capture = D)
    (hlarge : N ^ 2 < D) :
    (card - 1) * N * L < capture := by
  let a := card - 1
  have haT : a * T ≤ H := shiftedCard_mul_period_le hcard
  have haTL : a * T * L ≤ N :=
    (Nat.mul_le_mul_right L haT).trans hspan
  have hraw : T * (a * N * L) < T * capture := by
    calc
      T * (a * N * L) = (a * T * L) * N := by ring
      _ ≤ N * N := Nat.mul_le_mul_right N haTL
      _ = N ^ 2 := by ring
      _ < D := hlarge
      _ = T * capture := hfactor.symm
  exact (Nat.mul_lt_mul_left hT).mp hraw

/-- A period-weighted square consequence of the same exact ledger. -/
theorem shiftedCard_square_mul_period_scaleSq_lt_capture
    {card H T capture D N L : ℕ}
    (hT : 0 < T)
    (hcard : card ≤ H / T + 1)
    (hspan : H * L ≤ N)
    (hfactor : T * capture = D)
    (hlarge : N ^ 2 < D) :
    (card - 1) ^ 2 * T * L ^ 2 < capture := by
  let a := card - 1
  have haT : a * T ≤ H := shiftedCard_mul_period_le hcard
  have haTL : a * T * L ≤ N :=
    (Nat.mul_le_mul_right L haT).trans hspan
  have hlin := shiftedCard_mul_ambient_mul_scale_lt_capture
    hT hcard hspan hfactor hlarge
  change a ^ 2 * T * L ^ 2 < capture
  calc
    a ^ 2 * T * L ^ 2 = (a * T * L) * (a * L) := by ring
    _ ≤ N * (a * L) := Nat.mul_le_mul_right (a * L) haTL
    _ = a * N * L := by ring
    _ < capture := by simpa [a] using hlin

/-- A supplementary quadratic capture bound normalizes the square estimate
to one period factor.  This premise is distinct from the cubic non-arm
coefficient bound. -/
theorem shiftedCard_square_mul_period_lt_of_capture_le_quadratic
    {card H T capture D N L K : ℕ}
    (hT : 0 < T) (hL : 0 < L)
    (hcard : card ≤ H / T + 1)
    (hspan : H * L ≤ N)
    (hfactor : T * capture = D)
    (hlarge : N ^ 2 < D)
    (hcapture : capture ≤ K * L ^ 2) :
    (card - 1) ^ 2 * T < K := by
  have hsq := shiftedCard_square_mul_period_scaleSq_lt_capture
    hT hcard hspan hfactor hlarge
  have hchain : ((card - 1) ^ 2 * T) * L ^ 2 < K * L ^ 2 := by
    calc
      ((card - 1) ^ 2 * T) * L ^ 2 =
          (card - 1) ^ 2 * T * L ^ 2 := by ring
      _ < capture := hsq
      _ ≤ K * L ^ 2 := hcapture
  exact (Nat.mul_lt_mul_right (pow_pos hL 2)).mp hchain

/-- The period-squared shifted cubic cap, still retaining the exact capture. -/
theorem shiftedCard_cube_mul_periodSq_scaleCube_lt_capture_mul_ambient
    {card H T capture D N L : ℕ}
    (hT : 0 < T) (hN : 0 < N) (hL : 0 < L)
    (hcard : card ≤ H / T + 1)
    (hspan : H * L ≤ N)
    (hfactor : T * capture = D)
    (hlarge : N ^ 2 < D) :
    (card - 1) ^ 3 * T ^ 2 * L ^ 3 < capture * N := by
  let a := card - 1
  have haT : a * T ≤ H := shiftedCard_mul_period_le hcard
  have haTL : a * T * L ≤ N :=
    (Nat.mul_le_mul_right L haT).trans hspan
  have hsq := shiftedCard_square_mul_period_scaleSq_lt_capture
    hT hcard hspan hfactor hlarge
  by_cases ha : a = 0
  · change a ^ 3 * T ^ 2 * L ^ 3 < capture * N
    rw [ha]
    simp only [zero_pow (by norm_num : 3 ≠ 0), zero_mul]
    have hcap : 0 < capture := by
      by_contra hz
      have : capture = 0 := Nat.eq_zero_of_not_pos hz
      rw [this, mul_zero] at hfactor
      omega
    exact mul_pos hcap hN
  · have hapos : 0 < a := Nat.pos_of_ne_zero ha
    have hmultPos : 0 < a * T * L := mul_pos (mul_pos hapos hT) hL
    have hmul : (a * T * L) * (a ^ 2 * T * L ^ 2) <
        (a * T * L) * capture :=
      (Nat.mul_lt_mul_left hmultPos).2 (by simpa [a] using hsq)
    calc
      a ^ 3 * T ^ 2 * L ^ 3 =
          (a * T * L) * (a ^ 2 * T * L ^ 2) := by ring
      _ < (a * T * L) * capture := hmul
      _ ≤ N * capture := Nat.mul_le_mul_right capture haTL
      _ = capture * N := by ring

/-- The exact physical period cube. -/
theorem shiftedCard_physicalPeriod_cube_lt_labelProduct_mul_ambient
    {card H T capture D N L : ℕ}
    (hT : 0 < T) (hN : 0 < N) (hL : 0 < L)
    (hcard : card ≤ H / T + 1)
    (hspan : H * L ≤ N)
    (hfactor : T * capture = D)
    (hlarge : N ^ 2 < D) :
    ((card - 1) * T * L) ^ 3 < D * N := by
  have hcubic := shiftedCard_cube_mul_periodSq_scaleCube_lt_capture_mul_ambient
    hT hN hL hcard hspan hfactor hlarge
  have hmul : T * ((card - 1) ^ 3 * T ^ 2 * L ^ 3) <
      T * (capture * N) := (Nat.mul_lt_mul_left hT).2 hcubic
  calc
    ((card - 1) * T * L) ^ 3 =
        T * ((card - 1) ^ 3 * T ^ 2 * L ^ 3) := by ring
    _ < T * (capture * N) := hmul
    _ = D * N := by rw [← hfactor]; ring

/-! ## Signed non-arm directions -/

/-- Sup scale of a signed primitive direction. -/
def signedDirectionScale (s t : ℤ) : ℕ := max s.natAbs t.natAbs

/-- Absolute product of the three affine direction coefficients. -/
def signedDirectionProduct (B C : ℕ) (s t : ℤ) : ℕ :=
  s.natAbs * (s + (C : ℤ) * t).natAbs *
    (s + (B : ℤ) * t).natAbs

/-- Direction capture with arbitrary signed coefficients. -/
def signedDirectionCapture (label : ArmDivisorLabel)
    (B C : ℕ) (s t : ℤ) : ℕ :=
  directionCapture label s.natAbs
    (s + (C : ℤ) * t).natAbs
    (s + (B : ℤ) * t).natAbs

/-- Product of the three reduced periods for arbitrary signed direction
coefficients. -/
def signedDirectionPeriod (label : ArmDivisorLabel)
    (B C : ℕ) (s t : ℤ) : ℕ :=
  directionPeriod label s.natAbs
    (s + (C : ℤ) * t).natAbs
    (s + (B : ℤ) * t).natAbs

theorem signedDirectionPeriod_pos
    {label : ArmDivisorLabel} {B C : ℕ} {s t : ℤ}
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w) :
    0 < signedDirectionPeriod label B C s t :=
  directionPeriod_pos hu hv hw

/-- Exact signed factorization into reduced period and captured part. -/
theorem signedDirectionPeriod_mul_capture
    (label : ArmDivisorLabel) (B C : ℕ) (s t : ℤ) :
    signedDirectionPeriod label B C s t *
      signedDirectionCapture label B C s t = label.product :=
  directionPeriod_mul_capture label _ _ _

/-- Signed component divisibilities and pairwise coprimality make the product
of the three reduced periods divide the index gap. -/
theorem signedDirectionPeriod_dvd_gap
    {label : ArmDivisorLabel} {B C gap : ℕ} {s t : ℤ}
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (hpair : label.PairwiseCoprime)
    (hU : label.u ∣ gap * s.natAbs)
    (hV : label.v ∣ gap * (s + (C : ℤ) * t).natAbs)
    (hW : label.w ∣ gap * (s + (B : ℤ) * t).natAbs) :
    signedDirectionPeriod label B C s t ∣ gap :=
  directionPeriod_dvd_gap hu hv hw hpair hU hV hW

/-- Convert an integer signed direction divisibility into the natural
absolute-coefficient form used by `signedDirectionPeriod_dvd_gap`. -/
theorem nat_dvd_gap_mul_natAbs_of_intCast_dvd
    {d gap : ℕ} {A : ℤ} (h : (d : ℤ) ∣ (gap : ℤ) * A) :
    d ∣ gap * A.natAbs := by
  have habs : Int.natAbs (d : ℤ) ∣ Int.natAbs ((gap : ℤ) * A) :=
    Int.natAbs_dvd_natAbs.mpr h
  simpa [Int.natAbs_mul] using habs

/-- Two actual affine occurrences whose coordinate difference is an integer
multiple of a signed direction have index gap divisible by the exact signed
direction period. -/
theorem actualSignedLine_directionPeriod_dvd_gap
    {R B C gap : ℕ} {p q : ℕ × ℕ} {s t : ℤ}
    {label : ArmDivisorLabel}
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (hpair : label.PairwiseCoprime)
    (hp : armDivisorsAt R B C p label.u label.v label.w)
    (hq : armDivisorsAt R B C q label.u label.v label.w)
    (hfirst : (p.1 : ℤ) - q.1 = (gap : ℤ) * s)
    (hsecond : (p.2 : ℤ) - q.2 = (gap : ℤ) * t) :
    signedDirectionPeriod label B C s t ∣ gap := by
  have hUR : Nat.Coprime label.u R :=
    Nat.Coprime.of_dvd hp.1 (dvd_refl R) (by simp [affineU])
  have hVR : Nat.Coprime label.v R :=
    Nat.Coprime.of_dvd hp.2.1 (dvd_refl R) (by simp [affineV])
  have hWR : Nat.Coprime label.w R :=
    Nat.Coprime.of_dvd hp.2.2 (dvd_refl R) (by simp [affineW])
  obtain ⟨hUint, hVint, hWint⟩ :=
    affineTemplate_membership_gives_differenceDivisibilities
      hUR hVR hWR hp.1 hq.1 hp.2.1 hq.2.1 hp.2.2 hq.2.2
  have hUint' : (label.u : ℤ) ∣ (gap : ℤ) * s := by
    simpa [hfirst] using hUint
  have hVint' : (label.v : ℤ) ∣
      (gap : ℤ) * (s + (C : ℤ) * t) := by
    rw [hfirst, hsecond] at hVint
    convert hVint using 1
    ring
  have hWint' : (label.w : ℤ) ∣
      (gap : ℤ) * (s + (B : ℤ) * t) := by
    rw [hfirst, hsecond] at hWint
    convert hWint using 1
    ring
  exact signedDirectionPeriod_dvd_gap hu hv hw hpair
    (nat_dvd_gap_mul_natAbs_of_intCast_dvd hUint')
    (nat_dvd_gap_mul_natAbs_of_intCast_dvd hVint')
    (nat_dvd_gap_mul_natAbs_of_intCast_dvd hWint')

/-- On the non-arm branch the capture is at most the exact absolute
coefficient product. -/
theorem signedDirectionCapture_le_product
    (label : ArmDivisorLabel) {B C : ℕ} {s t : ℤ}
    (hU : s ≠ 0)
    (hV : s + (C : ℤ) * t ≠ 0)
    (hW : s + (B : ℤ) * t ≠ 0) :
    signedDirectionCapture label B C s t ≤
      signedDirectionProduct B C s t := by
  have hgU : Nat.gcd label.u s.natAbs ≤ s.natAbs :=
    Nat.gcd_le_right _ (Int.natAbs_pos.mpr hU)
  have hgV : Nat.gcd label.v (s + (C : ℤ) * t).natAbs ≤
      (s + (C : ℤ) * t).natAbs :=
    Nat.gcd_le_right _ (Int.natAbs_pos.mpr hV)
  have hgW : Nat.gcd label.w (s + (B : ℤ) * t).natAbs ≤
      (s + (B : ℤ) * t).natAbs :=
    Nat.gcd_le_right _ (Int.natAbs_pos.mpr hW)
  exact Nat.mul_le_mul (Nat.mul_le_mul hgU hgV) hgW

/-- Sharp universal cubic coefficient bound for signed directions. -/
theorem signedDirectionProduct_le_sharp_cubic
    {B C : ℕ} (s t : ℤ) :
    signedDirectionProduct B C s t ≤
      (B + 1) * (C + 1) * signedDirectionScale s t ^ 3 := by
  have hU : s.natAbs ≤ signedDirectionScale s t := Nat.le_max_left _ _
  have hV : (s + (C : ℤ) * t).natAbs ≤
      (C + 1) * signedDirectionScale s t :=
    secondForm_natAbs_le s t
  have hW : (s + (B : ℤ) * t).natAbs ≤
      (B + 1) * signedDirectionScale s t :=
    secondForm_natAbs_le s t
  calc
    signedDirectionProduct B C s t ≤
        signedDirectionScale s t *
          ((C + 1) * signedDirectionScale s t) *
            ((B + 1) * signedDirectionScale s t) := by
      exact Nat.mul_le_mul (Nat.mul_le_mul hU hV) hW
    _ = (B + 1) * (C + 1) * signedDirectionScale s t ^ 3 := by ring

/-- The universal coefficient is attained by the primitive direction
`(1,1)`. -/
theorem signedDirectionProduct_one_one_is_sharp (B C : ℕ) :
    signedDirectionProduct B C 1 1 =
      (B + 1) * (C + 1) * signedDirectionScale 1 1 ^ 3 := by
  have hC : (1 + (C : ℤ)).natAbs = C + 1 := by
    rw [show (1 : ℤ) + (C : ℤ) = ((C + 1 : ℕ) : ℤ) by omega,
      Int.natAbs_natCast]
  have hB : (1 + (B : ℤ)).natAbs = B + 1 := by
    rw [show (1 : ℤ) + (B : ℤ) = ((B + 1 : ℕ) : ℤ) by omega,
      Int.natAbs_natCast]
  simp [signedDirectionProduct, signedDirectionScale, hB, hC]
  ring

/-- Direction scale is positive for a nonzero signed direction. -/
theorem signedDirectionScale_pos {s t : ℤ} (hdir : s ≠ 0 ∨ t ≠ 0) :
    0 < signedDirectionScale s t := by
  unfold signedDirectionScale
  rcases hdir with hs | ht
  · exact lt_of_lt_of_le (Int.natAbs_pos.mpr hs) (Nat.le_max_left _ _)
  · exact lt_of_lt_of_le (Int.natAbs_pos.mpr ht) (Nat.le_max_right _ _)

/-- Pure signed non-arm cap after the exact period capacity is supplied. -/
theorem signedNonarm_shifted_mul_ambient_scale_lt_product
    {card H T D N B C : ℕ} {s t : ℤ} (label : ArmDivisorLabel)
    (_hdir : s ≠ 0 ∨ t ≠ 0)
    (hU : s ≠ 0)
    (hV : s + (C : ℤ) * t ≠ 0)
    (hW : s + (B : ℤ) * t ≠ 0)
    (hT : 0 < T)
    (hcard : card ≤ H / T + 1)
    (hspan : H * signedDirectionScale s t ≤ N)
    (hfactor : T * signedDirectionCapture label B C s t = D)
    (hlarge : N ^ 2 < D) :
    (card - 1) * N * signedDirectionScale s t <
      signedDirectionProduct B C s t := by
  exact (shiftedCard_mul_ambient_mul_scale_lt_capture hT hcard hspan
    hfactor hlarge).trans_le
      (signedDirectionCapture_le_product label hU hV hW)

/-- Retaining the period gives an inverse-square-period cubic cap with the
sharp universal direction coefficient. -/
theorem signedNonarm_shiftedCube_mul_periodSq_lt
    {card H T D N B C : ℕ} {s t : ℤ} (label : ArmDivisorLabel)
    (hdir : s ≠ 0 ∨ t ≠ 0)
    (hU : s ≠ 0)
    (hV : s + (C : ℤ) * t ≠ 0)
    (hW : s + (B : ℤ) * t ≠ 0)
    (hT : 0 < T) (hN : 0 < N)
    (hcard : card ≤ H / T + 1)
    (hspan : H * signedDirectionScale s t ≤ N)
    (hfactor : T * signedDirectionCapture label B C s t = D)
    (hlarge : N ^ 2 < D) :
    (card - 1) ^ 3 * T ^ 2 < (B + 1) * (C + 1) * N := by
  let L := signedDirectionScale s t
  have hL : 0 < L := signedDirectionScale_pos hdir
  have hcubic := shiftedCard_cube_mul_periodSq_scaleCube_lt_capture_mul_ambient
    hT hN hL hcard hspan hfactor hlarge
  have hcap := (signedDirectionCapture_le_product label hU hV hW).trans
    (signedDirectionProduct_le_sharp_cubic (B := B) (C := C) s t)
  have hchain : (card - 1) ^ 3 * T ^ 2 * L ^ 3 <
      ((B + 1) * (C + 1) * N) * L ^ 3 := by
    calc
      (card - 1) ^ 3 * T ^ 2 * L ^ 3 <
          signedDirectionCapture label B C s t * N := hcubic
      _ ≤ ((B + 1) * (C + 1) * L ^ 3) * N :=
        Nat.mul_le_mul_right N hcap
      _ = ((B + 1) * (C + 1) * N) * L ^ 3 := by ring
  exact (Nat.mul_lt_mul_right (pow_pos hL 3)).mp (by
    simpa [mul_assoc] using hchain)

/-- Any direction below the square-root direction threshold supports no
second occurrence of a large non-arm label. -/
theorem signedNonarm_smallDirection_is_singleton
    {card H T D N B C : ℕ} {s t : ℤ} (label : ArmDivisorLabel)
    (hcardPos : 0 < card)
    (hdir : s ≠ 0 ∨ t ≠ 0)
    (hU : s ≠ 0)
    (hV : s + (C : ℤ) * t ≠ 0)
    (hW : s + (B : ℤ) * t ≠ 0)
    (hT : 0 < T)
    (hcard : card ≤ H / T + 1)
    (hspan : H * signedDirectionScale s t ≤ N)
    (hfactor : T * signedDirectionCapture label B C s t = D)
    (hlarge : N ^ 2 < D)
    (hsmall : (B + 1) * (C + 1) * signedDirectionScale s t ^ 2 ≤ N) :
    card = 1 := by
  let a := card - 1
  let L := signedDirectionScale s t
  have hL : 0 < L := signedDirectionScale_pos hdir
  have hlin := signedNonarm_shifted_mul_ambient_scale_lt_product label
    hdir hU hV hW hT hcard hspan hfactor hlarge
  have hprod := signedDirectionProduct_le_sharp_cubic (B := B) (C := C) s t
  by_contra hne
  have ha : 0 < a := by dsimp [a]; omega
  have hNL : N * L ≤ a * N * L := by
    calc
      N * L = 1 * N * L := by simp
      _ ≤ a * N * L := Nat.mul_le_mul_right L
        (Nat.mul_le_mul_right N (by omega))
  have hupper : (B + 1) * (C + 1) * L ^ 3 ≤ N * L := by
    calc
      (B + 1) * (C + 1) * L ^ 3 =
          ((B + 1) * (C + 1) * L ^ 2) * L := by ring
      _ ≤ N * L := Nat.mul_le_mul_right L hsmall
  have hlin' : a * N * L < signedDirectionProduct B C s t := by
    simpa [a, L] using hlin
  have hprod' : signedDirectionProduct B C s t ≤
      (B + 1) * (C + 1) * L ^ 3 := by
    simpa [L] using hprod
  have : N * L < N * L :=
    hNL.trans_lt (hlin'.trans_le (hprod'.trans hupper))
  exact (Nat.lt_irrefl _ this).elim

/-! ## Exact canonical arm captures -/

/-- Primitive vertical direction: the capture is exactly the constant
`U`-component under the canonical coefficient coprimalities. -/
theorem directionCapture_zeroU_eq
    (label : ArmDivisorLabel) {B C : ℕ}
    (hVC : Nat.Coprime label.v C) (hWB : Nat.Coprime label.w B) :
    directionCapture label 0 C B = label.u := by
  simp [directionCapture, hVC.gcd_eq_one, hWB.gcd_eq_one]

/-- Primitive `V`-level direction `(C,-1)` when `C-B=1`. -/
theorem directionCapture_zeroV_eq
    (label : ArmDivisorLabel) {C : ℕ}
    (hUC : Nat.Coprime label.u C) :
    directionCapture label C 0 1 = label.v := by
  simp [directionCapture, hUC.gcd_eq_one]

/-- Primitive `W`-level direction `(B,-1)` when `C-B=1`. -/
theorem directionCapture_zeroW_eq
    (label : ArmDivisorLabel) {B : ℕ}
    (hUB : Nat.Coprime label.u B) :
    directionCapture label B 1 0 = label.w := by
  simp [directionCapture, hUB.gcd_eq_one]

/-- Linear capacity on the primitive `U`-level direction. -/
theorem zeroU_shifted_mul_ambient_lt
    {card H N B C : ℕ} (label : ArmDivisorLabel)
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (hVC : Nat.Coprime label.v C) (hWB : Nat.Coprime label.w B)
    (hcard : card ≤ H / directionPeriod label 0 C B + 1)
    (hspan : H ≤ N)
    (hlarge : N ^ 2 < label.product) :
    (card - 1) * N < label.u := by
  let T := directionPeriod label 0 C B
  have hT : 0 < T := directionPeriod_pos hu hv hw
  have hfactor : T * label.u = label.product := by
    rw [← directionCapture_zeroU_eq label hVC hWB]
    exact directionPeriod_mul_capture label 0 C B
  have := shiftedCard_mul_ambient_mul_scale_lt_capture
    (card := card) (H := H) (T := T) (capture := label.u)
    (D := label.product) (N := N) (L := 1)
    hT (by simpa [T] using hcard) (by simpa using hspan) hfactor hlarge
  simpa using this

/-- Linear capacity on the primitive `V`-level direction. -/
theorem zeroV_shifted_mul_ambient_scale_lt
    {card H N C : ℕ} (label : ArmDivisorLabel)
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (_hC : 0 < C) (hUC : Nat.Coprime label.u C)
    (hcard : card ≤ H / directionPeriod label C 0 1 + 1)
    (hspan : H * C ≤ N)
    (hlarge : N ^ 2 < label.product) :
    (card - 1) * N * C < label.v := by
  let T := directionPeriod label C 0 1
  have hT : 0 < T := directionPeriod_pos hu hv hw
  have hfactor : T * label.v = label.product := by
    rw [← directionCapture_zeroV_eq label hUC]
    exact directionPeriod_mul_capture label C 0 1
  exact shiftedCard_mul_ambient_mul_scale_lt_capture
    hT (by simpa [T] using hcard) hspan hfactor hlarge

/-- Linear capacity on the primitive `W`-level direction. -/
theorem zeroW_shifted_mul_ambient_scale_lt
    {card H N B : ℕ} (label : ArmDivisorLabel)
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (_hB : 0 < B) (hUB : Nat.Coprime label.u B)
    (hcard : card ≤ H / directionPeriod label B 1 0 + 1)
    (hspan : H * B ≤ N)
    (hlarge : N ^ 2 < label.product) :
    (card - 1) * N * B < label.w := by
  let T := directionPeriod label B 1 0
  have hT : 0 < T := directionPeriod_pos hu hv hw
  have hfactor : T * label.w = label.product := by
    rw [← directionCapture_zeroW_eq label hUB]
    exact directionPeriod_mul_capture label B 1 0
  exact shiftedCard_mul_ambient_mul_scale_lt_capture
    hT (by simpa [T] using hcard) hspan hfactor hlarge

/-- Factor-three canonical specialization of the `U`-level cap. -/
theorem zeroU_three_mul_shifted_ambient_lt_power
    {card N c dU : ℕ}
    (hcap : (card - 1) * N < dU)
    (harm : 3 * dU ≤ c ^ 6) :
    3 * (card - 1) * N < c ^ 6 := by
  calc
    3 * (card - 1) * N = 3 * ((card - 1) * N) := by ring
    _ < 3 * dU := Nat.mul_lt_mul_left (by norm_num) |>.2 hcap
    _ ≤ c ^ 6 := harm

/-- Factor-three canonical specialization of the `V`-level cap. -/
theorem zeroV_three_mul_shifted_ambient_scale_lt_power
    {card N C c dV : ℕ}
    (hcap : (card - 1) * N * C < dV)
    (harm : 3 * dV ≤ c ^ 7) :
    3 * (card - 1) * N * C < c ^ 7 := by
  calc
    3 * (card - 1) * N * C = 3 * ((card - 1) * N * C) := by ring
    _ < 3 * dV := Nat.mul_lt_mul_left (by norm_num) |>.2 hcap
    _ ≤ c ^ 7 := harm

/-- Factor-three canonical specialization of the `W`-level cap. -/
theorem zeroW_three_mul_shifted_ambient_scale_lt_power
    {card N B c dW : ℕ}
    (hcap : (card - 1) * N * B < dW)
    (harm : 3 * dW ≤ c ^ 7) :
    3 * (card - 1) * N * B < c ^ 7 := by
  calc
    3 * (card - 1) * N * B = 3 * ((card - 1) * N * B) := by ring
    _ < 3 * dW := Nat.mul_lt_mul_left (by norm_num) |>.2 hcap
    _ ≤ c ^ 7 := harm

/-! ## Shifted energy to global energy -/

/-- Optimal singleton-plus-shifted cubic conversion. -/
theorem cube_le_one_add_seven_shiftedCube (n : ℕ) :
    n ^ 3 ≤ 1 + 7 * (n - 1) ^ 3 := by
  by_cases hn0 : n = 0
  · subst n
    norm_num
  by_cases hn1 : n = 1
  · subst n
    norm_num
  let a := n - 1
  have hna : n = a + 1 := by dsimp [a]; omega
  have ha : 0 < a := by dsimp [a]; omega
  obtain ⟨b, hb⟩ : ∃ b, a = b + 1 := Nat.exists_eq_succ_of_ne_zero (ne_of_gt ha)
  rw [hna]
  rw [hb]
  simp only [Nat.add_sub_cancel]
  have hid : 1 + 7 * (b + 1) ^ 3 =
      (b + 1 + 1) ^ 3 + 3 * (b + 1) * b * (2 * (b + 1) + 1) := by ring
  rw [hid]
  omega

/-- The coefficient seven is forced already at occupancy two. -/
theorem factorSix_singletonShift_counterexample :
    ¬ (2 ^ 3 ≤ 1 + 6 * (2 - 1) ^ 3) := by norm_num

/-- Global weighted large-label energy is its singleton catalogue baseline
plus at most seven times its shifted energy. -/
theorem weightedCubicEnergy_le_catalogue_add_sevenShifted
    {α : Type*} (s : Finset α) (weight count : α → ℕ) :
    ∑ i ∈ s, weight i * count i ^ 3 ≤
      (∑ i ∈ s, weight i) +
        7 * ∑ i ∈ s, weight i * (count i - 1) ^ 3 := by
  calc
    ∑ i ∈ s, weight i * count i ^ 3 ≤
        ∑ i ∈ s, weight i * (1 + 7 * (count i - 1) ^ 3) := by
      exact Finset.sum_le_sum fun i hi ↦
        Nat.mul_le_mul_left (weight i) (cube_le_one_add_seven_shiftedCube _)
    _ = (∑ i ∈ s, weight i) +
        7 * ∑ i ∈ s, weight i * (count i - 1) ^ 3 := by
      simp_rw [mul_add]
      simp only [mul_one, Finset.sum_add_distrib]
      rw [Finset.mul_sum]
      apply congrArg₂ (· + ·) rfl
      apply Finset.sum_congr rfl
      intro i _hi
      ring

/-- Label-specific shifted caps aggregate globally without a number-of-rays
factor. -/
theorem weightedCubicEnergy_le_catalogue_add_caps
    {α : Type*} (s : Finset α) (weight count cap : α → ℕ)
    (hcap : ∀ i ∈ s, (count i - 1) ^ 3 ≤ cap i) :
    ∑ i ∈ s, weight i * count i ^ 3 ≤
      (∑ i ∈ s, weight i) + 7 * ∑ i ∈ s, weight i * cap i := by
  refine (weightedCubicEnergy_le_catalogue_add_sevenShifted
    s weight count).trans ?_
  apply Nat.add_le_add_left
  apply Nat.mul_le_mul_left
  exact Finset.sum_le_sum fun i hi ↦
    Nat.mul_le_mul_left (weight i) (hcap i hi)

/-- A fixed arm scale converts the linear capture squeeze into a global
third-moment bound. -/
theorem weightedShiftedEnergy_mul_scaledAmbientCube_le_armMoment
    {α : Type*} (s : Finset α) (weight count arm : α → ℕ)
    {N L : ℕ}
    (hcap : ∀ i ∈ s, (count i - 1) * N * L < arm i) :
    (N * L) ^ 3 * ∑ i ∈ s, weight i * (count i - 1) ^ 3 ≤
      ∑ i ∈ s, weight i * arm i ^ 3 := by
  rw [Finset.mul_sum]
  apply Finset.sum_le_sum
  intro i hi
  have hp : ((count i - 1) * N * L) ^ 3 ≤ arm i ^ 3 :=
    Nat.pow_le_pow_left (Nat.le_of_lt (hcap i hi)) 3
  calc
    (N * L) ^ 3 * (weight i * (count i - 1) ^ 3) =
        weight i * (((count i - 1) * N * L) ^ 3) := by ring
    _ ≤ weight i * arm i ^ 3 := Nat.mul_le_mul_left (weight i) hp

/-- Abstract owner-catalogue third-moment bound.  Each distinct label is
assigned to exactly one containing catalogue; the per-owner weight budget
then controls the coordinate moment without any disjointness premise on the
original catalogues. -/
theorem weightedCoordinateMoment_le_ownerCatalogue
    {α κ : Type*} [DecidableEq κ]
    (labels : Finset α) (classes : Finset κ)
    (owner : α → κ) (weight coordinate : α → ℕ)
    (mass cap : κ → ℕ)
    (hmaps : ∀ i ∈ labels, owner i ∈ classes)
    (hcoordinate : ∀ i ∈ labels, coordinate i ≤ cap (owner i))
    (hmass : ∀ k ∈ classes,
      ∑ i ∈ labels.filter (fun i ↦ owner i = k), weight i ≤ mass k) :
    ∑ i ∈ labels, weight i * coordinate i ^ 3 ≤
      ∑ k ∈ classes, mass k * cap k ^ 3 := by
  classical
  have hdecomp :
      (∑ i ∈ labels, weight i * coordinate i ^ 3) =
        ∑ k ∈ classes,
          ∑ i ∈ labels.filter (fun i ↦ owner i = k),
            weight i * coordinate i ^ 3 := by
    calc
      (∑ i ∈ labels, weight i * coordinate i ^ 3) =
          ∑ i ∈ labels, ∑ k ∈ classes,
            if owner i = k then weight i * coordinate i ^ 3 else 0 := by
        apply Finset.sum_congr rfl
        intro i hi
        simp [hmaps i hi]
      _ = ∑ k ∈ classes, ∑ i ∈ labels,
            if owner i = k then weight i * coordinate i ^ 3 else 0 := by
        rw [Finset.sum_comm]
      _ = ∑ k ∈ classes,
          ∑ i ∈ labels.filter (fun i ↦ owner i = k),
            weight i * coordinate i ^ 3 := by
        apply Finset.sum_congr rfl
        intro k _hk
        simp [Finset.sum_filter]
  rw [hdecomp]
  apply Finset.sum_le_sum
  intro k hk
  calc
    (∑ i ∈ labels.filter (fun i ↦ owner i = k),
        weight i * coordinate i ^ 3) ≤
        ∑ i ∈ labels.filter (fun i ↦ owner i = k),
          weight i * cap k ^ 3 := by
      apply Finset.sum_le_sum
      intro i hi
      have hi' := Finset.mem_filter.mp hi
      have hcoord : coordinate i ≤ cap k := by
        simpa [hi'.2] using hcoordinate i hi'.1
      exact Nat.mul_le_mul_left (weight i)
        (Nat.pow_le_pow_left hcoord 3)
    _ = (∑ i ∈ labels.filter (fun i ↦ owner i = k), weight i) *
        cap k ^ 3 := by rw [Finset.sum_mul]
    _ ≤ mass k * cap k ^ 3 :=
      Nat.mul_le_mul_right (cap k ^ 3) (hmass k hk)

/-- Owner-catalogue moment bound with the coordinate condition stated in its
actual divisor form.  The per-owner totient mass budget is the exact Euler
catalogue identity supplied by the imported catalogue module. -/
theorem weightedCoordinateMoment_le_ownerCatalogue_of_dvd
    {α κ : Type*} [DecidableEq κ]
    (labels : Finset α) (classes : Finset κ)
    (owner : α → κ) (weight coordinate : α → ℕ)
    (mass cap : κ → ℕ)
    (hmaps : ∀ i ∈ labels, owner i ∈ classes)
    (hcapPos : ∀ k ∈ classes, 0 < cap k)
    (hcoordinateDvd : ∀ i ∈ labels, coordinate i ∣ cap (owner i))
    (hmass : ∀ k ∈ classes,
      ∑ i ∈ labels.filter (fun i ↦ owner i = k), weight i ≤ mass k) :
    ∑ i ∈ labels, weight i * coordinate i ^ 3 ≤
      ∑ k ∈ classes, mass k * cap k ^ 3 := by
  apply weightedCoordinateMoment_le_ownerCatalogue
    labels classes owner weight coordinate mass cap hmaps
  · intro i hi
    exact Nat.le_of_dvd (hcapPos (owner i) (hmaps i hi))
      (hcoordinateDvd i hi)
  · exact hmass

/-- The corresponding owner-catalogue baseline-weight bound. -/
theorem weightedCatalogue_le_ownerMass
    {α κ : Type*} [DecidableEq κ]
    (labels : Finset α) (classes : Finset κ)
    (owner : α → κ) (weight : α → ℕ) (mass : κ → ℕ)
    (hmaps : ∀ i ∈ labels, owner i ∈ classes)
    (hmass : ∀ k ∈ classes,
      ∑ i ∈ labels.filter (fun i ↦ owner i = k), weight i ≤ mass k) :
    ∑ i ∈ labels, weight i ≤ ∑ k ∈ classes, mass k := by
  classical
  have hdecomp : (∑ i ∈ labels, weight i) =
      ∑ k ∈ classes,
        ∑ i ∈ labels.filter (fun i ↦ owner i = k), weight i := by
    calc
      (∑ i ∈ labels, weight i) =
          ∑ i ∈ labels, ∑ k ∈ classes,
            if owner i = k then weight i else 0 := by
        apply Finset.sum_congr rfl
        intro i hi
        simp [hmaps i hi]
      _ = ∑ k ∈ classes, ∑ i ∈ labels,
            if owner i = k then weight i else 0 := by
        rw [Finset.sum_comm]
      _ = ∑ k ∈ classes,
          ∑ i ∈ labels.filter (fun i ↦ owner i = k), weight i := by
        apply Finset.sum_congr rfl
        intro k _hk
        simp [Finset.sum_filter]
  rw [hdecomp]
  exact Finset.sum_le_sum hmass

/-- Final finite assembly: an owner baseline and separate non-arm and arm
shifted charges control the complete unshifted cubic energy. -/
theorem weightedCubicEnergy_le_ownerMass_add_sevenCharges
    {α : Type*} (labels : Finset α) (weight count : α → ℕ)
    (ownerMass nonarmCharge armCharge : ℕ)
    (hbase : ∑ i ∈ labels, weight i ≤ ownerMass)
    (hshift : ∑ i ∈ labels, weight i * (count i - 1) ^ 3 ≤
      nonarmCharge + armCharge) :
    ∑ i ∈ labels, weight i * count i ^ 3 ≤
      ownerMass + 7 * nonarmCharge + 7 * armCharge := by
  calc
    ∑ i ∈ labels, weight i * count i ^ 3 ≤
        (∑ i ∈ labels, weight i) +
          7 * ∑ i ∈ labels, weight i * (count i - 1) ^ 3 :=
      weightedCubicEnergy_le_catalogue_add_sevenShifted labels weight count
    _ ≤ ownerMass + 7 * (nonarmCharge + armCharge) :=
      Nat.add_le_add hbase (Nat.mul_le_mul_left 7 hshift)
    _ = ownerMass + 7 * nonarmCharge + 7 * armCharge := by ring

/-! ## Exact countermodels for over-strengthenings -/

/-- Replacing the strict large-label threshold by a closed threshold breaks
the linear capture squeeze with every other ledger premise retained. -/
theorem closedLargeThreshold_breaks_captureSqueeze :
    let card := 2
    let H := 1
    let T := 1
    let capture := 1
    let D := 1
    let N := 1
    let L := 1
    0 < T ∧ card ≤ H / T + 1 ∧ H * L ≤ N ∧
      T * capture = D ∧ N ^ 2 ≤ D ∧
      ¬ ((card - 1) * N * L < capture) := by norm_num

/-- All premises of the uniform cubic ledger hold, but adding a third
period factor while keeping the same `K*N` right side is false. -/
theorem extraPeriodFactor_cubic_counterexample :
    let card := 2
    let H := 3
    let T := 3
    let capture := 6
    let D := 18
    let N := 3
    let K := 6
    let L := 1
    0 < T ∧ 0 < N ∧ 0 < K ∧ 0 < L ∧
      card ≤ H / T + 1 ∧ H * L ≤ N ∧
      T * capture = D ∧ capture ≤ K * L ^ 3 ∧ N ^ 2 < D ∧
      (card - 1) ^ 3 * T ^ 2 < K * N ∧
      ¬ ((card - 1) ^ 3 * T ^ 3 < K * N) := by norm_num

/-- The same ledger also shows that the normalized square cap retains only
one period factor. -/
theorem extraPeriodFactor_square_counterexample :
    let card := 2
    let H := 3
    let T := 3
    let capture := 6
    let D := 18
    let N := 3
    let K := 6
    let L := 1
    0 < T ∧ card ≤ H / T + 1 ∧ H * L ≤ N ∧
      T * capture = D ∧ capture ≤ K * L ^ 2 ∧ N ^ 2 < D ∧
      (card - 1) ^ 2 * T < K ∧
      ¬ ((card - 1) ^ 2 * T ^ 2 < K) := by norm_num

/-- Primitive capture can fail on every arm if its relevant coefficient
coprimality premise is deleted. -/
theorem missingCoefficientCoprimality_breaks_all_armCaptures :
    (⟨1, 3, 1⟩ : ArmDivisorLabel).PairwiseCoprime ∧
      Nat.Coprime 1 2 ∧ ¬ Nat.Coprime 3 3 ∧
      directionCapture (⟨1, 3, 1⟩ : ArmDivisorLabel) 0 3 2 = 3 ∧
      3 ≠ (⟨1, 3, 1⟩ : ArmDivisorLabel).u ∧
    (⟨1, 1, 2⟩ : ArmDivisorLabel).PairwiseCoprime ∧
      Nat.Coprime 1 3 ∧ ¬ Nat.Coprime 2 2 ∧
      directionCapture (⟨1, 1, 2⟩ : ArmDivisorLabel) 0 3 2 = 2 ∧
      2 ≠ (⟨1, 1, 2⟩ : ArmDivisorLabel).u ∧
    (⟨3, 1, 1⟩ : ArmDivisorLabel).PairwiseCoprime ∧
      ¬ Nat.Coprime 3 3 ∧ Nat.Coprime 1 1 ∧
      directionCapture (⟨3, 1, 1⟩ : ArmDivisorLabel) 3 0 1 = 3 ∧
      3 ≠ (⟨3, 1, 1⟩ : ArmDivisorLabel).v ∧
    (⟨2, 1, 1⟩ : ArmDivisorLabel).PairwiseCoprime ∧
      ¬ Nat.Coprime 2 2 ∧ Nat.Coprime 1 1 ∧
      directionCapture (⟨2, 1, 1⟩ : ArmDivisorLabel) 2 1 0 = 2 ∧
      2 ≠ (⟨2, 1, 1⟩ : ArmDivisorLabel).w := by
  norm_num [ArmDivisorLabel.PairwiseCoprime, directionCapture]

/-- Even with coefficient coprimality, a scaled nonprimitive direction can
absorb the scale on every arm. -/
theorem nonprimitiveDirection_breaks_all_exact_armCaptures :
    (⟨1, 5, 1⟩ : ArmDivisorLabel).PairwiseCoprime ∧
      Nat.Coprime 5 3 ∧ Nat.Coprime 1 2 ∧ Nat.gcd 0 5 = 5 ∧
      directionCapture (⟨1, 5, 1⟩ : ArmDivisorLabel) 0 15 10 = 5 ∧
      5 ≠ (⟨1, 5, 1⟩ : ArmDivisorLabel).u ∧
    (⟨5, 1, 1⟩ : ArmDivisorLabel).PairwiseCoprime ∧
      Nat.Coprime 5 3 ∧ Nat.Coprime 1 1 ∧ Nat.gcd 15 5 = 5 ∧
      directionCapture (⟨5, 1, 1⟩ : ArmDivisorLabel) 15 0 5 = 5 ∧
      5 ≠ (⟨5, 1, 1⟩ : ArmDivisorLabel).v ∧
    (⟨5, 1, 1⟩ : ArmDivisorLabel).PairwiseCoprime ∧
      Nat.Coprime 5 2 ∧ Nat.Coprime 1 1 ∧ Nat.gcd 10 5 = 5 ∧
      directionCapture (⟨5, 1, 1⟩ : ArmDivisorLabel) 10 5 0 = 5 ∧
      5 ≠ (⟨5, 1, 1⟩ : ArmDivisorLabel).w := by
  norm_num [ArmDivisorLabel.PairwiseCoprime, directionCapture]
































end AffineSignedRayCanonicalCaps20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/AffineSignedRayCanonicalCaps20260901.lean -/

/- BEGIN EXACT BODY: IUTThreeClosures/IUTAdmissibleScalingOrderIndex20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/

/-!
# Admissible scaling and an exact integral-order index

The mathematical proofs precede this formalization in
`research/ABC_IUT_ADMISSIBLE_SCALING_ORDER_INDEX_2026_09_02.md`.

This module proves that an all-set real-valued scaling law is inconsistent,
that merely restricting it to nonempty sets does not repair it, and that the
congruence order used as the integral-order seam has exact additive index
`n`.  It does not assert a same-pilot comparison, IUT, or abc.
-/

namespace IUTThreeClosures
namespace IUTAdmissibleScalingOrderIndex20260901

/-! ## Total scaling no-go theorems -/

/-- A translation law on preimages of every set forces the translation to be
zero.  The empty set is a full-premise counterexample to every nonzero shift. -/
theorem shift_eq_zero_of_all_sets
    {X : Type*} (scale : X → X) (volume : Set X → ℝ) (shift : ℝ)
    (hshift : ∀ U : Set X,
      volume (scale ⁻¹' U) = volume U + shift) :
    shift = 0 := by
  have h := hshift (∅ : Set X)
  simp only [Set.preimage_empty] at h
  linarith

/-- Nonemptiness alone is not a sufficient domain restriction.  On an
inhabited space the whole set is nonempty and fixed by every preimage. -/
theorem shift_eq_zero_of_all_nonempty_sets
    {X : Type*} [Nonempty X]
    (scale : X → X) (volume : Set X → ℝ) (shift : ℝ)
    (hshift : ∀ U : Set X, U.Nonempty →
      volume (scale ⁻¹' U) = volume U + shift) :
    shift = 0 := by
  have h := hshift (Set.univ : Set X) Set.univ_nonempty
  simp only [Set.preimage_univ] at h
  linarith

/-! ## The exact congruence-order quotient -/

/-- Difference of the two coordinates modulo `n`. -/
def differenceMod (n : ℕ) : (ℤ × ℤ) →+ ZMod n where
  toFun x := (x.1 : ZMod n) - (x.2 : ZMod n)
  map_zero' := by simp
  map_add' x y := by
    simp only [Prod.fst_add, Prod.snd_add, Int.cast_add]
    abel

@[simp]
theorem differenceMod_apply (n : ℕ) (x : ℤ × ℤ) :
    differenceMod n x = (x.1 : ZMod n) - (x.2 : ZMod n) :=
  rfl

/-- Every residue class is represented by the first coordinate of `(a, 0)`. -/
theorem differenceMod_surjective (n : ℕ) :
    Function.Surjective (differenceMod n) := by
  intro z
  obtain ⟨a, rfl⟩ := ZMod.intCast_surjective z
  exact ⟨(a, 0), by simp [differenceMod]⟩

/-- The kernel of the difference map is exactly the additive group underlying
the congruence order. -/
theorem differenceMod_ker (n : ℕ) :
    (differenceMod n).ker =
      (congruenceOrder (n : ℤ)).toAddSubgroup := by
  ext x
  simp only [AddMonoidHom.mem_ker, differenceMod_apply,
    Subring.mem_toAddSubgroup, mem_congruenceOrder_iff]
  rw [sub_eq_zero, ZMod.intCast_eq_intCast_iff_dvd_sub]
  constructor
  · intro h
    simpa only [neg_sub] using (dvd_neg.mpr h)
  · intro h
    simpa only [neg_sub] using (dvd_neg.mpr h)

/-- The additive quotient by the congruence order is canonically `ZMod n`. -/
noncomputable def congruenceOrderQuotientEquiv (n : ℕ) :
    (ℤ × ℤ) ⧸ (congruenceOrder (n : ℤ)).toAddSubgroup ≃+ ZMod n := by
  rw [← differenceMod_ker n]
  exact QuotientAddGroup.quotientKerEquivOfSurjective
    (differenceMod n) (differenceMod_surjective n)

/-- The congruence order has exact additive index `n`.  With the library's
`Nat.card` convention this includes `n = 0`, when the quotient is infinite. -/
theorem congruenceOrder_index (n : ℕ) :
    (congruenceOrder (n : ℤ)).toAddSubgroup.index = n := by
  rw [← differenceMod_ker n, AddSubgroup.index_ker]
  have hrange : (differenceMod n).range = ⊤ :=
    AddMonoidHom.range_eq_top.mpr (differenceMod_surjective n)
  rw [hrange]
  exact (Nat.card_congr AddSubgroup.topEquiv.toEquiv).trans (Nat.card_zmod n)

/-- If `n > 1`, the congruence order is a proper subring even though both of
its coordinate projections are surjective. -/
theorem congruenceOrder_ne_top_of_one_lt {n : ℕ} (hn : 1 < n) :
    congruenceOrder (n : ℤ) ≠ (⊤ : Subring (ℤ × ℤ)) := by
  intro htop
  have hmem : (1, 0) ∈ congruenceOrder (n : ℤ) := by
    rw [htop]
    exact Subring.mem_top _
  have hdvd : (n : ℤ) ∣ (1 : ℤ) := by
    simpa using hmem
  have hdvdNat : n ∣ 1 := Int.natCast_dvd_natCast.mp hdvd
  have hnOne : n = 1 := Nat.dvd_one.mp hdvdNat
  omega

/-- The first coordinate projection of every congruence order is surjective. -/
theorem congruenceOrder_fst_surjective (n : ℕ) :
    ∀ z : ℤ, ∃ x : congruenceOrder (n : ℤ), x.1.1 = z := by
  intro z
  refine ⟨⟨(z, z), ?_⟩, rfl⟩
  simp [congruenceOrder]

/-- The second coordinate projection of every congruence order is surjective. -/
theorem congruenceOrder_snd_surjective (n : ℕ) :
    ∀ z : ℤ, ∃ x : congruenceOrder (n : ℤ), x.1.2 = z := by
  intro z
  refine ⟨⟨(z, z), ?_⟩, rfl⟩
  simp [congruenceOrder]

/-- Exact indices multiply when the congruence modulus is multiplied. -/
theorem congruenceOrder_index_mul (m n : ℕ) :
    (congruenceOrder ((m * n : ℕ) : ℤ)).toAddSubgroup.index =
      (congruenceOrder (m : ℤ)).toAddSubgroup.index *
        (congruenceOrder (n : ℤ)).toAddSubgroup.index := by
  simp only [congruenceOrder_index]

/-- The real logarithm of the exact index is additive for positive moduli. -/
theorem congruenceOrder_log_index_mul
    {m n : ℕ} (hm : 0 < m) (hn : 0 < n) :
    Real.log
        ((congruenceOrder ((m * n : ℕ) : ℤ)).toAddSubgroup.index : ℝ) =
      Real.log ((congruenceOrder (m : ℤ)).toAddSubgroup.index : ℝ) +
        Real.log ((congruenceOrder (n : ℤ)).toAddSubgroup.index : ℝ) := by
  rw [congruenceOrder_index (m * n), congruenceOrder_index m,
    congruenceOrder_index n]
  have hmR : (m : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hm)
  have hnR : (n : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hn)
  simpa only [Nat.cast_mul] using Real.log_mul hmR hnR

end IUTAdmissibleScalingOrderIndex20260901
end IUTThreeClosures

namespace IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901








end IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901
/- END EXACT BODY: IUTThreeClosures/IUTAdmissibleScalingOrderIndex20260901.lean -/

/- BEGIN EXACT BODY: IUTThreeClosures/MersenneCriticalSlowSlackGate20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/

/-!
# Critical slow-slack support compression for Mersenne order blocks

The mathematical proof precedes this file in
`research/ABC_MERSENNE_CRITICAL_SLOW_SLACK_GATE_2026_09_01.md`.

That proof replaces the fixed log-log power in the preceding Mersenne gate by
an arbitrarily slowly divergent slack.  The analytic input is still Yamada's
published pointwise valuation bound.  This module formalizes the finite core:
increasing either survivor threshold shrinks the corresponding support and
its nonnegative mass, while decreasing the slack enlarges the balanced
multiplier scale.  It also records the exact `1093` counterexample to an
overstrong parity claim.

No real asymptotic estimate, Yamada theorem, Wieferich-density statement, or
abc consequence is introduced as an assumption.
-/

namespace IUTThreeClosures
namespace MersenneCriticalSlowSlackGate20260901

open scoped BigOperators
open MersenneOrderBlockDecomposition20260901
open MersenneBalancedMultiplierDepthLocalization20260901
open MersenneCanonicalBlockWitness20260901
open MersenneMultiplierIndexTwoArm20260901

/-! ## Nested finite survivor supports -/

section FiniteSupports

variable {α : Type*}

/-- Elements whose integral multiplier survives a lower cutoff. -/
def highMultiplierSupport
    (s : Finset α) (label : α → ℕ) (H : ℕ) : Finset α :=
  s.filter (fun x => H ≤ label x)

/-- Elements whose size survives a strict lower cutoff. -/
noncomputable def aboveSizeSupport
    (s : Finset α) (size : α → ℝ) (T : ℝ) : Finset α :=
  s.filter (fun x => T < size x)

/-- Raising the multiplier threshold can only shrink the surviving support. -/
theorem highMultiplierSupport_anti
    (s : Finset α) (label : α → ℕ) {H₁ H₂ : ℕ} (hH : H₁ ≤ H₂) :
    highMultiplierSupport s label H₂ ⊆
      highMultiplierSupport s label H₁ := by
  intro x hx
  simp only [highMultiplierSupport, Finset.mem_filter] at hx ⊢
  exact ⟨hx.1, hH.trans hx.2⟩

/-- Raising the size threshold can only shrink the surviving support. -/
theorem aboveSizeSupport_anti
    (s : Finset α) (size : α → ℝ) {T₁ T₂ : ℝ} (hT : T₁ ≤ T₂) :
    aboveSizeSupport s size T₂ ⊆
      aboveSizeSupport s size T₁ := by
  intro x hx
  simp only [aboveSizeSupport, Finset.mem_filter] at hx ⊢
  exact ⟨hx.1, hT.trans_lt hx.2⟩

/-- With nonnegative weights, the mass above a larger multiplier threshold
is no larger. -/
theorem highMultiplierMass_anti
    (s : Finset α) (label : α → ℕ) (weight : α → ℝ)
    {H₁ H₂ : ℕ} (hH : H₁ ≤ H₂) (hweight : ∀ x, 0 ≤ weight x) :
    (∑ x ∈ highMultiplierSupport s label H₂, weight x) ≤
      ∑ x ∈ highMultiplierSupport s label H₁, weight x := by
  apply Finset.sum_le_sum_of_subset_of_nonneg
    (highMultiplierSupport_anti s label hH)
  intro x _ _
  exact hweight x

/-- With nonnegative weights, the mass above a larger size threshold is no
larger. -/
theorem aboveSizeMass_anti
    (s : Finset α) (size weight : α → ℝ)
    {T₁ T₂ : ℝ} (hT : T₁ ≤ T₂) (hweight : ∀ x, 0 ≤ weight x) :
    (∑ x ∈ aboveSizeSupport s size T₂, weight x) ≤
      ∑ x ∈ aboveSizeSupport s size T₁, weight x := by
  apply Finset.sum_le_sum_of_subset_of_nonneg
    (aboveSizeSupport_anti s size hT)
  intro x _ _
  exact hweight x

/-- A simultaneous increase of both survivor thresholds shrinks the sum of
the two surviving nonnegative arms. -/
theorem twoSurvivorMass_anti
    (sDeep sOne : Finset α) (multiplier : α → ℕ) (size : α → ℝ)
    (deepWeight oneWeight : α → ℝ) {H₁ H₂ : ℕ} {T₁ T₂ : ℝ}
    (hH : H₁ ≤ H₂) (hT : T₁ ≤ T₂)
    (hdeep : ∀ x, 0 ≤ deepWeight x) (hone : ∀ x, 0 ≤ oneWeight x) :
    (∑ x ∈ highMultiplierSupport sDeep multiplier H₂, deepWeight x) +
        (∑ x ∈ aboveSizeSupport sOne size T₂, oneWeight x) ≤
      (∑ x ∈ highMultiplierSupport sDeep multiplier H₁, deepWeight x) +
        (∑ x ∈ aboveSizeSupport sOne size T₁, oneWeight x) := by
  exact add_le_add
    (highMultiplierMass_anti sDeep multiplier deepWeight hH hdeep)
    (aboveSizeMass_anti sOne size oneWeight hT hone)

end FiniteSupports





/-! ## Exact cutoff balance and slack comparison -/

/-- Abstract realization of `log(3m) * L_m * sigma(m)`. -/
def slowSlackSizeCutoff (A L σ : ℝ) : ℝ := A * L * σ

/-- The squared, unrounded multiplier scale paired with the size cutoff. -/
noncomputable def slowSlackMultiplierScaleSq (A L σ : ℝ) : ℝ := A / (L * σ)

/-- The two scales have constant product `A^2`; this is the exact balance
behind the identical `1 / sigma` losses in the paper proof. -/
theorem slowSlack_cutoff_mul_multiplierScaleSq
    {A L σ : ℝ} (hL : L ≠ 0) (hσ : σ ≠ 0) :
    slowSlackSizeCutoff A L σ * slowSlackMultiplierScaleSq A L σ = A ^ 2 := by
  unfold slowSlackSizeCutoff slowSlackMultiplierScaleSq
  field_simp

/-- Increasing the slack increases the size-cutoff denominator. -/
theorem slowSlackSizeCutoff_mono
    {A L σ₁ σ₂ : ℝ} (hA : 0 ≤ A) (hL : 0 ≤ L) (hσ : σ₁ ≤ σ₂) :
    slowSlackSizeCutoff A L σ₁ ≤ slowSlackSizeCutoff A L σ₂ := by
  unfold slowSlackSizeCutoff
  gcongr

/-- Increasing a positive slack decreases the squared multiplier scale. -/
theorem slowSlackMultiplierScaleSq_anti
    {A L σ₁ σ₂ : ℝ} (hA : 0 ≤ A) (hL : 0 < L)
    (hσ₁ : 0 < σ₁) (hσ : σ₁ ≤ σ₂) :
    slowSlackMultiplierScaleSq A L σ₂ ≤
      slowSlackMultiplierScaleSq A L σ₁ := by
  unfold slowSlackMultiplierScaleSq
  have hden₁ : 0 < L * σ₁ := mul_pos hL hσ₁
  have hden : L * σ₁ ≤ L * σ₂ :=
    mul_le_mul_of_nonneg_left hσ hL.le
  exact div_le_div_of_nonneg_left hA hden₁ hden

/-- The two directions of the slack comparison are recorded together. -/
theorem slowSlack_scale_comparison
    {A L σ₁ σ₂ : ℝ} (hA : 0 ≤ A) (hL : 0 < L)
    (hσ₁ : 0 < σ₁) (hσ : σ₁ ≤ σ₂) :
    slowSlackSizeCutoff A L σ₁ ≤ slowSlackSizeCutoff A L σ₂ ∧
      slowSlackMultiplierScaleSq A L σ₂ ≤
        slowSlackMultiplierScaleSq A L σ₁ := by
  exact ⟨slowSlackSizeCutoff_mono hA hL.le hσ,
    slowSlackMultiplierScaleSq_anti hA hL hσ₁ hσ⟩




/-! ## Finite ledger after enlarging the controlled region -/

/-- The existing two-survivor alternative applies unchanged after the two
controlled arms have been enlarged.  The theorem is finite and contains no
asymptotic premise. -/
theorem criticalHigh_or_criticalNearSquare_of_enlarged_low_budgets
    {target oldLow newlyRemovedDeep newlyRemovedOne
        criticalHigh criticalNear share : ℝ}
    (htotal : target ≤
      oldLow + newlyRemovedDeep + newlyRemovedOne +
        criticalHigh + criticalNear)
    (hlow : oldLow + newlyRemovedDeep + newlyRemovedOne ≤
      target - 2 * share) :
    share ≤ criticalHigh ∨ share ≤ criticalNear := by
  apply highDeep_or_balancedNearSquare_of_two_low_budgets
      (target := target) (lowOne := oldLow)
      (lowDeep := newlyRemovedDeep + newlyRemovedOne)
      (highDeep := criticalHigh) (nearSquare := criticalNear)
  · linarith
  · linarith

/-! ## Exact-order Euler-character core -/

/-- If an odd prime has exact base-two order `d` and `p - 1 = d * r`,
Euler's half-power is exactly `(-1)^r`.  Composing this with Euler's
criterion gives the quadratic-character identity `(2/p) = (-1)^r` used in
the mathematical report. -/
theorem exactOrder_eulerPower_eq_negOnePow_multiplier
    {p d r : ℕ} (hp : p.Prime) (hpOdd : Odd p)
    (horder : orderOf (2 : ZMod p) = d)
    (hpred : p - 1 = d * r) :
    (2 : ZMod p) ^ ((p - 1) / 2) = (-1 : ZMod p) ^ r := by
  letI : Fact p.Prime := ⟨hp⟩
  have hpPredPos : 0 < p - 1 := by
    have : 2 ≤ p := hp.two_le
    omega
  have hpNeTwo : p ≠ 2 := by
    intro hpTwo
    subst p
    norm_num at hpOdd
  have htwo : (2 : ZMod p) ≠ 0 := by
    intro hzero
    have hpDvdTwo : p ∣ 2 :=
      (CharP.cast_eq_zero_iff (ZMod p) p 2).mp hzero
    exact hpNeTwo ((Nat.prime_dvd_prime_iff_eq hp Nat.prime_two).mp hpDvdTwo)
  have hordDvd : orderOf (2 : ZMod p) ∣ p - 1 :=
    ZMod.orderOf_dvd_card_sub_one htwo
  have hordPos : 0 < orderOf (2 : ZMod p) :=
    Nat.pos_of_dvd_of_pos hordDvd hpPredPos
  have hdPos : 0 < d := by simpa [horder] using hordPos
  have hpowd : (2 : ZMod p) ^ d = 1 := by
    rw [← horder]
    exact pow_orderOf_eq_one _
  obtain ⟨s, hrs | hrs⟩ := Nat.even_or_odd' r
  · subst r
    have hhalf : (p - 1) / 2 = d * s := by
      rw [hpred]
      calc
        d * (2 * s) / 2 = (d * s) * 2 / 2 := by
          congr 1
          ring
        _ = d * s := Nat.mul_div_left _ (by norm_num)
    rw [hhalf, pow_mul, hpowd, one_pow]
    simp
  · subst r
    have hrOdd : Odd (2 * s + 1) := by simp
    have hpPredEven : Even (p - 1) :=
      Nat.Odd.sub_odd hpOdd (by norm_num : Odd (1 : ℕ))
    rw [hpred] at hpPredEven
    have hdEven : Even d := by
      by_contra hdNotEven
      have hdOdd : Odd d := Nat.not_even_iff_odd.mp hdNotEven
      exact (Nat.not_odd_iff_even.mpr hpPredEven) (hdOdd.mul hrOdd)
    rcases hdEven with ⟨t, ht⟩
    have htPos : 0 < t := by omega
    have hhalf : (p - 1) / 2 = t * (2 * s + 1) := by
      rw [hpred, ht]
      calc
        (t + t) * (2 * s + 1) / 2 =
            (t * (2 * s + 1)) * 2 / 2 := by
          congr 1
          ring
        _ = t * (2 * s + 1) := Nat.mul_div_left _ (by norm_num)
    have hpowTwoT : (2 : ZMod p) ^ (t + t) = 1 := by
      simpa [ht] using hpowd
    have hsquare :
        ((2 : ZMod p) ^ t) * ((2 : ZMod p) ^ t) = 1 := by
      rw [← pow_add]
      exact hpowTwoT
    have hhalfOrder : (2 : ZMod p) ^ t = -1 := by
      rcases (mul_self_eq_one_iff.mp hsquare) with hOne | hNeg
      · have hdDvdT : d ∣ t := by
          rw [← horder]
          exact orderOf_dvd_of_pow_eq_one hOne
        have hdLeT : d ≤ t := Nat.le_of_dvd htPos hdDvdT
        omega
      · exact hNeg
    rw [hhalf, pow_mul, hhalfOrder]

/-- Euler's criterion turns the preceding exact-order identity into the
Legendre-character statement, recorded after casting to `ZMod p`. -/
theorem exactOrder_legendreTwo_cast_eq_negOnePow_multiplier
    {p d r : ℕ} [Fact p.Prime] (hpOdd : Odd p)
    (horder : orderOf (2 : ZMod p) = d)
    (hpred : p - 1 = d * r) :
    ((legendreSym p 2 : ℤ) : ZMod p) = (-1 : ZMod p) ^ r := by
  have hp : p.Prime := Fact.out
  have hhalf : p / 2 = (p - 1) / 2 := by
    rcases hpOdd with ⟨s, hs⟩
    omega
  rw [legendreSym.eq_pow, hhalf]
  simpa using exactOrder_eulerPower_eq_negOnePow_multiplier
    hp hpOdd horder hpred

/-- Actual exact-order fibres satisfy the Euler half-power identity with the
canonical integral multiplier `(p - 1) / d`. -/
theorem exactOrderPrimeFiber_eulerPower_eq_negOnePow_multiplier
    {p d : ℕ} (hd : 0 < d) (hpMem : p ∈ exactOrderPrimeFiber d) :
    (2 : ZMod p) ^ ((p - 1) / 2) =
      (-1 : ZMod p) ^ ((p - 1) / d) := by
  have hpFactors : p ∈ (2 ^ d - 1).primeFactors :=
    (Finset.mem_filter.mp hpMem).1
  have hpOrder : mersenneExactOrder p = d :=
    (Finset.mem_filter.mp hpMem).2
  have hp : p.Prime := Nat.prime_of_mem_primeFactors hpFactors
  have hpDvd : p ∣ 2 ^ d - 1 := Nat.dvd_of_mem_primeFactors hpFactors
  have hpNeTwo : p ≠ 2 :=
    prime_ne_two_of_dvd_mersenne hd hp hpDvd
  have hpOdd : Odd p := hp.odd_of_ne_two hpNeTwo
  have hpRep := exactOrder_prime_eq_one_add_mul_multiplier hd hpMem
  have hpred : p - 1 = d * ((p - 1) / d) := by omega
  exact exactOrder_eulerPower_eq_negOnePow_multiplier
    hp hpOdd hpOrder hpred



/-! ## Sharp abstract and arithmetic counterexample boundaries -/

/-- The complete positive packet from the preceding module remains a full
counterexample to every proposed linear-in-`H` energy bound.  Thus the
critical `sigma = 1` estimate cannot follow from positivity and multiplier
injectivity alone. -/
theorem critical_packet_refutes_every_fixed_linear_energy_coefficient
    (C : ℕ) :
    ∃ (H : ℕ) (s : Finset ℕ) (label : ℕ → ℕ),
      Set.InjOn label (s : Set ℕ) ∧
        (∀ x ∈ s, 0 < label x) ∧
        (∀ x ∈ s, label x < H) ∧
        C * H < ∑ x ∈ s, label x := by
  exact no_uniform_nat_linear_bound_for_positive_injective_labels C

/-- `1093` is an actual repeated base-two exact-order prime with odd
multiplier three. -/
theorem wieferich_1093_exact_order_multiplier_three_odd :
    Nat.Prime 1093 ∧
      mersenneExactOrder 1093 = 364 ∧
      1093 ^ 2 ∣ 2 ^ 364 - 1 ∧
      ¬ 1093 ^ 3 ∣ 2 ^ 364 - 1 ∧
      (1093 - 1) / 364 = 3 ∧
      Odd ((1093 - 1) / 364) := by
  exact ⟨prime_1093, mersenneExactOrder_1093,
    wieferich_1093_sq_dvd_two_pow_364_sub_one,
    wieferich_1093_cube_not_dvd_two_pow_364_sub_one,
    by norm_num, by norm_num⟩

/-- Full-premise negation of the tempting parity strengthening.  This
retires only that pointwise claim, not either asymptotic Mersenne arm. -/
theorem repeated_exact_order_multiplier_even_false :
    ¬ (∀ p d : ℕ,
      Nat.Prime p →
      mersenneExactOrder p = d →
      p ^ 2 ∣ 2 ^ d - 1 →
      Even ((p - 1) / d)) := by
  intro hall
  have hodd := hall 1093 364 prime_1093 mersenneExactOrder_1093
    wieferich_1093_sq_dvd_two_pow_364_sub_one
  norm_num at hodd



end MersenneCriticalSlowSlackGate20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/MersenneCriticalSlowSlackGate20260901.lean -/

/- BEGIN EXACT BODY: IUTThreeClosures/PellLucasCorrelatedAllOrderExclusion20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/


/-!
# Correlated all-order Pell--Lucas companion staircases

The mathematical arguments precede this module in
`research/ABC_PELL_LUCAS_CORRELATED_ALL_ORDER_EXCLUSION_2026_09_01.md`.

This file kernel-checks only the reusable algebraic core:

* the original product-to-binomial coefficient identity and correlation;
* the exact weighted identity for two correlated coefficient lists;
* the normalized-tail congruence at an arbitrary order;
* the every-order paired correction and recovery of one common half-companion;
* the cross-order determinant-zero relation;
* propagation of channel signs from cubes to sixth powers;
* a finite negative-row extraction with the opposite rank congruence; and
* the elementary half-unit power identity behind the quartic-two column sign.

No Lucas multiplication theorem, Pell rank theorem, perfect-power theorem,
squarefull packet, or abc statement is introduced as an axiom.  Arithmetic
specializations enter the generic interface only as explicit hypotheses.
-/

namespace IUTThreeClosures
namespace PellLucasCorrelatedAllOrderExclusion20260901

open scoped BigOperators

/-! ## Closed-form coefficient correlation -/

/-- Companion coefficient `choose (theta+j) (2*j)`, regarded in `ℚ`. -/
def companionCoeffQ (theta j : ℕ) : ℚ :=
  Nat.choose (theta + j) (2 * j)

/-- The closed form `ell/(2*j+1) * companionCoeffQ`. -/
def firstCoeffQ (ell theta j : ℕ) : ℚ :=
  (ell : ℚ) * companionCoeffQ theta j / (2 * j + 1 : ℕ)

/-- The coefficient identity after the first coefficient has been put into
its closed binomial form.  The substantive passage from the original product
formula to this form is proved in `product_firstCoeff_eq_closedForm` below. -/
theorem rational_coefficient_correlation (ell theta j : ℕ) :
    (2 * j + 1 : ℕ) * firstCoeffQ ell theta j =
      (ell : ℚ) * companionCoeffQ theta j := by
  have hne : ((2 * j + 1 : ℕ) : ℚ) ≠ 0 := by positivity
  simp only [firstCoeffQ]
  field_simp

/-- The product of the odd quadratic factors in the original Lucas
coefficient formula (2.2), evaluated in `ℚ`.  The range index `i` represents
the odd integer `2*i+1`. -/
def lucasOddFactorProductQ (ell j : ℕ) : ℚ :=
  ∏ i ∈ Finset.range j,
    ((ell : ℚ) ^ 2 - ((2 * i + 1 : ℕ) : ℚ) ^ 2)

/-- The first-sequence coefficient in the original product form (2.2). -/
def productFirstCoeffQ (ell j : ℕ) : ℚ :=
  (ell : ℚ) * lucasOddFactorProductQ ell j /
    ((4 : ℚ) ^ j * ((2 * j + 1).factorial : ℚ))

/-- Pairing the descending factors below `theta` with the ascending factors
above it produces one centered descending factorial. -/
theorem centeredFactorProduct_eq_descFactorial (theta j : ℕ) :
    (∏ i ∈ Finset.range j, (theta - i) * (theta + i + 1)) =
      (theta + j).descFactorial (2 * j) := by
  rw [Finset.prod_mul_distrib]
  rw [← Nat.descFactorial_eq_prod_range]
  have hasc : (∏ i ∈ Finset.range j, (theta + i + 1)) =
      (theta + 1).ascFactorial j := by
    rw [Nat.ascFactorial_eq_prod_range]
    apply Finset.prod_congr rfl
    intro i hi
    omega
  rw [hasc, ← Nat.add_descFactorial_eq_ascFactorial]
  have h := Nat.descFactorial_mul_descFactorial (n := theta + j)
    (k := j) (m := 2 * j) (by omega)
  have hsub : 2 * j - j = j := by omega
  rw [hsub] at h
  simpa [Nat.add_sub_cancel_left] using h

/-- For `j ≤ theta`, the raw odd-factor product with `ell = 2*theta+1`
is exactly `4^j` times the centered descending factorial. -/
theorem lucasOddFactorProductQ_eq (theta j : ℕ) (hj : j ≤ theta) :
    lucasOddFactorProductQ (2 * theta + 1) j =
      (4 : ℚ) ^ j * ((theta + j).descFactorial (2 * j) : ℚ) := by
  unfold lucasOddFactorProductQ
  calc
    (∏ i ∈ Finset.range j,
        (((2 * theta + 1 : ℕ) : ℚ) ^ 2 -
          ((2 * i + 1 : ℕ) : ℚ) ^ 2)) =
        ∏ i ∈ Finset.range j,
          (4 : ℚ) * (((theta - i) * (theta + i + 1) : ℕ) : ℚ) := by
      apply Finset.prod_congr rfl
      intro i hi
      have hit : i ≤ theta :=
        le_trans (Nat.le_of_lt (Finset.mem_range.mp hi)) hj
      rw [Nat.cast_mul, Nat.cast_sub hit]
      push_cast
      ring
    _ = (4 : ℚ) ^ j *
        ((∏ i ∈ Finset.range j, (theta - i) * (theta + i + 1) : ℕ) : ℚ) := by
      rw [Finset.prod_mul_distrib, Finset.prod_const, Finset.card_range]
      push_cast
      rfl
    _ = (4 : ℚ) ^ j * ((theta + j).descFactorial (2 * j) : ℚ) := by
      rw [centeredFactorProduct_eq_descFactorial]

/-- The original product formula (2.2) equals the closed binomial formula
used for `firstCoeffQ`.  This is the formal counterpart of the nontrivial
factorial calculation in Theorem 2.1. -/
theorem product_firstCoeff_eq_closedForm (theta j : ℕ) (hj : j ≤ theta) :
    productFirstCoeffQ (2 * theta + 1) j =
      firstCoeffQ (2 * theta + 1) theta j := by
  rw [productFirstCoeffQ, firstCoeffQ, companionCoeffQ,
    lucasOddFactorProductQ_eq theta j hj,
    Nat.descFactorial_eq_factorial_mul_choose]
  push_cast
  rw [show 2 * j + 1 = (2 * j).succ by omega, Nat.factorial_succ]
  push_cast
  have h4 : (4 : ℚ) ^ j ≠ 0 := by positivity
  have hfac : (((2 * j).factorial : ℕ) : ℚ) ≠ 0 := by positivity
  have hodd : (((2 * j).succ : ℕ) : ℚ) ≠ 0 := by positivity
  field_simp

/-- The paper's coefficient correlation, with `c_j` represented by its
original odd-factor product rather than defined from the claimed result. -/
theorem product_coefficient_correlation (theta j : ℕ) (hj : j ≤ theta) :
    (2 * j + 1 : ℕ) * productFirstCoeffQ (2 * theta + 1) j =
      ((2 * theta + 1 : ℕ) : ℚ) * companionCoeffQ theta j := by
  rw [product_firstCoeff_eq_closedForm theta j hj]
  exact rational_coefficient_correlation (2 * theta + 1) theta j

/-- The same identity after multiplying both coefficients by an arbitrary
common scale, such as `32^j` in the balancing-Pell specialization. -/
theorem scaled_rational_coefficient_correlation
    (ell theta j : ℕ) (scale : ℚ) :
    (2 * j + 1 : ℕ) * (scale * firstCoeffQ ell theta j) =
      (ell : ℚ) * (scale * companionCoeffQ theta j) := by
  rw [show ((2 * j + 1 : ℕ) : ℚ) * (scale * firstCoeffQ ell theta j) =
      scale * (((2 * j + 1 : ℕ) : ℚ) * firstCoeffQ ell theta j) by ring,
    rational_coefficient_correlation]
  ring

/-- The scaled correlation with the first coefficient still represented by
the original product formula.  Taking `scale = 32^j` is the coefficient
identity used by the balancing-Pell tails. -/
theorem scaled_product_coefficient_correlation
    (theta j : ℕ) (hj : j ≤ theta) (scale : ℚ) :
    (2 * j + 1 : ℕ) *
        (scale * productFirstCoeffQ (2 * theta + 1) j) =
      ((2 * theta + 1 : ℕ) : ℚ) *
        (scale * companionCoeffQ theta j) := by
  rw [product_firstCoeff_eq_closedForm theta j hj]
  exact scaled_rational_coefficient_correlation
    (2 * theta + 1) theta j scale

/-! ## Exact weighted identity for correlated coefficient lists -/

/-- Two integer coefficient lists are correlated from order `start` when
their heads obey `(2*start+1)*a = ell*b` at every successive order. -/
def CorrelatedFrom (ell start : ℤ) : List ℤ → List ℤ → Prop
  | [], [] => True
  | a :: as, b :: bs =>
      (2 * start + 1) * a = ell * b ∧
        CorrelatedFrom ell (start + 1) as bs
  | _, _ => False

/-- Weighted Horner evaluation of `sum_i (2*(start+i)+1)*a_i*U^(2*i)`. -/
def weightedEvenPowerSum (start U : ℤ) : List ℤ → ℤ
  | [] => 0
  | a :: as =>
      (2 * start + 1) * a + U ^ 2 * weightedEvenPowerSum (start + 1) U as

/-- Exact list form of the differential companion identity. -/
theorem weightedEvenPowerSum_eq_mul
    (ell start U : ℤ) (as bs : List ℤ)
    (hcorr : CorrelatedFrom ell start as bs) :
    weightedEvenPowerSum start U as =
      ell * PellLucasAllOrderStaircase20260901.evenPowerSum U bs := by
  induction as generalizing start bs with
  | nil =>
      cases bs <;> simp [CorrelatedFrom, weightedEvenPowerSum,
        PellLucasAllOrderStaircase20260901.evenPowerSum] at hcorr ⊢
  | cons a as ih =>
      cases bs with
      | nil => simp [CorrelatedFrom] at hcorr
      | cons b bs =>
          rcases hcorr with ⟨hhead, htail⟩
          simp only [weightedEvenPowerSum,
            PellLucasAllOrderStaircase20260901.evenPowerSum]
          rw [ih (start := start + 1) (bs := bs) htail, hhead]
          ring

/-- An even-power Horner tail is congruent to its leading coefficient modulo
`U^2`. -/
theorem evenPowerSum_cons_modEq (U a : ℤ) (as : List ℤ) :
    PellLucasAllOrderStaircase20260901.evenPowerSum U (a :: as) ≡
      a [ZMOD U ^ 2] := by
  apply Int.modEq_of_dvd
  refine ⟨-PellLucasAllOrderStaircase20260901.evenPowerSum U as, ?_⟩
  simp only [PellLucasAllOrderStaircase20260901.evenPowerSum]
  ring

/-- At any tail order, the head coefficient correlation induces the paired
normalized-tail congruence modulo `U^2`. -/
theorem normalized_tail_correlation
    (U ell weight a b : ℤ) (as bs : List ℤ)
    (hcoeff : weight * a = ell * b) :
    weight * PellLucasAllOrderStaircase20260901.evenPowerSum U (a :: as) ≡
      ell * PellLucasAllOrderStaircase20260901.evenPowerSum U
        (b :: bs) [ZMOD U ^ 2] := by
  calc
    weight * PellLucasAllOrderStaircase20260901.evenPowerSum U (a :: as) ≡
        weight * a [ZMOD U ^ 2] :=
      (evenPowerSum_cons_modEq U a as).mul_left weight
    _ = ell * b := hcoeff
    _ ≡ ell * PellLucasAllOrderStaircase20260901.evenPowerSum U
        (b :: bs) [ZMOD U ^ 2] :=
      ((evenPowerSum_cons_modEq U b bs).mul_left ell).symm

/-! ## Every-order paired correction and reconstruction -/

/-- Multiplying a normalized-tail correlation by the companion value gives
the every-order paired correction. -/
theorem everyOrderPairedCorrection
    (U ell weight v E F T : ℤ)
    (hEF : weight * E ≡ ell * F [ZMOD U ^ 2])
    (hT : T = v * F) :
    ell * T ≡ weight * v * E [ZMOD U ^ 2] := by
  rw [hT]
  calc
    ell * (v * F) = v * (ell * F) := by ring
    _ ≡ v * (weight * E) [ZMOD U ^ 2] := hEF.symm.mul_left v
    _ = weight * v * E := by ring

/-- The coefficient used to reconstruct the half-companion is a unit modulo
`U^2` when each of its three factors is a support unit. -/
theorem everyOrderDenominatorUnit
    (U weight E : ℤ)
    (h2 : IsCoprime 2 U)
    (hweight : IsCoprime weight U)
    (hE : IsCoprime E U) :
    IsCoprime (2 * weight * E) (U ^ 2) :=
  ((h2.mul_left hweight).mul_left hE).pow_right

/-- Every normalized tail reconstructs the same half-companion residue. -/
theorem everyOrderSplitter_recovers_halfCompanion
    (U ell weight v E T Z Z0 : ℤ)
    (hv : v = 2 * Z0)
    (hunit : IsCoprime (2 * weight * E) (U ^ 2))
    (hpair : ell * T ≡ weight * v * E [ZMOD U ^ 2])
    (hZ : (2 * weight * E) * Z ≡ ell * T [ZMOD U ^ 2]) :
    Z ≡ Z0 [ZMOD U ^ 2] := by
  have hright : ell * T ≡ (2 * weight * E) * Z0 [ZMOD U ^ 2] := by
    calc
      ell * T ≡ weight * v * E [ZMOD U ^ 2] := hpair
      _ = (2 * weight * E) * Z0 := by rw [hv]; ring
  have hmul : (2 * weight * E) * Z ≡
      (2 * weight * E) * Z0 [ZMOD U ^ 2] := hZ.trans hright
  exact PellLucasAllOrderStaircase20260901.cancel_coprime_factor_modEq
    (U ^ 2) (2 * weight * E) Z Z0 hunit hmul

/-- All tail levels have zero two-by-two determinant modulo `U^2`: they lie
on one projective line after weighting by their odd order. -/
theorem crossOrderDeterminant_zero
    (U ell v wr ws Er Es Tr Ts : ℤ)
    (hell : IsCoprime ell (U ^ 2))
    (hr : ell * Tr ≡ wr * v * Er [ZMOD U ^ 2])
    (hs : ell * Ts ≡ ws * v * Es [ZMOD U ^ 2]) :
    Tr * (ws * Es) ≡ Ts * (wr * Er) [ZMOD U ^ 2] := by
  have hmul : ell * (Tr * (ws * Es)) ≡
      ell * (Ts * (wr * Er)) [ZMOD U ^ 2] := by
    calc
      ell * (Tr * (ws * Es)) = (ell * Tr) * (ws * Es) := by ring
      _ ≡ (wr * v * Er) * (ws * Es) [ZMOD U ^ 2] :=
        hr.mul_right (ws * Es)
      _ = (ws * v * Es) * (wr * Er) := by ring
      _ ≡ (ell * Ts) * (wr * Er) [ZMOD U ^ 2] :=
        hs.symm.mul_right (wr * Er)
      _ = ell * (Ts * (wr * Er)) := by ring
  exact PellLucasAllOrderStaircase20260901.cancel_coprime_factor_modEq
    (U ^ 2) ell (Tr * (ws * Es)) (Ts * (wr * Er)) hell hmul

/-! ## Channel signs and the depth-six specialization -/

/-- A cubic divisor of a channel gives a sixth-power divisor of its square. -/
theorem cube_dvd_channel_gives_sixth_dvd_square
    (q A : ℤ) (h : q ^ 3 ∣ A) : q ^ 6 ∣ A ^ 2 := by
  rcases h with ⟨k, rfl⟩
  refine ⟨k ^ 2, ?_⟩
  ring

/-- Reduction of a positive channel sign from `A^2` to a selected cube
prime's sixth power. -/
theorem positiveChannel_depthSix
    (q A Z : ℤ) (hq : q ^ 3 ∣ A)
    (hZ : Z ≡ 1 [ZMOD A ^ 2]) :
    Z ≡ 1 [ZMOD q ^ 6] :=
  Int.ModEq.of_dvd (cube_dvd_channel_gives_sixth_dvd_square q A hq) hZ

/-- Reduction of a negative channel sign from `B^2` to a selected cube
prime's sixth power. -/
theorem negativeChannel_depthSix
    (r B Z : ℤ) (hr : r ^ 3 ∣ B)
    (hZ : Z ≡ -1 [ZMOD B ^ 2]) :
    Z ≡ -1 [ZMOD r ^ 6] :=
  Int.ModEq.of_dvd (cube_dvd_channel_gives_sixth_dvd_square r B hr) hZ

/-- A recovered half-companion has the two channel signs once the exact
Pell companion identities are supplied. -/
theorem recoveredHalfCompanion_channelSigns
    (A B U Z Z0 : ℤ)
    (hU : U = A * B)
    (hZU : Z ≡ Z0 [ZMOD U ^ 2])
    (hA : Z0 = 2 * A ^ 2 + 1)
    (hB : Z0 = 4 * B ^ 2 - 1) :
    Z ≡ 1 [ZMOD A ^ 2] ∧ Z ≡ -1 [ZMOD B ^ 2] := by
  rcases PellLucasAllOrderStaircase20260901.channel_square_divisors
    U A B hU with ⟨hAdiv, hBdiv⟩
  have hZ0A : Z0 ≡ 1 [ZMOD A ^ 2] := by
    apply Int.modEq_of_dvd
    refine ⟨-2, ?_⟩
    rw [hA]
    ring
  have hZ0B : Z0 ≡ -1 [ZMOD B ^ 2] := by
    apply Int.modEq_of_dvd
    refine ⟨-4, ?_⟩
    rw [hB]
    ring
  exact ⟨(Int.ModEq.of_dvd hAdiv hZU).trans hZ0A,
    (Int.ModEq.of_dvd hBdiv hZU).trans hZ0B⟩

/-- A single recovered half-companion simultaneously carries the positive
and negative sixth-power signs at an opposite depth-three pair. -/
theorem recoveredHalfCompanion_oppositeDepthSix
    (q r A B U Z Z0 : ℤ)
    (hU : U = A * B)
    (hZU : Z ≡ Z0 [ZMOD U ^ 2])
    (hA : Z0 = 2 * A ^ 2 + 1)
    (hB : Z0 = 4 * B ^ 2 - 1)
    (hq : q ^ 3 ∣ A)
    (hr : r ^ 3 ∣ B) :
    Z ≡ 1 [ZMOD q ^ 6] ∧ Z ≡ -1 [ZMOD r ^ 6] := by
  rcases recoveredHalfCompanion_channelSigns A B U Z Z0 hU hZU hA hB with
    ⟨hZA, hZB⟩
  exact ⟨positiveChannel_depthSix q A Z hq hZA,
    negativeChannel_depthSix r B Z hr hZB⟩

/-! ## Vertexwise sign rows and the forced opposite congruence -/

/-- A list of signs with negative product contains a negative entry. -/
theorem exists_negative_of_sign_product
    (xs : List ℤ)
    (hsign : ∀ x ∈ xs, x = 1 ∨ x = -1)
    (hprod : xs.prod = -1) :
    ∃ x ∈ xs, x = -1 := by
  by_contra hnone
  have hall : ∀ x ∈ xs, x = 1 := by
    intro x hx
    rcases hsign x hx with hone | hneg
    · exact hone
    · exact False.elim (hnone ⟨x, hx, hneg⟩)
  have : xs.prod = 1 := List.prod_eq_one hall
  omega

/-- A negative vertex row plus the two opposite rank congruences produces an
actual negative edge whose prime labels sum to a multiple of `2*ell`. -/
theorem negativeRow_forces_oppositeCongruence
    (ell r : ℤ) (qs : List ℤ) (chi : ℤ → ℤ)
    (hsign : ∀ q ∈ qs, chi q = 1 ∨ chi q = -1)
    (hprod : (qs.map chi).prod = -1)
    (hq : ∀ q ∈ qs, q ≡ 1 [ZMOD 2 * ell])
    (hr : r ≡ -1 [ZMOD 2 * ell]) :
    ∃ q ∈ qs, chi q = -1 ∧ (2 * ell) ∣ q + r := by
  have mappedSign : ∀ x ∈ qs.map chi, x = 1 ∨ x = -1 := by
    intro x hx
    rcases List.mem_map.mp hx with ⟨q, hqmem, rfl⟩
    exact hsign q hqmem
  rcases exists_negative_of_sign_product (qs.map chi) mappedSign hprod with
    ⟨x, hx, hneg⟩
  rcases List.mem_map.mp hx with ⟨q, hqmem, rfl⟩
  refine ⟨q, hqmem, hneg, ?_⟩
  have hadd : q + r ≡ 0 [ZMOD 2 * ell] := by
    simpa using (hq q hqmem).add hr
  have hneg : (2 * ell) ∣ -(q + r) := by simpa using hadd.dvd
  exact (dvd_neg.mp hneg)

/-! ## The algebra behind the quartic-two column sign -/

/-- If `two * B^2 = 1`, the Euler half-power of `B` times the corresponding
quarter-power of `two` is one.  In `ZMod q` with `q = 1 mod 8`, both factors
are signs, so they are equal. -/
theorem halfUnit_power_product
    {R : Type*} [CommMonoid R] (two B : R) (n : ℕ)
    (hhalf : two * B ^ 2 = 1) :
    B ^ (2 * n) * two ^ n = 1 := by
  calc
    B ^ (2 * n) * two ^ n = (B ^ 2) ^ n * two ^ n := by rw [pow_mul]
    _ = (B ^ 2 * two) ^ n := (mul_pow (B ^ 2) two n).symm
    _ = 1 := by rw [mul_comm, hhalf]; simp

#check rational_coefficient_correlation
#check product_firstCoeff_eq_closedForm
#check product_coefficient_correlation
#check scaled_rational_coefficient_correlation
#check scaled_product_coefficient_correlation
#check weightedEvenPowerSum_eq_mul
#check normalized_tail_correlation
#check everyOrderPairedCorrection
#check everyOrderDenominatorUnit
#check everyOrderSplitter_recovers_halfCompanion
#check crossOrderDeterminant_zero
#check cube_dvd_channel_gives_sixth_dvd_square
#check positiveChannel_depthSix
#check negativeChannel_depthSix
#check recoveredHalfCompanion_channelSigns
#check recoveredHalfCompanion_oppositeDepthSix
#check exists_negative_of_sign_product
#check negativeRow_forces_oppositeCongruence
#check halfUnit_power_product



















end PellLucasCorrelatedAllOrderExclusion20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/PellLucasCorrelatedAllOrderExclusion20260901.lean -/

/- BEGIN GENERATED COMPLETE THEOREM/LEMMA AXIOM AUDIT -/
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.shiftedCard_mul_period_le
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.shiftedCard_mul_ambient_mul_scale_lt_capture
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.shiftedCard_square_mul_period_scaleSq_lt_capture
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.shiftedCard_square_mul_period_lt_of_capture_le_quadratic
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.shiftedCard_cube_mul_periodSq_scaleCube_lt_capture_mul_ambient
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.shiftedCard_physicalPeriod_cube_lt_labelProduct_mul_ambient
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedDirectionPeriod_pos
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedDirectionPeriod_mul_capture
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedDirectionPeriod_dvd_gap
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.nat_dvd_gap_mul_natAbs_of_intCast_dvd
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.actualSignedLine_directionPeriod_dvd_gap
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedDirectionCapture_le_product
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedDirectionProduct_le_sharp_cubic
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedDirectionProduct_one_one_is_sharp
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedDirectionScale_pos
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedNonarm_shifted_mul_ambient_scale_lt_product
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedNonarm_shiftedCube_mul_periodSq_lt
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.signedNonarm_smallDirection_is_singleton
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.directionCapture_zeroU_eq
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.directionCapture_zeroV_eq
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.directionCapture_zeroW_eq
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.zeroU_shifted_mul_ambient_lt
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.zeroV_shifted_mul_ambient_scale_lt
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.zeroW_shifted_mul_ambient_scale_lt
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.zeroU_three_mul_shifted_ambient_lt_power
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.zeroV_three_mul_shifted_ambient_scale_lt_power
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.zeroW_three_mul_shifted_ambient_scale_lt_power
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.cube_le_one_add_seven_shiftedCube
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.factorSix_singletonShift_counterexample
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.weightedCubicEnergy_le_catalogue_add_sevenShifted
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.weightedCubicEnergy_le_catalogue_add_caps
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.weightedShiftedEnergy_mul_scaledAmbientCube_le_armMoment
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.weightedCoordinateMoment_le_ownerCatalogue
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.weightedCoordinateMoment_le_ownerCatalogue_of_dvd
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.weightedCatalogue_le_ownerMass
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.weightedCubicEnergy_le_ownerMass_add_sevenCharges
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.closedLargeThreshold_breaks_captureSqueeze
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.extraPeriodFactor_cubic_counterexample
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.extraPeriodFactor_square_counterexample
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.missingCoefficientCoprimality_breaks_all_armCaptures
#print axioms IUTThreeClosures.AffineSignedRayCanonicalCaps20260901.nonprimitiveDirection_breaks_all_exact_armCaptures
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.shift_eq_zero_of_all_sets
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.shift_eq_zero_of_all_nonempty_sets
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.differenceMod_apply
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.differenceMod_surjective
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.differenceMod_ker
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.congruenceOrder_index
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.congruenceOrder_ne_top_of_one_lt
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.congruenceOrder_fst_surjective
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.congruenceOrder_snd_surjective
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.congruenceOrder_index_mul
#print axioms IUTThreeClosures.IUTAdmissibleScalingOrderIndex20260901.congruenceOrder_log_index_mul
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.highMultiplierSupport_anti
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.aboveSizeSupport_anti
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.highMultiplierMass_anti
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.aboveSizeMass_anti
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.twoSurvivorMass_anti
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.slowSlack_cutoff_mul_multiplierScaleSq
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.slowSlackSizeCutoff_mono
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.slowSlackMultiplierScaleSq_anti
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.slowSlack_scale_comparison
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.criticalHigh_or_criticalNearSquare_of_enlarged_low_budgets
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.exactOrder_eulerPower_eq_negOnePow_multiplier
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.exactOrder_legendreTwo_cast_eq_negOnePow_multiplier
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.exactOrderPrimeFiber_eulerPower_eq_negOnePow_multiplier
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.critical_packet_refutes_every_fixed_linear_energy_coefficient
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.wieferich_1093_exact_order_multiplier_three_odd
#print axioms IUTThreeClosures.MersenneCriticalSlowSlackGate20260901.repeated_exact_order_multiplier_even_false
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.rational_coefficient_correlation
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.centeredFactorProduct_eq_descFactorial
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.lucasOddFactorProductQ_eq
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.product_firstCoeff_eq_closedForm
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.product_coefficient_correlation
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.scaled_rational_coefficient_correlation
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.scaled_product_coefficient_correlation
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.weightedEvenPowerSum_eq_mul
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.evenPowerSum_cons_modEq
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.normalized_tail_correlation
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.everyOrderPairedCorrection
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.everyOrderDenominatorUnit
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.everyOrderSplitter_recovers_halfCompanion
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.crossOrderDeterminant_zero
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.cube_dvd_channel_gives_sixth_dvd_square
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.positiveChannel_depthSix
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.negativeChannel_depthSix
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.recoveredHalfCompanion_channelSigns
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.recoveredHalfCompanion_oppositeDepthSix
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.exists_negative_of_sign_product
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.negativeRow_forces_oppositeCongruence
#print axioms IUTThreeClosures.PellLucasCorrelatedAllOrderExclusion20260901.halfUnit_power_product
/- END GENERATED COMPLETE THEOREM/LEMMA AXIOM AUDIT -/
