/-
Generated by validate.py.  Do not edit by hand.

This file recompiles the exact declaration bodies of the four checkpoint
modules and issues one #print axioms command for every source theorem or
lemma.  Recompilation in one file keeps private source names addressable.
-/
import IUTThreeClosures.AffineCollinearPeriodEnergy20260901
import IUTThreeClosures.IUTRationalTripodShadowComparison20260901
import Genl.GeneralPosition.ProofPackage
import IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901
import IUTThreeClosures.MersenneSuperWieferichDepth20260901
import Mathlib

/- BEGIN EXACT BODY: IUTThreeClosures/AffineCatalogueWeightOverlap20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/

/-!
# Actual catalogue weight and monotone overlap in the affine route

The mathematical proofs precede this module in
`research/ABC_AFFINE_CATALOGUE_WEIGHT_OVERLAP_2026_09_01.md`.

This file proves the exact Euler-totient weight of the downward divisor
catalogue, a finite lower bound for its determinant-large tail, the monotone
cubic aggregation of overlapping canonical-kernel catalogues, and a weighted
cubic incidence inequality.  It also checks the precise powerful,
pairwise-coprime counterexample to the false shortcut that subtracts only the
threshold.  It assumes no exceptional-point lower bound and proves no abc
statement.
-/

namespace IUTThreeClosures
namespace AffineCatalogueWeightOverlap20260901

open scoped BigOperators

/-! ## Exact actual divisor-catalogue weights -/

/-- Euler-totient weight of one three-coordinate divisor label. -/
def totientTripleWeight (eU eV eW : ℕ) : ℕ :=
  Nat.totient eU * Nat.totient eV * Nat.totient eW

/-- Total weight of the complete downward divisor catalogue. -/
def divisorTripleCatalogueWeight (dU dV dW : ℕ) : ℕ :=
  ∑ eU ∈ dU.divisors,
    ∑ eV ∈ dV.divisors,
      ∑ eW ∈ dW.divisors, totientTripleWeight eU eV eW

/-- Weight of divisor labels whose component product is at most `T`. -/
def smallDivisorTripleWeight (dU dV dW T : ℕ) : ℕ :=
  ∑ eU ∈ dU.divisors,
    ∑ eV ∈ dV.divisors,
      ∑ eW ∈ dW.divisors,
        if eU * eV * eW ≤ T then totientTripleWeight eU eV eW else 0

/-- Weight of divisor labels whose component product is larger than `T`. -/
def largeDivisorTripleWeight (dU dV dW T : ℕ) : ℕ :=
  ∑ eU ∈ dU.divisors,
    ∑ eV ∈ dV.divisors,
      ∑ eW ∈ dW.divisors,
        if T < eU * eV * eW then totientTripleWeight eU eV eW else 0

/-- Number of triples in the complete downward divisor catalogue. -/
def divisorTripleCatalogueCard (dU dV dW : ℕ) : ℕ :=
  dU.divisors.card * dV.divisors.card * dW.divisors.card

/-- The actual three-coordinate catalogue has total totient weight exactly
the product of its three top components. -/
theorem divisorTripleCatalogueWeight_eq_product (dU dV dW : ℕ) :
    divisorTripleCatalogueWeight dU dV dW = dU * dV * dW := by
  simp only [divisorTripleCatalogueWeight, totientTripleWeight]
  simp_rw [← Finset.mul_sum]
  rw [Nat.sum_totient]
  simp_rw [← Finset.sum_mul]
  have hUV :
      (∑ eU ∈ dU.divisors,
        ∑ eV ∈ dV.divisors,
          Nat.totient eU * Nat.totient eV) = dU * dV := by
    simp_rw [← Finset.mul_sum]
    rw [Nat.sum_totient]
    simp_rw [← Finset.sum_mul]
    rw [Nat.sum_totient]
  rw [hUV]

/-- The small- and large-product pieces partition the full catalogue. -/
theorem small_add_large_eq_catalogue (dU dV dW T : ℕ) :
    smallDivisorTripleWeight dU dV dW T +
      largeDivisorTripleWeight dU dV dW T =
        divisorTripleCatalogueWeight dU dV dW := by
  simp only [smallDivisorTripleWeight, largeDivisorTripleWeight,
    divisorTripleCatalogueWeight]
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro eU heU
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro eV heV
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro eW heW
  by_cases h : eU * eV * eW ≤ T
  · simp [h, Nat.not_lt_of_ge h]
  · have hlt : T < eU * eV * eW := Nat.lt_of_not_ge h
    simp [h, hlt]

/-- Every small-product label has weight at most the threshold; summing over
the actual number of divisor triples gives the finite discarded-weight
bound. -/
theorem smallDivisorTripleWeight_le
    (dU dV dW T : ℕ) :
    smallDivisorTripleWeight dU dV dW T ≤
      T * divisorTripleCatalogueCard dU dV dW := by
  simp only [smallDivisorTripleWeight, divisorTripleCatalogueCard]
  calc
    (∑ eU ∈ dU.divisors,
      ∑ eV ∈ dV.divisors,
        ∑ eW ∈ dW.divisors,
          if eU * eV * eW ≤ T then
            totientTripleWeight eU eV eW else 0) ≤
        ∑ _eU ∈ dU.divisors,
          ∑ _eV ∈ dV.divisors,
            ∑ _eW ∈ dW.divisors, T := by
      apply Finset.sum_le_sum
      intro eU heU
      apply Finset.sum_le_sum
      intro eV heV
      apply Finset.sum_le_sum
      intro eW heW
      split_ifs with h
      · have hweight : totientTripleWeight eU eV eW ≤
            eU * eV * eW := by
          exact Nat.mul_le_mul
            (Nat.mul_le_mul (Nat.totient_le eU) (Nat.totient_le eV))
            (Nat.totient_le eW)
        exact hweight.trans h
      · exact Nat.zero_le T
    _ = T *
        (dU.divisors.card * dV.divisors.card * dW.divisors.card) := by
      simp [mul_assoc, mul_comm, mul_left_comm]

/-- Exact finite tail inequality: the top product is paid for by the large
catalogue plus at most `T` for every possible divisor triple. -/
theorem product_le_largeWeight_add_threshold_mul_card
    (dU dV dW T : ℕ) :
    dU * dV * dW ≤
      largeDivisorTripleWeight dU dV dW T +
        T * divisorTripleCatalogueCard dU dV dW := by
  have hpartition := small_add_large_eq_catalogue dU dV dW T
  have hsmall := smallDivisorTripleWeight_le dU dV dW T
  rw [divisorTripleCatalogueWeight_eq_product] at hpartition
  omega

/-- Subtraction-free margin form of the large-tail estimate. -/
theorem margin_le_largeDivisorTripleWeight
    {dU dV dW T Q : ℕ}
    (hmargin :
      T * divisorTripleCatalogueCard dU dV dW + Q ≤ dU * dV * dW) :
    Q ≤ largeDivisorTripleWeight dU dV dW T := by
  have htail :=
    product_le_largeWeight_add_threshold_mul_card dU dV dW T
  omega

/-- The top divisor label itself belongs to the large catalogue whenever its
product exceeds the threshold.  This gives a nonzero baseline even when the
coarse divisor-count margin is not positive. -/
theorem topLabelWeight_le_largeDivisorTripleWeight
    {dU dV dW T : ℕ}
    (hU : 0 < dU) (hV : 0 < dV) (hW : 0 < dW)
    (hlarge : T < dU * dV * dW) :
    totientTripleWeight dU dV dW ≤
      largeDivisorTripleWeight dU dV dW T := by
  have hUd : dU ∈ dU.divisors :=
    Nat.mem_divisors.mpr ⟨dvd_rfl, Nat.ne_of_gt hU⟩
  have hVd : dV ∈ dV.divisors :=
    Nat.mem_divisors.mpr ⟨dvd_rfl, Nat.ne_of_gt hV⟩
  have hWd : dW ∈ dW.divisors :=
    Nat.mem_divisors.mpr ⟨dvd_rfl, Nat.ne_of_gt hW⟩
  simp only [largeDivisorTripleWeight]
  calc
    totientTripleWeight dU dV dW =
        if T < dU * dV * dW then totientTripleWeight dU dV dW else 0 := by
      simp [hlarge]
    _ ≤ ∑ eW ∈ dW.divisors,
        if T < dU * dV * eW then totientTripleWeight dU dV eW else 0 := by
      exact Finset.single_le_sum
        (s := dW.divisors)
        (f := fun eW ↦
          if T < dU * dV * eW then totientTripleWeight dU dV eW else 0)
        (fun _ _ ↦ Nat.zero_le _) hWd
    _ ≤ ∑ eV ∈ dV.divisors,
        ∑ eW ∈ dW.divisors,
          if T < dU * eV * eW then totientTripleWeight dU eV eW else 0 := by
      exact Finset.single_le_sum
        (s := dV.divisors)
        (f := fun eV ↦
          ∑ eW ∈ dW.divisors,
            if T < dU * eV * eW then totientTripleWeight dU eV eW else 0)
        (fun _ _ ↦ Nat.zero_le _) hVd
    _ ≤ ∑ eU ∈ dU.divisors,
        ∑ eV ∈ dV.divisors,
          ∑ eW ∈ dW.divisors,
            if T < eU * eV * eW then totientTripleWeight eU eV eW else 0 := by
      exact Finset.single_le_sum
        (s := dU.divisors)
        (f := fun eU ↦
          ∑ eV ∈ dV.divisors,
            ∑ eW ∈ dW.divisors,
              if T < eU * eV * eW then totientTripleWeight eU eV eW else 0)
        (fun _ _ ↦ Nat.zero_le _) hUd






/-! ## Cubic aggregation of overlapping catalogues -/

/-- Cubing is superadditive on a finite family of natural numbers. -/
theorem sum_cube_le_cube_sum
    {α : Type*} (s : Finset α) (a : α → ℕ) :
    ∑ i ∈ s, a i ^ 3 ≤ (∑ i ∈ s, a i) ^ 3 := by
  let A := ∑ i ∈ s, a i
  have hai : ∀ i ∈ s, a i ≤ A := by
    intro i hi
    exact Finset.single_le_sum (fun _ _ ↦ Nat.zero_le _) hi
  calc
    ∑ i ∈ s, a i ^ 3 ≤ ∑ i ∈ s, a i * A ^ 2 := by
      apply Finset.sum_le_sum
      intro i hi
      have hsquare : a i ^ 2 ≤ A ^ 2 := Nat.pow_le_pow_left (hai i hi) 2
      calc
        a i ^ 3 = a i * a i ^ 2 := by ring
        _ ≤ a i * A ^ 2 := Nat.mul_le_mul_left (a i) hsquare
    _ = A ^ 3 := by
      rw [← Finset.sum_mul]
      simp only [A]
      ring

/-- Monotone-overlap theorem.  If the occupancy of every label dominates the
sum of the sizes of all kernel classes supporting that label, overlapping
catalogues can only increase the weighted cubic energy. -/
theorem monotone_overlap_cubicEnergy_lower
    {κ ι : Type*}
    (kernels : Finset κ) (labels : Finset ι)
    (supports : κ → ι → Prop) (weight : ι → ℕ)
    [DecidableRel supports]
    (multiplicity : κ → ℕ) (occupancy : ι → ℕ)
    (hoccupancy : ∀ e ∈ labels,
      ∑ k ∈ kernels with supports k e, multiplicity k ≤ occupancy e) :
    ∑ k ∈ kernels,
        multiplicity k ^ 3 *
          (∑ e ∈ labels with supports k e, weight e) ≤
      ∑ e ∈ labels, weight e * occupancy e ^ 3 := by
  classical
  calc
    ∑ k ∈ kernels,
        multiplicity k ^ 3 *
          (∑ e ∈ labels with supports k e, weight e) =
      ∑ e ∈ labels,
        weight e *
          (∑ k ∈ kernels with supports k e, multiplicity k ^ 3) := by
      simp_rw [Finset.mul_sum, Finset.sum_filter]
      rw [Finset.sum_comm]
      apply Finset.sum_congr rfl
      intro e he
      apply Finset.sum_congr rfl
      intro k hk
      by_cases h : supports k e <;> simp [h, mul_comm]
    _ ≤ ∑ e ∈ labels, weight e * occupancy e ^ 3 := by
      apply Finset.sum_le_sum
      intro e he
      apply Nat.mul_le_mul_left
      calc
        ∑ k ∈ kernels with supports k e, multiplicity k ^ 3 ≤
            (∑ k ∈ kernels with supports k e, multiplicity k) ^ 3 :=
          sum_cube_le_cube_sum _ _
        _ ≤ occupancy e ^ 3 :=
          Nat.pow_le_pow_left (hoccupancy e he) 3


/-! ## Weighted cubic incidence inequality -/

/-- Weighted Hölder in polynomial form.  This fallback uses only total
weighted incidence and total catalogue weight. -/
theorem weightedIncidence_cube_le_weight_sq_mul_cubicEnergy
    {α : Type*} (s : Finset α) (weight count : α → ℝ)
    (hweight : ∀ i ∈ s, 0 ≤ weight i)
    (hcount : ∀ i ∈ s, 0 ≤ count i) :
    (∑ i ∈ s, weight i * count i) ^ 3 ≤
      (∑ i ∈ s, weight i) ^ 2 *
        ∑ i ∈ s, weight i * count i ^ 3 := by
  let I : ℝ := ∑ i ∈ s, weight i * count i
  let W : ℝ := ∑ i ∈ s, weight i
  let Q : ℝ := ∑ i ∈ s, weight i * count i ^ 2
  let E : ℝ := ∑ i ∈ s, weight i * count i ^ 3
  have hI : 0 ≤ I := by
    dsimp [I]
    exact Finset.sum_nonneg fun i hi ↦
      mul_nonneg (hweight i hi) (hcount i hi)
  have hW : 0 ≤ W := by
    dsimp [W]
    exact Finset.sum_nonneg hweight
  have hQ : 0 ≤ Q := by
    dsimp [Q]
    exact Finset.sum_nonneg fun i hi ↦
      mul_nonneg (hweight i hi) (sq_nonneg (count i))
  have hE : 0 ≤ E := by
    dsimp [E]
    exact Finset.sum_nonneg fun i hi ↦
      mul_nonneg (hweight i hi)
        (mul_nonneg (sq_nonneg (count i)) (hcount i hi))
  have hIQ : I ^ 2 ≤ W * Q := by
    dsimp [I, W, Q]
    exact Finset.sum_sq_le_sum_mul_sum_of_sq_le_mul s
      hweight
      (fun i hi ↦ mul_nonneg (hweight i hi) (sq_nonneg (count i)))
      (fun i hi ↦ by ring_nf; exact le_rfl)
  have hQE : Q ^ 2 ≤ I * E := by
    dsimp [Q, I, E]
    exact Finset.sum_sq_le_sum_mul_sum_of_sq_le_mul s
      (fun i hi ↦ mul_nonneg (hweight i hi) (hcount i hi))
      (fun i hi ↦ mul_nonneg (hweight i hi)
        (mul_nonneg (sq_nonneg (count i)) (hcount i hi)))
      (fun i hi ↦ by ring_nf; exact le_rfl)
  change I ^ 3 ≤ W ^ 2 * E
  by_cases hIz : I = 0
  · rw [hIz]
    norm_num
    exact mul_nonneg (sq_nonneg W) hE
  · have hIpos : 0 < I := lt_of_le_of_ne hI (Ne.symm hIz)
    have hIQsq : I ^ 4 ≤ W ^ 2 * Q ^ 2 := by
      have h := mul_self_le_mul_self (sq_nonneg I) hIQ
      nlinarith
    have hQEw : W ^ 2 * Q ^ 2 ≤ W ^ 2 * (I * E) :=
      mul_le_mul_of_nonneg_left hQE (sq_nonneg W)
    have hchain : I ^ 4 ≤ W ^ 2 * (I * E) := hIQsq.trans hQEw
    have hcancel : I * I ^ 3 ≤ I * (W ^ 2 * E) := by
      nlinarith
    have hfinal : I ^ 3 ≤ W ^ 2 * E :=
      le_of_mul_le_mul_left hcancel hIpos
    exact hfinal

/-- Shifted weighted Hölder.  This is the form that matches the exact affine
ray estimate, whose natural variable is `occupancy - 1`. -/
theorem weightedShiftedIncidence_cube_le
    {α : Type*} (s : Finset α) (weight : α → ℝ) (count : α → ℕ)
    (hweight : ∀ i ∈ s, 0 ≤ weight i) :
    (∑ i ∈ s, weight i * ((count i - 1 : ℕ) : ℝ)) ^ 3 ≤
      (∑ i ∈ s, weight i) ^ 2 *
        ∑ i ∈ s, weight i * ((count i - 1 : ℕ) : ℝ) ^ 3 := by
  exact weightedIncidence_cube_le_weight_sq_mul_cubicEnergy s weight
    (fun i ↦ ((count i - 1 : ℕ) : ℝ)) hweight
    (fun _ _ ↦ Nat.cast_nonneg _)

/-- If every label in the catalogue occurs, weighted incidence splits exactly
as catalogue weight plus shifted incidence. -/
theorem weightedIncidence_eq_catalogue_add_shifted
    {α : Type*} (s : Finset α) (weight : α → ℝ) (count : α → ℕ)
    (hcount : ∀ i ∈ s, 1 ≤ count i) :
    (∑ i ∈ s, weight i * (count i : ℝ)) =
      (∑ i ∈ s, weight i) +
        ∑ i ∈ s, weight i * ((count i - 1 : ℕ) : ℝ) := by
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro i hi
  have hci : 1 ≤ count i := hcount i hi
  have hdecomp : count i = 1 + (count i - 1) := by
    omega
  have hcast : (count i : ℝ) = 1 + ((count i - 1 : ℕ) : ℝ) := by
    exact_mod_cast hdecomp
  rw [hcast]
  ring

/-- Polynomial overlap lower bound.  Here `I-W` is exactly the weighted
incidence contributed beyond the first occurrence of every label. -/
theorem weightedIncidence_sub_catalogue_cube_le_shiftedEnergy
    {α : Type*} (s : Finset α) (weight : α → ℝ) (count : α → ℕ)
    (hweight : ∀ i ∈ s, 0 ≤ weight i)
    (hcount : ∀ i ∈ s, 1 ≤ count i) :
    ((∑ i ∈ s, weight i * (count i : ℝ)) -
        ∑ i ∈ s, weight i) ^ 3 ≤
      (∑ i ∈ s, weight i) ^ 2 *
        ∑ i ∈ s, weight i * ((count i - 1 : ℕ) : ℝ) ^ 3 := by
  have hsplit := weightedIncidence_eq_catalogue_add_shifted
    s weight count hcount
  have hsub :
      (∑ i ∈ s, weight i * (count i : ℝ)) -
          ∑ i ∈ s, weight i =
        ∑ i ∈ s, weight i * ((count i - 1 : ℕ) : ℝ) := by
    linarith
  rw [hsub]
  exact weightedShiftedIncidence_cube_le s weight count hweight

/-- Aggregated shifted-cap consequence.  Labels may lie on different rays;
only their individual shifted-cube caps enter, so no raw number-of-rays
factor is introduced. -/
theorem weightedShiftedIncidence_cube_le_of_caps
    {α : Type*} (s : Finset α) (weight : α → ℝ)
    (count : α → ℕ) (cap : α → ℝ)
    (hweight : ∀ i ∈ s, 0 ≤ weight i)
    (hcap : ∀ i ∈ s, ((count i - 1 : ℕ) : ℝ) ^ 3 ≤ cap i) :
    (∑ i ∈ s, weight i * ((count i - 1 : ℕ) : ℝ)) ^ 3 ≤
      (∑ i ∈ s, weight i) ^ 2 *
        ∑ i ∈ s, weight i * cap i := by
  calc
    (∑ i ∈ s, weight i * ((count i - 1 : ℕ) : ℝ)) ^ 3 ≤
        (∑ i ∈ s, weight i) ^ 2 *
          ∑ i ∈ s, weight i * ((count i - 1 : ℕ) : ℝ) ^ 3 :=
      weightedShiftedIncidence_cube_le s weight count hweight
    _ ≤ (∑ i ∈ s, weight i) ^ 2 *
          ∑ i ∈ s, weight i * cap i := by
      apply mul_le_mul_of_nonneg_left
      · apply Finset.sum_le_sum
        intro i hi
        exact mul_le_mul_of_nonneg_left (hcap i hi) (hweight i hi)
      · exact sq_nonneg _




/-! ## Exact counterexample to a false tail strengthening -/

/-- The powerful, pairwise-coprime catalogue `(9,25,1)` at threshold five
has total weight `225` but small weight seven and large weight `218`. -/
theorem powerful_pairwiseCatalogue_tail_counterexample :
    Nat.Coprime 9 25 ∧ Nat.Coprime 9 1 ∧ Nat.Coprime 25 1 ∧
      5 < 9 * 25 * 1 ∧
      smallDivisorTripleWeight 9 25 1 5 = 7 ∧
      largeDivisorTripleWeight 9 25 1 5 = 218 ∧
      largeDivisorTripleWeight 9 25 1 5 < 9 * 25 * 1 - 5 := by
  decide

end AffineCatalogueWeightOverlap20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/AffineCatalogueWeightOverlap20260901.lean -/

/- BEGIN EXACT BODY: IUTThreeClosures/IUTRationalDegreeOneSourceRealization20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/


/-!
# A source-faithful rational degree-one tripod realization

The mathematical proofs precede this module in
`research/ABC_IUT_RATIONAL_DEGREE_ONE_SOURCE_REALIZATION_2026_09_01.md`.

This file isolates the abstract core of the genuine rational-tripod source
calculation.  A realization maps open rational points to exact-degree-one
tripod points, identifies the pulled-back log-canonical height and conductor
with the elementary rational functions up to bounded discrepancy, and makes
the rational different zero.  Its restricted Statement I is exactly integer
abc.  No intended arithmetic `Genl.HeightTheory`, IUT theorem, Statement I, or
abc assertion is postulated here.
-/

namespace IUTThreeClosures
namespace IUTRationalDegreeOneSourceRealization20260901

open IUTAdmissibleVolumeIntegerBridge20260901
open IUTRationalTripodShadowComparison20260901

/-! ## Degree one is forced by the abstract recurrence -/

/-- In every `Genl.HeightTheory`, the degree-at-most-one and exact-degree-one
loci coincide.  This follows solely from `ptLE_zero` and `ptLE_succ`. -/
theorem ptLE_one_eq_ptEQ_one (T : Genl.HeightTheory) (X : T.Curve) :
    T.ptLE X 1 = T.ptEQ X 1 := by
  have h := T.ptLE_succ X 0
  simpa [T.ptLE_zero X] using h

/-- Exact-degree-one membership therefore supplies the degree-at-most-one
membership used by Statement I. -/
theorem mem_ptLE_one_of_mem_ptEQ_one
    (T : Genl.HeightTheory) (X : T.Curve) {x : T.Pt X}
    (hx : x ∈ T.ptEQ X 1) : x ∈ T.ptLE X 1 := by
  rwa [ptLE_one_eq_ptEQ_one T X]

/-! ## Source-faithful realization and restricted Statement I -/

/-- Source-faithful data for the positive rational chart of the genuine
degree-one tripod.

The exact arithmetic construction of these fields from
`(ℙ¹_ℚ, {0,1,∞})` is proved in the companion research note.  This structure is
an explicit interface; it is not asserted to be inhabited by the current
abstract LANA `HeightTheory`. -/
structure RationalDegreeOneSourceRealization (T : Genl.HeightTheory) where
  point : OpenUnitRational → T.Pt T.tripod
  point_mem_degreeOne : ∀ x, point x ∈ T.ptEQ T.tripod 1
  height_equiv :
    (fun x => T.htCan T.tripod (point x)) ≈[(Set.univ : Set OpenUnitRational)]
      openUnitHeight
  logDiff_eq_zero : ∀ x, T.logDiff T.tripod (point x) = 0
  conductor_equiv :
    (fun x => T.logCond T.tripod (point x)) ≈[(Set.univ : Set OpenUnitRational)]
      openUnitCounting

namespace RationalDegreeOneSourceRealization

variable {T : Genl.HeightTheory} (R : RationalDegreeOneSourceRealization T)

/-- Pulled-back source height. -/
noncomputable def sourceHeight (x : OpenUnitRational) : ℝ :=
  T.htCan T.tripod (R.point x)

/-- Pulled-back source different. -/
noncomputable def sourceDifferent (x : OpenUnitRational) : ℝ :=
  T.logDiff T.tripod (R.point x)

/-- Pulled-back source conductor. -/
noncomputable def sourceConductor (x : OpenUnitRational) : ℝ :=
  T.logCond T.tripod (R.point x)

/-- Statement I restricted to the realized positive rational degree-one
tripod chart.  The additive constant may depend on `ε`, but not on the point. -/
def RestrictedStatementI : Prop :=
  UniformOpenUnitBound R.sourceHeight R.sourceDifferent R.sourceConductor

/-- Exact-degree-one source points lie in the locus on which full Statement I
with `d = 1` is stated. -/
theorem point_mem_degreeAtMostOne (x : OpenUnitRational) :
    R.point x ∈ T.ptLE T.tripod 1 :=
  mem_ptLE_one_of_mem_ptEQ_one T T.tripod (R.point_mem_degreeOne x)

/-- The source-faithful realization extracts the earlier one-sided comparison.
The selected errors are the needed directions of the two BD equivalences. -/
noncomputable def toOpenUnitTripodComparison : OpenUnitTripodComparison T := by
  refine
    { encode := R.point
      encode_mem_degreeAtMostOne := R.point_mem_degreeAtMostOne
      heightError := Classical.choose R.height_equiv.ge
      radicalError := Classical.choose R.conductor_equiv.le
      height_le := ?_
      logDiff_add_logCond_le := ?_ }
  · intro x
    exact (Classical.choose_spec R.height_equiv.ge) x (Set.mem_univ x)
  · intro x
    have hc := (Classical.choose_spec R.conductor_equiv.le) x (Set.mem_univ x)
    rw [R.logDiff_eq_zero x, zero_add]
    exact hc

/-- Full Statement I restricts to the realized degree-one chart. -/
theorem restrictedStatementI_of_statementI
    (hI : T.StatementI) : R.RestrictedStatementI := by
  intro ε hε
  obtain ⟨C, hC⟩ := hI T.tripod T.hyperbolic_tripod 1 ε hε
  refine ⟨C, ?_⟩
  intro x
  have h := hC (R.point x) (R.point_mem_degreeAtMostOne x)
  simpa only [sourceHeight, sourceDifferent, sourceConductor,
    Pi.smul_apply, Pi.add_apply, smul_eq_mul] using h

/-- The source-restricted Statement I is exactly the repository's integer abc
statement.  Both directions keep every additive error uniform in the rational
point. -/
theorem restrictedStatementI_iff_abc :
    R.RestrictedStatementI ↔ ABCConjecture := by
  constructor
  · intro hsource
    apply abc_of_uniformRationalSUnitTripodBound
    intro ε hε
    obtain ⟨C, hC⟩ := hsource ε hε
    obtain ⟨AH, hAH⟩ := R.height_equiv.ge
    obtain ⟨BN, hBN⟩ := R.conductor_equiv.le
    refine ⟨C + AH + (1 + ε) * BN, ?_⟩
    intro x hx0 hx1
    let y : OpenUnitRational := ⟨x, hx0, hx1⟩
    have hheight := hAH y (Set.mem_univ y)
    have hbound := hC y
    have hcond := hBN y (Set.mem_univ y)
    change openUnitHeight y ≤ R.sourceHeight y + AH at hheight
    change R.sourceHeight y ≤
      (1 + ε) * (R.sourceDifferent y + R.sourceConductor y) + C at hbound
    change R.sourceConductor y ≤ openUnitCounting y + BN at hcond
    have hdiff : R.sourceDifferent y = 0 := R.logDiff_eq_zero y
    rw [hdiff, zero_add] at hbound
    have hcoefficient : 0 ≤ 1 + ε := by linarith
    have hscaled := mul_le_mul_of_nonneg_left hcond hcoefficient
    change rationalTripodHeight x ≤
      (1 + ε) * rationalTripodCounting x +
        (C + AH + (1 + ε) * BN)
    dsimp [openUnitHeight, openUnitCounting, y] at hheight hscaled
    linarith
  · intro habc ε hε
    obtain ⟨C, hC⟩ :=
      uniformRationalSUnitTripodBound_of_abc habc ε hε
    obtain ⟨AH, hAH⟩ := R.height_equiv.le
    obtain ⟨BN, hBN⟩ := R.conductor_equiv.ge
    refine ⟨C + AH + (1 + ε) * BN, ?_⟩
    intro x
    have htarget := hC x.1 x.2.1 x.2.2
    have hheight := hAH x (Set.mem_univ x)
    have hcond := hBN x (Set.mem_univ x)
    change R.sourceHeight x ≤ openUnitHeight x + AH at hheight
    change openUnitCounting x ≤ R.sourceConductor x + BN at hcond
    have hcoefficient : 0 ≤ 1 + ε := by linarith
    have hscaled := mul_le_mul_of_nonneg_left hcond hcoefficient
    change R.sourceHeight x ≤
      (1 + ε) * (R.sourceDifferent x + R.sourceConductor x) +
        (C + AH + (1 + ε) * BN)
    rw [sourceDifferent, R.logDiff_eq_zero x, zero_add]
    dsimp [openUnitHeight, openUnitCounting] at hheight hscaled
    linarith

/-- Full Statement I plus the source realization proves integer abc. -/
theorem abc_of_statementI
    (R : RationalDegreeOneSourceRealization T)
    (hI : T.StatementI) : ABCConjecture :=
  (restrictedStatementI_iff_abc R).mp (restrictedStatementI_of_statementI R hI)

end RationalDegreeOneSourceRealization

/-! ## Consistency witness: the exact rational shadow -/

/-- The previously constructed exact rational shadow realizes every field of
the source interface with zero discrepancy.  This is a consistency witness,
not an identification with an intended arithmetic or IUT height theory. -/
noncomputable def rationalTripodShadowSourceRealization :
    RationalDegreeOneSourceRealization rationalTripodShadow where
  point := id
  point_mem_degreeOne x := by
    change x ∈ shadowPtEQ 1
    simp [shadowPtEQ]
  height_equiv := by
    simpa [rationalTripodShadow, openUnitShadowHeightTheory] using
      (DiscrepancyEquiv.refl openUnitHeight (Set.univ : Set OpenUnitRational))
  logDiff_eq_zero x := by
    simp [rationalTripodShadow, openUnitShadowHeightTheory]
  conductor_equiv := by
    simpa [rationalTripodShadow, openUnitShadowHeightTheory] using
      (DiscrepancyEquiv.refl openUnitCounting (Set.univ : Set OpenUnitRational))

/-! ## The abstract proof package does not force source semantics -/

/-- Even the degree-empty pressure model admits every field of the abstract
`Genl.HeightTheory.ProofPackage`.  Its degree loci are empty, and the Belyi
failure premise contradicts the vacuous BD inequality. -/
noncomputable def degreeEmptyProofPackage :
    Genl.HeightTheory.ProofPackage degreeEmptyHeightTheory where
  covering X hX d ε hε :=
    { Y := ()
      hyperbolic := True.intro
      divisorFree := True.intro
      d' := 0
      π := fun _ => ()
      surjOn := by
        intro x hx
        change x ∈ (∅ : Set Unit) at hx
        exact hx.elim
      logDiff_le := DiscrepancyLE.empty
      htCan_le := DiscrepancyLE.empty }
  belyi X hX hD d ε hε hnot :=
    False.elim (hnot DiscrepancyLE.empty)

/-- Full `HeightTheory`, full `ProofPackage`, and Statement I still do not
manufacture a rational degree-one realization in the degree-empty model. -/
theorem degreeEmpty_fullGenlPremise_countermodel :
    degreeEmptyHeightTheory.StatementI ∧
      Nonempty (Genl.HeightTheory.ProofPackage degreeEmptyHeightTheory) ∧
      ¬ Nonempty (OpenUnitTripodComparison degreeEmptyHeightTheory) :=
  ⟨degreeEmptyHeightTheory_statementI, ⟨degreeEmptyProofPackage⟩,
    degreeEmptyHeightTheory_no_openUnitComparison⟩

/-- The height-zero pressure model also admits the full abstract proof package.
The identity covering supplies its comparisons, and the Belyi failure premise
is impossible because zero is BD-dominated by zero. -/
noncomputable def heightZeroProofPackage :
    Genl.HeightTheory.ProofPackage heightZeroShadow where
  covering X hX d ε hε :=
    { Y := ()
      hyperbolic := True.intro
      divisorFree := True.intro
      d' := d
      π := id
      surjOn := by
        intro x hx
        exact ⟨x, hx, rfl⟩
      logDiff_le := DiscrepancyLE.of_forall_le (by
        intro x hx
        change (0 : ℝ) ≤ 0 + openUnitCounting x
        simpa using openUnitCounting_nonneg x)
      htCan_le := DiscrepancyLE.of_forall_le (by
        intro x hx
        change (0 : ℝ) ≤ (1 + ε) * 0
        simp) }
  belyi X hX hD d ε hε hnot :=
    False.elim (hnot (DiscrepancyLE.of_forall_le (by
      intro x hx
      change (0 : ℝ) ≤ (1 + ε) * 0
      simp)))

/-- Adding the full abstract proof package does not repair the missing uniform
height comparison in the height-zero model. -/
theorem heightZero_fullGenlPremise_countermodel :
    heightZeroShadow.StatementI ∧
      Nonempty (Genl.HeightTheory.ProofPackage heightZeroShadow) ∧
      (∀ x : OpenUnitRational,
        x ∈ heightZeroShadow.ptLE heightZeroShadow.tripod 1) ∧
      (∀ x : OpenUnitRational,
        heightZeroShadow.logDiff heightZeroShadow.tripod x +
          heightZeroShadow.logCond heightZeroShadow.tripod x =
            openUnitCounting x) ∧
      ¬ ∃ A : ℝ, ∀ x : OpenUnitRational,
        openUnitHeight x ≤
          heightZeroShadow.htCan heightZeroShadow.tripod x + A :=
  ⟨heightZeroShadow_statementI, ⟨heightZeroProofPackage⟩,
    heightZeroShadow_degree_mem, heightZeroShadow_radical_exact,
    heightZeroShadow_no_uniform_height_error⟩

/-- The different-inflated pressure model likewise admits the full abstract
proof package.  Its inflated different makes the negated Belyi premise
impossible. -/
noncomputable def radicalInflatedProofPackage :
    Genl.HeightTheory.ProofPackage radicalInflatedShadow where
  covering X hX d ε hε :=
    { Y := ()
      hyperbolic := True.intro
      divisorFree := True.intro
      d' := d
      π := id
      surjOn := by
        intro x hx
        exact ⟨x, hx, rfl⟩
      logDiff_le := DiscrepancyLE.of_forall_le (by
        intro x hx
        change inflatedDifferent x ≤ inflatedDifferent x + openUnitCounting x
        linarith [openUnitCounting_nonneg x])
      htCan_le := DiscrepancyLE.of_forall_le (by
        intro x hx
        change openUnitHeight x ≤ (1 + ε) * openUnitHeight x
        have hH := openUnitHeight_nonneg x
        nlinarith) }
  belyi X hX hD d ε hε hnot :=
    False.elim (hnot (DiscrepancyLE.of_forall_le (by
      intro x hx
      change openUnitHeight x ≤ (1 + ε) * inflatedDifferent x
      have hH := openUnitHeight_nonneg x
      have hExp := Real.add_one_le_exp (2 * openUnitHeight x)
      have hPos := Real.exp_pos (2 * openUnitHeight x)
      dsimp [inflatedDifferent]
      nlinarith)))

/-! ## Full-premise pressure test for conductor normalization -/

/-- Actual rational height and exact zero different, with an unbounded term
inserted specifically into the conductor field. -/
noncomputable def conductorInflatedShadow : Genl.HeightTheory :=
  openUnitShadowHeightTheory openUnitHeight (fun _ => 0)
    (fun x => openUnitCounting x + inflatedDifferent x)

/-- The conductor-inflated shadow still satisfies Statement I. -/
theorem conductorInflatedShadow_statementI :
    conductorInflatedShadow.StatementI := by
  change (openUnitShadowHeightTheory openUnitHeight (fun _ => 0)
    (fun x => openUnitCounting x + inflatedDifferent x)).StatementI
  rw [openUnitShadow_statementI_iff]
  intro ε hε
  refine ⟨0, ?_⟩
  intro x
  have hH : 0 ≤ openUnitHeight x := openUnitHeight_nonneg x
  have hcount : 0 ≤ openUnitCounting x := openUnitCounting_nonneg x
  have hexp : 1 + 2 * openUnitHeight x ≤ inflatedDifferent x := by
    simpa [inflatedDifferent, add_comm] using
      (Real.add_one_le_exp (2 * openUnitHeight x))
  have hmass : 0 ≤ openUnitCounting x + inflatedDifferent x :=
    add_nonneg hcount (Real.exp_pos _).le
  have hheightMass :
      openUnitHeight x ≤ openUnitCounting x + inflatedDifferent x := by
    linarith
  have hscale :
      openUnitCounting x + inflatedDifferent x ≤
        (1 + ε) * (openUnitCounting x + inflatedDifferent x) := by
    nlinarith
  change openUnitHeight x ≤
    (1 + ε) * (0 + (openUnitCounting x + inflatedDifferent x)) + 0
  linarith

theorem conductorInflatedShadow_degreeOne (x : OpenUnitRational) :
    x ∈ conductorInflatedShadow.ptEQ conductorInflatedShadow.tripod 1 := by
  change x ∈ shadowPtEQ 1
  simp [shadowPtEQ]

theorem conductorInflatedShadow_height_exact (x : OpenUnitRational) :
    conductorInflatedShadow.htCan conductorInflatedShadow.tripod x =
      openUnitHeight x := by
  rfl

theorem conductorInflatedShadow_different_zero (x : OpenUnitRational) :
    conductorInflatedShadow.logDiff conductorInflatedShadow.tripod x = 0 := by
  rfl

/-- No uniform upper conductor discrepancy exists in the inflated model. -/
theorem conductorInflatedShadow_no_uniform_conductor_upper :
    ¬ ∃ B : ℝ, ∀ x : OpenUnitRational,
      conductorInflatedShadow.logCond conductorInflatedShadow.tripod x ≤
        openUnitCounting x + B := by
  rintro ⟨B, hB⟩
  obtain ⟨x, hx⟩ := openUnitHeight_unbounded ((B - 1) / 2)
  have hexpLower := Real.add_one_le_exp (2 * openUnitHeight x)
  have hexpGt : B < inflatedDifferent x := by
    dsimp [inflatedDifferent]
    linarith
  have hle := hB x
  change openUnitCounting x + inflatedDifferent x ≤
    openUnitCounting x + B at hle
  linarith

/-- All retained premises of the conductor-normalization pressure test in one
statement. -/
theorem conductorInflatedShadow_fullPremise_countermodel :
    conductorInflatedShadow.StatementI ∧
      (∀ x : OpenUnitRational,
        x ∈ conductorInflatedShadow.ptEQ conductorInflatedShadow.tripod 1) ∧
      (∀ x : OpenUnitRational,
        conductorInflatedShadow.htCan conductorInflatedShadow.tripod x =
          openUnitHeight x) ∧
      (∀ x : OpenUnitRational,
        conductorInflatedShadow.logDiff conductorInflatedShadow.tripod x = 0) ∧
      ¬ ∃ B : ℝ, ∀ x : OpenUnitRational,
        conductorInflatedShadow.logCond conductorInflatedShadow.tripod x ≤
          openUnitCounting x + B :=
  ⟨conductorInflatedShadow_statementI,
    conductorInflatedShadow_degreeOne,
    conductorInflatedShadow_height_exact,
    conductorInflatedShadow_different_zero,
    conductorInflatedShadow_no_uniform_conductor_upper⟩

/-! ## The current record does not force zero different -/

/-- The already constructed different-inflated model keeps exact degree,
height, and conductor, satisfies Statement I, but its different is nowhere
zero. -/
theorem differentInflatedShadow_fullPremise_countermodel :
    radicalInflatedShadow.StatementI ∧
      Nonempty (Genl.HeightTheory.ProofPackage radicalInflatedShadow) ∧
      (∀ x : OpenUnitRational,
        x ∈ radicalInflatedShadow.ptEQ radicalInflatedShadow.tripod 1) ∧
      (∀ x : OpenUnitRational,
        radicalInflatedShadow.htCan radicalInflatedShadow.tripod x =
          openUnitHeight x) ∧
      (∀ x : OpenUnitRational,
        radicalInflatedShadow.logCond radicalInflatedShadow.tripod x =
          openUnitCounting x) ∧
      (∀ x : OpenUnitRational,
        radicalInflatedShadow.logDiff radicalInflatedShadow.tripod x ≠ 0) := by
  refine ⟨radicalInflatedShadow_statementI, ⟨radicalInflatedProofPackage⟩,
    ?_, ?_, ?_, ?_⟩
  · intro x
    change x ∈ shadowPtEQ 1
    simp [shadowPtEQ]
  · exact radicalInflatedShadow_height_exact
  · intro x
    rfl
  · intro x
    change inflatedDifferent x ≠ 0
    exact (Real.exp_pos _).ne'

/-! ## Reverse-direction full-premise sequence countermodels -/

/-- A target bound and exact radical comparison do not transport backwards if
the source height lacks a uniform upper comparison to the target height. -/
theorem counterexample_reverse_without_source_height_upper :
    ∃ (sourceHeight sourceRadical targetHeight targetRadical : ℕ → ℝ),
      UniformEpsilonBound targetHeight targetRadical ∧
      (∀ n, targetRadical n ≤ sourceRadical n) ∧
      ¬ UniformEpsilonBound sourceHeight sourceRadical := by
  refine ⟨(fun n => (n : ℝ)), (fun _ => 0), (fun _ => 0), (fun _ => 0),
    uniformEpsilonBound_zero, ?_, not_uniformEpsilonBound_nat_zero⟩
  simp

/-- A target bound and exact height comparison do not transport backwards if
the target radical lacks a uniform upper comparison to the source radical. -/
theorem counterexample_reverse_without_target_radical_upper :
    ∃ (sourceHeight sourceRadical targetHeight targetRadical : ℕ → ℝ),
      UniformEpsilonBound targetHeight targetRadical ∧
      (∀ n, sourceHeight n ≤ targetHeight n) ∧
      ¬ UniformEpsilonBound sourceHeight sourceRadical := by
  refine ⟨(fun n => (n : ℝ)), (fun _ => 0),
    (fun n => (n : ℝ)), (fun n => (n : ℝ)),
    uniformEpsilonBound_nat_self, ?_, not_uniformEpsilonBound_nat_zero⟩
  simp














end IUTRationalDegreeOneSourceRealization20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/IUTRationalDegreeOneSourceRealization20260901.lean -/

/- BEGIN EXACT BODY: IUTThreeClosures/MersenneBalancedMultiplierDepthLocalization20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/


/-!
# Balanced multiplier and depth localization for Mersenne order blocks

The mathematical proofs precede this file in
`research/ABC_MERSENNE_BALANCED_MULTIPLIER_DEPTH_LOCALIZATION_2026_09_01.md`.

The new finite core is a multiplier-energy estimate.  Distinct positive
integral labels below `H` have total label at most `H * (H - 1) / 2` and
cardinality at most `H - 1`.  Consequently, any nonnegative weight admitting
a pointwise affine envelope in the multiplier has an exact triangular-energy
bound.  The paper combines this fact with Yamada's published explicit
`p`-adic logarithm estimate.  That external analytic theorem, and the passage
to moving real logarithmic thresholds and little-oh estimates, remain paper
mathematics rather than new Lean axioms.

The final section composes two controlled arms before applying the existing
two-arm alternative.  It also checks the actual `3511` certificate: the
base-two Wieferich prime has exact order `1755` and multiplier two, so any
universal pointwise lower bound of three is false.
-/

namespace IUTThreeClosures
namespace MersenneBalancedMultiplierDepthLocalization20260901

open scoped BigOperators
open MersenneOrderBlockDecomposition20260901
open MersenneMultiplierIndexTwoArm20260901
open MersenneSuperWieferichDepth20260901

/-! ## Triangular multiplier energy -/

/-- Injective natural labels below `H` have at most the full triangular
energy of `Finset.range H`. -/
theorem sum_injective_labels_lt_le_triangular
    (s : Finset ℕ) (label : ℕ → ℕ) (H : ℕ)
    (hinj : Set.InjOn label (s : Set ℕ))
    (hlt : ∀ x ∈ s, label x < H) :
    (∑ x ∈ s, label x) ≤ H * (H - 1) / 2 := by
  have hsubset : s.image label ⊆ Finset.range H := by
    intro y hy
    rcases Finset.mem_image.mp hy with ⟨x, hx, rfl⟩
    exact Finset.mem_range.mpr (hlt x hx)
  have hsum :
      (∑ y ∈ s.image label, y) ≤ ∑ y ∈ Finset.range H, y :=
    Finset.sum_le_sum_of_subset hsubset
  rw [Finset.sum_image hinj] at hsum
  simpa [Finset.sum_range_id] using hsum

/-- Positivity removes the zero label, sharpening the capacity from `H` to
`H - 1`. -/
theorem card_le_pred_of_positive_injective_labels_lt
    (s : Finset ℕ) (label : ℕ → ℕ) (H : ℕ)
    (hinj : Set.InjOn label (s : Set ℕ))
    (hpos : ∀ x ∈ s, 0 < label x)
    (hlt : ∀ x ∈ s, label x < H) :
    s.card ≤ H - 1 := by
  apply card_le_of_injective_multiplier_lt
      s (fun x => label x - 1) (H - 1)
  · intro x hx y hy hxy
    apply hinj hx hy
    have hxpos := hpos x hx
    have hypos := hpos y hy
    exact Nat.pred_inj hxpos hypos (by
      simpa [Nat.pred_eq_sub_one] using hxy)
  · intro x hx
    have hxpos := hpos x hx
    have hxlt := hlt x hx
    omega

/-- The triangular multiplier energy and the positive-label capacity combine
with a pointwise affine weight envelope.  In the paper `slope` is the
Yamada coefficient times `d / log d`, while `error` is a logarithmic cap. -/
theorem weighted_mass_le_triangular_envelope
    (s : Finset ℕ) (label : ℕ → ℕ) (weight : ℕ → ℝ)
    (H : ℕ) {slope error : ℝ}
    (hinj : Set.InjOn label (s : Set ℕ))
    (hpos : ∀ x ∈ s, 0 < label x)
    (hlt : ∀ x ∈ s, label x < H)
    (hslope : 0 ≤ slope) (herror : 0 ≤ error)
    (henv : ∀ x ∈ s,
      weight x ≤ slope * (label x : ℝ) + error) :
    (∑ x ∈ s, weight x) ≤
      slope * (H * (H - 1) / 2 : ℕ) +
        error * (H - 1 : ℕ) := by
  have hpoint :
      (∑ x ∈ s, weight x) ≤
        ∑ x ∈ s, (slope * (label x : ℝ) + error) := by
    exact Finset.sum_le_sum fun x hx => henv x hx
  have hlabelNat :
      (∑ x ∈ s, label x) ≤ H * (H - 1) / 2 :=
    sum_injective_labels_lt_le_triangular s label H hinj hlt
  have hlabel :
      (∑ x ∈ s, (label x : ℝ)) ≤
        (H * (H - 1) / 2 : ℕ) := by
    exact_mod_cast hlabelNat
  have hcardNat : s.card ≤ H - 1 :=
    card_le_pred_of_positive_injective_labels_lt
      s label H hinj hpos hlt
  have hcard : (s.card : ℝ) ≤ (H - 1 : ℕ) := by
    exact_mod_cast hcardNat
  calc
    (∑ x ∈ s, weight x) ≤
        ∑ x ∈ s, (slope * (label x : ℝ) + error) := hpoint
    _ = slope * (∑ x ∈ s, (label x : ℝ)) +
          error * s.card := by
      rw [Finset.sum_add_distrib]
      simp only [← Finset.mul_sum, Finset.sum_const, nsmul_eq_mul]
      ring
    _ ≤ slope * (H * (H - 1) / 2 : ℕ) +
          error * (H - 1 : ℕ) := by
      gcongr

/-! ## The actual exact-order fibre -/

/-- At an actual positive exact-order prime, the `p`-adic depth at the
Fermat exponent `p - 1` equals the canonical depth at the exact order.  This
is the exact LTE transport used before applying Yamada's paper theorem. -/
theorem factorization_fermat_eq_exactOrder
    {d p : ℕ} (hd : 0 < d) (hpMem : p ∈ exactOrderPrimeFiber d) :
    (2 ^ (p - 1) - 1).factorization p =
      (2 ^ d - 1).factorization p := by
  have hpPrimeFactors : p ∈ (2 ^ d - 1).primeFactors :=
    (Finset.mem_filter.mp hpMem).1
  have hpOrder : mersenneExactOrder p = d :=
    (Finset.mem_filter.mp hpMem).2
  have hp : p.Prime := Nat.prime_of_mem_primeFactors hpPrimeFactors
  have hpDvd : p ∣ 2 ^ d - 1 :=
    Nat.dvd_of_mem_primeFactors hpPrimeFactors
  have hdDvd : d ∣ p - 1 := by
    simpa [hpOrder] using
      (mersenneExactOrder_dvd_prime_sub_one hd hp hpDvd)
  have hpm : p ∣ 2 ^ (p - 1) - 1 :=
    hpDvd.trans (Nat.pow_sub_one_dvd_pow_sub_one 2 hdDvd)
  have hpTwo : 2 ≤ p := hp.two_le
  have hpPredPos : 0 < p - 1 := by omega
  have hlte := factorization_mersenne_eq_exactOrder_add_index
    hpPredPos hp hpm
  have hpNotDvdPred : ¬ p ∣ p - 1 := by
    intro h
    have hle : p ≤ p - 1 := Nat.le_of_dvd hpPredPos h
    omega
  have hpredFac : (p - 1).factorization p = 0 :=
    Nat.factorization_eq_zero_of_not_dvd hpNotDvdPred
  rw [hpOrder, hpredFac, add_zero] at hlte
  exact hlte

/-- Positivity of the actual order multiplier sharpens the existing exact
fibre capacity by one. -/
theorem lowMultiplierExactOrderPrimes_card_le_pred
    {d H : ℕ} (hd : 0 < d) :
    (lowMultiplierExactOrderPrimes d H).card ≤ H - 1 := by
  apply card_le_pred_of_positive_injective_labels_lt
      (lowMultiplierExactOrderPrimes d H)
      (fun p : ℕ => (p - 1) / d) H
  · intro p hp q hq hpq
    exact exactOrder_multiplier_injectiveOn d hd
      (Finset.mem_filter.mp hp).1 (Finset.mem_filter.mp hq).1 hpq
  · intro p hp
    exact exactOrder_multiplier_pos hd (Finset.mem_filter.mp hp).1
  · intro p hp
    exact (Finset.mem_filter.mp hp).2

/-- The actual multipliers below `H` obey the triangular-energy bound. -/
theorem lowMultiplierExactOrderPrimes_sum_multiplier_le
    {d H : ℕ} (hd : 0 < d) :
    (∑ p ∈ lowMultiplierExactOrderPrimes d H,
      (p - 1) / d) ≤ H * (H - 1) / 2 := by
  apply sum_injective_labels_lt_le_triangular
      (lowMultiplierExactOrderPrimes d H)
      (fun p : ℕ => (p - 1) / d) H
  · intro p hp q hq hpq
    exact exactOrder_multiplier_injectiveOn d hd
      (Finset.mem_filter.mp hp).1 (Finset.mem_filter.mp hq).1 hpq
  · intro p hp
    exact (Finset.mem_filter.mp hp).2

/-- Any affine depth envelope on the actual low-multiplier fibre inherits the
exact triangular bound.  This is deliberately generic: no unformalized
valuation estimate is asserted by the theorem. -/
theorem lowMultiplierExactOrderWeight_le_triangular_envelope
    {d H : ℕ} (hd : 0 < d) (weight : ℕ → ℝ)
    {slope error : ℝ} (hslope : 0 ≤ slope) (herror : 0 ≤ error)
    (henv : ∀ p ∈ lowMultiplierExactOrderPrimes d H,
      weight p ≤ slope * (((p - 1) / d : ℕ) : ℝ) + error) :
    (∑ p ∈ lowMultiplierExactOrderPrimes d H, weight p) ≤
      slope * (H * (H - 1) / 2 : ℕ) +
        error * (H - 1 : ℕ) := by
  apply weighted_mass_le_triangular_envelope
      (lowMultiplierExactOrderPrimes d H)
      (fun p : ℕ => (p - 1) / d) weight H
  · intro p hp q hq hpq
    exact exactOrder_multiplier_injectiveOn d hd
      (Finset.mem_filter.mp hp).1 (Finset.mem_filter.mp hq).1 hpq
  · intro p hp
    exact exactOrder_multiplier_pos hd (Finset.mem_filter.mp hp).1
  · intro p hp
    exact (Finset.mem_filter.mp hp).2
  · exact hslope
  · exact herror
  · exact henv







/-! ## Two controlled arms and two surviving arms -/

/-- Once the one-copy low-multiplier arm and the low-multiplier deep arm fit
inside one common error budget, the surviving high-multiplier deep arm or the
balanced near-square-root arm carries `share`. -/
theorem highDeep_or_balancedNearSquare_of_two_low_budgets
    {target lowOne lowDeep highDeep nearSquare share : ℝ}
    (htotal : target ≤ lowOne + lowDeep + highDeep + nearSquare)
    (hlow : lowOne + lowDeep ≤ target - 2 * share) :
    share ≤ highDeep ∨ share ≤ nearSquare := by
  apply deep_or_nearSquare_of_low_budget
      (target := target) (low := lowOne + lowDeep)
      (deep := highDeep) (nearSquare := nearSquare)
  · linarith
  · exact hlow

/-- One half remains the exact algebraic ceiling after both controlled arms
vanish. -/
theorem one_half_is_sharp_after_two_controlled_arms
    {c : ℝ} (hc : (1 : ℝ) / 2 < c) :
    ∃ target lowOne lowDeep highDeep nearSquare : ℝ,
      0 ≤ target ∧ 0 ≤ lowOne ∧ 0 ≤ lowDeep ∧
      0 ≤ highDeep ∧ 0 ≤ nearSquare ∧
      target = lowOne + lowDeep + highDeep + nearSquare ∧
      lowOne = 0 ∧ lowDeep = 0 ∧
      ¬ (c * target ≤ highDeep ∨ c * target ≤ nearSquare) := by
  refine ⟨2, 0, 0, 1, 1, ?_⟩
  constructor
  · norm_num
  constructor
  · norm_num
  constructor
  · norm_num
  constructor
  · norm_num
  constructor
  · norm_num
  constructor
  · norm_num
  constructor
  · norm_num
  constructor
  · norm_num
  push Not
  constructor <;> nlinarith


/-! ## Exact counterexamples to overstrong finite inferences -/

/-- The full packet of positive labels below `n + 1` attains the triangular
energy bound.  Keeping `n` free is essential: one isolated packet cannot
exclude a linear bound with an arbitrary constant. -/
theorem complete_positive_label_packet (n : ℕ) :
    let s := (Finset.range (n + 1)).erase 0
    Set.InjOn (fun x : ℕ => x) (s : Set ℕ) ∧
      (∀ x ∈ s, 0 < x) ∧
      (∀ x ∈ s, x < n + 1) ∧
      (∑ x ∈ s, x) = n * (n + 1) / 2 := by
  dsimp only
  constructor
  · intro x _ y _ hxy
    exact hxy
  constructor
  · intro x hx
    have hxne : x ≠ 0 := Finset.ne_of_mem_erase hx
    omega
  constructor
  · intro x hx
    exact Finset.mem_range.mp (Finset.mem_of_mem_erase hx)
  · rw [Finset.sum_erase]
    · rw [Finset.sum_range_id]
      simp [Nat.mul_comm]
    · simp

/-- No uniform natural constant times `H` bounds the energy of positive
injective labels below `H`.  For a proposed coefficient `C`, the complete
packet below `2 * (C + 1) + 1` already exceeds `C * H`. -/
theorem no_uniform_nat_linear_bound_for_positive_injective_labels
    (C : ℕ) :
    ∃ (H : ℕ) (s : Finset ℕ) (label : ℕ → ℕ),
      Set.InjOn label (s : Set ℕ) ∧
        (∀ x ∈ s, 0 < label x) ∧
        (∀ x ∈ s, label x < H) ∧
        C * H < ∑ x ∈ s, label x := by
  let n := 2 * (C + 1)
  let H := n + 1
  let s := (Finset.range H).erase 0
  refine ⟨H, s, fun x : ℕ => x, ?_⟩
  have hpacket := complete_positive_label_packet n
  change Set.InjOn (fun x : ℕ => x) (s : Set ℕ) ∧
      (∀ x ∈ s, 0 < x) ∧
      (∀ x ∈ s, x < H) ∧
      C * H < ∑ x ∈ s, x
  have hs : s = (Finset.range (n + 1)).erase 0 := by rfl
  rw [hs]
  rcases hpacket with ⟨hinj, hpos, hlt, hsum⟩
  refine ⟨hinj, hpos, hlt, ?_⟩
  rw [hsum]
  have hmul :
      n * (n + 1) = ((C + 1) * (n + 1)) * 2 := by
    dsimp [n]
    ring
  rw [hmul]
  rw [Nat.mul_div_cancel _ (by norm_num : 0 < (2 : ℕ))]
  dsimp [H]
  nlinarith

/-- The first nontrivial complete packet already refutes the coefficient-one
bound `sum label ≤ H`; the parameterized results above give the stronger
failure for every fixed linear coefficient. -/
theorem triangular_energy_exceeds_coefficient_one_at_four :
    let s : Finset ℕ := {1, 2, 3}
    Set.InjOn (fun x : ℕ => x) (s : Set ℕ) ∧
      (∀ x ∈ s, 0 < x) ∧
      (∀ x ∈ s, x < 4) ∧
      (∑ x ∈ s, x) = 6 ∧
      ¬ ((∑ x ∈ s, x) ≤ 4) := by
  norm_num

/-- `3511` is a complete actual base-two Wieferich exact-order packet with
multiplier two. -/
theorem wieferich_3511_exact_order_multiplier_two :
    Nat.Prime 3511 ∧
      mersenneExactOrder 3511 = 1755 ∧
      3511 ^ 2 ∣ 2 ^ 1755 - 1 ∧
      (3511 - 1) / 1755 = 2 := by
  exact ⟨prime_3511, mersenneExactOrder_3511,
    wieferich_3511_sq_dvd_two_pow_1755_sub_one, by norm_num⟩

/-- Therefore a universal pointwise assertion that every repeated
exact-order prime has multiplier at least three is false under all of its
displayed arithmetic premises. -/
theorem repeated_exact_order_multiplier_ge_three_false :
    ¬ (∀ p d : ℕ,
      Nat.Prime p →
      mersenneExactOrder p = d →
      p ^ 2 ∣ 2 ^ d - 1 →
      3 ≤ (p - 1) / d) := by
  intro hall
  have h := hall 3511 1755 prime_3511 mersenneExactOrder_3511
    wieferich_3511_sq_dvd_two_pow_1755_sub_one
  norm_num at h





end MersenneBalancedMultiplierDepthLocalization20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/MersenneBalancedMultiplierDepthLocalization20260901.lean -/

/- BEGIN EXACT BODY: IUTThreeClosures/PellLucasAllOrderStaircase20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/

/-!
# All-order Pell--Lucas support-unit staircases

The mathematical proofs precede this file in
`research/ABC_PELL_LUCAS_ALL_ORDER_STAIRCASE_2026_09_01.md`.

This module checks the reusable algebraic and finite core:

* splitting an even-power multiplication polynomial into a prefix and tail;
* preservation of Bezout coprimality in every normalized tail;
* the small-factor argument making an integral multiplication coefficient a
  unit at a larger prime;
* correlation of the `u` and companion-`v` fourth-order corrections;
* the two channel signs and the resulting square root of one;
* the logical refutation of fixed-zero rigidity from full local
  surjectivity;
* a kernel-reduced modular recurrence certificate for the actual
  `n=3, s=5, t=1, k=2451` counterexample.

The external all-orders Lucas multiplication theorem and Pell rank theorem
are never introduced as axioms.  Their outputs occur only as explicit
hypotheses of the algebraic results below.
-/

namespace IUTThreeClosures
namespace PellLucasAllOrderStaircase20260901

/-! ## Even-power polynomial tails -/

/-- Horner form of `sum_i a_i U^(2*i)`. -/
def evenPowerSum (U : ℤ) : List ℤ → ℤ
  | [] => 0
  | a :: as => a + U ^ 2 * evenPowerSum U as

/-- Appending coefficient packets separates a prefix from a shifted tail. -/
theorem evenPowerSum_append (U : ℤ) (as bs : List ℤ) :
    evenPowerSum U (as ++ bs) =
      evenPowerSum U as + U ^ (2 * as.length) * evenPowerSum U bs := by
  induction as with
  | nil => simp [evenPowerSum]
  | cons a as ih =>
      simp only [List.cons_append, evenPowerSum, List.length_cons]
      rw [ih]
      rw [show 2 * (as.length + 1) = 2 + 2 * as.length by omega, pow_add]
      ring

/-- Adding a multiple of `U^2` to a coefficient preserves its Bezout
coprimality with `U`. -/
theorem coprime_add_square_tail (U a h : ℤ) (ha : IsCoprime a U) :
    IsCoprime (a + U ^ 2 * h) U := by
  rcases ha with ⟨x, y, hxy⟩
  refine ⟨x, y - x * U * h, ?_⟩
  calc
    x * (a + U ^ 2 * h) + (y - x * U * h) * U =
        x * a + y * U := by ring
    _ = 1 := hxy

/-- A normalized nonempty all-order tail is a support unit as soon as its
leading coefficient is. -/
theorem evenPowerSum_coprime_of_leading
    (U a : ℤ) (as : List ℤ) (ha : IsCoprime a U) :
    IsCoprime (evenPowerSum U (a :: as)) U := by
  simpa [evenPowerSum] using
    coprime_add_square_tail U a (evenPowerSum U as) ha

/-- No nonunit divisor of `U` divides a normalized tail with a coprime
leading coefficient.  This is the divisibility form of the exact valuation
statement in the paper. -/
theorem support_not_dvd_normalized_tail
    (U a p : ℤ) (as : List ℤ)
    (ha : IsCoprime a U) (hpU : p ∣ U) (hpOne : ¬p ∣ (1 : ℤ)) :
    ¬p ∣ evenPowerSum U (a :: as) := by
  have hcop := evenPowerSum_coprime_of_leading U a as ha
  intro hpTail
  rcases hcop with ⟨x, y, hbezout⟩
  apply hpOne
  rw [← hbezout]
  exact dvd_add (dvd_mul_of_dvd_right hpTail x)
    (dvd_mul_of_dvd_right hpU y)

/-! ## The larger-prime coefficient argument -/

/-- A prime larger than every positive factor cannot divide their product. -/
theorem prime_not_dvd_list_prod_of_small
    (p : ℕ) (hp : p.Prime) (fs : List ℕ)
    (hsmall : ∀ x ∈ fs, 0 < x ∧ x < p) :
    ¬p ∣ fs.prod := by
  induction fs with
  | nil => simpa using hp.not_dvd_one
  | cons x xs ih =>
      have hx := hsmall x (by simp)
      have htail : ∀ y ∈ xs, 0 < y ∧ y < p := by
        intro y hy
        exact hsmall y (by simp [hy])
      intro hdiv
      rcases hp.dvd_mul.mp hdiv with hpx | hptail
      · exact (Nat.not_dvd_of_pos_of_lt hx.1 hx.2) hpx
      · exact (ih htail) hptail

/-- If an integral coefficient times its denominator is a product of
positive factors all smaller than `p`, then `p` cannot divide the
coefficient.  In the Pell specialization these factors are
`ell`, `ell-(2*j-1)`, and `ell+(2*j-1)`. -/
theorem integral_coefficient_not_dvd_of_small_numerator
    (p ell denominator c : ℕ) (fs : List ℕ)
    (hp : p.Prime)
    (hell : 0 < ell ∧ ell < p)
    (hsmall : ∀ x ∈ fs, 0 < x ∧ x < p)
    (hcoeff : denominator * c = ell * fs.prod) :
    ¬p ∣ c := by
  intro hpc
  have hnum : p ∣ ell * fs.prod := by
    rw [← hcoeff]
    exact dvd_mul_of_dvd_right hpc denominator
  rcases hp.dvd_mul.mp hnum with hpell | hpprod
  · exact (Nat.not_dvd_of_pos_of_lt hell.1 hell.2) hpell
  · exact prime_not_dvd_list_prod_of_small p hp fs hsmall hpprod

/-! ## Paired fourth-order corrections and channel signs -/

/-- If the two leading correction coefficients obey `ell*d=3*c`, the
normalized `u` and companion corrections obey the paired congruence. -/
theorem paired_correction_modEq
    (U ell v W S c d : ℤ)
    (hW : W ≡ c [ZMOD U ^ 2])
    (hS : S ≡ v * d [ZMOD U ^ 2])
    (hcoeff : ell * d = 3 * c) :
    ell * S ≡ 3 * v * W [ZMOD U ^ 2] := by
  calc
    ell * S ≡ ell * (v * d) [ZMOD U ^ 2] := hS.mul_left ell
    _ = v * (ell * d) := by ring
    _ = v * (3 * c) := by rw [hcoeff]
    _ = 3 * v * c := by ring
    _ ≡ 3 * v * W [ZMOD U ^ 2] := (hW.mul_left (3 * v)).symm

/-- The two channel squares divide the square of their product. -/
theorem channel_square_divisors (U A B : ℤ) (hU : U = A * B) :
    A ^ 2 ∣ U ^ 2 ∧ B ^ 2 ∣ U ^ 2 := by
  constructor
  · refine ⟨B ^ 2, ?_⟩
    rw [hU]
    ring
  · refine ⟨A ^ 2, ?_⟩
    rw [hU]
    ring

/-- The exact companion identity `v=4*A^2+2` gives the positive channel
sign. -/
theorem companion_mod_A (v A : ℤ) (hv : v = 4 * A ^ 2 + 2) :
    v ≡ 2 [ZMOD A ^ 2] := by
  apply Int.modEq_of_dvd
  refine ⟨-4, ?_⟩
  rw [hv]
  ring

/-- The exact companion identity `v=8*B^2-2` gives the negative channel
sign. -/
theorem companion_mod_B (v B : ℤ) (hv : v = 8 * B ^ 2 - 2) :
    v ≡ -2 [ZMOD B ^ 2] := by
  apply Int.modEq_of_dvd
  refine ⟨-8, ?_⟩
  rw [hv]
  ring

/-- Reduction of the paired correction to the positive channel. -/
theorem channel_A_sign
    (U A ell v W S : ℤ)
    (hAdiv : A ^ 2 ∣ U ^ 2)
    (hpair : ell * S ≡ 3 * v * W [ZMOD U ^ 2])
    (hvA : v ≡ 2 [ZMOD A ^ 2]) :
    ell * S ≡ 6 * W [ZMOD A ^ 2] := by
  have hp := Int.ModEq.of_dvd hAdiv hpair
  have hv : 3 * v * W ≡ 6 * W [ZMOD A ^ 2] := by
    have h := (hvA.mul_left 3).mul_right W
    calc
      3 * v * W = 3 * (v * W) := by ring
      _ ≡ 6 * W [ZMOD A ^ 2] := by simpa [mul_assoc] using h
  exact hp.trans hv

/-- Reduction of the paired correction to the negative channel. -/
theorem channel_B_sign
    (U B ell v W S : ℤ)
    (hBdiv : B ^ 2 ∣ U ^ 2)
    (hpair : ell * S ≡ 3 * v * W [ZMOD U ^ 2])
    (hvB : v ≡ -2 [ZMOD B ^ 2]) :
    ell * S ≡ -6 * W [ZMOD B ^ 2] := by
  have hp := Int.ModEq.of_dvd hBdiv hpair
  have hv : 3 * v * W ≡ -6 * W [ZMOD B ^ 2] := by
    have h := (hvB.mul_left 3).mul_right W
    calc
      3 * v * W ≡ (3 * (-2)) * W [ZMOD B ^ 2] := h
      _ = -6 * W := by ring
  exact hp.trans hv

/-- The exact two-channel splitter derived from the companion identities. -/
theorem paired_correction_channel_splitter
    (U A B ell v W S : ℤ)
    (hU : U = A * B)
    (hvA : v = 4 * A ^ 2 + 2)
    (hvB : v = 8 * B ^ 2 - 2)
    (hpair : ell * S ≡ 3 * v * W [ZMOD U ^ 2]) :
    ell * S ≡ 6 * W [ZMOD A ^ 2] ∧
      ell * S ≡ -6 * W [ZMOD B ^ 2] := by
  rcases channel_square_divisors U A B hU with ⟨hA, hB⟩
  exact ⟨channel_A_sign U A ell v W S hA hpair
      (companion_mod_A v A hvA),
    channel_B_sign U B ell v W S hB hpair
      (companion_mod_B v B hvB)⟩

/-! ## Cancellation and the reconstructed square root of one -/

/-- A factor coprime to the modulus cancels from a modular equality. -/
theorem cancel_coprime_factor_modEq
    (m c x y : ℤ) (hc : IsCoprime c m)
    (h : c * x ≡ c * y [ZMOD m]) : x ≡ y [ZMOD m] := by
  apply Int.modEq_of_dvd
  have hd : m ∣ c * (y - x) := by
    simpa [mul_sub] using h.dvd
  apply hc.symm.dvd_of_dvd_mul_right
  simpa [mul_comm] using hd

/-- Separate coprimality of `6` and `W` with `U` makes `6*W` a unit
modulo `U^2`. -/
theorem six_mul_tail_unit_mod_square
    (U W : ℤ) (h6 : IsCoprime 6 U) (hW : IsCoprime W U) :
    IsCoprime (6 * W) (U ^ 2) :=
  (h6.mul_left hW).pow_right

/-- Dividing the paired correction by its support unit recovers the half
companion residue. -/
theorem splitter_recovers_half_companion
    (U ell v W S Z Z0 : ℤ)
    (hv : v = 2 * Z0)
    (hunit : IsCoprime (6 * W) (U ^ 2))
    (hpair : ell * S ≡ 3 * v * W [ZMOD U ^ 2])
    (hZ : 6 * W * Z ≡ ell * S [ZMOD U ^ 2]) :
    Z ≡ Z0 [ZMOD U ^ 2] := by
  have hright : ell * S ≡ 6 * W * Z0 [ZMOD U ^ 2] := by
    calc
      ell * S ≡ 3 * v * W [ZMOD U ^ 2] := hpair
      _ = 6 * W * Z0 := by rw [hv]; ring
  have hmul : (6 * W) * Z ≡ (6 * W) * Z0 [ZMOD U ^ 2] :=
    hZ.trans hright
  exact cancel_coprime_factor_modEq (U ^ 2) (6 * W) Z Z0 hunit hmul

/-- Opposite signs on two coprime channel squares combine to a square root
of one modulo the complete product square. -/
theorem channel_signs_give_square_root
    (A B U Z : ℤ)
    (hU : U = A * B)
    (hAB : IsCoprime A B)
    (hZA : Z ≡ 1 [ZMOD A ^ 2])
    (hZB : Z ≡ -1 [ZMOD B ^ 2]) :
    Z ^ 2 ≡ 1 [ZMOD U ^ 2] := by
  have hA : Z ^ 2 ≡ 1 [ZMOD A ^ 2] := by
    simpa using hZA.pow 2
  have hB : Z ^ 2 ≡ 1 [ZMOD B ^ 2] := by
    simpa using hZB.pow 2
  have hcop : IsCoprime (A ^ 2) (B ^ 2) := hAB.pow_left.pow_right
  have hd : A ^ 2 * B ^ 2 ∣ 1 - Z ^ 2 :=
    hcop.mul_dvd hA.dvd hB.dvd
  apply Int.modEq_of_dvd
  rw [hU]
  simpa [mul_pow] using hd

/-! ## Exact logical boundary of local surjectivity -/

/-- Full local surjectivity, including all admissibility premises, refutes
the assertion that every admissible correction is zero.  It refutes only
this exact fixed-zero claim. -/
theorem no_fixed_zero_of_full_local_surjectivity
    (s : ℤ) (Admissible : ℤ → Prop) (corr : ℤ → ℤ)
    (hsurj : ∀ c : ℤ, ∃ k : ℤ,
      Admissible k ∧ corr k ≡ c [ZMOD s])
    (hone : ¬(1 : ℤ) ≡ 0 [ZMOD s]) :
    ¬∀ k : ℤ, Admissible k → corr k ≡ 0 [ZMOD s] := by
  intro hrigid
  rcases hsurj 1 with ⟨k, hk, hcorr⟩
  exact hone (hcorr.symm.trans (hrigid k hk))

/-! ## Kernel-reduced actual recurrence certificate -/

/-- The norm-one Lucas recurrence over an arbitrary ring. -/
def lucasU {R : Type*} [Ring R] : ℕ → R
  | 0 => 0
  | 1 => 1
  | n + 2 => 6 * lucasU (n + 1) - lucasU n

/-- Companion matrix for `u_(n+2)=6*u_(n+1)-u_n`. -/
def lucasMatrix (R : Type*) [CommRing R] :
    Matrix (Fin 2) (Fin 2) R :=
  !![(6 : R), -1; 1, 0]

/-- The first column of the companion power contains two consecutive Lucas
terms. -/
theorem lucasMatrix_firstColumn
    {R : Type*} [CommRing R] (n : ℕ) :
    (lucasMatrix R ^ n) 0 0 = lucasU (R := R) (n + 1) ∧
    (lucasMatrix R ^ n) 1 0 = lucasU (R := R) n := by
  induction n with
  | zero => simp [lucasMatrix, lucasU]
  | succ n ih =>
      rw [pow_succ']
      simp only [Matrix.mul_apply, Fin.sum_univ_two]
      rcases ih with ⟨ih0, ih1⟩
      constructor
      · rw [show (lucasMatrix R) 0 0 = 6 by simp [lucasMatrix],
            show (lucasMatrix R) 0 1 = -1 by simp [lucasMatrix], ih0, ih1]
        simp only [lucasU]
        ring
      · rw [show (lucasMatrix R) 1 0 = 1 by simp [lucasMatrix],
            show (lucasMatrix R) 1 1 = 0 by simp [lucasMatrix], ih0]
        simp

/-- The lower-left companion entry is the Lucas term. -/
theorem lucasMatrix_entry
    {R : Type*} [CommRing R] (n : ℕ) :
    (lucasMatrix R ^ n) 1 0 = lucasU (R := R) n :=
  (lucasMatrix_firstColumn n).2

set_option maxHeartbeats 0 in
-- Kernel reduction of the displayed index 7353 recurrence needs an unbounded
-- heartbeat budget; this is a finite `decide` certificate, not `native_decide`.
set_option maxRecDepth 170000 in
-- The same kernel computation expands a deeply nested binary matrix power.
theorem u7353_mod_214375_certificate :
    lucasU (R := ZMod 214375) 7353 = (85785 : ZMod 214375) := by
  rw [← lucasMatrix_entry]
  decide

/-- The remaining arithmetic in the fixed-zero counterexample: `k=2451`
is positive odd and congruent to one modulo `35^2`, while the frozen
quotient residue has normalized correction two modulo five. -/
theorem fixedZeroCounterexample_arithmetic :
    (2451 : ℤ) = 1 + 2 * 35 ^ 2 ∧
      0 < (2451 : ℤ) ∧ Odd (2451 : ℤ) ∧
      (85785 : ℤ) = 35 * 2451 ∧
      (2451 - 1) / 35 ^ 2 = 2 ∧
      ¬(2 : ℤ) ≡ 0 [ZMOD 5] := by
  norm_num [Int.ModEq, Odd]

#check evenPowerSum_append
#check coprime_add_square_tail
#check evenPowerSum_coprime_of_leading
#check support_not_dvd_normalized_tail
#check prime_not_dvd_list_prod_of_small
#check integral_coefficient_not_dvd_of_small_numerator
#check paired_correction_modEq
#check channel_square_divisors
#check companion_mod_A
#check companion_mod_B
#check paired_correction_channel_splitter
#check cancel_coprime_factor_modEq
#check six_mul_tail_unit_mod_square
#check splitter_recovers_half_companion
#check channel_signs_give_square_root
#check no_fixed_zero_of_full_local_surjectivity
#check lucasMatrix_firstColumn
#check lucasMatrix_entry
#check u7353_mod_214375_certificate
#check fixedZeroCounterexample_arithmetic




















end PellLucasAllOrderStaircase20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/PellLucasAllOrderStaircase20260901.lean -/

/- BEGIN GENERATED COMPLETE THEOREM/LEMMA AXIOM AUDIT -/
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.divisorTripleCatalogueWeight_eq_product
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.small_add_large_eq_catalogue
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.smallDivisorTripleWeight_le
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.product_le_largeWeight_add_threshold_mul_card
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.margin_le_largeDivisorTripleWeight
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.topLabelWeight_le_largeDivisorTripleWeight
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.sum_cube_le_cube_sum
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.monotone_overlap_cubicEnergy_lower
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.weightedIncidence_cube_le_weight_sq_mul_cubicEnergy
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.weightedShiftedIncidence_cube_le
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.weightedIncidence_eq_catalogue_add_shifted
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.weightedIncidence_sub_catalogue_cube_le_shiftedEnergy
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.weightedShiftedIncidence_cube_le_of_caps
#print axioms IUTThreeClosures.AffineCatalogueWeightOverlap20260901.powerful_pairwiseCatalogue_tail_counterexample
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.ptLE_one_eq_ptEQ_one
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.mem_ptLE_one_of_mem_ptEQ_one
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.RationalDegreeOneSourceRealization.point_mem_degreeAtMostOne
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.RationalDegreeOneSourceRealization.restrictedStatementI_of_statementI
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.RationalDegreeOneSourceRealization.restrictedStatementI_iff_abc
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.RationalDegreeOneSourceRealization.abc_of_statementI
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.degreeEmpty_fullGenlPremise_countermodel
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.heightZero_fullGenlPremise_countermodel
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.conductorInflatedShadow_statementI
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.conductorInflatedShadow_degreeOne
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.conductorInflatedShadow_height_exact
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.conductorInflatedShadow_different_zero
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.conductorInflatedShadow_no_uniform_conductor_upper
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.conductorInflatedShadow_fullPremise_countermodel
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.differentInflatedShadow_fullPremise_countermodel
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.counterexample_reverse_without_source_height_upper
#print axioms IUTThreeClosures.IUTRationalDegreeOneSourceRealization20260901.counterexample_reverse_without_target_radical_upper
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.sum_injective_labels_lt_le_triangular
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.card_le_pred_of_positive_injective_labels_lt
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.weighted_mass_le_triangular_envelope
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.factorization_fermat_eq_exactOrder
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.lowMultiplierExactOrderPrimes_card_le_pred
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.lowMultiplierExactOrderPrimes_sum_multiplier_le
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.lowMultiplierExactOrderWeight_le_triangular_envelope
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.highDeep_or_balancedNearSquare_of_two_low_budgets
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.one_half_is_sharp_after_two_controlled_arms
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.complete_positive_label_packet
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.no_uniform_nat_linear_bound_for_positive_injective_labels
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.triangular_energy_exceeds_coefficient_one_at_four
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.wieferich_3511_exact_order_multiplier_two
#print axioms IUTThreeClosures.MersenneBalancedMultiplierDepthLocalization20260901.repeated_exact_order_multiplier_ge_three_false
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.evenPowerSum_append
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.coprime_add_square_tail
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.evenPowerSum_coprime_of_leading
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.support_not_dvd_normalized_tail
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.prime_not_dvd_list_prod_of_small
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.integral_coefficient_not_dvd_of_small_numerator
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.paired_correction_modEq
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.channel_square_divisors
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.companion_mod_A
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.companion_mod_B
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.channel_A_sign
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.channel_B_sign
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.paired_correction_channel_splitter
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.cancel_coprime_factor_modEq
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.six_mul_tail_unit_mod_square
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.splitter_recovers_half_companion
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.channel_signs_give_square_root
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.no_fixed_zero_of_full_local_surjectivity
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.lucasMatrix_firstColumn
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.lucasMatrix_entry
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.u7353_mod_214375_certificate
#print axioms IUTThreeClosures.PellLucasAllOrderStaircase20260901.fixedZeroCounterexample_arithmetic
/- END GENERATED COMPLETE THEOREM/LEMMA AXIOM AUDIT -/
