import P2M.Sol.S_AbsoluteValue_Completion_isUltrametricDist_of_isNonarchimedean
import P2M.Sol.S_AbsoluteValue_Completion_norm_coe_and_exists_one_lt_norm
import P2M.Sol.S_AbsoluteValue_exists_forall_sub_lt_of_pairwise_not_isEquiv
import P2M.Sol.S_AddChar_exists_continuousLinearMap_fourierChar_eq
import P2M.Sol.S_AddCircle_exists_eq_coe_div_of_nsmul_eq_zero_of_dvd
import P2M.Sol.S_AddCommGroup_apply_zsmul_add_eq_of_forall_cube

#print axioms P2MW.S_AbsoluteValue_Completion_isUltrametricDist_of_isNonarchimedean.solution
#print axioms P2MW.S_AbsoluteValue_Completion_norm_coe_and_exists_one_lt_norm.solution
#print axioms P2MW.S_AbsoluteValue_exists_forall_sub_lt_of_pairwise_not_isEquiv.solution
#print axioms P2MW.S_AddChar_exists_continuousLinearMap_fourierChar_eq.solution
#print axioms P2MW.S_AddCircle_exists_eq_coe_div_of_nsmul_eq_zero_of_dvd.solution
#print axioms P2MW.S_AddCommGroup_apply_zsmul_add_eq_of_forall_cube.solution
