import Theorems.Thm_AbsoluteValue_Completion_isUltrametricDist_of_isNonarchimedean
import Theorems.Thm_AbsoluteValue_Completion_norm_coe_and_exists_one_lt_norm
import Theorems.Thm_AbsoluteValue_exists_forall_sub_lt_of_pairwise_not_isEquiv
import Theorems.Thm_AddChar_exists_continuousLinearMap_fourierChar_eq
import Theorems.Thm_AddCircle_exists_eq_coe_div_of_nsmul_eq_zero_of_dvd
import Theorems.Thm_AddCommGroup_apply_zsmul_add_eq_of_forall_cube

#print axioms AbsoluteValue.Completion.isUltrametricDist_of_isNonarchimedean
#print axioms AbsoluteValue.Completion.norm_coe_and_exists_one_lt_norm
#print axioms AbsoluteValue.exists_forall_sub_lt_of_pairwise_not_isEquiv
#print axioms AddChar.exists_continuousLinearMap_fourierChar_eq
#print axioms AddCircle.exists_eq_coe_div_of_nsmul_eq_zero_of_dvd
#print axioms AddCommGroup.apply_zsmul_add_eq_of_forall_cube
