import IUTThreeClosures.TraceCovariantRationalReturn20260831

#check IUTThreeClosures.TraceCovariantRationalReturn20260831.scalar_return_trace_balance
#print axioms IUTThreeClosures.TraceCovariantRationalReturn20260831.scalar_return_trace_balance
#check IUTThreeClosures.TraceCovariantRationalReturn20260831.scalar_return_of_equal_finrank
#print axioms IUTThreeClosures.TraceCovariantRationalReturn20260831.scalar_return_of_equal_finrank
#check IUTThreeClosures.TraceCovariantRationalReturn20260831.map_one_of_nonzero_scalar_return
#print axioms IUTThreeClosures.TraceCovariantRationalReturn20260831.map_one_of_nonzero_scalar_return
#check IUTThreeClosures.TraceCovariantRationalReturn20260831.scalar_line_of_nonzero_return
#print axioms IUTThreeClosures.TraceCovariantRationalReturn20260831.scalar_line_of_nonzero_return
#check IUTThreeClosures.TraceCovariantRationalReturn20260831.exists_nonzero_return_iff_scalar_line
#print axioms IUTThreeClosures.TraceCovariantRationalReturn20260831.exists_nonzero_return_iff_scalar_line
#check IUTThreeClosures.TraceCovariantRationalReturn20260831.scalar_return_addValuation
#print axioms IUTThreeClosures.TraceCovariantRationalReturn20260831.scalar_return_addValuation
#check IUTThreeClosures.TraceCovariantRationalReturn20260831.no_scalar_return_of_addValuation_ne
#print axioms IUTThreeClosures.TraceCovariantRationalReturn20260831.no_scalar_return_of_addValuation_ne
