/-
Generated by validate.py.  Do not edit by hand.

This file recompiles the exact declaration bodies of the four checkpoint
modules and issues one #print axioms command for every source theorem or
lemma.  Recompilation in one file keeps private source names addressable.
-/
import IUTThreeClosures.AffineCommonKernelTripleSelection20260901
import IUTThreeClosures.IUTAdmissibleVolumeIntegerBridge20260901
import IUTThreeClosures.SUnitUniformTripod
import IUTThreeClosures.MersenneFixedPolylogBlockMassTriage20260901
import Mathlib

/- BEGIN EXACT BODY: IUTThreeClosures/AffineCollinearPeriodEnergy20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/

/-!
# Direction periods and collinear cubic energy in the affine route

The mathematical proofs precede this module in
`research/ABC_AFFINE_COLLINEAR_PERIOD_ENERGY_2026_09_01.md`.

This file extracts the exact index period of one actual arm-divisor label on
an affine ray.  It proves a cube-root occupancy bound away from arm-level
directions, a weighted cubic-energy ceiling, and a square-root bound on the
vertical exceptional direction when the constant arm component is capped.
It also checks the precise countermodels recorded in the paper.  It assumes
no density theorem and proves no abc statement.
-/

namespace IUTThreeClosures
namespace AffineCollinearPeriodEnergy20260901

open scoped BigOperators
open AffineTemplateEntropy20260901
open AffineDeterminantLayerEntropy20260901
open AffineAdaptiveCommonKernel20260901
open AffineCommonKernelTripleSelection20260901

/-! ## Direction periods -/

/-- A nonnegative affine ray in the parameter lattice. -/
def affineRayPoint (base : ℕ × ℕ) (s t n : ℕ) : ℕ × ℕ :=
  (base.1 + n * s, base.2 + n * t)

/-- The part of a label component that is not absorbed by one direction
coefficient. -/
def reducedDirectionPeriod (d A : ℕ) : ℕ :=
  d / Nat.gcd d A

/-- Product of the three reduced periods. -/
def directionPeriod (label : ArmDivisorLabel) (AU AV AW : ℕ) : ℕ :=
  reducedDirectionPeriod label.u AU *
    reducedDirectionPeriod label.v AV *
      reducedDirectionPeriod label.w AW

/-- Product of the three pieces absorbed by the direction coefficients. -/
def directionCapture (label : ArmDivisorLabel) (AU AV AW : ℕ) : ℕ :=
  Nat.gcd label.u AU * Nat.gcd label.v AV * Nat.gcd label.w AW

theorem reducedDirectionPeriod_pos {d A : ℕ} (hd : 0 < d) :
    0 < reducedDirectionPeriod d A := by
  unfold reducedDirectionPeriod
  apply Nat.div_pos
  · exact Nat.le_of_dvd hd (Nat.gcd_dvd_left d A)
  · exact Nat.gcd_pos_of_pos_left A hd

theorem reducedDirectionPeriod_dvd_self (d A : ℕ) :
    reducedDirectionPeriod d A ∣ d := by
  exact Nat.div_dvd_of_dvd (Nat.gcd_dvd_left d A)

/-- If `d ∣ gap*A`, cancellation by `gcd d A` leaves the reduced period as
a divisor of `gap`. -/
theorem reducedDirectionPeriod_dvd_of_dvd_mul {d A gap : ℕ}
    (hd : 0 < d) (hdiv : d ∣ gap * A) :
    reducedDirectionPeriod d A ∣ gap := by
  unfold reducedDirectionPeriod
  have hgpos : 0 < Nat.gcd d A := Nat.gcd_pos_of_pos_left A hd
  rw [Nat.div_dvd_iff_dvd_mul (Nat.gcd_dvd_left d A) hgpos]
  rw [mul_comm]
  exact Nat.dvd_mul_gcd_iff_dvd_mul.mpr hdiv

theorem directionPeriod_pos
    {label : ArmDivisorLabel} {AU AV AW : ℕ}
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w) :
    0 < directionPeriod label AU AV AW := by
  unfold directionPeriod
  exact mul_pos (mul_pos (reducedDirectionPeriod_pos hu)
    (reducedDirectionPeriod_pos hv)) (reducedDirectionPeriod_pos hw)

/-- Pairwise coprimality lets the three component periods multiply rather
than merely take an lcm. -/
theorem directionPeriod_dvd_gap
    {label : ArmDivisorLabel} {AU AV AW gap : ℕ}
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (hpair : label.PairwiseCoprime)
    (hU : label.u ∣ gap * AU)
    (hV : label.v ∣ gap * AV)
    (hW : label.w ∣ gap * AW) :
    directionPeriod label AU AV AW ∣ gap := by
  have hrU := reducedDirectionPeriod_dvd_of_dvd_mul hu hU
  have hrV := reducedDirectionPeriod_dvd_of_dvd_mul hv hV
  have hrW := reducedDirectionPeriod_dvd_of_dvd_mul hw hW
  have hUV : Nat.Coprime (reducedDirectionPeriod label.u AU)
      (reducedDirectionPeriod label.v AV) :=
    Nat.Coprime.of_dvd (reducedDirectionPeriod_dvd_self _ _)
      (reducedDirectionPeriod_dvd_self _ _) hpair.1
  have hUW : Nat.Coprime (reducedDirectionPeriod label.u AU)
      (reducedDirectionPeriod label.w AW) :=
    Nat.Coprime.of_dvd (reducedDirectionPeriod_dvd_self _ _)
      (reducedDirectionPeriod_dvd_self _ _) hpair.2.1
  have hVW : Nat.Coprime (reducedDirectionPeriod label.v AV)
      (reducedDirectionPeriod label.w AW) :=
    Nat.Coprime.of_dvd (reducedDirectionPeriod_dvd_self _ _)
      (reducedDirectionPeriod_dvd_self _ _) hpair.2.2
  have hUVdvd : reducedDirectionPeriod label.u AU *
      reducedDirectionPeriod label.v AV ∣ gap :=
    hUV.mul_dvd_of_dvd_of_dvd hrU hrV
  exact (hUW.mul_left hVW).mul_dvd_of_dvd_of_dvd hUVdvd hrW

/-- Exact factorization of the label product into period and direction
capture. -/
theorem directionPeriod_mul_capture
    (label : ArmDivisorLabel) (AU AV AW : ℕ) :
    directionPeriod label AU AV AW *
      directionCapture label AU AV AW = label.product := by
  unfold directionPeriod directionCapture reducedDirectionPeriod
    ArmDivisorLabel.product
  calc
    label.u / Nat.gcd label.u AU * (label.v / Nat.gcd label.v AV) *
          (label.w / Nat.gcd label.w AW) *
          (Nat.gcd label.u AU * Nat.gcd label.v AV * Nat.gcd label.w AW) =
        (label.u / Nat.gcd label.u AU * Nat.gcd label.u AU) *
          (label.v / Nat.gcd label.v AV * Nat.gcd label.v AV) *
          (label.w / Nat.gcd label.w AW * Nat.gcd label.w AW) := by ring
    _ = label.u * label.v * label.w := by
      rw [Nat.div_mul_cancel (Nat.gcd_dvd_left label.u AU),
        Nat.div_mul_cancel (Nat.gcd_dvd_left label.v AV),
        Nat.div_mul_cancel (Nat.gcd_dvd_left label.w AW)]






/-! ## Actual affine cancellation on a ray -/

private theorem natAbs_natCast_sub_eq_dist (n m : ℕ) :
    Int.natAbs ((n : ℤ) - m) = Nat.dist n m := by
  by_cases h : m ≤ n
  · rw [Int.natAbs_natCast_sub_natCast_of_ge h, Nat.dist_comm,
      Nat.dist_eq_sub_of_le h]
  · have hnm : n ≤ m := Nat.le_of_not_ge h
    rw [Int.natAbs_natCast_sub_natCast_of_le hnm,
      Nat.dist_eq_sub_of_le hnm]

private theorem nat_dvd_dist_mul_of_intCast_dvd_sub_mul
    {d n m A : ℕ}
    (hdiv : (d : ℤ) ∣ ((n : ℤ) - m) * (A : ℤ)) :
    d ∣ Nat.dist n m * A := by
  have habs : Int.natAbs (d : ℤ) ∣
      Int.natAbs (((n : ℤ) - m) * (A : ℤ)) :=
    Int.natAbs_dvd_natAbs.mpr hdiv
  simpa [natAbs_natCast_sub_eq_dist, Int.natAbs_mul] using habs

/-- Two actual occurrences of one label on a ray give the three direction
divisibilities after cancellation of the affine step `R`. -/
theorem sharedLabel_ray_directionDivisibilities
    {R B C : ℕ} {base : ℕ × ℕ} {s t n m : ℕ}
    {label : ArmDivisorLabel}
    (hn : armDivisorsAt R B C (affineRayPoint base s t n)
      label.u label.v label.w)
    (hm : armDivisorsAt R B C (affineRayPoint base s t m)
      label.u label.v label.w) :
    label.u ∣ Nat.dist n m * s ∧
      label.v ∣ Nat.dist n m * (s + C * t) ∧
      label.w ∣ Nat.dist n m * (s + B * t) := by
  have hUR : Nat.Coprime label.u R :=
    Nat.Coprime.of_dvd hn.1 (dvd_refl R) (by simp [affineU])
  have hVR : Nat.Coprime label.v R :=
    Nat.Coprime.of_dvd hn.2.1 (dvd_refl R) (by simp [affineV])
  have hWR : Nat.Coprime label.w R :=
    Nat.Coprime.of_dvd hn.2.2 (dvd_refl R) (by simp [affineW])
  have hdiff := affineTemplate_membership_gives_differenceDivisibilities
    hUR hVR hWR hn.1 hm.1 hn.2.1 hm.2.1 hn.2.2 hm.2.2
  have hUeq :
      (((affineRayPoint base s t n).1 : ℤ) -
        (affineRayPoint base s t m).1) =
      ((n : ℤ) - m) * (s : ℤ) := by
    simp only [affineRayPoint, Nat.cast_add, Nat.cast_mul]
    ring
  have hVeq :
      (((affineRayPoint base s t n).1 : ℤ) -
          (affineRayPoint base s t m).1) +
          (C : ℤ) * (((affineRayPoint base s t n).2 : ℤ) -
            (affineRayPoint base s t m).2) =
      ((n : ℤ) - m) * ((s : ℤ) + (C : ℤ) * (t : ℤ)) := by
    simp only [affineRayPoint, Nat.cast_add, Nat.cast_mul]
    ring
  have hWeq :
      (((affineRayPoint base s t n).1 : ℤ) -
          (affineRayPoint base s t m).1) +
          (B : ℤ) * (((affineRayPoint base s t n).2 : ℤ) -
            (affineRayPoint base s t m).2) =
      ((n : ℤ) - m) * ((s : ℤ) + (B : ℤ) * (t : ℤ)) := by
    simp only [affineRayPoint, Nat.cast_add, Nat.cast_mul]
    ring
  rcases hdiff with ⟨hU, hV, hW⟩
  rw [hUeq] at hU
  rw [hVeq] at hV
  rw [hWeq] at hW
  exact ⟨nat_dvd_dist_mul_of_intCast_dvd_sub_mul hU,
    nat_dvd_dist_mul_of_intCast_dvd_sub_mul hV,
    nat_dvd_dist_mul_of_intCast_dvd_sub_mul hW⟩

/-- The actual affine version of the direction-period divisibility. -/
theorem sharedLabel_ray_directionPeriod_dvd_dist
    {R B C : ℕ} {base : ℕ × ℕ} {s t n m : ℕ}
    {label : ArmDivisorLabel}
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (hpair : label.PairwiseCoprime)
    (hn : armDivisorsAt R B C (affineRayPoint base s t n)
      label.u label.v label.w)
    (hm : armDivisorsAt R B C (affineRayPoint base s t m)
      label.u label.v label.w) :
    directionPeriod label s (s + C * t) (s + B * t) ∣
      Nat.dist n m := by
  rcases sharedLabel_ray_directionDivisibilities hn hm with ⟨hU, hV, hW⟩
  exact directionPeriod_dvd_gap hu hv hw hpair hU hV hW




/-! ## Exact period capacity -/

/-- A finite set in `[0,H]` whose pairwise differences are divisible by a
positive period has the exact residue-class capacity. -/
theorem periodicIndexSet_card_le
    (S : Finset ℕ) (H T : ℕ)
    (hT : 0 < T)
    (hbox : ∀ n ∈ S, n ≤ H)
    (hperiod : ∀ n ∈ S, ∀ m ∈ S, n ≠ m → T ∣ Nat.dist n m) :
    S.card ≤ H / T + 1 := by
  have hsep : ∀ n ∈ S, ∀ m ∈ S, n ≠ m →
      T - 1 < Nat.dist n m := by
    intro n hn m hm hnm
    have hdist : 0 < Nat.dist n m := by
      rcases le_total n m with hle | hle
      · rw [Nat.dist_eq_sub_of_le hle]
        omega
      · rw [Nat.dist_comm, Nat.dist_eq_sub_of_le hle]
        omega
    have hle : T ≤ Nat.dist n m :=
      Nat.le_of_dvd hdist (hperiod n hn m hm hnm)
    omega
  have hcard := oneDimSeparated_card_le S H (T - 1) hbox hsep
  have hsucc : T - 1 + 1 = T := by omega
  simpa [hsucc] using hcard

/-- Actual ray indices carrying one label. -/
noncomputable def rayLabelFiber (S : Finset ℕ) (R B C : ℕ)
    (base : ℕ × ℕ) (s t : ℕ) (label : ArmDivisorLabel) : Finset ℕ := by
  classical
  exact S.filter fun n ↦ armDivisorsAt R B C
    (affineRayPoint base s t n) label.u label.v label.w

@[simp] theorem mem_rayLabelFiber_iff
    {S : Finset ℕ} {R B C : ℕ} {base : ℕ × ℕ}
    {s t n : ℕ} {label : ArmDivisorLabel} :
    n ∈ rayLabelFiber S R B C base s t label ↔
      n ∈ S ∧ armDivisorsAt R B C
        (affineRayPoint base s t n) label.u label.v label.w := by
  classical
  simp [rayLabelFiber]

/-- Exact period capacity for one actual label fibre on a ray. -/
theorem rayLabelFiber_card_le_directionPeriod
    (S : Finset ℕ) {H R B C : ℕ} {base : ℕ × ℕ}
    {s t : ℕ} (label : ArmDivisorLabel)
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (hpair : label.PairwiseCoprime)
    (hbox : ∀ n ∈ S, n ≤ H) :
    (rayLabelFiber S R B C base s t label).card ≤
      H / directionPeriod label s (s + C * t) (s + B * t) + 1 := by
  apply periodicIndexSet_card_le
    (rayLabelFiber S R B C base s t label) H
    (directionPeriod label s (s + C * t) (s + B * t))
    (directionPeriod_pos hu hv hw)
  · intro n hn
    exact hbox n (mem_rayLabelFiber_iff.mp hn).1
  · intro n hn m hm _hnm
    exact sharedLabel_ray_directionPeriod_dvd_dist hu hv hw hpair
      (mem_rayLabelFiber_iff.mp hn).2 (mem_rayLabelFiber_iff.mp hm).2



/-! ## Nonconstant-ray cube-root capacity -/

/-- The direction capture is cubic in the sup scale when the first direction
coordinate is nonzero. -/
theorem directionCapture_nonconstant_le_cubic
    (label : ArmDivisorLabel) {B C s t : ℕ} (hs : 0 < s) :
    directionCapture label s (s + C * t) (s + B * t) ≤
      (B + 1) * (C + 1) * (max s t) ^ 3 := by
  let L := max s t
  have hsL : s ≤ L := Nat.le_max_left s t
  have htL : t ≤ L := Nat.le_max_right s t
  have hVpos : 0 < s + C * t := by omega
  have hWpos : 0 < s + B * t := by omega
  have hV : s + C * t ≤ (C + 1) * L := by
    calc
      s + C * t ≤ L + C * L :=
        Nat.add_le_add hsL (Nat.mul_le_mul_left C htL)
      _ = (C + 1) * L := by ring
  have hW : s + B * t ≤ (B + 1) * L := by
    calc
      s + B * t ≤ L + B * L :=
        Nat.add_le_add hsL (Nat.mul_le_mul_left B htL)
      _ = (B + 1) * L := by ring
  have hgU : Nat.gcd label.u s ≤ s := Nat.gcd_le_right label.u hs
  have hgV : Nat.gcd label.v (s + C * t) ≤ s + C * t :=
    Nat.gcd_le_right label.v hVpos
  have hgW : Nat.gcd label.w (s + B * t) ≤ s + B * t :=
    Nat.gcd_le_right label.w hWpos
  calc
    directionCapture label s (s + C * t) (s + B * t) ≤
        s * (s + C * t) * (s + B * t) := by
      exact Nat.mul_le_mul (Nat.mul_le_mul hgU hgV) hgW
    _ ≤ L * ((C + 1) * L) * ((B + 1) * L) := by
      exact Nat.mul_le_mul (Nat.mul_le_mul hsL hV) hW
    _ = (B + 1) * (C + 1) * L ^ 3 := by ring

/-- Pure arithmetic form of the cube-root capacity argument. -/
theorem cubic_card_bound_of_period
    {card H T capture D N K L : ℕ}
    (hT : 0 < T) (hN : 0 < N) (hK : 0 < K) (hL : 0 < L)
    (hcard : card ≤ H / T + 1)
    (hHL : H * L ≤ N)
    (hfactor : T * capture = D)
    (hcapture : capture ≤ K * L ^ 3)
    (hlarge : N ^ 2 < D) :
    (card - 1) ^ 3 < K * N := by
  let a := card - 1
  have haDiv : a ≤ H / T := by
    dsimp [a]
    apply Nat.sub_le_iff_le_add.mpr
    simpa [add_comm] using hcard
  have haT : a * T ≤ H := by
    calc
      a * T ≤ (H / T) * T := Nat.mul_le_mul_right T haDiv
      _ ≤ H := Nat.div_mul_le_self H T
  have haTL : a * T * L ≤ N :=
    (Nat.mul_le_mul_right L haT).trans hHL
  have hcoeff : D ≤ T * (K * L ^ 3) := by
    rw [← hfactor]
    exact Nat.mul_le_mul_left T hcapture
  have hsquare : (a * T * L) ^ 2 ≤ N ^ 2 :=
    Nat.pow_le_pow_left haTL 2
  have hraw : (T * L ^ 2) * (a ^ 2 * T) <
      (T * L ^ 2) * (K * L) := by
    calc
      (T * L ^ 2) * (a ^ 2 * T) = (a * T * L) ^ 2 := by ring
      _ ≤ N ^ 2 := hsquare
      _ < D := hlarge
      _ ≤ T * (K * L ^ 3) := hcoeff
      _ = (T * L ^ 2) * (K * L) := by ring
  have hfactorPos : 0 < T * L ^ 2 := mul_pos hT (pow_pos hL 2)
  have ha2T : a ^ 2 * T < K * L :=
    (Nat.mul_lt_mul_left hfactorPos).mp hraw
  have hTone : 1 ≤ T := hT
  have ha2le : a ^ 2 ≤ a ^ 2 * T := by
    simpa using Nat.mul_le_mul_left (a ^ 2) hTone
  have ha2 : a ^ 2 < K * L := ha2le.trans_lt ha2T
  have haL : a * L ≤ N := by
    calc
      a * L ≤ a * T * L := by
        apply Nat.mul_le_mul_right L
        calc
          a = a * 1 := by simp
          _ ≤ a * T := Nat.mul_le_mul_left a hTone
      _ ≤ N := haTL
  change a ^ 3 < K * N
  by_cases ha : a = 0
  · rw [ha]
    simpa using Nat.mul_pos hK hN
  · have hapos : 0 < a := Nat.pos_of_ne_zero ha
    calc
      a ^ 3 = a * a ^ 2 := by ring
      _ < a * (K * L) := (Nat.mul_lt_mul_left hapos).2 ha2
      _ = K * (a * L) := by ring
      _ ≤ K * N := Nat.mul_le_mul_left K haL

/-- Actual nonconstant-ray cube-root occupancy bound. -/
theorem rayLabelFiber_nonconstant_shiftedCube_lt
    (S : Finset ℕ) {H R B C N : ℕ} {base : ℕ × ℕ}
    {s t : ℕ} (label : ArmDivisorLabel)
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (hpair : label.PairwiseCoprime)
    (hs : 0 < s) (hN : 0 < N)
    (hbox : ∀ n ∈ S, n ≤ H)
    (hspan : H * max s t ≤ N)
    (hlarge : N ^ 2 < label.product) :
    ((rayLabelFiber S R B C base s t label).card - 1) ^ 3 <
      (B + 1) * (C + 1) * N := by
  let T := directionPeriod label s (s + C * t) (s + B * t)
  let capture := directionCapture label s (s + C * t) (s + B * t)
  let K := (B + 1) * (C + 1)
  let L := max s t
  apply cubic_card_bound_of_period
    (T := T) (capture := capture) (D := label.product)
    (K := K) (L := L)
  · exact directionPeriod_pos hu hv hw
  · exact hN
  · dsimp [K]
    positivity
  · dsimp [L]
    exact lt_of_lt_of_le hs (Nat.le_max_left s t)
  · exact rayLabelFiber_card_le_directionPeriod S label hu hv hw hpair hbox
  · exact hspan
  · exact directionPeriod_mul_capture label s (s + C * t) (s + B * t)
  · exact directionCapture_nonconstant_le_cubic label hs
  · exact hlarge

/-- Every other displayed premise of the pure cubic ledger can hold at
`N = 0`, while its strict conclusion fails.  Thus ambient positivity is a
necessary premise rather than a proof artefact. -/
theorem omitting_positive_ambient_breaks_cubic_card_bound :
    let card : ℕ := 1
    let H : ℕ := 0
    let T : ℕ := 1
    let capture : ℕ := 1
    let D : ℕ := 1
    let N : ℕ := 0
    let K : ℕ := 1
    let L : ℕ := 1
    0 < T ∧ 0 < K ∧ 0 < L ∧
      card ≤ H / T + 1 ∧ H * L ≤ N ∧
      T * capture = D ∧ capture ≤ K * L ^ 3 ∧ N ^ 2 < D ∧
      ¬ ((card - 1) ^ 3 < K * N) := by
  norm_num




/-! ## Optimal weighted cubic conversion -/

/-- The optimal integer conversion from a shifted cube bound to an
unshifted cube bound. -/
theorem cube_le_four_mul_of_shiftedCube_lt
    {n X : ℕ} (hX : 0 < X) (hshift : (n - 1) ^ 3 < X) :
    n ^ 3 ≤ 4 * X := by
  by_cases hn : n = 0
  · subst n
    simp
  have hnpos : 0 < n := Nat.pos_of_ne_zero hn
  let a := n - 1
  have hna : n = a + 1 := by
    dsimp [a]
    omega
  have haCube : a ^ 3 + 1 ≤ X := by
    rw [show a = n - 1 by rfl]
    omega
  by_cases ha : a = 0
  · rw [hna, ha]
    simp
    omega
  · obtain ⟨b, hb⟩ : ∃ b, a = b + 1 := by
      exact Nat.exists_eq_succ_of_ne_zero ha
    have hpoly : (a + 1) ^ 3 ≤ 4 * (a ^ 3 + 1) := by
      rw [hb]
      have hid : 4 * ((b + 1) ^ 3 + 1) =
          (b + 1 + 1) ^ 3 + 3 * b ^ 2 * (b + 2) := by ring
      rw [hid]
      omega
    calc
      n ^ 3 = (a + 1) ^ 3 := by rw [hna]
      _ ≤ 4 * (a ^ 3 + 1) := hpoly
      _ ≤ 4 * X := Nat.mul_le_mul_left 4 haCube

/-- Factor three already fails at `n=X=2`, so factor four is the optimal
integer constant in the preceding conversion. -/
theorem factorThree_shiftedCube_counterexample :
    ((2 - 1) ^ 3 < 2) ∧ ¬ (2 ^ 3 ≤ 3 * 2) := by
  norm_num

/-- Weighted cubic-moment consequence of uniform shifted-cube bounds. -/
theorem weightedCubicMoment_le_four
    {α : Type*} (I : Finset α) (weight count : α → ℕ) (X : ℕ)
    (hX : 0 < X)
    (hshift : ∀ i ∈ I, (count i - 1) ^ 3 < X) :
    ∑ i ∈ I, weight i * count i ^ 3 ≤
      4 * X * ∑ i ∈ I, weight i := by
  calc
    ∑ i ∈ I, weight i * count i ^ 3 ≤
        ∑ i ∈ I, weight i * (4 * X) := by
      exact Finset.sum_le_sum fun i hi ↦
        Nat.mul_le_mul_left (weight i)
          (cube_le_four_mul_of_shiftedCube_lt hX (hshift i hi))
    _ = 4 * X * ∑ i ∈ I, weight i := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro i _hi
      ring

/-- The weighted cubic-energy ceiling for any finite catalogue of actual
large labels on one nonconstant ray. -/
theorem rayCatalogue_weightedCubicEnergy_le
    (S : Finset ℕ) (labels : Finset ArmDivisorLabel)
    (weight : ArmDivisorLabel → ℕ)
    {H R B C N : ℕ} {base : ℕ × ℕ} {s t : ℕ}
    (hs : 0 < s) (hN : 0 < N)
    (hbox : ∀ n ∈ S, n ≤ H)
    (hspan : H * max s t ≤ N)
    (hpositive : ∀ label ∈ labels,
      0 < label.u ∧ 0 < label.v ∧ 0 < label.w)
    (hpair : ∀ label ∈ labels, label.PairwiseCoprime)
    (hlarge : ∀ label ∈ labels, N ^ 2 < label.product) :
    ∑ label ∈ labels, weight label *
        (rayLabelFiber S R B C base s t label).card ^ 3 ≤
      4 * ((B + 1) * (C + 1) * N) *
        ∑ label ∈ labels, weight label := by
  apply weightedCubicMoment_le_four labels weight
    (fun label ↦ (rayLabelFiber S R B C base s t label).card)
    ((B + 1) * (C + 1) * N)
  · positivity
  · intro label hlabel
    exact rayLabelFiber_nonconstant_shiftedCube_lt S label
      (hpositive label hlabel).1 (hpositive label hlabel).2.1
      (hpositive label hlabel).2.2 (hpair label hlabel)
      hs hN hbox hspan (hlarge label hlabel)




/-! ## The vertical exceptional direction -/

/-- On a vertical ray, the entire `U` component is absorbed by the direction;
an individual cap on it leaves a quadratic direction capture. -/
theorem directionCapture_vertical_le_quadratic
    (label : ArmDivisorLabel) {B C t XU : ℕ}
    (hB : 0 < B) (hC : 0 < C) (ht : 0 < t)
    (hUcap : label.u ≤ XU) :
    directionCapture label 0 (C * t) (B * t) ≤
      (XU * B * C) * t ^ 2 := by
  have hCt : 0 < C * t := mul_pos hC ht
  have hBt : 0 < B * t := mul_pos hB ht
  have hgV : Nat.gcd label.v (C * t) ≤ C * t :=
    Nat.gcd_le_right label.v hCt
  have hgW : Nat.gcd label.w (B * t) ≤ B * t :=
    Nat.gcd_le_right label.w hBt
  simp only [directionCapture, Nat.gcd_zero_right]
  calc
    label.u * Nat.gcd label.v (C * t) * Nat.gcd label.w (B * t) ≤
        XU * (C * t) * (B * t) := by
      exact Nat.mul_le_mul (Nat.mul_le_mul hUcap hgV) hgW
    _ = (XU * B * C) * t ^ 2 := by ring

/-- Pure arithmetic form of the square-root vertical capacity argument. -/
theorem quadratic_card_bound_of_period
    {card H T capture D N K L : ℕ}
    (hT : 0 < T) (hL : 0 < L)
    (hcard : card ≤ H / T + 1)
    (hHL : H * L ≤ N)
    (hfactor : T * capture = D)
    (hcapture : capture ≤ K * L ^ 2)
    (hlarge : N ^ 2 < D) :
    (card - 1) ^ 2 < K := by
  let a := card - 1
  have haDiv : a ≤ H / T := by
    dsimp [a]
    apply Nat.sub_le_iff_le_add.mpr
    simpa [add_comm] using hcard
  have haT : a * T ≤ H := by
    calc
      a * T ≤ (H / T) * T := Nat.mul_le_mul_right T haDiv
      _ ≤ H := Nat.div_mul_le_self H T
  have haTL : a * T * L ≤ N :=
    (Nat.mul_le_mul_right L haT).trans hHL
  have hcoeff : D ≤ T * (K * L ^ 2) := by
    rw [← hfactor]
    exact Nat.mul_le_mul_left T hcapture
  have hsquare : (a * T * L) ^ 2 ≤ N ^ 2 :=
    Nat.pow_le_pow_left haTL 2
  have hraw : (T * L ^ 2) * (a ^ 2 * T) <
      (T * L ^ 2) * K := by
    calc
      (T * L ^ 2) * (a ^ 2 * T) = (a * T * L) ^ 2 := by ring
      _ ≤ N ^ 2 := hsquare
      _ < D := hlarge
      _ ≤ T * (K * L ^ 2) := hcoeff
      _ = (T * L ^ 2) * K := by ring
  have hfactorPos : 0 < T * L ^ 2 := mul_pos hT (pow_pos hL 2)
  have ha2T : a ^ 2 * T < K :=
    (Nat.mul_lt_mul_left hfactorPos).mp hraw
  have hTone : 1 ≤ T := hT
  have ha2le : a ^ 2 ≤ a ^ 2 * T := by
    simpa using Nat.mul_le_mul_left (a ^ 2) hTone
  exact ha2le.trans_lt ha2T

/-- Actual square-root cap for a large label on a vertical ray. -/
theorem rayLabelFiber_vertical_shiftedSquare_lt
    (S : Finset ℕ) {H R B C N XU : ℕ} {base : ℕ × ℕ}
    {t : ℕ} (label : ArmDivisorLabel)
    (hu : 0 < label.u) (hv : 0 < label.v) (hw : 0 < label.w)
    (hpair : label.PairwiseCoprime)
    (hB : 0 < B) (hC : 0 < C) (ht : 0 < t)
    (hUcap : label.u ≤ XU)
    (hbox : ∀ n ∈ S, n ≤ H)
    (hspan : H * t ≤ N)
    (hlarge : N ^ 2 < label.product) :
    ((rayLabelFiber S R B C base 0 t label).card - 1) ^ 2 <
      XU * B * C := by
  let T := directionPeriod label 0 (C * t) (B * t)
  let capture := directionCapture label 0 (C * t) (B * t)
  let K := XU * B * C
  apply quadratic_card_bound_of_period
    (T := T) (capture := capture) (D := label.product)
    (K := K) (L := t)
  · exact directionPeriod_pos hu hv hw
  · exact ht
  · simpa [T] using
      (rayLabelFiber_card_le_directionPeriod
        (R := R) (B := B) (C := C) (base := base) (s := 0) (t := t)
        S label hu hv hw hpair hbox)
  · exact hspan
  · simpa [T, capture] using
      directionPeriod_mul_capture label 0 (C * t) (B * t)
  · exact directionCapture_vertical_le_quadratic label hB hC ht hUcap
  · exact hlarge



/-! ## Exact pressure tests -/

/-- Without pairwise coprimality, component periods need not multiply. -/
theorem omitting_pairwise_breaks_directionPeriod_product :
    let label : ArmDivisorLabel := ⟨2, 2, 1⟩
    label.u ∣ 2 * 1 ∧ label.v ∣ 2 * 1 ∧ label.w ∣ 2 * 1 ∧
      ¬ label.PairwiseCoprime ∧
      reducedDirectionPeriod label.u 1 = 2 ∧
      reducedDirectionPeriod label.v 1 = 2 ∧
      reducedDirectionPeriod label.w 1 = 1 ∧
      directionPeriod label 1 1 1 = 4 ∧
      ¬ directionPeriod label 1 1 1 ∣ 2 := by
  norm_num [ArmDivisorLabel.PairwiseCoprime, reducedDirectionPeriod,
    directionPeriod]

/-- The deliberately overstrong assertion that uses the whole label product
as a ray period while retaining the actual seed, box, admissibility, and
arm-divisibility premises. -/
def productAsPeriodRayCapacityImplication
    (S : Finset ℕ) (H R B C M N : ℕ) (base : ℕ × ℕ)
    (s t : ℕ) (label : ArmDivisorLabel) : Prop :=
  (seedOneCanonicalPremises R B C M ∧
      (∀ n ∈ S, n ≤ H) ∧
      (∀ n ∈ S, certifiedAffinePointInBox R B C M
        (affineRayPoint base s t n)) ∧
      (∀ n ∈ S, armDivisorsAt R B C
        (affineRayPoint base s t n) label.u label.v label.w) ∧
      0 < label.u ∧ 0 < label.v ∧ 0 < label.w ∧
      label.PairwiseCoprime ∧ N ^ 2 < label.product) →
    S.card ≤ H / label.product + 1

private theorem radical_72 : abcRadical 72 = 6 := by
  rw [show 72 = 2 ^ 3 * 3 ^ 2 by norm_num, abcRadical_eq_natRadical,
    UniqueFactorizationMonoid.radical_mul
      (Nat.coprime_iff_isRelPrime.mp (by norm_num)),
    UniqueFactorizationMonoid.radical_pow_of_prime
      (by exact (by norm_num : Nat.Prime 2).prime) (by norm_num),
    UniqueFactorizationMonoid.radical_pow_of_prime
      (by exact (by norm_num : Nat.Prime 3).prime) (by norm_num)]
  norm_num

/-- The canonical `(1,8,9)` four-point fibre attains the correct period cap
but refutes the whole-product-as-period assertion with every actual premise
retained. -/
theorem seed189_productAsPeriod_fullPremise_counterexample :
    let B : ℕ := 8
    let C : ℕ := 9
    let R : ℕ := 6
    let M : ℕ := canonicalBoxM C R
    let N : ℕ := M - 1
    let base : ℕ × ℕ := (21480, 282)
    let s : ℕ := 0
    let t : ℕ := 1
    let H : ℕ := 17787
    let S : Finset ℕ := {0, 5929, 11858, 17787}
    let label : ArmDivisorLabel := ⟨128881, 49, 121⟩
    seedOneCanonicalPremises R B C M ∧
      (∀ n ∈ S, n ≤ H) ∧
      (∀ n ∈ S, certifiedAffinePointInBox R B C M
        (affineRayPoint base s t n)) ∧
      (∀ n ∈ S, armDivisorsAt R B C
        (affineRayPoint base s t n) label.u label.v label.w) ∧
      label.PairwiseCoprime ∧
      N ^ 2 < label.product ∧ S.card = 4 ∧
      directionPeriod label s (s + C * t) (s + B * t) = 5929 ∧
      directionCapture label s (s + C * t) (s + B * t) = 128881 ∧
      ¬ directionCapture label s (s + C * t) (s + B * t) ≤
        (B + 1) * (C + 1) * (max s t) ^ 3 ∧
      directionPeriod label s (s + C * t) (s + B * t) *
        directionCapture label s (s + C * t) (s + B * t) =
          label.product ∧
      S.card = H /
        directionPeriod label s (s + C * t) (s + B * t) + 1 ∧
      H / label.product + 1 = 1 ∧
      ¬ productAsPeriodRayCapacityImplication
        S H R B C M N base s t label := by
  norm_num [seedOneCanonicalPremises, certifiedAffinePointInBox,
    armDivisorsAt, productAsPeriodRayCapacityImplication,
    ArmDivisorLabel.PairwiseCoprime, ArmDivisorLabel.product,
    canonicalBoxM, affineRayPoint, affineU, affineV, affineW,
    reducedDirectionPeriod, directionPeriod, directionCapture, radical_72]


end AffineCollinearPeriodEnergy20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/AffineCollinearPeriodEnergy20260901.lean -/

/- BEGIN EXACT BODY: IUTThreeClosures/IUTRationalTripodShadowComparison20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/


/-!
# The rational-tripod shadow comparison

The mathematical proofs precede this formalization in
`research/ABC_IUT_RATIONAL_TRIPOD_SHADOW_COMPARISON_2026_09_01.md`.

This module constructs an explicit shadow `Genl.HeightTheory` on the actual
open rational tripod. Its degree-at-most-one encoding and its height and
radical comparisons are exact. Statement I for this shadow is equivalent to
integer abc. Separate full-premise models show why the current abstract
`HeightTheory` fields do not automatically provide degree realization or
uniform normalization constants for an intended arithmetic theory.

The shadow and the pressure models are audit interfaces. None is identified
with Mochizuki's IUT or with Project LANA's intended arithmetic height theory.
-/

namespace IUTThreeClosures
namespace IUTRationalTripodShadowComparison20260901

open IUTAdmissibleVolumeIntegerBridge20260901

/-! ## The actual open rational tripod and exact arithmetic conversions -/

/-- Rational points strictly between the three marked values `0` and `1`. -/
def OpenUnitRational := {x : ℚ // 0 < x ∧ x < 1}

/-- The rational point `1/2` witnesses that the open rational tripod is
inhabited. -/
def halfOpenUnitRational : OpenUnitRational :=
  ⟨1 / 2, by norm_num, by norm_num⟩

instance : Nonempty OpenUnitRational := ⟨halfOpenUnitRational⟩

/-- Actual normalized rational Weil height on the open tripod. -/
noncomputable def openUnitHeight (x : OpenUnitRational) : ℝ :=
  rationalTripodHeight x.1

/-- Actual truncated rational tripod counting function. -/
noncomputable def openUnitCounting (x : OpenUnitRational) : ℝ :=
  rationalTripodCounting x.1

/-- Both actual rational-tripod functions are nonnegative. -/
theorem openUnitHeight_nonneg (x : OpenUnitRational) :
    0 ≤ openUnitHeight x := by
  exact Heights.normalizedLogHeight_nonneg ℚ x.1

theorem openUnitCounting_nonneg (x : OpenUnitRational) :
    0 ≤ openUnitCounting x := by
  exact Real.log_natCast_nonneg _

/-- Forgetting the duplicate wrapper yields the repository's established
`ABCPoint` representation. -/
def tripleToABCPoint (t : PositivePrimitiveABCTriple) : ABCPoint where
  a := t.a
  b := t.b
  c := t.c
  a_pos := t.a_pos
  b_pos := t.b_pos
  c_pos := t.c_pos
  sum_eq := t.sum_eq
  pairwise_coprime := t.pairwiseCoprime

/-- The canonical open rational tripod coordinate of a primitive triple. -/
noncomputable def openUnitCoordinate
    (t : PositivePrimitiveABCTriple) : OpenUnitRational :=
  ⟨(tripleToABCPoint t).lambda, (tripleToABCPoint t).lambda_pos,
    (tripleToABCPoint t).lambda_lt_one⟩

/-- The actual rational height of the encoded coordinate is exactly the
integer height in `ABCConjecture`. -/
theorem openUnitHeight_coordinate (t : PositivePrimitiveABCTriple) :
    openUnitHeight (openUnitCoordinate t) = t.logHeight := by
  change rationalTripodHeight (tripleToABCPoint t).lambda = t.logHeight
  rw [ABCPoint.rationalTripodHeight_lambda]
  rfl

/-- The actual rational tripod count is exactly the logarithm of the integer
radical. -/
theorem openUnitCounting_coordinate (t : PositivePrimitiveABCTriple) :
    openUnitCounting (openUnitCoordinate t) = t.logRadical := by
  change rationalTripodCounting (tripleToABCPoint t).lambda = t.logRadical
  rw [ABCPoint.rationalTripodCounting_lambda]
  rfl

namespace OpenUnitRational

/-- The inverse reduced primitive triple attached to an open rational point. -/
def toABCPoint (x : OpenUnitRational) : ABCPoint :=
  ABCPoint.ofRat x.1 x.2.1 x.2.2

/-- The inverse point, expressed in the comparison module's triple wrapper. -/
def toPositivePrimitiveABCTriple
    (x : OpenUnitRational) : PositivePrimitiveABCTriple where
  a := x.toABCPoint.a
  b := x.toABCPoint.b
  c := x.toABCPoint.c
  a_pos := x.toABCPoint.a_pos
  b_pos := x.toABCPoint.b_pos
  c_pos := x.toABCPoint.c_pos
  sum_eq := x.toABCPoint.sum_eq
  pairwiseCoprime := x.toABCPoint.pairwise_coprime

/-- The inverse triple has exactly the original rational-tripod height. -/
theorem logHeight_toPositivePrimitiveABCTriple (x : OpenUnitRational) :
    x.toPositivePrimitiveABCTriple.logHeight = openUnitHeight x := by
  let P : ABCPoint := ABCPoint.ofRat x.1 x.2.1 x.2.2
  change P.height = rationalTripodHeight x.1
  have hcoord : P.lambda = x.1 :=
    ABCPoint.ofRat_lambda x.1 x.2.1 x.2.2
  calc
    P.height = rationalTripodHeight P.lambda :=
      P.rationalTripodHeight_lambda.symm
    _ = rationalTripodHeight x.1 := congrArg rationalTripodHeight hcoord

/-- The inverse triple has exactly the original rational-tripod count. -/
theorem logRadical_toPositivePrimitiveABCTriple (x : OpenUnitRational) :
    x.toPositivePrimitiveABCTriple.logRadical = openUnitCounting x := by
  let P : ABCPoint := ABCPoint.ofRat x.1 x.2.1 x.2.2
  change P.conductor = rationalTripodCounting x.1
  have hcoord : P.lambda = x.1 :=
    ABCPoint.ofRat_lambda x.1 x.2.1 x.2.2
  calc
    P.conductor = rationalTripodCounting P.lambda :=
      P.rationalTripodCounting_lambda.symm
    _ = rationalTripodCounting x.1 := congrArg rationalTripodCounting hcoord

/-- Passing to the reduced primitive triple and back recovers the original
open rational point. -/
theorem openUnitCoordinate_toPositivePrimitiveABCTriple
    (x : OpenUnitRational) :
    openUnitCoordinate x.toPositivePrimitiveABCTriple = x := by
  apply Subtype.ext
  change (ABCPoint.ofRat x.1 x.2.1 x.2.2).lambda = x.1
  exact ABCPoint.ofRat_lambda x.1 x.2.1 x.2.2

end OpenUnitRational

/-! ## The semantic comparison on all open rational points -/

/-- The minimal semantic realization of the standard rational tripod inside
an abstract height theory, with errors uniform over every rational point. -/
structure OpenUnitTripodComparison (T : Genl.HeightTheory) where
  encode : OpenUnitRational → T.Pt T.tripod
  encode_mem_degreeAtMostOne : ∀ x, encode x ∈ T.ptLE T.tripod 1
  heightError : ℝ
  radicalError : ℝ
  height_le : ∀ x,
    openUnitHeight x ≤ T.htCan T.tripod (encode x) + heightError
  logDiff_add_logCond_le : ∀ x,
    T.logDiff T.tripod (encode x) + T.logCond T.tripod (encode x) ≤
      openUnitCounting x + radicalError

namespace OpenUnitTripodComparison

/-- Restriction to primitive integer triples gives the earlier exact integer
comparison package without changing either error constant. -/
noncomputable def toStatementIIntegerComparison
    {T : Genl.HeightTheory} (B : OpenUnitTripodComparison T) :
    StatementIIntegerComparison T where
  encode t := B.encode (openUnitCoordinate t)
  encode_mem_degreeAtMostOne t :=
    B.encode_mem_degreeAtMostOne (openUnitCoordinate t)
  heightError := B.heightError
  radicalError := B.radicalError
  logHeight_le t := by
    rw [← openUnitHeight_coordinate t]
    exact B.height_le (openUnitCoordinate t)
  logDiff_add_logCond_le t := by
    rw [← openUnitCounting_coordinate t]
    exact B.logDiff_add_logCond_le (openUnitCoordinate t)

/-- Conversely, the inverse reduced triple construction upgrades an integer
comparison to all open rational points, preserving its constants. -/
noncomputable def ofStatementIIntegerComparison
    {T : Genl.HeightTheory} (B : StatementIIntegerComparison T) :
    OpenUnitTripodComparison T where
  encode x := B.encode x.toPositivePrimitiveABCTriple
  encode_mem_degreeAtMostOne x :=
    B.encode_mem_degreeAtMostOne x.toPositivePrimitiveABCTriple
  heightError := B.heightError
  radicalError := B.radicalError
  height_le x := by
    rw [← x.logHeight_toPositivePrimitiveABCTriple]
    exact B.logHeight_le x.toPositivePrimitiveABCTriple
  logDiff_add_logCond_le x := by
    rw [← x.logRadical_toPositivePrimitiveABCTriple]
    exact B.logDiff_add_logCond_le x.toPositivePrimitiveABCTriple

/-- At the level of existence, the rational and integer comparison packages
have exactly the same strength. -/
theorem nonempty_iff_statementIIntegerComparison
    (T : Genl.HeightTheory) :
    Nonempty (OpenUnitTripodComparison T) ↔
      Nonempty (StatementIIntegerComparison T) :=
  ⟨fun ⟨B⟩ => ⟨B.toStatementIIntegerComparison⟩,
    fun ⟨B⟩ => ⟨ofStatementIIntegerComparison B⟩⟩

end OpenUnitTripodComparison

/-! ## A family of one-curve shadow height theories -/

/-- Degree-at-most loci for a shadow in which every point has exact degree
one. -/
def shadowPtLE (d : ℕ) : Set OpenUnitRational :=
  if d = 0 then ∅ else Set.univ

/-- Exact-degree loci for a shadow in which every point has exact degree one. -/
def shadowPtEQ (d : ℕ) : Set OpenUnitRational :=
  if d = 1 then Set.univ else ∅

theorem shadowPtLE_zero : shadowPtLE 0 = ∅ := by
  simp [shadowPtLE]

theorem shadowPtLE_succ (d : ℕ) :
    shadowPtLE (d + 1) = shadowPtLE d ∪ shadowPtEQ (d + 1) := by
  cases d with
  | zero => simp [shadowPtLE, shadowPtEQ]
  | succ d => simp [shadowPtLE, shadowPtEQ]

/-- A one-curve `HeightTheory` with the actual open rational tripod as its
point type and caller-supplied numerical functions. This is an audit shadow,
not the intended arithmetic-geometric implementation. -/
noncomputable def openUnitShadowHeightTheory
    (height logDiff logCond : OpenUnitRational → ℝ) :
    Genl.HeightTheory where
  Curve := Unit
  Pt := fun _ => OpenUnitRational
  Hyperbolic := fun _ => True
  DivisorFree := fun _ => True
  ptLE := fun _ d => shadowPtLE d
  ptEQ := fun _ d => shadowPtEQ d
  ptLE_zero := fun _ => shadowPtLE_zero
  ptLE_succ := fun _ d => shadowPtLE_succ d
  htCan := fun _ => height
  logDiff := fun _ => logDiff
  logCond := fun _ => logCond
  tripod := ()
  hyperbolic_tripod := True.intro
  CBS := Unit
  cbsSet := fun _ => Set.univ

/-- The quantifier-correct pointwise form of Statement I on the one-curve
shadow. -/
def UniformOpenUnitBound
    (height logDiff logCond : OpenUnitRational → ℝ) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∃ C : ℝ, ∀ x : OpenUnitRational,
    height x ≤ (1 + ε) * (logDiff x + logCond x) + C

/-- Statement I for a one-curve shadow is exactly its uniform pointwise
inequality. -/
theorem openUnitShadow_statementI_iff
    (height logDiff logCond : OpenUnitRational → ℝ) :
    (openUnitShadowHeightTheory height logDiff logCond).StatementI ↔
      UniformOpenUnitBound height logDiff logCond := by
  constructor
  · intro hI ε hε
    obtain ⟨C, hC⟩ := hI () True.intro 1 ε hε
    refine ⟨C, ?_⟩
    intro x
    have hx : x ∈ (openUnitShadowHeightTheory height logDiff logCond).ptLE
        (openUnitShadowHeightTheory height logDiff logCond).tripod 1 := by
      change x ∈ shadowPtLE 1
      simp [shadowPtLE]
    have h := hC x hx
    change height x ≤ ((1 + ε) • (logDiff + logCond)) x + C at h
    simpa only [Pi.smul_apply, Pi.add_apply, smul_eq_mul] using h
  · intro hbound X hX d ε hε
    obtain ⟨C, hC⟩ := hbound ε hε
    refine ⟨C, ?_⟩
    intro x hx
    have h := hC x
    change height x ≤ ((1 + ε) • (logDiff + logCond)) x + C
    simpa only [Pi.smul_apply, Pi.add_apply, smul_eq_mul] using h

/-! ## The exact rational-tripod shadow -/

/-- The canonical rational shadow: actual Weil height, zero different, and
actual truncated tripod count. -/
noncomputable def rationalTripodShadow : Genl.HeightTheory :=
  openUnitShadowHeightTheory openUnitHeight (fun _ => 0) openUnitCounting

/-- All four comparison fields are inhabited with the identity encoding and
zero error. -/
noncomputable def rationalTripodShadowComparison :
    OpenUnitTripodComparison rationalTripodShadow where
  encode := id
  encode_mem_degreeAtMostOne x := by
    change x ∈ shadowPtLE 1
    simp [shadowPtLE]
  heightError := 0
  radicalError := 0
  height_le x := by
    simp [rationalTripodShadow, openUnitShadowHeightTheory]
  logDiff_add_logCond_le x := by
    simp [rationalTripodShadow, openUnitShadowHeightTheory]

/-- The earlier integer comparison package is therefore unconditionally
inhabited for the exact rational shadow. -/
noncomputable def rationalTripodShadowIntegerComparison :
    StatementIIntegerComparison rationalTripodShadow :=
  rationalTripodShadowComparison.toStatementIIntegerComparison

/-- Statement I for the exact rational shadow is exactly integer abc. -/
theorem rationalTripodShadow_statementI_iff_abc :
    rationalTripodShadow.StatementI ↔ ABCConjecture := by
  constructor
  · intro hI
    exact abcConjecture_of_statementI_comparison hI
      rationalTripodShadowIntegerComparison
  · intro habc
    change (openUnitShadowHeightTheory openUnitHeight (fun _ => 0)
      openUnitCounting).StatementI
    rw [openUnitShadow_statementI_iff]
    intro ε hε
    obtain ⟨C, hC⟩ :=
      uniformRationalSUnitTripodBound_of_abc habc ε hε
    refine ⟨C, ?_⟩
    intro x
    have hx := hC x.1 x.2.1 x.2.2
    simpa [openUnitHeight, openUnitCounting] using hx

/-! ## Unboundedness on actual open rational points -/

/-- The actual rational-tripod height is unbounded on `0 < x < 1`. -/
theorem openUnitHeight_unbounded (A : ℝ) :
    ∃ x : OpenUnitRational, A < openUnitHeight x := by
  have htendsto :
      Filter.Tendsto (fun n : ℕ => Real.log (n : ℝ))
        Filter.atTop Filter.atTop :=
    Real.tendsto_log_atTop.comp tendsto_natCast_atTop_atTop
  obtain ⟨N, hN⟩ :=
    Filter.eventually_atTop.1 (htendsto.eventually_gt_atTop A)
  let n : ℕ := max N 1
  have hnN : N ≤ n := le_max_left _ _
  have hn : 0 < n := lt_of_lt_of_le Nat.zero_lt_one (le_max_right _ _)
  have hlog : A < Real.log (n : ℝ) := hN n hnN
  let P : ABCPoint :=
    { a := 1
      b := n
      c := n + 1
      a_pos := by simp
      b_pos := hn
      c_pos := Nat.succ_pos n
      sum_eq := by omega
      pairwise_coprime := by simp [PairwiseCoprimeABC] }
  let x : OpenUnitRational :=
    ⟨P.lambda, P.lambda_pos, P.lambda_lt_one⟩
  refine ⟨x, ?_⟩
  change A < rationalTripodHeight P.lambda
  rw [P.rationalTripodHeight_lambda, P.height_eq_log_c]
  have hnR : 0 < (n : ℝ) := by exact_mod_cast hn
  have hnle : (n : ℝ) ≤ ((n + 1 : ℕ) : ℝ) := by
    exact_mod_cast Nat.le_succ n
  exact hlog.trans_le (Real.log_le_log hnR hnle)

/-! ## Full-premise pressure test: degree realization -/

/-- A full `HeightTheory` whose point type is inhabited but whose degree loci
are all empty. -/
noncomputable def degreeEmptyHeightTheory : Genl.HeightTheory where
  Curve := Unit
  Pt := fun _ => Unit
  Hyperbolic := fun _ => True
  DivisorFree := fun _ => True
  ptLE := fun _ _ => ∅
  ptEQ := fun _ _ => ∅
  ptLE_zero := by simp
  ptLE_succ := by simp
  htCan := fun _ _ => 0
  logDiff := fun _ _ => 0
  logCond := fun _ _ => 0
  tripod := ()
  hyperbolic_tripod := True.intro
  CBS := Unit
  cbsSet := fun _ => ∅

/-- Statement I is vacuously true in the degree-empty model. -/
theorem degreeEmptyHeightTheory_statementI :
    degreeEmptyHeightTheory.StatementI := by
  intro X hX d ε hε
  change DiscrepancyLE (fun _ : Unit => (0 : ℝ))
    ((1 + ε) • ((fun _ : Unit => (0 : ℝ)) + fun _ : Unit => 0)) ∅
  exact DiscrepancyLE.empty

/-- Nevertheless the nonempty open rational tripod cannot be encoded into its
empty degree-at-most-one locus. This refutes only automatic degree realization
from the current abstract fields and Statement I. -/
theorem degreeEmptyHeightTheory_no_openUnitComparison :
    ¬ Nonempty (OpenUnitTripodComparison degreeEmptyHeightTheory) := by
  rintro ⟨B⟩
  have hmem := B.encode_mem_degreeAtMostOne halfOpenUnitRational
  change B.encode halfOpenUnitRational ∈ (∅ : Set Unit) at hmem
  exact hmem

/-- A single existential countermodel to the claim that Statement I for the
current bare interface automatically supplies the rational comparison. -/
theorem statementI_does_not_force_openUnitComparison :
    ∃ T : Genl.HeightTheory.{0},
      T.StatementI ∧ ¬ Nonempty (OpenUnitTripodComparison T) :=
  ⟨degreeEmptyHeightTheory, degreeEmptyHeightTheory_statementI,
    degreeEmptyHeightTheory_no_openUnitComparison⟩

/-! ## Full-premise pressure test: uniform height normalization -/

/-- Actual rational points and counting, but a zero canonical-height field. -/
noncomputable def heightZeroShadow : Genl.HeightTheory :=
  openUnitShadowHeightTheory (fun _ => 0) (fun _ => 0) openUnitCounting

/-- Statement I holds unconditionally in the height-zero shadow. -/
theorem heightZeroShadow_statementI : heightZeroShadow.StatementI := by
  change (openUnitShadowHeightTheory (fun _ => 0) (fun _ => 0)
    openUnitCounting).StatementI
  rw [openUnitShadow_statementI_iff]
  intro ε hε
  refine ⟨0, ?_⟩
  intro x
  simp only [zero_add, add_zero]
  exact mul_nonneg (by linarith) (openUnitCounting_nonneg x)

theorem heightZeroShadow_degree_mem (x : OpenUnitRational) :
    x ∈ heightZeroShadow.ptLE heightZeroShadow.tripod 1 := by
  change x ∈ shadowPtLE 1
  simp [shadowPtLE]

/-- The radical comparison survives with error zero. -/
theorem heightZeroShadow_radical_exact (x : OpenUnitRational) :
    heightZeroShadow.logDiff heightZeroShadow.tripod x +
      heightZeroShadow.logCond heightZeroShadow.tripod x =
        openUnitCounting x := by
  simp [heightZeroShadow, openUnitShadowHeightTheory]

/-- A point-dependent height error makes the missing comparison hold
tautologically. -/
theorem heightZeroShadow_pointwise_height_error (x : OpenUnitRational) :
    openUnitHeight x ≤
      heightZeroShadow.htCan heightZeroShadow.tripod x + openUnitHeight x := by
  simp [heightZeroShadow, openUnitShadowHeightTheory]

/-- No single height error works on every actual open rational point. -/
theorem heightZeroShadow_no_uniform_height_error :
    ¬ ∃ A : ℝ, ∀ x : OpenUnitRational,
      openUnitHeight x ≤
        heightZeroShadow.htCan heightZeroShadow.tripod x + A := by
  rintro ⟨A, hA⟩
  obtain ⟨x, hx⟩ := openUnitHeight_unbounded A
  have hle := hA x
  change openUnitHeight x ≤ 0 + A at hle
  linarith

/-- All retained premises of the height-normalization test are displayed in
one theorem. -/
theorem heightZeroShadow_fullPremise_countermodel :
    heightZeroShadow.StatementI ∧
      (∀ x : OpenUnitRational,
        x ∈ heightZeroShadow.ptLE heightZeroShadow.tripod 1) ∧
      (∀ x : OpenUnitRational,
        heightZeroShadow.logDiff heightZeroShadow.tripod x +
          heightZeroShadow.logCond heightZeroShadow.tripod x =
            openUnitCounting x) ∧
      (∀ x : OpenUnitRational,
        openUnitHeight x ≤ heightZeroShadow.htCan
          heightZeroShadow.tripod x + openUnitHeight x) ∧
      ¬ ∃ A : ℝ, ∀ x : OpenUnitRational,
        openUnitHeight x ≤
          heightZeroShadow.htCan heightZeroShadow.tripod x + A :=
  ⟨heightZeroShadow_statementI, heightZeroShadow_degree_mem,
    heightZeroShadow_radical_exact,
    heightZeroShadow_pointwise_height_error,
    heightZeroShadow_no_uniform_height_error⟩

/-! ## Full-premise pressure test: uniform radical normalization -/

/-- An artificial positive different term used to test whether the bare
interface forces the arithmetic radical normalization. -/
noncomputable def inflatedDifferent (x : OpenUnitRational) : ℝ :=
  Real.exp (2 * openUnitHeight x)

/-- Actual rational height and counting, with an inflated different term. -/
noncomputable def radicalInflatedShadow : Genl.HeightTheory :=
  openUnitShadowHeightTheory openUnitHeight inflatedDifferent openUnitCounting

/-- The inflated shadow still satisfies Statement I unconditionally. -/
theorem radicalInflatedShadow_statementI :
    radicalInflatedShadow.StatementI := by
  change (openUnitShadowHeightTheory openUnitHeight inflatedDifferent
    openUnitCounting).StatementI
  rw [openUnitShadow_statementI_iff]
  intro ε hε
  refine ⟨0, ?_⟩
  intro x
  let H : ℝ := openUnitHeight x
  let M : ℝ := inflatedDifferent x + openUnitCounting x
  have hH : 0 ≤ H := openUnitHeight_nonneg x
  have hcount : 0 ≤ openUnitCounting x := openUnitCounting_nonneg x
  have hexp : 1 + 2 * H ≤ inflatedDifferent x := by
    simpa [inflatedDifferent, H, add_comm] using
      (Real.add_one_le_exp (2 * H))
  have hM : 0 ≤ M := by
    exact add_nonneg (Real.exp_pos _).le hcount
  have hHM : H ≤ M := by
    dsimp [M]
    linarith
  have hcoef : 1 ≤ 1 + ε := by linarith
  have hscale : M ≤ (1 + ε) * M := by
    nlinarith
  change H ≤ (1 + ε) * M + 0
  linarith

theorem radicalInflatedShadow_degree_mem (x : OpenUnitRational) :
    x ∈ radicalInflatedShadow.ptLE radicalInflatedShadow.tripod 1 := by
  change x ∈ shadowPtLE 1
  simp [shadowPtLE]

/-- The height comparison survives with error zero. -/
theorem radicalInflatedShadow_height_exact (x : OpenUnitRational) :
    openUnitHeight x =
      radicalInflatedShadow.htCan radicalInflatedShadow.tripod x := by
  rfl

/-- A point-dependent radical error makes the inflated comparison exact. -/
theorem radicalInflatedShadow_pointwise_radical_error
    (x : OpenUnitRational) :
    radicalInflatedShadow.logDiff radicalInflatedShadow.tripod x +
      radicalInflatedShadow.logCond radicalInflatedShadow.tripod x =
        openUnitCounting x + inflatedDifferent x := by
  change inflatedDifferent x + openUnitCounting x =
    openUnitCounting x + inflatedDifferent x
  ring

/-- No single radical error absorbs the inflated different term. -/
theorem radicalInflatedShadow_no_uniform_radical_error :
    ¬ ∃ A : ℝ, ∀ x : OpenUnitRational,
      radicalInflatedShadow.logDiff radicalInflatedShadow.tripod x +
        radicalInflatedShadow.logCond radicalInflatedShadow.tripod x ≤
          openUnitCounting x + A := by
  rintro ⟨A, hA⟩
  obtain ⟨x, hx⟩ := openUnitHeight_unbounded ((A - 1) / 2)
  have hexpLower := Real.add_one_le_exp (2 * openUnitHeight x)
  have hexpGt : A < inflatedDifferent x := by
    dsimp [inflatedDifferent]
    linarith
  have hle := hA x
  change inflatedDifferent x + openUnitCounting x ≤
    openUnitCounting x + A at hle
  linarith

/-- All retained premises of the radical-normalization test are displayed in
one theorem. -/
theorem radicalInflatedShadow_fullPremise_countermodel :
    radicalInflatedShadow.StatementI ∧
      (∀ x : OpenUnitRational,
        x ∈ radicalInflatedShadow.ptLE radicalInflatedShadow.tripod 1) ∧
      (∀ x : OpenUnitRational,
        openUnitHeight x = radicalInflatedShadow.htCan
          radicalInflatedShadow.tripod x) ∧
      (∀ x : OpenUnitRational,
        radicalInflatedShadow.logDiff radicalInflatedShadow.tripod x +
          radicalInflatedShadow.logCond radicalInflatedShadow.tripod x =
            openUnitCounting x + inflatedDifferent x) ∧
      ¬ ∃ A : ℝ, ∀ x : OpenUnitRational,
        radicalInflatedShadow.logDiff radicalInflatedShadow.tripod x +
          radicalInflatedShadow.logCond radicalInflatedShadow.tripod x ≤
            openUnitCounting x + A :=
  ⟨radicalInflatedShadow_statementI, radicalInflatedShadow_degree_mem,
    radicalInflatedShadow_height_exact,
    radicalInflatedShadow_pointwise_radical_error,
    radicalInflatedShadow_no_uniform_radical_error⟩













end IUTRationalTripodShadowComparison20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/IUTRationalTripodShadowComparison20260901.lean -/

/- BEGIN EXACT BODY: IUTThreeClosures/MersenneMultiplierIndexTwoArm20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/

/-!
# Multiplier-index compression for the Mersenne exact-order gate

The mathematical proofs precede this file in
`research/ABC_MERSENNE_MULTIPLIER_INDEX_TWO_ARM_2026_09_01.md`.

If a prime `p` has exact base-two order `d`, then `d ∣ p - 1`.  The quotient
`(p - 1) / d` is a positive multiplier, and it determines `p` injectively
inside the exact-order fibre.  Therefore any subfibre whose multipliers lie
below `H` has at most `H` members.  This is the finite arithmetic core of an
elementary estimate for all repeated exact-order primes below a moving
near-quadratic cutoff.

After that low-multiplier mass is removed, only two nonnegative arms remain:
deep valuation excess and primes whose exact order is at most a moving
polylogarithmic multiple of the square root of their size.  The final section
formalizes the exact two-arm subtraction, its composition over the existing
fixed-polylogarithmic window, and the sharp abstract ceiling one half.

No order-distribution, Wieferich-density, cyclotomic squarefreeness, or abc
assertion is introduced as an axiom.
-/

namespace IUTThreeClosures
namespace MersenneMultiplierIndexTwoArm20260901

open scoped BigOperators
open MersenneOrderBlockDecomposition20260901
open MersenneWeightedOrderTail20260901
open MersenneTotientDivisorConcentration20260901
open MersennePolylogCodivisorGate20260901
open MersenneFixedPolylogBlockMassTriage20260901

/-! ## Exact-order multiplier packets -/

/-- The finite prime fibre having exact base-two order `d`. -/
noncomputable def exactOrderPrimeFiber (d : ℕ) : Finset ℕ :=
  (2 ^ d - 1).primeFactors.filter
    (fun p => mersenneExactOrder p = d)

/-- Every prime in the positive exact-order fibre is represented by its
integral multiplier `(p - 1) / d`. -/
theorem exactOrder_prime_eq_one_add_mul_multiplier
    {d p : ℕ} (hd : 0 < d) (hpMem : p ∈ exactOrderPrimeFiber d) :
    p = 1 + d * ((p - 1) / d) := by
  have hpPrimeFactors : p ∈ (2 ^ d - 1).primeFactors :=
    (Finset.mem_filter.mp hpMem).1
  have hpOrder : mersenneExactOrder p = d :=
    (Finset.mem_filter.mp hpMem).2
  have hp : p.Prime := Nat.prime_of_mem_primeFactors hpPrimeFactors
  have hpDvd : p ∣ 2 ^ d - 1 := Nat.dvd_of_mem_primeFactors hpPrimeFactors
  have hdDvd : d ∣ p - 1 := by
    simpa [hpOrder] using
      (mersenneExactOrder_dvd_prime_sub_one hd hp hpDvd)
  have hmul : d * ((p - 1) / d) = p - 1 :=
    Nat.mul_div_cancel' hdDvd
  have hpPos : 0 < p := hp.pos
  omega

/-- The multiplier in a positive exact-order fibre is positive. -/
theorem exactOrder_multiplier_pos
    {d p : ℕ} (hd : 0 < d) (hpMem : p ∈ exactOrderPrimeFiber d) :
    0 < (p - 1) / d := by
  have hpPrimeFactors : p ∈ (2 ^ d - 1).primeFactors :=
    (Finset.mem_filter.mp hpMem).1
  have hpOrder : mersenneExactOrder p = d :=
    (Finset.mem_filter.mp hpMem).2
  have hp : p.Prime := Nat.prime_of_mem_primeFactors hpPrimeFactors
  have hpDvd : p ∣ 2 ^ d - 1 := Nat.dvd_of_mem_primeFactors hpPrimeFactors
  have hdDvd : d ∣ p - 1 := by
    simpa [hpOrder] using
      (mersenneExactOrder_dvd_prime_sub_one hd hp hpDvd)
  have hpTwo : 2 ≤ p := hp.two_le
  have hpPredPos : 0 < p - 1 := by omega
  exact Nat.div_pos (Nat.le_of_dvd hpPredPos hdDvd) hd

/-- Within one exact-order fibre, the integral multiplier determines the
prime injectively. -/
theorem exactOrder_multiplier_injectiveOn
    (d : ℕ) (hd : 0 < d) :
    Set.InjOn (fun p : ℕ => (p - 1) / d)
      (exactOrderPrimeFiber d : Set ℕ) := by
  intro p hp q hq hpq
  change (p - 1) / d = (q - 1) / d at hpq
  calc
    p = 1 + d * ((p - 1) / d) :=
      exactOrder_prime_eq_one_add_mul_multiplier hd hp
    _ = 1 + d * ((q - 1) / d) := by rw [hpq]
    _ = q := (exactOrder_prime_eq_one_add_mul_multiplier hd hq).symm

/-- A finite family with an injective natural label below `H` has at most
`H` members. -/
theorem card_le_of_injective_multiplier_lt
    (s : Finset ℕ) (multiplier : ℕ → ℕ) (H : ℕ)
    (hinj : Set.InjOn multiplier (s : Set ℕ))
    (hlt : ∀ p ∈ s, multiplier p < H) :
    s.card ≤ H := by
  have hmaps : Set.MapsTo multiplier (s : Set ℕ)
      (Finset.range H : Set ℕ) := by
    intro p hp
    exact Finset.mem_range.mpr (hlt p hp)
  have hcard : s.card ≤ (Finset.range H).card :=
    Finset.card_le_card_of_injOn multiplier hmaps hinj
  simpa using hcard

/-- Exact-order primes whose multiplier is below `H`.  The repeated-prime
support used in the paper is a subset of this stronger fibre. -/
noncomputable def lowMultiplierExactOrderPrimes (d H : ℕ) : Finset ℕ :=
  (exactOrderPrimeFiber d).filter
    (fun p => (p - 1) / d < H)

/-- The actual low-multiplier exact-order fibre has cardinality at most the
multiplier cutoff. -/
theorem lowMultiplierExactOrderPrimes_card_le
    {d H : ℕ} (hd : 0 < d) :
    (lowMultiplierExactOrderPrimes d H).card ≤ H := by
  apply card_le_of_injective_multiplier_lt
      (lowMultiplierExactOrderPrimes d H)
      (fun p : ℕ => (p - 1) / d) H
  · intro p hp q hq hpq
    exact exactOrder_multiplier_injectiveOn d hd
      (Finset.mem_filter.mp hp).1 (Finset.mem_filter.mp hq).1 hpq
  · intro p hp
    exact (Finset.mem_filter.mp hp).2

/-- Logarithmic mass of the actual low-multiplier fibre. -/
noncomputable def lowMultiplierExactOrderLogMass (d H : ℕ) : ℝ :=
  ∑ p ∈ lowMultiplierExactOrderPrimes d H, Real.log (p : ℝ)

/-- A pointwise logarithmic cap and multiplier injectivity give the exact
finite mass bound `H * cap`. -/
theorem lowMultiplierExactOrderLogMass_le
    {d H : ℕ} (hd : 0 < d) {cap : ℝ} (hcapNonneg : 0 ≤ cap)
    (hcap : ∀ p ∈ lowMultiplierExactOrderPrimes d H,
      Real.log (p : ℝ) ≤ cap) :
    lowMultiplierExactOrderLogMass d H ≤ (H : ℝ) * cap := by
  have hsum :
      lowMultiplierExactOrderLogMass d H ≤
        ((lowMultiplierExactOrderPrimes d H).card : ℝ) * cap := by
    unfold lowMultiplierExactOrderLogMass
    calc
      (∑ p ∈ lowMultiplierExactOrderPrimes d H, Real.log (p : ℝ)) ≤
          ∑ _p ∈ lowMultiplierExactOrderPrimes d H, cap := by
            exact Finset.sum_le_sum fun p hp => hcap p hp
      _ = ((lowMultiplierExactOrderPrimes d H).card : ℝ) * cap := by
            simp
  have hcard :
      ((lowMultiplierExactOrderPrimes d H).card : ℝ) ≤ (H : ℝ) := by
    exact_mod_cast lowMultiplierExactOrderPrimes_card_le (d := d) (H := H) hd
  exact hsum.trans (mul_le_mul_of_nonneg_right hcard hcapNonneg)






/-! ## Two-arm subtraction -/

/-- Once the controlled low-multiplier arm fits below the target after two
copies of `share` are reserved, the deep or near-square-root arm carries
`share`. -/
theorem deep_or_nearSquare_of_low_budget
    {target low deep nearSquare share : ℝ}
    (htotal : target ≤ low + deep + nearSquare)
    (hlow : low ≤ target - 2 * share) :
    share ≤ deep ∨ share ≤ nearSquare := by
  by_contra h
  push Not at h
  rcases h with ⟨hdeep, hnear⟩
  linarith

/-- Exact fixed-window composition of the two-arm lemma.  A pointwise
three-term decomposition is summed over the existing strict
fixed-polylogarithmic window. -/
theorem polylogLocalizedBlockMass_twoArm_of_low_budget
    (total low deep nearSquare : ℕ → ℝ) (k m : ℕ)
    {target share : ℝ}
    (hdecomp : ∀ d, total d ≤ low d + deep d + nearSquare d)
    (htarget : target ≤ polylogLocalizedBlockMass total k m)
    (hlow : polylogLocalizedBlockMass low k m ≤ target - 2 * share) :
    share ≤ polylogLocalizedBlockMass deep k m ∨
      share ≤ polylogLocalizedBlockMass nearSquare k m := by
  have hsum :
      polylogLocalizedBlockMass total k m ≤
        polylogLocalizedBlockMass low k m +
          polylogLocalizedBlockMass deep k m +
          polylogLocalizedBlockMass nearSquare k m := by
    unfold polylogLocalizedBlockMass restrictedDivisorMass
    calc
      (∑ d ∈ m.divisors.filter
          (fun d => Real.log (m / d : ℕ) < fixedPolylogScale k m),
          total d) ≤
          ∑ d ∈ m.divisors.filter
            (fun d => Real.log (m / d : ℕ) < fixedPolylogScale k m),
            (low d + deep d + nearSquare d) := by
              exact Finset.sum_le_sum fun d _ => hdecomp d
      _ =
          (∑ d ∈ m.divisors.filter
              (fun d => Real.log (m / d : ℕ) < fixedPolylogScale k m),
              low d) +
            (∑ d ∈ m.divisors.filter
              (fun d => Real.log (m / d : ℕ) < fixedPolylogScale k m),
              deep d) +
            (∑ d ∈ m.divisors.filter
              (fun d => Real.log (m / d : ℕ) < fixedPolylogScale k m),
              nearSquare d) := by
                simp only [Finset.sum_add_distrib]
  exact deep_or_nearSquare_of_low_budget (htarget.trans hsum) hlow

/-- Convenient one-third specialization of the two-arm theorem. -/
theorem deep_or_nearSquare_of_one_controlled_arm
    {target low deep nearSquare : ℝ}
    (htotal : target ≤ low + deep + nearSquare)
    (hlow : low ≤ target / 3) :
    target / 3 ≤ deep ∨ target / 3 ≤ nearSquare := by
  apply deep_or_nearSquare_of_low_budget htotal
  calc
    low ≤ target / 3 := hlow
    _ = target - 2 * (target / 3) := by ring



/-! ## Exact abstract ceiling -/

/-- Full finite premises for zero controlled mass and two unresolved arms. -/
def ZeroLowTwoArmPremises
    (target low deep nearSquare : ℝ) : Prop :=
  0 ≤ target ∧ 0 ≤ low ∧ 0 ≤ deep ∧ 0 ≤ nearSquare ∧
  target = low + deep + nearSquare ∧ low = 0

/-- One half is the sharp algebraic ceiling: `(2,0,1,1)` defeats every
larger coefficient under every displayed premise. -/
theorem one_half_is_sharp_two_arm_ceiling
    {c : ℝ} (hc : (1 : ℝ) / 2 < c) :
    ∃ target low deep nearSquare : ℝ,
      ZeroLowTwoArmPremises target low deep nearSquare ∧
      ¬ (c * target ≤ deep ∨ c * target ≤ nearSquare) := by
  refine ⟨2, 0, 1, 1, ?_, ?_⟩
  · norm_num [ZeroLowTwoArmPremises]
  · push Not
    constructor <;> nlinarith

end MersenneMultiplierIndexTwoArm20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/MersenneMultiplierIndexTwoArm20260901.lean -/

/- BEGIN EXACT BODY: IUTThreeClosures/PellOddKernelThirdOrderPacket20260901.lean -/
/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/

/-!
# Odd-kernel and third-order localization for the balancing-Pell packet

The mathematical proofs precede this module in
`research/ABC_PELL_ODD_KERNEL_THIRD_ORDER_PACKET_2026_09_01.md`.

This file checks the reusable integer core:

* the cubic-square normal form of a finite squarefull factor packet;
* transport of the odd-exponent kernel through congruences;
* the quadratic-reciprocity steps used by the index--kernel triangle;
* the third-order expansion of an arbitrary finite product;
* cancellation to the quotient and the third-order two-channel coupling.

No existence or nonexistence assertion for a squarefull Pell packet is
assumed.
-/

namespace IUTThreeClosures
namespace PellOddKernelThirdOrderPacket20260901

/-! ## Cubic-square encoding of squarefull exponent vectors -/

/-- A squarefull exponent is either `2 + 2*tail` or `3 + 2*tail`.
The Boolean records whether it is odd. -/
structure SquarefullFactor where
  base : ℤ
  tail : ℕ
  oddDepth : Bool
deriving DecidableEq

def SquarefullFactor.exponent (f : SquarefullFactor) : ℕ :=
  if f.oddDepth then 3 + 2 * f.tail else 2 + 2 * f.tail

def SquarefullFactor.kernelTerm (f : SquarefullFactor) : ℤ :=
  if f.oddDepth then f.base else 1

def SquarefullFactor.coreTerm (f : SquarefullFactor) : ℤ :=
  f.base ^ (if f.oddDepth then f.tail else f.tail + 1)

def packetValue (fs : List SquarefullFactor) : ℤ :=
  (fs.map fun f => f.base ^ f.exponent).prod

def oddKernel (fs : List SquarefullFactor) : ℤ :=
  (fs.map SquarefullFactor.kernelTerm).prod

def squareCore (fs : List SquarefullFactor) : ℤ :=
  (fs.map SquarefullFactor.coreTerm).prod

/-- Each encoded squarefull prime power is its odd-kernel contribution
cubed times a square. -/
theorem factor_value_eq_kernel_cube_mul_core_square (f : SquarefullFactor) :
    f.base ^ f.exponent = f.kernelTerm ^ 3 * f.coreTerm ^ 2 := by
  cases h : f.oddDepth
  · simp only [SquarefullFactor.exponent, SquarefullFactor.kernelTerm,
      SquarefullFactor.coreTerm, h, Bool.false_eq_true, ↓reduceIte]
    rw [show 2 + 2 * f.tail = (f.tail + 1) + (f.tail + 1) by omega, pow_add]
    ring
  · simp only [SquarefullFactor.exponent, SquarefullFactor.kernelTerm,
      SquarefullFactor.coreTerm, h, ↓reduceIte]
    rw [show 3 + 2 * f.tail = 3 + f.tail + f.tail by omega, pow_add, pow_add]
    ring

/-- The complete finite packet has the canonical shape `D^3*C^2`. -/
theorem packetValue_eq_oddKernel_cube_mul_squareCore_square
    (fs : List SquarefullFactor) :
    packetValue fs = oddKernel fs ^ 3 * squareCore fs ^ 2 := by
  induction fs with
  | nil => simp [packetValue, oddKernel, squareCore]
  | cons f fs ih =>
      simp only [packetValue, oddKernel, squareCore] at ih
      simp only [packetValue, oddKernel, squareCore, List.map_cons, List.prod_cons]
      rw [factor_value_eq_kernel_cube_mul_core_square, ih]
      ring

/-- A factor marked as odd has an odd exponent at least three. -/
theorem odd_depth_exponent_packet (f : SquarefullFactor)
    (hodd : f.oddDepth = true) :
    Odd f.exponent ∧ 3 ≤ f.exponent := by
  simp only [SquarefullFactor.exponent, hodd, ↓reduceIte]
  constructor
  · refine ⟨f.tail + 1, ?_⟩
    omega
  · omega

/-! ## Congruence transport for the odd kernel -/

/-- If every base is one modulo `m`, so is the odd-exponent kernel. -/
theorem oddKernel_modEq_one (m : ℤ) (fs : List SquarefullFactor)
    (hbase : ∀ f ∈ fs, f.base ≡ 1 [ZMOD m]) :
    oddKernel fs ≡ 1 [ZMOD m] := by
  induction fs with
  | nil => simp [oddKernel]
  | cons f fs ih =>
      have hfmem : f ∈ f :: fs := by simp
      have htail : ∀ g ∈ fs, g.base ≡ 1 [ZMOD m] := by
        intro g hg
        exact hbase g (by simp [hg])
      have hi := ih htail
      have hf : f.kernelTerm ≡ 1 [ZMOD m] := by
        cases h : f.oddDepth
        · simp [SquarefullFactor.kernelTerm, h]
        · simpa [SquarefullFactor.kernelTerm, h] using hbase f hfmem
      simpa [oddKernel] using hf.mul hi

def oddSignProduct (sign : SquarefullFactor → ℤ)
    (fs : List SquarefullFactor) : ℤ :=
  (fs.map fun f => if f.oddDepth then sign f else 1).prod

/-- Base congruences with individual signs collapse, after parity reduction,
to the corresponding product over the odd-exponent kernel. -/
theorem oddKernel_modEq_oddSignProduct
    (m : ℤ) (sign : SquarefullFactor → ℤ) (fs : List SquarefullFactor)
    (hbase : ∀ f ∈ fs, f.base ≡ sign f [ZMOD m]) :
    oddKernel fs ≡ oddSignProduct sign fs [ZMOD m] := by
  induction fs with
  | nil => simp [oddKernel, oddSignProduct]
  | cons f fs ih =>
      have hfmem : f ∈ f :: fs := by simp
      have htail : ∀ g ∈ fs, g.base ≡ sign g [ZMOD m] := by
        intro g hg
        exact hbase g (by simp [hg])
      have hi := ih htail
      have hf : f.kernelTerm ≡ (if f.oddDepth then sign f else 1) [ZMOD m] := by
        cases h : f.oddDepth
        · simp [SquarefullFactor.kernelTerm, h]
        · simpa [SquarefullFactor.kernelTerm, h] using hbase f hfmem
      simpa [oddKernel, oddSignProduct] using hf.mul hi

/-- Once the kernel and the packet have the same sign modulo `m`, the square
core has square one modulo `m`. -/
theorem squareCore_sq_modEq_one_of_signed_packet
    (m s : ℤ) (fs : List SquarefullFactor)
    (hsign : s = 1 ∨ s = -1)
    (hkernel : oddKernel fs ≡ s [ZMOD m])
    (hvalue : packetValue fs ≡ s [ZMOD m]) :
    squareCore fs ^ 2 ≡ 1 [ZMOD m] := by
  have hpacket : oddKernel fs ^ 3 * squareCore fs ^ 2 ≡ s [ZMOD m] := by
    simpa [packetValue_eq_oddKernel_cube_mul_squareCore_square] using hvalue
  have hreplace : oddKernel fs ^ 3 * squareCore fs ^ 2 ≡
      s ^ 3 * squareCore fs ^ 2 [ZMOD m] :=
    (hkernel.pow 3).mul_right (squareCore fs ^ 2)
  have hsigned : s ^ 3 * squareCore fs ^ 2 ≡ s [ZMOD m] :=
    hreplace.symm.trans hpacket
  rcases hsign with rfl | rfl
  · simpa using hsigned
  · have hneg := hsigned.neg
    simpa using hneg

/-! ## Jacobi reciprocity steps for the index--kernel triangle -/

open scoped NumberTheorySymbols

/-- A numerator congruent to one has Jacobi symbol one. -/
theorem jacobi_eq_one_of_mod_eq_one (a b : ℕ) (hmod : a % b = 1) :
    J((a : ℤ) | b) = 1 := by
  have hz : (a : ℤ) % (b : ℤ) = 1 := by exact_mod_cast hmod
  calc
    J((a : ℤ) | b) = J(((a : ℤ) % b) | b) := jacobiSym.mod_left _ _
    _ = J(1 | b) := by rw [hz]
    _ = 1 := jacobiSym.one_left b

/-- If both odd arguments are `3 mod 4` and the forward symbol is one,
reciprocity makes the reverse symbol negative. -/
theorem jacobi_reverse_neg_of_both_three_mod_four
    (ell D : ℕ)
    (hell : ell % 4 = 3) (hD : D % 4 = 3)
    (hforward : J((D : ℤ) | ell) = 1) :
    J((ell : ℤ) | D) = -1 := by
  have hrec := jacobiSym.quadratic_reciprocity_three_mod_four hell hD
  rw [hforward] at hrec
  simpa using hrec

/-- A denominator `1 mod 4` introduces no reciprocity sign. -/
theorem jacobi_reverse_eq_of_denominator_one_mod_four
    (ell D : ℕ) (hellOdd : Odd ell) (hD : D % 4 = 1) :
    J((ell : ℤ) | D) = J((D : ℤ) | ell) :=
  jacobiSym.quadratic_reciprocity_one_mod_four' hellOdd hD

/-- The complete three-negative aggregate triangle forced in the
`ell = 3 mod 8` class, expressed at the exact Jacobi interface. -/
theorem three_negative_character_triangle
    (ell DA DB : ℕ)
    (hell3 : ell % 4 = 3)
    (hDA3 : DA % 4 = 3)
    (hDB1 : DB % 4 = 1)
    (hellOdd : Odd ell)
    (hDAForward : J((DA : ℤ) | ell) = 1)
    (hDBForward : J((DB : ℤ) | ell) = -1)
    (hCross : J((DA : ℤ) | DB) = -1) :
    J((DA : ℤ) | DB) = -1 ∧
      J((ell : ℤ) | DA) = -1 ∧
      J((ell : ℤ) | DB) = -1 := by
  refine ⟨hCross, jacobi_reverse_neg_of_both_three_mod_four ell DA hell3 hDA3
    hDAForward, ?_⟩
  rw [jacobi_reverse_eq_of_denominator_one_mod_four ell DB hellOdd hDB1]
  exact hDBForward

/-- The all-positive aggregate triangle in the `ell = 1 mod 8` class. -/
theorem all_positive_character_triangle
    (ell DA DB : ℕ)
    (hell1 : ell % 4 = 1)
    (hDAOdd : Odd DA) (hDB1 : DB % 4 = 1)
    (hellOdd : Odd ell)
    (hDAForward : J((DA : ℤ) | ell) = 1)
    (hDBForward : J((DB : ℤ) | ell) = 1)
    (hCross : J((DA : ℤ) | DB) = 1) :
    J((DA : ℤ) | DB) = 1 ∧
      J((ell : ℤ) | DA) = 1 ∧
      J((ell : ℤ) | DB) = 1 := by
  refine ⟨hCross, ?_, ?_⟩
  · rw [jacobiSym.quadratic_reciprocity_one_mod_four hell1 hDAOdd]
    exact hDAForward
  · rw [jacobi_reverse_eq_of_denominator_one_mod_four ell DB hellOdd hDB1]
    exact hDBForward

/-- The aggregate sign row in the `ell = 5 mod 8` class. -/
theorem cross_only_negative_character_triangle
    (ell DA DB : ℕ)
    (hell1 : ell % 4 = 1)
    (hDAOdd : Odd DA) (hDB1 : DB % 4 = 1)
    (hellOdd : Odd ell)
    (hDAForward : J((DA : ℤ) | ell) = 1)
    (hDBForward : J((DB : ℤ) | ell) = 1)
    (hCross : J((DA : ℤ) | DB) = -1) :
    J((DA : ℤ) | DB) = -1 ∧
      J((ell : ℤ) | DA) = 1 ∧
      J((ell : ℤ) | DB) = 1 := by
  refine ⟨hCross, ?_, ?_⟩
  · rw [jacobiSym.quadratic_reciprocity_one_mod_four hell1 hDAOdd]
    exact hDAForward
  · rw [jacobi_reverse_eq_of_denominator_one_mod_four ell DB hellOdd hDB1]
    exact hDBForward

/-- The aggregate sign row in the `ell = 7 mod 8` class. -/
theorem index_A_only_negative_character_triangle
    (ell DA DB : ℕ)
    (hell3 : ell % 4 = 3)
    (hDA3 : DA % 4 = 3) (hDB1 : DB % 4 = 1)
    (hellOdd : Odd ell)
    (hDAForward : J((DA : ℤ) | ell) = 1)
    (hDBForward : J((DB : ℤ) | ell) = 1)
    (hCross : J((DA : ℤ) | DB) = 1) :
    J((DA : ℤ) | DB) = 1 ∧
      J((ell : ℤ) | DA) = -1 ∧
      J((ell : ℤ) | DB) = 1 := by
  refine ⟨hCross, jacobi_reverse_neg_of_both_three_mod_four ell DA hell3 hDA3
    hDAForward, ?_⟩
  rw [jacobi_reverse_eq_of_denominator_one_mod_four ell DB hellOdd hDB1]
  exact hDBForward

/-! ## Third-order finite products and the coupled quotient ledger -/

/-- Degree-two elementary coefficient of `prod_i (1+x*t_i)`. -/
def pairCoefficient : List ℤ → ℤ
  | [] => 0
  | t :: ts => t * ts.sum + pairCoefficient ts

/-- Degree-three elementary coefficient of `prod_i (1+x*t_i)`. -/
def tripleCoefficient : List ℤ → ℤ
  | [] => 0
  | t :: ts => t * pairCoefficient ts + tripleCoefficient ts

/-- Truncation of an arbitrary finite product after the cubic term. -/
theorem product_one_add_thirdOrder (x : ℤ) (ts : List ℤ) :
    (ts.map fun t => 1 + x * t).prod ≡
      1 + x * ts.sum + x ^ 2 * pairCoefficient ts +
        x ^ 3 * tripleCoefficient ts [ZMOD x ^ 4] := by
  induction ts with
  | nil => simp [pairCoefficient, tripleCoefficient]
  | cons t ts ih =>
      have hmul := ih.mul_left (1 + x * t)
      have htruncate :
          (1 + x * t) *
              (1 + x * ts.sum + x ^ 2 * pairCoefficient ts +
                x ^ 3 * tripleCoefficient ts) ≡
            1 + x * (t + ts.sum) +
              x ^ 2 * (t * ts.sum + pairCoefficient ts) +
              x ^ 3 * (t * pairCoefficient ts + tripleCoefficient ts)
              [ZMOD x ^ 4] := by
        apply Int.modEq_of_dvd
        refine ⟨-(t * tripleCoefficient ts), ?_⟩
        ring
      simpa [pairCoefficient, tripleCoefficient] using hmul.trans htruncate

/-- Cancelling `x` turns a product expansion modulo `x^4` into a quotient
expansion modulo `x^3`. -/
theorem quotient_thirdOrder_of_product
    (x a : ℤ) (ts : List ℤ) (hx : x ≠ 0)
    (hprod : 1 + x * a = (ts.map fun t => 1 + x * t).prod) :
    a ≡ ts.sum + x * pairCoefficient ts + x ^ 2 * tripleCoefficient ts
      [ZMOD x ^ 3] := by
  have hfull :
      1 + x * a ≡
        1 + x * ts.sum + x ^ 2 * pairCoefficient ts +
          x ^ 3 * tripleCoefficient ts [ZMOD x ^ 4] := by
    rw [hprod]
    exact product_one_add_thirdOrder x ts
  apply Int.modEq_of_dvd
  rcases hfull.dvd with ⟨k, hk⟩
  refine ⟨k, ?_⟩
  have hcancel :
      x * (ts.sum + x * pairCoefficient ts +
          x ^ 2 * tripleCoefficient ts - a) =
        x * (x ^ 3 * k) := by
    calc
      x * (ts.sum + x * pairCoefficient ts +
          x ^ 2 * tripleCoefficient ts - a) =
          (1 + x * ts.sum + x ^ 2 * pairCoefficient ts +
            x ^ 3 * tripleCoefficient ts) - (1 + x * a) := by ring
      _ = x ^ 4 * k := hk
      _ = x * (x ^ 3 * k) := by ring
  exact mul_left_cancel₀ hx hcancel

/-- Transfer of the two third-order channel congruences through the exact
negative-Pell quotient conic. -/
theorem thirdOrderCoupling_of_channelCongruences
    (ell a b KA KB CA CB HA HB : ℤ)
    (ha : a ≡ KA + 2 * ell * CA + 4 * ell ^ 2 * HA [ZMOD 8 * ell ^ 3])
    (hb : b ≡ KB + 2 * ell * CB + 4 * ell ^ 2 * HB [ZMOD 8 * ell ^ 3])
    (hExact : a - 2 * b + ell * (a ^ 2 - 2 * b ^ 2) = 0) :
    KA - 2 * KB + ell * (KA ^ 2 - 2 * KB ^ 2) +
        2 * ell * (CA - 2 * CB) +
        4 * ell ^ 2 * (HA - 2 * HB + KA * CA - 2 * KB * CB) +
        4 * ell ^ 3 * (CA ^ 2 - 2 * CB ^ 2) ≡ 0 [ZMOD 8 * ell ^ 3] := by
  let a0 := KA + 2 * ell * CA + 4 * ell ^ 2 * HA
  let b0 := KB + 2 * ell * CB + 4 * ell ^ 2 * HB
  have hlinear : a - 2 * b ≡ a0 - 2 * b0 [ZMOD 8 * ell ^ 3] :=
    ha.sub (hb.mul_left 2)
  have hquadratic :
      ell * (a ^ 2 - 2 * b ^ 2) ≡
        ell * (a0 ^ 2 - 2 * b0 ^ 2) [ZMOD 8 * ell ^ 3] :=
    ((ha.pow 2).sub ((hb.pow 2).mul_left 2)).mul_left ell
  have hsum := hlinear.add hquadratic
  have htruncate :
      a0 - 2 * b0 + ell * (a0 ^ 2 - 2 * b0 ^ 2) ≡
        KA - 2 * KB + ell * (KA ^ 2 - 2 * KB ^ 2) +
          2 * ell * (CA - 2 * CB) +
          4 * ell ^ 2 * (HA - 2 * HB + KA * CA - 2 * KB * CB) +
          4 * ell ^ 3 * (CA ^ 2 - 2 * CB ^ 2)
          [ZMOD 8 * ell ^ 3] := by
    apply Int.modEq_of_dvd
    refine ⟨-((KA * HA - 2 * KB * HB) +
      2 * ell * (CA * HA - 2 * CB * HB) +
      2 * ell ^ 2 * (HA ^ 2 - 2 * HB ^ 2)), ?_⟩
    dsimp [a0, b0]
    ring
  have hzero :
      a - 2 * b + ell * (a ^ 2 - 2 * b ^ 2) ≡ 0
        [ZMOD 8 * ell ^ 3] := by
    rw [hExact]
  exact htruncate.symm.trans (hsum.symm.trans hzero)

/-- Complete third-order coefficient certificate at index seven:
`T_A=[17]` and `T_B=[-1,-1]`. -/
theorem indexSeven_thirdOrderCoefficientCertificate :
    ([17].sum, pairCoefficient [17], tripleCoefficient [17],
      ([-1, -1] : List ℤ).sum, pairCoefficient [-1, -1],
      tripleCoefficient [-1, -1]) =
      ((17 : ℤ), 0, 0, -2, 1, 0) := by
  norm_num [pairCoefficient, tripleCoefficient]

/-- The resulting third-order coupling is exact, hence in particular zero
modulo `8*7^3`. -/
theorem indexSeven_thirdOrderCouplingCertificate :
    (17 : ℤ) - 2 * (-2) + 7 * (17 ^ 2 - 2 * (-2) ^ 2) +
        2 * 7 * (0 - 2 * 1) +
        4 * 7 ^ 2 * (0 - 2 * 0 + 17 * 0 - 2 * (-2) * 1) +
        4 * 7 ^ 3 * (0 ^ 2 - 2 * 1 ^ 2) ≡ 0 [ZMOD 8 * 7 ^ 3] := by
  norm_num [Int.ModEq]

#check packetValue_eq_oddKernel_cube_mul_squareCore_square
#check factor_value_eq_kernel_cube_mul_core_square
#check odd_depth_exponent_packet
#check oddKernel_modEq_one
#check oddKernel_modEq_oddSignProduct
#check squareCore_sq_modEq_one_of_signed_packet
#check jacobi_eq_one_of_mod_eq_one
#check jacobi_reverse_neg_of_both_three_mod_four
#check jacobi_reverse_eq_of_denominator_one_mod_four
#check three_negative_character_triangle
#check all_positive_character_triangle
#check cross_only_negative_character_triangle
#check index_A_only_negative_character_triangle
#check product_one_add_thirdOrder
#check quotient_thirdOrder_of_product
#check thirdOrderCoupling_of_channelCongruences
#check indexSeven_thirdOrderCoefficientCertificate
#check indexSeven_thirdOrderCouplingCertificate


















end PellOddKernelThirdOrderPacket20260901
end IUTThreeClosures
/- END EXACT BODY: IUTThreeClosures/PellOddKernelThirdOrderPacket20260901.lean -/

/- BEGIN GENERATED COMPLETE THEOREM/LEMMA AXIOM AUDIT -/
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.reducedDirectionPeriod_pos
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.reducedDirectionPeriod_dvd_self
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.reducedDirectionPeriod_dvd_of_dvd_mul
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.directionPeriod_pos
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.directionPeriod_dvd_gap
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.directionPeriod_mul_capture
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.natAbs_natCast_sub_eq_dist
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.nat_dvd_dist_mul_of_intCast_dvd_sub_mul
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.sharedLabel_ray_directionDivisibilities
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.sharedLabel_ray_directionPeriod_dvd_dist
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.periodicIndexSet_card_le
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.mem_rayLabelFiber_iff
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.rayLabelFiber_card_le_directionPeriod
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.directionCapture_nonconstant_le_cubic
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.cubic_card_bound_of_period
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.rayLabelFiber_nonconstant_shiftedCube_lt
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.omitting_positive_ambient_breaks_cubic_card_bound
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.cube_le_four_mul_of_shiftedCube_lt
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.factorThree_shiftedCube_counterexample
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.weightedCubicMoment_le_four
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.rayCatalogue_weightedCubicEnergy_le
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.directionCapture_vertical_le_quadratic
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.quadratic_card_bound_of_period
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.rayLabelFiber_vertical_shiftedSquare_lt
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.omitting_pairwise_breaks_directionPeriod_product
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.radical_72
#print axioms IUTThreeClosures.AffineCollinearPeriodEnergy20260901.seed189_productAsPeriod_fullPremise_counterexample
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.openUnitHeight_nonneg
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.openUnitCounting_nonneg
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.openUnitHeight_coordinate
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.openUnitCounting_coordinate
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.OpenUnitRational.logHeight_toPositivePrimitiveABCTriple
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.OpenUnitRational.logRadical_toPositivePrimitiveABCTriple
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.OpenUnitRational.openUnitCoordinate_toPositivePrimitiveABCTriple
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.OpenUnitTripodComparison.nonempty_iff_statementIIntegerComparison
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.shadowPtLE_zero
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.shadowPtLE_succ
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.openUnitShadow_statementI_iff
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.rationalTripodShadow_statementI_iff_abc
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.openUnitHeight_unbounded
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.degreeEmptyHeightTheory_statementI
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.degreeEmptyHeightTheory_no_openUnitComparison
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.statementI_does_not_force_openUnitComparison
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.heightZeroShadow_statementI
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.heightZeroShadow_degree_mem
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.heightZeroShadow_radical_exact
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.heightZeroShadow_pointwise_height_error
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.heightZeroShadow_no_uniform_height_error
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.heightZeroShadow_fullPremise_countermodel
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.radicalInflatedShadow_statementI
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.radicalInflatedShadow_degree_mem
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.radicalInflatedShadow_height_exact
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.radicalInflatedShadow_pointwise_radical_error
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.radicalInflatedShadow_no_uniform_radical_error
#print axioms IUTThreeClosures.IUTRationalTripodShadowComparison20260901.radicalInflatedShadow_fullPremise_countermodel
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.exactOrder_prime_eq_one_add_mul_multiplier
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.exactOrder_multiplier_pos
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.exactOrder_multiplier_injectiveOn
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.card_le_of_injective_multiplier_lt
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.lowMultiplierExactOrderPrimes_card_le
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.lowMultiplierExactOrderLogMass_le
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.deep_or_nearSquare_of_low_budget
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.polylogLocalizedBlockMass_twoArm_of_low_budget
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.deep_or_nearSquare_of_one_controlled_arm
#print axioms IUTThreeClosures.MersenneMultiplierIndexTwoArm20260901.one_half_is_sharp_two_arm_ceiling
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.factor_value_eq_kernel_cube_mul_core_square
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.packetValue_eq_oddKernel_cube_mul_squareCore_square
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.odd_depth_exponent_packet
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.oddKernel_modEq_one
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.oddKernel_modEq_oddSignProduct
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.squareCore_sq_modEq_one_of_signed_packet
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.jacobi_eq_one_of_mod_eq_one
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.jacobi_reverse_neg_of_both_three_mod_four
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.jacobi_reverse_eq_of_denominator_one_mod_four
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.three_negative_character_triangle
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.all_positive_character_triangle
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.cross_only_negative_character_triangle
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.index_A_only_negative_character_triangle
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.product_one_add_thirdOrder
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.quotient_thirdOrder_of_product
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.thirdOrderCoupling_of_channelCongruences
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.indexSeven_thirdOrderCoefficientCertificate
#print axioms IUTThreeClosures.PellOddKernelThirdOrderPacket20260901.indexSeven_thirdOrderCouplingCertificate
/- END GENERATED COMPLETE THEOREM/LEMMA AXIOM AUDIT -/
