import IUTThreeClosures.ActualDistinguishedProcessionProductRegion

/-! Dependency audit for the actual distinguished-procession product region. -/

#print axioms
  IUTThreeClosures.ActualDistinguishedProcessionProductRegion.processionCoordinateRegion_logVolume
#print axioms
  IUTThreeClosures.ActualDistinguishedProcessionProductRegion.distinguishedProcessionProductRegion_logVolume
#print axioms
  IUTThreeClosures.ActualDistinguishedProcessionProductRegion.distinguishedProcessionProductRegion_logVolume_eq_length_mul_average
#print axioms
  IUTThreeClosures.ActualDistinguishedProcessionProductRegion.distinguishedProcessionProductRegion_logVolume_eq_length_mul_squareAverage
#print axioms
  IUTThreeClosures.ActualDistinguishedProcessionProductRegion.normalizedDistinguishedProcessionMass_eq_normalizedProcessionMass
#print axioms
  IUTThreeClosures.ActualDistinguishedProcessionProductRegion.normalizedDistinguishedProcessionMass_eq_squareAverage_mul_arithmeticLogQ
#print axioms
  IUTThreeClosures.ActualDistinguishedProcessionProductRegion.canonicalQPilot_normalizedDistinguishedProcessionMass_eq_publicLogQ
