/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.ActualHodgeTheaterOutput
import IUTThreeClosures.NormControlledSourceGenerators

/-!
# A relational Tate/Kummer source at one actual bad place

The generic source framework models Ind3 by upper semi-compatibility: a target
region need only be contained in the image of the source region under a
log-link map. This module instantiates that framework at the completed local
field of an actual bad Hodge-theater place.

* ordinary branches are the genuine Tate regions `q^n O`;
* Ind1 is multiplication by a norm-one Kummer unit;
* the one-component shadow of Ind2 is the identity;
* the local Ind3 map is multiplication by a nonnegative power of the actual
  Tate parameter;
* the common radial envelope is the norm unit ball.

The induced Ind3 relation is not equality with a prescribed image: every
actual target contained in the q-power image is accepted. Norm arithmetic
then proves the native-image and possible-image-envelope conclusions.

This is a local analytic source theorem. It does not assert that every global
Hodge-theater possible image is represented by these operations; the genuine
Theorem 3.11 realization and procession/archimedean assembly remain separate.
-/

namespace IUTThreeClosures

open Iut NumberField TateCurvesTheta

universe u

variable {AG : AnabelianGeometry.{u}} {TG : TemperedGeometry AG}
variable {D : InitialThetaData AG TG}

namespace ActualBadHodgeTheaterPlace

/-- The norm-controlled relational source generated by the actual Tate
parameter at one bad place. -/
noncomputable def actualTateRelationalSource
    (H : ActualBadHodgeTheaterPlace D) :
    NormControlledSourceGenerators H.TateField where
  Ordinary := ℕ
  Ind1 := NormOneKummerUnit H.TateField
  Ind2 := Unit
  Ind3 := ℕ
  ordinaryRegion := H.tate.qPowerRegion
  native := 1
  radius := 1
  ordinary_le_radius := by
    intro n
    have h := H.tate.qPowerRegion_antitone (Nat.zero_le n)
    simpa [radialEnvelope, normIntegralRegion] using h
  ind1Map := fun a z => (a.unit : H.TateField) * z
  ind2Map := fun _ z => z
  ind3Map := fun n z => (H.tate.q : H.TateField) ^ n * z
  ind1_norm := by
    intro a z
    rw [norm_mul, a.norm_eq_one, one_mul]
  ind2_norm := by
    intro a z
    exact le_rfl
  ind3_norm := by
    intro n z
    rw [norm_mul, norm_pow]
    exact mul_le_of_le_one_left
      (norm_nonneg z)
      (pow_le_one₀ (norm_nonneg _) H.tate.norm_lt_one.le)

/-- The relational Ind3 step accepts every target region contained in the
q-power image of the source region. -/
theorem actualTate_step3_iff
    (H : ActualBadHodgeTheaterPlace D)
    (n : ℕ) (U V : Set H.TateField) :
    H.actualTateRelationalSource.step3 n U V ↔
      V ⊆ (fun z : H.TateField =>
        (H.tate.q : H.TateField) ^ n * z) '' U :=
  Iff.rfl

/-- The native ordinary branch is exactly the actual `q O` region. -/
@[simp]
theorem actualTateRelational_nativeRegion
    (H : ActualBadHodgeTheaterPlace D) :
    H.actualTateRelationalSource.ordinaryRegion
        H.actualTateRelationalSource.native =
      H.tate.qPowerRegion 1 :=
  rfl

/-- The radial envelope is the actual local norm unit ball. -/
theorem actualTateRelational_radialEnvelope
    (H : ActualBadHodgeTheaterPlace D) :
    radialEnvelope (α := H.TateField)
        H.actualTateRelationalSource.radius =
      normIntegralRegion (K := H.TateField) := by
  ext z
  rfl

/-- The actual local `q O` native branch lies in the relationally generated
possible-image union. -/
theorem actualTateRelational_nativeImage
    (H : ActualBadHodgeTheaterPlace D) :
    H.tate.qPowerRegion 1 ⊆
      H.actualTateRelationalSource.toUpperSemicompatibleSystem.possibleUnion := by
  simpa using H.actualTateRelationalSource.actualNativeImage

/-- Every image generated by ordinary Tate branches, norm-one Kummer maps,
identity reindexing and relational q-power Ind3 steps lies in the local unit
ball. -/
theorem actualTateRelational_possibleImageEnvelope
    (H : ActualBadHodgeTheaterPlace D) :
    H.actualTateRelationalSource.toUpperSemicompatibleSystem.possibleUnion ⊆
      normIntegralRegion (K := H.TateField) := by
  rw [← H.actualTateRelational_radialEnvelope]
  exact H.actualTateRelationalSource.actualPossibleImageEnvelope

/-- Consequently the native q-pilot region lies in the common unit-ball
envelope. -/
theorem actualTateRelational_native_le_envelope
    (H : ActualBadHodgeTheaterPlace D) :
    H.tate.qPowerRegion 1 ⊆
      normIntegralRegion (K := H.TateField) :=
  H.actualTateRelational_nativeImage.trans
    H.actualTateRelational_possibleImageEnvelope

end ActualBadHodgeTheaterPlace

end IUTThreeClosures
