/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.ActualLocalKummerChoices

/-!
# Normal form for the generated local Kummer choice closure

This file gives a genuine coverage theorem for the formal choice system
generated by the ordinary theta-pilot branch, norm-one Kummer ambiguities, and
nonnegative Ind3 exponent enlargements.

Rather than postulating that every output has the form `unit * q^n`, we define
the possible-image type inductively by the source operations and prove, by
normalization, that every generated image admits a unique explicit
`FactorKummerChoice` representative up to multiplication of norm-one units.
The exact norm and principal-region formulas then follow from the previously
proved factorwise theorems.

Ind2 label permutations act before the primitive factor decomposition: they
change the initial squared-label exponent function supplied to `ordinary`.
Thus the post-decomposition closure below contains exactly the operations that
act factorwise.  A full comparison with Mochizuki's possible-image collection
must still prove that its ordinary branch and Ind3 arrows are generated by
these constructors, or else use the more general hull-envelope theorem already
present on `main`.
-/

set_option linter.checkUnivs false

namespace IUTThreeClosures

universe u v

namespace NormOneKummerUnit

variable {K : Type v} [NormedField K]

/-- Product of norm-one ambiguities. -/
def mul (a b : NormOneKummerUnit K) : NormOneKummerUnit K where
  unit := a.unit * b.unit
  norm_eq_one := by
    rw [norm_mul, a.norm_eq_one, b.norm_eq_one, one_mul]

@[simp]
theorem mul_unit (a b : NormOneKummerUnit K) :
    (a.mul b).unit = a.unit * b.unit := rfl

end NormOneKummerUnit

/-- Possible images generated from one ordinary factorwise theta-pilot packet
by the actual factorwise Ind1 and exponent-enlargement operations. -/
inductive GeneratedFactorKummerImage
    {C : Type u} (K : C → Type v)
    [∀ c, NormedField (K c)]
    (tate : ∀ c, TateCurvesTheta.TateParameter (K c))
    (ordinaryPower : C → ℕ) : Type (max u (v + 1))
  | ordinary : GeneratedFactorKummerImage K tate ordinaryPower
  | ind1
      (unit : ∀ c, NormOneKummerUnit (K c))
      (previous : GeneratedFactorKummerImage K tate ordinaryPower) :
      GeneratedFactorKummerImage K tate ordinaryPower
  | ind3
      (extra : C → ℕ)
      (previous : GeneratedFactorKummerImage K tate ordinaryPower) :
      GeneratedFactorKummerImage K tate ordinaryPower

namespace GeneratedFactorKummerImage

variable {C : Type u} {K : C → Type v}
variable [∀ c, NormedField (K c)]
variable {tate : ∀ c, TateCurvesTheta.TateParameter (K c)}
variable {ordinaryPower : C → ℕ}

/-- Normalize a generated possible image to an explicit factorwise Kummer
choice. -/
noncomputable def normalize :
    GeneratedFactorKummerImage K tate ordinaryPower →
      FactorKummerChoice C K
  | .ordinary =>
      { tate := tate
        ind1 := fun _ => NormOneKummerUnit.one
        power := ordinaryPower }
  | .ind1 unit previous =>
      let A := normalize previous
      { tate := A.tate
        ind1 := fun c => (unit c).mul (A.ind1 c)
        power := A.power }
  | .ind3 extra previous =>
      let A := normalize previous
      { tate := A.tate
        ind1 := A.ind1
        power := fun c => A.power c + extra c }

@[simp]
theorem normalize_ordinary_tate (c : C) :
    (normalize
      (GeneratedFactorKummerImage.ordinary
        (K := K) tate ordinaryPower)).tate c = tate c := rfl

@[simp]
theorem normalize_ordinary_power (c : C) :
    (normalize
      (GeneratedFactorKummerImage.ordinary
        (K := K) tate ordinaryPower)).power c = ordinaryPower c := rfl

/-- Every generated possible image has an exact norm-one-unit times q-power
normal form. -/
theorem exists_normalForm
    (X : GeneratedFactorKummerImage K tate ordinaryPower) :
    ∃ A : FactorKummerChoice C K,
      A = X.normalize ∧
      (∀ c,
        ‖A.outputValue c‖ =
          ‖((A.tate c).q : K c)‖ ^ A.power c) := by
  refine ⟨X.normalize, rfl, ?_⟩
  intro c
  exact X.normalize.norm_outputValue c

/-- Region-level coverage theorem for the generated choice closure. -/
theorem normalized_region_eq_qPowerProduct
    (X : GeneratedFactorKummerImage K tate ordinaryPower) :
    X.normalize.packetRegion =
      {x | ∀ c,
        x c ∈ (X.normalize.tate c).qPowerRegion
          (X.normalize.power c)} :=
  X.normalize.packetRegion_eq_qPowerProduct

/-- Ind3 can only increase each normalized exponent. -/
theorem power_le_normalize_ind3
    (extra : C → ℕ)
    (X : GeneratedFactorKummerImage K tate ordinaryPower)
    (c : C) :
    X.normalize.power c ≤
      (normalize (.ind3 extra X)).power c := by
  simp [normalize]

end GeneratedFactorKummerImage

end IUTThreeClosures
