/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.PossibleImageGeneratorClosure
import Iut.Cor312.ThetaData.Basic

/-!
# The source-generated IUT output relation

The possible images in IUT III are not required to admit an exact normal form
`unit * q^n`.  They are generated from an ordinary theta branch by the three
indeterminacies:

* Ind1: procession reindexing;
* Ind2: local summand automorphisms;
* Ind3: upper-semicompatible vertical/log-Kummer enlargement.

This module records the exact order-theoretic source relation.  An output is a
finite expression generated by these three operations.  The native q-pilot
image is the ordinary constructor at the distinguished source branch.  Hence
it belongs to the possible-image union definitionally.  If the ordinary
branches lie in a common envelope and every genuine generator preserves that
envelope, structural induction proves that every possible image lies in the
envelope.

The two principal theorems are therefore:

`actualNativeImage`

and

`actualPossibleImageEnvelope`.

No component volume, theta coefficient, height inequality, or abc statement
is an input.  The remaining geometric obligation is to instantiate the four
source operations and their envelope-preservation laws from the actual Hodge
theaters, Kummer correspondences, and upper-semicompatibility theorem.
-/

namespace IUTThreeClosures

open Iut

universe u v w

variable {AG : AnabelianGeometry.{u}} {TG : TemperedGeometry AG}

/-- A source presentation of the actual IUT possible-image relation.

All output expressions are generated from the ordinary branch; there is no
unrelated output type and no freely supplied map from arbitrary outputs. -/
structure ActualIUTOutputRelation
    (D : InitialThetaData AG TG)
    (I : Type v)
    (α : I → Type w) where
  Ordinary : Type v
  Ind1 : Type v
  Ind2 : Type v
  Ind3 : Type v

  ordinaryRegion : Ordinary → ∀ i, Set (α i)
  act1 : Ind1 → ∀ i, Set (α i) → Set (α i)
  act2 : Ind2 → ∀ i, Set (α i) → Set (α i)
  act3 : Ind3 → ∀ i, Set (α i) → Set (α i)

  /-- The ordinary branch corresponding, under the theta/q link, to the native
  q-pilot object. -/
  native : Ordinary

  /-- One actual multiradial container at every packet component. -/
  envelope : ∀ i, Set (α i)

  ordinary_le_envelope :
    ∀ o i, ordinaryRegion o i ⊆ envelope i
  ind1_preserves_envelope :
    ∀ a i U, U ⊆ envelope i → act1 a i U ⊆ envelope i
  ind2_preserves_envelope :
    ∀ a i U, U ⊆ envelope i → act2 a i U ⊆ envelope i
  ind3_preserves_envelope :
    ∀ a i U, U ⊆ envelope i → act3 a i U ⊆ envelope i

namespace ActualIUTOutputRelation

variable {D : InitialThetaData AG TG}
variable {I : Type v} {α : I → Type w}

/-- The genuine generated output syntax: finite compositions of Ind1, Ind2,
and Ind3 applied to an ordinary source branch. -/
abbrev PossibleImage
    (S : ActualIUTOutputRelation D I α) :=
  PossibleImageWord S.Ordinary S.Ind1 S.Ind2 S.Ind3

/-- Realization of one generated possible image at one packet component. -/
def realize
    (S : ActualIUTOutputRelation D I α)
    (W : S.PossibleImage)
    (i : I) : Set (α i) :=
  W.realize
    (fun o => S.ordinaryRegion o i)
    (fun a U => S.act1 a i U)
    (fun a U => S.act2 a i U)
    (fun a U => S.act3 a i U)

/-- The distinguished native source word. -/
def nativePossibleImage
    (S : ActualIUTOutputRelation D I α) : S.PossibleImage :=
  .ordinary S.native

/-- The actual native q-pilot region. -/
def nativeQPilotRegion
    (S : ActualIUTOutputRelation D I α)
    (i : I) : Set (α i) :=
  S.ordinaryRegion S.native i

@[simp]
theorem realize_nativePossibleImage
    (S : ActualIUTOutputRelation D I α)
    (i : I) :
    S.realize S.nativePossibleImage i = S.nativeQPilotRegion i :=
  rfl

/-- The literal union of all generated actual possible images. -/
def actualThetaPossibleUnion
    (S : ActualIUTOutputRelation D I α)
    (i : I) : Set (α i) :=
  ⋃ W : S.PossibleImage, S.realize W i

/-- **Actual native-image theorem.**  The native q-pilot branch is one of the
ordinary outputs and therefore lies in the genuine generated possible-image
union. -/
theorem actualNativeImage
    (S : ActualIUTOutputRelation D I α)
    (i : I) :
    S.nativeQPilotRegion i ⊆ S.actualThetaPossibleUnion i := by
  intro x hx
  exact Set.mem_iUnion.mpr
    ⟨S.nativePossibleImage, by simpa using hx⟩

/-- Every generated possible-image word lies in the explicit multiradial
envelope.  This is the structural induction that converts generator-level
source theorems into full Ind1/Ind2/Ind3 coverage. -/
theorem realize_le_envelope
    (S : ActualIUTOutputRelation D I α)
    (i : I) :
    ∀ W : S.PossibleImage, S.realize W i ⊆ S.envelope i := by
  intro W
  induction W with
  | ordinary o =>
      exact S.ordinary_le_envelope o i
  | ind1 a W ih =>
      exact S.ind1_preserves_envelope a i _ ih
  | ind2 a W ih =>
      exact S.ind2_preserves_envelope a i _ ih
  | ind3 a W ih =>
      exact S.ind3_preserves_envelope a i _ ih

/-- **Actual possible-image envelope theorem.**  The full possible-image union
is contained in the explicit source-derived multiradial envelope. -/
theorem actualPossibleImageEnvelope
    (S : ActualIUTOutputRelation D I α)
    (i : I) :
    S.actualThetaPossibleUnion i ⊆ S.envelope i := by
  intro x hx
  rcases Set.mem_iUnion.mp hx with ⟨W, hx⟩
  exact S.realize_le_envelope i W hx

/-- The native q-pilot region also lies in the common envelope. -/
theorem nativeQPilotRegion_le_envelope
    (S : ActualIUTOutputRelation D I α)
    (i : I) :
    S.nativeQPilotRegion i ⊆ S.envelope i :=
  (S.actualNativeImage i).trans (S.actualPossibleImageEnvelope i)

/-- The possible-image union is the least set containing every generated
realization. -/
theorem actualThetaPossibleUnion_le
    (S : ActualIUTOutputRelation D I α)
    (i : I)
    (U : Set (α i))
    (hU : ∀ W : S.PossibleImage, S.realize W i ⊆ U) :
    S.actualThetaPossibleUnion i ⊆ U := by
  intro x hx
  rcases Set.mem_iUnion.mp hx with ⟨W, hx⟩
  exact hU W hx

end ActualIUTOutputRelation

end IUTThreeClosures
