/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.NumberTheory.NumberField.Basic

/-!
# Adjoining an explicit square root of `-1`

The fixed initial-theta field need not obtain `sqrt(-1)` from the Weil pairing.
Given a number field `K`, an algebraic closure `Kbar`, and one element
`i : Kbar` with `i² = -1`, adjoin `i` to `K`.  The resulting simple extension
is finite over `K`, hence is again a number field, and contains a square root
of `-1` by construction.

This provides a direct alternative to formalizing the Weil pairing.  In the
Frey application one may first construct the full level-twelve torsion field
and then adjoin this quadratic element.  The ambient Galois group remains
solvable by the separate `GL2ZMod12WithI` theorem.
-/

namespace IUTThreeClosures

universe u

variable (K : Type u) [Field K] [NumberField K]
variable (Kbar : Type u) [Field Kbar] [Algebra K Kbar]

/-- The simple intermediate field generated by an element `i`. -/
noncomputable def adjoinElementField (i : Kbar) :
    IntermediateField K Kbar :=
  IntermediateField.adjoin K {i}

namespace adjoinElementField

variable {K Kbar}
variable [IsAlgClosure K Kbar]
variable (i : Kbar)

/-- The adjoined element belongs to the simple extension. -/
noncomputable def generator : adjoinElementField K Kbar i :=
  ⟨i, IntermediateField.subset_adjoin (Set.mem_singleton i)⟩

@[simp]
theorem generator_coe :
    (generator i : Kbar) = i :=
  rfl

/-- The simple extension generated by one algebraic element is finite over the
base field. -/
noncomputable instance finiteDimensional :
    FiniteDimensional K (adjoinElementField K Kbar i) := by
  apply IntermediateField.finiteDimensional_adjoin
  · exact Set.finite_singleton i
  · intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact IsAlgebraic.isAlgebraic i

/-- The simple finite extension of a number field is itself a number field. -/
noncomputable instance numberField :
    NumberField (adjoinElementField K Kbar i) := by
  haveI : CharZero (adjoinElementField K Kbar i) :=
    charZero_of_injective_algebraMap
      (algebraMap K (adjoinElementField K Kbar i)).injective
  haveI : IsScalarTower ℚ K (adjoinElementField K Kbar i) :=
    IsScalarTower.of_algebraMap_eq' (Subsingleton.elim _ _)
  haveI : FiniteDimensional ℚ (adjoinElementField K Kbar i) :=
    Module.Finite.trans K (adjoinElementField K Kbar i)
  exact { }

/-- If the chosen generator squares to `-1` in the algebraic closure, the
adjoined number field contains a square root of `-1`. -/
theorem isSquare_neg_one
    (hi : i ^ 2 = -1) :
    IsSquare (-1 : adjoinElementField K Kbar i) := by
  refine ⟨generator i, ?_⟩
  apply Subtype.ext
  simpa [pow_two] using hi

end adjoinElementField

/-- Every algebraic closure supplies a square root of `-1`, and adjoining it
produces a finite number-field extension containing that square root. -/
theorem exists_numberField_extension_with_sqrt_neg_one
    [IsAlgClosure K Kbar] :
    ∃ i : Kbar,
      IsSquare (-1 : adjoinElementField K Kbar i) := by
  obtain ⟨i, hi⟩ := IsAlgClosed.exists_sq_eq (-1 : Kbar)
  exact ⟨i, adjoinElementField.isSquare_neg_one i hi⟩

end IUTThreeClosures
