import IUTThreeClosures.BridgeInhabitationAudit
import IUTThreeClosures.MaximalValuationRingHull
import IUTThreeClosures.SublinearQPilotAbsorption
import IUTThreeClosures.TateThetaOddGraphDescent
import IUTThreeClosures.TateGraphPeriodQuotient
import IUTThreeClosures.TateThetaOddGraphAction
import IUTThreeClosures.TateThetaOddGraphProperness
import IUTThreeClosures.TateThetaValuationCircleComparison
import IUTThreeClosures.MultiradialScaleCompatibilityNoGo
import IUTThreeClosures.MultiradialLabelScaleCalibration
import IUTThreeClosures.SourceFaithfulTheorem110
import IUTThreeClosures.HaarResidueNormalization
import IUTThreeClosures.TateHaarResidueNormalization
import IUTThreeClosures.LocalCompletionNormValuationBridge
import IUTThreeClosures.ActualBadPlaceHaarNormalization
import IUTThreeClosures.ActualBadPlaceQPilotPacket
import IUTThreeClosures.ActualBadPlaceProcessionAssembly
import IUTThreeClosures.TateThetaDiscreteSkeletonImage
import IUTThreeClosures.PolynomialGaussPointOrbit
import IUTThreeClosures.LaurentGaussPointOrbit
import IUTThreeClosures.LaurentGaussCompletion
import IUTThreeClosures.LaurentGaussSeminormSpectrum
import IUTThreeClosures.MultiradialIntegerEffectObstruction
import IUTThreeClosures.MultiradialLabelAbsoluteValue
import IUTThreeClosures.CrossLabelTensorDegreeLine
import IUTThreeClosures.ConcreteGenEllKummerCover
import IUTThreeClosures.ConcreteGenEllTripodCover
import IUTThreeClosures.ConcreteFermatIrreducibility
import IUTThreeClosures.ConcreteFermatOpenRing
import IUTThreeClosures.ConcreteProjectiveFermatSmoothness
import IUTThreeClosures.ConcreteProjectiveFermatScheme
import IUTThreeClosures.ConcreteAffineFermatJacobian
import IUTThreeClosures.ConcreteProjectiveFermatChartEquiv
import IUTThreeClosures.ConcreteProjectiveFermatSchemeSmooth
import IUTThreeClosures.ConcreteFermatPresentationEquiv
import IUTThreeClosures.ConcreteFermatTripodEquiv
import IUTThreeClosures.ConcreteFermatBelyiRamification
import IUTThreeClosures.LocalPowerRamificationIndex
import IUTThreeClosures.ConcreteFermatBoundaryLocalRing
import IUTThreeClosures.ArakelovFermatLogCanonical
import IUTThreeClosures.SUnitUniformTripod
import IUTThreeClosures.ArithmeticPDerivation
import IUTThreeClosures.FreyModifiedSzpiroRoute
import IUTThreeClosures.ArithmeticLeibnizWronskian
import IUTThreeClosures.WronskianKernelLattice
import IUTThreeClosures.FermatKummerDiscriminant

#print axioms IUTThreeClosures.PointwiseIUTIIIFamily.corollary312Variant_all
#print axioms IUTThreeClosures.ThreeClosureCertificate.abc_conjecture_of_three_closures
#print axioms IUTThreeClosures.NonCircularIUTIVBridge.nonempty_iff_abc
#print axioms IUTThreeClosures.nonempty_fourStageProgram_iff
#print axioms IUTThreeClosures.thetaProd_qpow_smul_nat
#print axioms IUTThreeClosures.thetaProd_qpow_smul_odd
#print axioms IUTThreeClosures.TateThetaRootPoint.oddPeriodShiftEquiv
#print axioms IUTThreeClosures.MaximalValuationRingHull.exists_least_productHull
#print axioms IUTThreeClosures.MaximalValuationRingHull.scaledFinitePositiveRegion
#print axioms IUTThreeClosures.MaximalValuationRingHull.rational_prime_specialization_scale_rigidity
#print axioms IUTThreeClosures.sqrt_mul_log_le_linear_explicit
#print axioms IUTThreeClosures.mul_sqrt_mul_log_le_linear_explicit
#print axioms IUTThreeClosures.proposition21_absorption_with_sqrtLog
#print axioms IUTThreeClosures.TateGraphPeriodQuotient.graphPeriodQuotientEquivZMod
#print axioms IUTThreeClosures.TateThetaRootPoint.oddPeriodShiftAddAction_isCancelVAdd
#print axioms IUTThreeClosures.TateThetaRootPoint.oddPeriodShiftAddAction_properlyDiscontinuousVAdd
#print axioms
  IUTThreeClosures.TateThetaRootPoint.oddPeriodShift_orbitQuotient_isAddQuotientCoveringMap
#print axioms IUTThreeClosures.TateThetaRootPoint.valuationCircleMap_not_injective_of_charZero
#print axioms IUTThreeClosures.KummerTorsor.no_common_scale_thetaPoint_one_two
#print axioms IUTThreeClosures.KummerTorsor.scale_calibrates_thetaPoint_iff
#print axioms IUTThreeClosures.KummerTorsor.horizontalEquiv_one_two_not_log_norm_preserving
#print axioms IUTThreeClosures.SourceFaithfulTheorem110.tatePower_component_logVolume
#print axioms IUTThreeClosures.HaarResidueNormalization.log_distribHaarChar_integerUnit
#print axioms IUTThreeClosures.TateHaarResidueNormalization.log_distribHaarChar_tateParameter
#print axioms
  IUTThreeClosures.LocalCompletionNormValuationBridge.normIntegerRing_eq_nativeIntegerRing
#print axioms IUTThreeClosures.LocalCompletionNormValuationBridge.nativeResidueFinite
#print axioms IUTThreeClosures.LocalCompletionNormValuationBridge.completionProperSpace
#print axioms
  IUTThreeClosures.ActualBadHodgeTheaterPlace.log_distribHaarChar_q_eq_qOrder_residueCard
#print axioms
  IUTThreeClosures.LocalCompletionNormValuationBridge.globalResidueEquivNativeResidue
#print axioms
  IUTThreeClosures.LocalCompletionNormValuationBridge.natCard_nativeResidue_eq_absNorm
#print axioms
  IUTThreeClosures.ActualBadPlaceQPilotPacket.localHaarLog_eq_neg_qOrder_arithmeticPlaceWeight
#print axioms
  IUTThreeClosures.ActualBadPlaceQPilotPacket.neg_signedHaarLogSum_eq_arithmeticDivisorDegree
#print axioms
  IUTThreeClosures.ActualBadPlaceQPilotPacket.normalizedHaarLogQ_eq_arithmeticLogQ
#print axioms
  IUTThreeClosures.ActualBadPlaceQPilotPacket.normalizedHaarLogQ_eq_publicLogQ
#print axioms
  IUTThreeClosures.ActualBadHodgeTheaterPlace.squareLabelRegion_logVolume
#print axioms
  IUTThreeClosures.ActualBadHodgeTheaterPlace.reachableFinitePositiveRegion_logVolume_le_zero
#print axioms
  IUTThreeClosures.ActualBadPlaceProcessionAssembly.componentLog_eq_squareLabelRegion_logVolume
namespace IUTThreeClosures.ActualBadPlaceProcessionAssembly
#print axioms processionAverage_eq_squareAverage_mul_signedHaarLogSum
#print axioms canonicalQPilot_normalizedProcessionMass_eq_squareAverage_mul_publicLogQ
end IUTThreeClosures.ActualBadPlaceProcessionAssembly
#print axioms IUTThreeClosures.TateThetaRootPoint.valuationCircleMap_ker_eq_angularKernel
#print axioms IUTThreeClosures.TateThetaRootPoint.valuationCircleRangeEquivZMod
#print axioms IUTThreeClosures.TateThetaRootPoint.natCard_valuationCircleMap_range
#print axioms IUTThreeClosures.PolynomialGaussPointOrbit.gaussPoint_injective
#print axioms IUTThreeClosures.PolynomialGaussPointOrbit.gaussPoint_ne_rationalEvaluation
#print axioms IUTThreeClosures.PolynomialGaussPointOrbit.pullbackGaussPoint_eq
#print axioms IUTThreeClosures.PolynomialGaussPointOrbit.radiusCircleMap_eq_iff_zpow
#print axioms IUTThreeClosures.PolynomialGaussPointOrbit.radiusOrbitQuotientHomeomorphCircle
#print axioms IUTThreeClosures.LaurentGaussPointOrbit.laurentGaussPoint_toLaurent
#print axioms IUTThreeClosures.LaurentGaussPointOrbit.laurentGaussPoint_T_neg_one
#print axioms IUTThreeClosures.LaurentGaussPointOrbit.laurentGaussPoint_injective
#print axioms IUTThreeClosures.LaurentGaussPointOrbit.laurentVariableScale_toLaurent
#print axioms IUTThreeClosures.LaurentGaussPointOrbit.laurentGaussPoint_variableScale
#print axioms IUTThreeClosures.LaurentGaussPointOrbit.pullbackLaurentGaussPoint_eq
#print axioms IUTThreeClosures.LaurentGaussCompletion.norm_mul_completed
#print axioms IUTThreeClosures.LaurentGaussCompletion.toCompletion_denseRange
#print axioms IUTThreeClosures.LaurentGaussCompletion.scaleCompletion_toCompletion
#print axioms
  IUTThreeClosures.LaurentGaussSeminormSpectrum.BoundedKSeminorm.isEmbedding_coe
#print axioms
  IUTThreeClosures.LaurentGaussSeminormSpectrum.BoundedKSeminorm.pullbackHomeomorph
#print axioms
  IUTThreeClosures.LaurentGaussSeminormSpectrum.completedGaussPoint_T
#print axioms
  IUTThreeClosures.LaurentGaussSeminormSpectrum.scaleSpectrumHomeomorph_gaussPoint
#print axioms
  IUTThreeClosures.LaurentGaussSeminormSpectrum.unitNormSpectrumZAction_one_vadd
#print axioms IUTThreeClosures.KummerTorsor.no_integer_effect_compatible_calibration_one_two
#print axioms IUTThreeClosures.log_labelAbsoluteValue_q_square
#print axioms IUTThreeClosures.padic_no_labelOneTwoRingEquiv_logNormIsometry
#print axioms IUTThreeClosures.tensorIntegerAt_label_independent
#print axioms
  IUTThreeClosures.FinitePositiveRegion.logVolume_tensorIntegerImage
#print axioms
  IUTThreeClosures.padic_no_common_isometric_label_integer_identification
#print axioms IUTThreeClosures.ConcreteGenEllKummerCover.kummer_derivative_bezout
#print axioms IUTThreeClosures.ConcreteGenEllKummerCover.kummer_ring_nontrivial
#print axioms IUTThreeClosures.ConcreteGenEllTripodCover.fermat_etale_over_tripod
#print axioms IUTThreeClosures.ConcreteGenEllTripodCover.fermat_finrank_over_tripod
#print axioms IUTThreeClosures.ConcreteGenEllTripodCover.fermat_primeSpectrum_surjective
#print axioms
  IUTThreeClosures.ConcreteFermatIrreducibility.fermatPolynomial_irreducible
#print axioms IUTThreeClosures.ConcreteFermatOpenRing.affineBoundary_ne_zero
#print axioms
  IUTThreeClosures.ConcreteProjectiveFermatSmoothness.projectiveFermatPoint_not_jacobianSingular
#print axioms IUTThreeClosures.ConcreteProjectiveFermatScheme.quotientGrade_iSupIndep
#print axioms IUTThreeClosures.ConcreteProjectiveFermatScheme.iSup_coordinateOpen_eq_top
#print axioms IUTThreeClosures.ConcreteProjectiveFermatScheme.coordinateAwayι_opensRange
#print axioms IUTThreeClosures.ConcreteProjectiveFermatScheme.chartTwo_fermat_equation
#print axioms IUTThreeClosures.ConcreteAffineFermatJacobian.fermatJacobianIdeal_eq_top
#print axioms IUTThreeClosures.ConcreteAffineFermatJacobian.fermatJacobianRing_smooth
#print axioms
  IUTThreeClosures.ConcreteProjectiveFermatChartEquiv.quotientGrade_zero_eq_algebraMap
#print axioms
  IUTThreeClosures.ConcreteProjectiveFermatChartEquiv.chartRatio_pair_adjoin_eq_top
#print axioms
  IUTThreeClosures.ConcreteProjectiveFermatChartEquiv.chartToAffine_comp_affineToChart
#print axioms
  IUTThreeClosures.ConcreteProjectiveFermatChartEquiv.affineToChart_comp_chartToAffine
#print axioms
  IUTThreeClosures.ConcreteProjectiveFermatChartEquiv.fermatAffineChartEquiv
#print axioms
  IUTThreeClosures.ConcreteProjectiveFermatChartEquiv.coordinateChartRing_smooth
#print axioms
  IUTThreeClosures.ConcreteProjectiveFermatSchemeSmooth.fermatAffineOddChartEquiv
#print axioms
  IUTThreeClosures.ConcreteProjectiveFermatSchemeSmooth.projectiveFermatScheme_smooth
#print axioms
  IUTThreeClosures.ConcreteFermatPresentationEquiv.fermatAffinePresentationEquiv
#print axioms IUTThreeClosures.ConcreteFermatPresentationEquiv.fermatOpenRing_smooth
#print axioms
  IUTThreeClosures.ConcreteFermatTripodEquiv.tripodFermatToOpen_comp_openToTripod
#print axioms
  IUTThreeClosures.ConcreteFermatTripodEquiv.openToTripod_comp_tripodFermatToOpen
#print axioms IUTThreeClosures.ConcreteFermatTripodEquiv.fermatOpenTripodAlgEquiv
#print axioms IUTThreeClosures.ConcreteFermatTripodEquiv.fermatOpenTripodBaseAlgEquiv
#print axioms IUTThreeClosures.ConcreteFermatTripodEquiv.fermatOpen_etale_over_tripod
#print axioms IUTThreeClosures.ConcreteFermatTripodEquiv.fermatOpen_finite_over_tripod
#print axioms IUTThreeClosures.ConcreteFermatTripodEquiv.fermatOpen_finrank_over_tripod
#print axioms
  IUTThreeClosures.ConcreteFermatBelyiRamification.outsideThreeFibres_iff_XYZ_ne_zero
namespace IUTThreeClosures.ConcreteFermatBelyiRamification.TripodCertificate
#print axioms beta_etale_away_from_zero_one_infinity
end IUTThreeClosures.ConcreteFermatBelyiRamification.TripodCertificate
#print axioms
  IUTThreeClosures.LocalPowerRamificationIndex.local_power_law_exact_conclusions
#print axioms
  IUTThreeClosures.ConcreteFermatBoundaryLocalRing.chartZeroIdeal_eq_span
#print axioms
  IUTThreeClosures.ConcreteFermatBoundaryLocalRing.source_maximalIdeal_eq_span_uniformizer
#print axioms
  IUTThreeClosures.ConcreteFermatBoundaryLocalRing.zeroBoundary_exact_ramification
#print axioms
  IUTThreeClosures.ConcreteFermatBoundaryLocalRing.chartZeroStalkIso
#print axioms IUTThreeClosures.tripodTruncatedCounting_eq_conductor
#print axioms IUTThreeClosures.normalizedLogHeight_pow
#print axioms
  IUTThreeClosures.ConcreteFermatBelyiRamification.normalizedLogHeight_one_sub_affineBeta
#print axioms IUTThreeClosures.fermat_riemann_hurwitz_numerical
#print axioms IUTThreeClosures.fermat_logCanonicalDegree_eq_coverDegree
#print axioms IUTThreeClosures.fermat_open_finrank_eq_logCanonicalDegree
#print axioms IUTThreeClosures.positive_degree_coefficient_rigidity
#print axioms
  IUTThreeClosures.ABCPoint.rationalTripodPrimeSupport_lambda
#print axioms IUTThreeClosures.ABCPoint.ofRat_lambda
#print axioms
  IUTThreeClosures.abcConjecture_iff_uniformRationalSUnitTripodBound
#print axioms IUTThreeClosures.toy_fixed_support_finite
#print axioms IUTThreeClosures.toy_no_uniform_card_linear_bound
#print axioms IUTThreeClosures.intDerivation_eq_zero
#print axioms IUTThreeClosures.ratOverIntDerivation_eq_zero
#print axioms IUTThreeClosures.fermatDelta_add
#print axioms IUTThreeClosures.prime_dvd_fermatDelta_iff_sq_dvd
#print axioms IUTThreeClosures.fermatDelta_unbounded_at_fixed_radical
#print axioms IUTThreeClosures.ABCPoint.freyModifiedHeightNat_eq_invariants
#print axioms IUTThreeClosures.ABCPoint.six_mul_height_le_freyModifiedHeight
#print axioms IUTThreeClosures.ABCPoint.freyModifiedHeight_le
#print axioms IUTThreeClosures.ABCPoint.freyDiscriminantConductor_le_log_two
#print axioms IUTThreeClosures.abc_of_uniform_freyModifiedSzpiro
#print axioms IUTThreeClosures.twoIsogenyAffineEquation
#print axioms IUTThreeClosures.abcFreyTwoIsogenousZ_c₄
#print axioms IUTThreeClosures.abcFreyTwoIsogenousZ_Δ
#print axioms IUTThreeClosures.ABCPoint.height_le_of_twoIsogenousDiscriminantSzpiro
#print axioms IUTThreeClosures.no_uniform_c_pow_five_lower_for_endpointFrey
#print axioms IUTThreeClosures.no_uniform_c_pow_six_lower_for_endpointTwoIsogenous
#print axioms IUTThreeClosures.powerfulProduct_dvd_arithmeticWronskian
#print axioms IUTThreeClosures.log_c_le_log_radical_add_log_normalizedDerivative
#print axioms IUTThreeClosures.weightedArithmeticDerivative_mul
#print axioms IUTThreeClosures.abcPowerfulPart_dvd_weightedArithmeticDerivative
#print axioms IUTThreeClosures.weightedArithmeticDerivative_abc_bound
#print axioms IUTThreeClosures.siegel_nondegenerate_kernel_lower_bound
#print axioms IUTThreeClosures.twoCoordinateKernelWitness
#print axioms IUTThreeClosures.powerfulLatticeC_dvd_wronskianQuotient
#print axioms IUTThreeClosures.normalizedPowerfulLatticeHeightRadicalLowerBound
#print axioms IUTThreeClosures.weightedArithmeticDerivative_two_pow
#print axioms IUTThreeClosures.mersenneCompatibleNormalizedDerivative_gt_half
#print axioms IUTThreeClosures.discr_kummerIntegralPolynomial
#print axioms IUTThreeClosures.natAbs_discr_kummerIntegralPolynomial
#print axioms IUTThreeClosures.prime_dvd_rescaledKummerPolynomialDiscriminantAbs
#print axioms IUTThreeClosures.kummerTameGlobalBudget_eq_primeLogMass
#print axioms IUTThreeClosures.tame_budget_forces_coefficient_one
