import IUTThreeClosures.BridgeInhabitationAudit

#print axioms IUTThreeClosures.PointwiseIUTIIIFamily.corollary312Variant_all
#print axioms IUTThreeClosures.ThreeClosureCertificate.abc_conjecture_of_three_closures
#print axioms IUTThreeClosures.NonCircularIUTIVBridge.nonempty_iff_abc
#print axioms IUTThreeClosures.nonempty_fourStageProgram_iff
