/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import Mathlib.RingTheory.Extension.Presentation.Submersive
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.MvPolynomial.EulerIdentity
import Mathlib.RingTheory.RingHom.LocallyStandardSmooth

/-!
# An affine Jacobian certificate for the Fermat equation

For a characteristic-zero field `K` and `n > 0`, put

`f = X₀^n + X₁^n - 1 ∈ K[X₀,X₁]`.

This file proves the formal Euler--Jacobian Bezout identity

`X₀ * ∂₀f + X₁ * ∂₁f - n * f = n`

and then pushes it to the quotient by `(f)`.  Since `n` is invertible in
`K`, the images of the two partial derivatives generate the unit ideal in
the affine Fermat quotient.

This is an honest global Jacobian unit-ideal certificate.  It is not, by
itself, a construction of a single standard-smooth presentation: globally
the two derivatives generate `1`, although neither selected derivative has
been proved to be a unit.  The second half of the file therefore passes to
their two basic opens, constructs a dimension-one submersive presentation on
each open, and applies target-locality to prove smoothness of the affine
Fermat quotient.
-/

namespace IUTThreeClosures
namespace ConcreteAffineFermatJacobian

noncomputable section

open MvPolynomial

universe u v

variable (K : Type u) [Field K]

/-- The first variable in the bivariate Fermat presentation. -/
def fermatX : MvPolynomial (Fin 2) K := X 0

/-- The second variable in the bivariate Fermat presentation. -/
def fermatY : MvPolynomial (Fin 2) K := X 1

/-- The affine Fermat relation `X^n + Y^n - 1`. -/
def fermatRelation (n : ℕ) : MvPolynomial (Fin 2) K :=
  fermatX K ^ n + fermatY K ^ n - 1

/-- The singleton family of equations used by the naive quotient
presentation. -/
def fermatRelationFamily (n : ℕ) (_ : Unit) : MvPolynomial (Fin 2) K :=
  fermatRelation K n

/-- The formal partial derivative of the Fermat relation in the first
coordinate. -/
def fermatPartialX (n : ℕ) : MvPolynomial (Fin 2) K :=
  pderiv 0 (fermatRelation K n)

/-- The formal partial derivative of the Fermat relation in the second
coordinate. -/
def fermatPartialY (n : ℕ) : MvPolynomial (Fin 2) K :=
  pderiv 1 (fermatRelation K n)

/-- The partial derivative at either of the two coordinates. -/
def fermatPartialAt (n : ℕ) (i : Fin 2) : MvPolynomial (Fin 2) K :=
  pderiv i (fermatRelation K n)

@[simp]
theorem fermatPartialAt_zero (n : ℕ) :
    fermatPartialAt K n 0 = fermatPartialX K n := rfl

@[simp]
theorem fermatPartialAt_one (n : ℕ) :
    fermatPartialAt K n 1 = fermatPartialY K n := rfl

/-- The first partial derivative has the expected explicit formula. -/
theorem fermatPartialX_eq (n : ℕ) :
    fermatPartialX K n = C (n : K) * fermatX K ^ (n - 1) := by
  simp [fermatPartialX, fermatRelation, fermatX, fermatY]

/-- The second partial derivative has the expected explicit formula. -/
theorem fermatPartialY_eq (n : ℕ) :
    fermatPartialY K n = C (n : K) * fermatY K ^ (n - 1) := by
  simp [fermatPartialY, fermatRelation, fermatX, fermatY]

/-- Euler's identity for the inhomogeneous affine Fermat equation, written
as a Bezout identity involving the relation itself. -/
theorem euler_jacobian_bezout {n : ℕ} (hn : 0 < n) :
    fermatX K * fermatPartialX K n +
          fermatY K * fermatPartialY K n -
          C (n : K) * fermatRelation K n = C (n : K) := by
  obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
  rw [fermatPartialX_eq K (m + 1), fermatPartialY_eq K (m + 1)]
  simp only [fermatRelation, fermatX, fermatY, Nat.succ_sub_one,
    pow_succ, Nat.cast_succ, map_add, map_one]
  ring

/-- The principal relation ideal of the affine Fermat equation. -/
def fermatRelationIdeal (n : ℕ) : Ideal (MvPolynomial (Fin 2) K) :=
  Ideal.span (Set.range (fermatRelationFamily K n))

/-- The bivariate affine Fermat quotient. -/
abbrev FermatJacobianRing (n : ℕ) :=
  MvPolynomial (Fin 2) K ⧸ fermatRelationIdeal K n

/-- The quotient map for the bivariate Fermat presentation. -/
abbrev fermatQuotientMap (n : ℕ) :
    MvPolynomial (Fin 2) K →+* FermatJacobianRing K n :=
  Ideal.Quotient.mk (fermatRelationIdeal K n)

/-- The defining Fermat relation vanishes in its quotient. -/
theorem fermatRelation_quotient_eq_zero (n : ℕ) :
    fermatQuotientMap K n (fermatRelation K n) = 0 := by
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span ⟨(), rfl⟩

/-- The image of a selected partial derivative in the Fermat quotient. -/
def quotientPartial (n : ℕ) (i : Fin 2) : FermatJacobianRing K n :=
  fermatQuotientMap K n (fermatPartialAt K n i)

/-- The ideal generated by the two partial derivatives in the affine
Fermat quotient. -/
def fermatJacobianIdeal (n : ℕ) : Ideal (FermatJacobianRing K n) :=
  Ideal.span (Set.range (quotientPartial K n))

/-- The scalar `n` belongs to the quotient Jacobian ideal.  This is the
Euler--Bezout identity after imposing the Fermat relation. -/
theorem natCast_mem_fermatJacobianIdeal {n : ℕ} (hn : 0 < n) :
    fermatQuotientMap K n (C (n : K)) ∈ fermatJacobianIdeal K n := by
  let q := fermatQuotientMap K n
  let J := fermatJacobianIdeal K n
  have hx : q (fermatPartialX K n) ∈ J := by
    exact Ideal.subset_span ⟨0, rfl⟩
  have hy : q (fermatPartialY K n) ∈ J := by
    exact Ideal.subset_span ⟨1, rfl⟩
  have heuler := congrArg q (euler_jacobian_bezout K hn)
  have hrel : q (fermatRelation K n) = 0 :=
    fermatRelation_quotient_eq_zero K n
  have hscalar :
      q (C (n : K)) =
        q (fermatX K) * q (fermatPartialX K n) +
          q (fermatY K) * q (fermatPartialY K n) := by
    simpa [map_add, map_sub, map_mul, hrel] using heuler.symm
  rw [hscalar]
  exact J.add_mem (J.mul_mem_left _ hx) (J.mul_mem_left _ hy)

/-- In characteristic zero, the two partial derivatives generate the unit
ideal in the affine Fermat quotient. -/
theorem fermatJacobianIdeal_eq_top [CharZero K] {n : ℕ} (hn : 0 < n) :
    fermatJacobianIdeal K n = ⊤ := by
  let q := fermatQuotientMap K n
  let J := fermatJacobianIdeal K n
  apply J.eq_top_iff_one.mpr
  have hnK : (n : K) ≠ 0 := Nat.cast_ne_zero.mpr (Nat.ne_of_gt hn)
  have hnmem : q (C (n : K)) ∈ J :=
    natCast_mem_fermatJacobianIdeal K hn
  have hmul := J.mul_mem_left (q (C (n : K)⁻¹)) hnmem
  have hone : q (C (n : K)⁻¹) * q (C (n : K)) = 1 := by
    rw [← map_mul, ← C_mul, inv_mul_cancel₀ hnK]
    exact map_one q
  exact hone ▸ hmul

/-- The naive one-relation presentation, with the selected Jacobian column
indexed by `i`.  It need not be submersive before localization. -/
def fermatPrePresentation (n : ℕ) (i : Fin 2) :
    Algebra.PreSubmersivePresentation K (FermatJacobianRing K n) (Fin 2) Unit :=
  Algebra.PreSubmersivePresentation.naive
    (v := fermatRelationFamily K n) (fun _ => i)
    (fun _ _ _ => Subsingleton.elim _ _)

/-- The Jacobian of the selected naive hypersurface presentation is exactly
the image of the selected partial derivative. -/
theorem fermatPrePresentation_jacobian (n : ℕ) (i : Fin 2) :
    (fermatPrePresentation K n i).jacobian = quotientPartial K n i := by
  classical
  rw [Algebra.PreSubmersivePresentation.jacobian_eq_jacobiMatrix_det]
  simp only [Matrix.det_unique]
  rw [Algebra.PreSubmersivePresentation.jacobiMatrix_apply,
    Algebra.Generators.algebraMap_apply]
  let qA := Ideal.Quotient.mkₐ K (fermatRelationIdeal K n)
  change
    aeval (qA ∘ X)
        (pderiv i (fermatRelation K n)) =
      qA (pderiv i (fermatRelation K n))
  exact DFunLike.congr_fun (aeval_unique qA).symm _

/-- The basic open chart on which the selected partial derivative is
inverted. -/
abbrev FermatJacobianChart (n : ℕ) (i : Fin 2) :=
  Localization.Away (quotientPartial K n i)

/-- Compose the naive hypersurface presentation with localization at its
selected partial derivative. -/
def fermatChartPrePresentation (n : ℕ) (i : Fin 2) :
    Algebra.PreSubmersivePresentation K (FermatJacobianChart K n i)
      (Unit ⊕ Fin 2) (Unit ⊕ Unit) :=
  (Algebra.PreSubmersivePresentation.localizationAway
      (FermatJacobianChart K n i) (quotientPartial K n i)).comp
    (fermatPrePresentation K n i)

/-- On the selected basic open, the composite Jacobian is the square of the
localized selected partial derivative. -/
theorem fermatChartPrePresentation_jacobian (n : ℕ) (i : Fin 2) :
    (fermatChartPrePresentation K n i).jacobian =
      algebraMap (FermatJacobianRing K n) (FermatJacobianChart K n i)
          (quotientPartial K n i) *
        algebraMap (FermatJacobianRing K n) (FermatJacobianChart K n i)
          (quotientPartial K n i) := by
  rw [fermatChartPrePresentation,
    Algebra.PreSubmersivePresentation.comp_jacobian_eq_jacobian_smul_jacobian,
    Algebra.smul_def, fermatPrePresentation_jacobian,
    Algebra.PreSubmersivePresentation.localizationAway_jacobian]

/-- The localized presentation is genuinely submersive. -/
def fermatChartPresentation (n : ℕ) (i : Fin 2) :
    Algebra.SubmersivePresentation K (FermatJacobianChart K n i)
      (Unit ⊕ Fin 2) (Unit ⊕ Unit) where
  toPreSubmersivePresentation := fermatChartPrePresentation K n i
  jacobian_isUnit := by
    rw [fermatChartPrePresentation_jacobian]
    exact
      (IsLocalization.Away.algebraMap_isUnit
        (S := FermatJacobianChart K n i) (quotientPartial K n i)).mul
      (IsLocalization.Away.algebraMap_isUnit
        (S := FermatJacobianChart K n i) (quotientPartial K n i))

/-- The localized presentation has relative dimension one. -/
theorem fermatChartPresentation_dimension (n : ℕ) (i : Fin 2) :
    (fermatChartPresentation K n i).dimension = 1 := by
  simp [Algebra.Presentation.dimension]

/-- Each derivative basic open is standard smooth over the coefficient
field. -/
theorem fermatJacobianChart_isStandardSmooth (n : ℕ) (i : Fin 2) :
    Algebra.IsStandardSmooth K (FermatJacobianChart K n i) :=
  (fermatChartPresentation K n i).isStandardSmooth

/-- More precisely, each derivative chart is standard smooth of relative
dimension one. -/
theorem fermatJacobianChart_isStandardSmoothOfRelativeDimension
    (n : ℕ) (i : Fin 2) :
    Algebra.IsStandardSmoothOfRelativeDimension 1 K
      (FermatJacobianChart K n i) :=
  (fermatChartPresentation K n i).isStandardSmoothOfRelativeDimension
    (fermatChartPresentation_dimension K n i)

/-- The affine Fermat quotient is smooth over a characteristic-zero field.
The proof uses the two derivative basic opens, whose generators span the
unit ideal by the Euler--Bezout identity. -/
theorem fermatJacobianRing_smooth [CharZero K] {n : ℕ} (hn : 0 < n) :
    Algebra.Smooth K (FermatJacobianRing K n) := by
  rw [← RingHom.smooth_algebraMap]
  apply RingHom.smooth_iff_locally_isStandardSmooth.mpr
  refine ⟨Set.range (quotientPartial K n), ?_, ?_⟩
  · simpa [fermatJacobianIdeal] using fermatJacobianIdeal_eq_top K hn
  · rintro _ ⟨i, rfl⟩
    rw [← IsScalarTower.algebraMap_eq K (FermatJacobianRing K n)
      (FermatJacobianChart K n i), RingHom.isStandardSmooth_algebraMap]
    exact fermatJacobianChart_isStandardSmooth K n i

end
end ConcreteAffineFermatJacobian
end IUTThreeClosures
