/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.ConcreteProjectiveFermatChartEquiv
import IUTThreeClosures.ConcreteFermatPresentationEquiv
import IUTThreeClosures.LocalPowerRamificationIndex
import Mathlib.AlgebraicGeometry.AffineScheme

/-!
# An honest boundary local ring of the projective Fermat curve

Let `C` be the genuine degree-zero homogeneous coordinate ring of the
`X₂ ≠ 0` chart of the projective Fermat curve.  For a positive exponent,
this file constructs the maximal ideal of the chart point `(u,v)=(0,1)`,
localizes `C` at that ideal, proves that the resulting local ring is a DVR
with uniformizer `u`, and computes the ramification index of `t ↦ u^n`.

Unlike the earlier coordinate-level power identities, the source here is an
actual localization of the homogeneous Proj chart ring.  The corresponding
point of `Spec C` and the standard affine-scheme stalk isomorphism are also
recorded explicitly.

Only the rational point `(0,1)` above zero is treated here.  Other roots of
unity, the fibre above one, infinity, and the global finite Belyi morphism
remain separate tasks.
-/

namespace IUTThreeClosures
namespace ConcreteFermatBoundaryLocalRing

noncomputable section

open Polynomial
open IsLocalRing

universe u

variable (K : Type u) [Field K]

namespace J

abbrev Ring := ConcreteAffineFermatJacobian.FermatJacobianRing
abbrev Ideal := ConcreteAffineFermatJacobian.fermatRelationIdeal

abbrev quotientAlgHom (n : ℕ) :
    MvPolynomial (Fin 2) K →ₐ[K] Ring K n :=
  Ideal.Quotient.mkₐ K (Ideal K n)

def x (n : ℕ) : Ring K n := quotientAlgHom K n (MvPolynomial.X 0)
def y (n : ℕ) : Ring K n := quotientAlgHom K n (MvPolynomial.X 1)

end J

namespace P

abbrev Chart := ConcreteProjectiveFermatScheme.CoordinateChartRing
abbrev ratio := ConcreteProjectiveFermatScheme.chartRatio

end P

/-! ## The rational boundary point of the affine Fermat presentation -/

/-- Evaluation coordinates `(0,1)` in the bivariate polynomial ring. -/
def zeroCoordinates : Fin 2 → K := ![0, 1]

/-- Evaluation of bivariate polynomials at `(0,1)`. -/
def polynomialZeroEval : MvPolynomial (Fin 2) K →ₐ[K] K :=
  MvPolynomial.aeval (zeroCoordinates K)

@[simp]
theorem polynomialZeroEval_X_zero :
    polynomialZeroEval K (MvPolynomial.X 0) = 0 := by
  simp [polynomialZeroEval, zeroCoordinates]

@[simp]
theorem polynomialZeroEval_X_one :
    polynomialZeroEval K (MvPolynomial.X 1) = 1 := by
  simp [polynomialZeroEval, zeroCoordinates]

/-- The Fermat relation vanishes at `(0,1)` for a positive exponent. -/
theorem polynomialZeroEval_relation_eq_zero
    (n : ℕ) [NeZero n] :
    polynomialZeroEval K
      (ConcreteAffineFermatJacobian.fermatRelation K n) = 0 := by
  simp [ConcreteAffineFermatJacobian.fermatRelation,
    ConcreteAffineFermatJacobian.fermatX,
    ConcreteAffineFermatJacobian.fermatY,
    polynomialZeroEval, zeroCoordinates, NeZero.ne n]

/-- Evaluation at `(0,1)` kills the principal Fermat relation ideal. -/
theorem fermatIdeal_le_ker_polynomialZeroEval
    (n : ℕ) [NeZero n] :
    J.Ideal K n ≤ RingHom.ker (polynomialZeroEval K).toRingHom := by
  rw [J.Ideal, ConcreteAffineFermatJacobian.fermatRelationIdeal]
  apply Ideal.span_le.mpr
  rintro _ ⟨i, rfl⟩
  simpa [ConcreteAffineFermatJacobian.fermatRelationFamily] using
    polynomialZeroEval_relation_eq_zero K n

/-- The residue map of the affine Fermat quotient at `(0,1)`. -/
def jacobianZeroEval (n : ℕ) [NeZero n] : J.Ring K n →ₐ[K] K :=
  Ideal.Quotient.liftₐ (J.Ideal K n) (polynomialZeroEval K)
    (fun _ f_mem ↦ fermatIdeal_le_ker_polynomialZeroEval K n f_mem)

@[simp]
theorem jacobianZeroEval_x (n : ℕ) [NeZero n] :
    jacobianZeroEval K n (J.x K n) = 0 := by
  simp [jacobianZeroEval, J.x, J.quotientAlgHom]

@[simp]
theorem jacobianZeroEval_y (n : ℕ) [NeZero n] :
    jacobianZeroEval K n (J.y K n) = 1 := by
  simp [jacobianZeroEval, J.y, J.quotientAlgHom]

/-- The maximal ideal of the affine presentation at `(0,1)`. -/
def jacobianZeroIdeal (n : ℕ) [NeZero n] : Ideal (J.Ring K n) :=
  RingHom.ker (jacobianZeroEval K n).toRingHom

instance jacobianZeroIdeal_isMaximal (n : ℕ) [NeZero n] :
    (jacobianZeroIdeal K n).IsMaximal := by
  apply RingHom.ker_isMaximal_of_surjective
  intro a
  exact ⟨algebraMap K (J.Ring K n) a, by simp [jacobianZeroEval]⟩

instance jacobianZeroIdeal_isPrime (n : ℕ) [NeZero n] :
    (jacobianZeroIdeal K n).IsPrime :=
  (jacobianZeroIdeal_isMaximal K n).isPrime

/-- Before quotienting, a polynomial differs from its value at `(0,1)` by
an element of the ideal generated by `X₀` and `X₁-1`.  The conclusion is
stated after quotienting so it can be used directly for the point ideal. -/
theorem quotient_sub_zeroEval_mem_span (n : ℕ) [NeZero n]
    (f : MvPolynomial (Fin 2) K) :
    J.quotientAlgHom K n f -
        algebraMap K (J.Ring K n) (polynomialZeroEval K f) ∈
      Ideal.span ({J.x K n, J.y K n - 1} : Set (J.Ring K n)) := by
  let I : Ideal (J.Ring K n) :=
    Ideal.span ({J.x K n, J.y K n - 1} : Set (J.Ring K n))
  change J.quotientAlgHom K n f -
      algebraMap K (J.Ring K n) (polynomialZeroEval K f) ∈ I
  induction f using MvPolynomial.induction_on with
  | C r =>
      simp [polynomialZeroEval, J.quotientAlgHom]
  | add p q hp hq =>
      have h := I.add_mem hp hq
      simpa only [map_add, sub_eq_add_neg, neg_add_rev, add_assoc,
        add_left_comm, add_comm] using h
  | mul_X p i hp =>
      fin_cases i
      · have hx : J.x K n ∈ I :=
          Ideal.subset_span (Set.mem_insert _ _)
        have hmul := I.mul_mem_left (J.quotientAlgHom K n p) hx
        convert hmul using 1
        simp [J.x, polynomialZeroEval, zeroCoordinates]
      · have hy : J.y K n - 1 ∈ I :=
          Ideal.subset_span (Set.mem_insert_iff.mpr
            (Or.inr (Set.mem_singleton _)))
        have hmul := I.mul_mem_left (J.quotientAlgHom K n p) hy
        have hadd := I.add_mem hmul hp
        convert hadd using 1
        simp [J.y, polynomialZeroEval, zeroCoordinates]
        ring

/-- The point ideal is exactly `(x,y-1)`. -/
theorem jacobianZeroIdeal_eq_span (n : ℕ) [NeZero n] :
    jacobianZeroIdeal K n =
      Ideal.span ({J.x K n, J.y K n - 1} : Set (J.Ring K n)) := by
  apply le_antisymm
  · intro z hz
    obtain ⟨f, rfl⟩ := Ideal.Quotient.mkₐ_surjective K (J.Ideal K n) z
    have heval : polynomialZeroEval K f = 0 := by
      simpa [jacobianZeroIdeal, jacobianZeroEval, J.quotientAlgHom] using hz
    simpa [heval] using quotient_sub_zeroEval_mem_span K n f
  · apply Ideal.span_le.mpr
    rintro z (rfl | rfl)
    · exact jacobianZeroEval_x K n
    · simp [jacobianZeroIdeal, RingHom.mem_ker]

/-! ## Transport to the genuine homogeneous projective chart -/

/-- The explicit affine-quotient/homogeneous-chart equivalence from E.11. -/
abbrev chartEquiv (n : ℕ) : J.Ring K n ≃ₐ[K] P.Chart K n 2 :=
  ConcreteProjectiveFermatChartEquiv.fermatAffineChartEquiv K n

/-- The residue map of the genuine homogeneous chart at `(u,v)=(0,1)`. -/
def chartZeroEval (n : ℕ) [NeZero n] : P.Chart K n 2 →ₐ[K] K :=
  (jacobianZeroEval K n).comp (chartEquiv K n).symm.toAlgHom

@[simp]
theorem chartZeroEval_u (n : ℕ) [NeZero n] :
    chartZeroEval K n (P.ratio K n 0 2) = 0 := by
  change jacobianZeroEval K n
    (ConcreteProjectiveFermatChartEquiv.chartToAffine K n
      (P.ratio K n 0 2)) = 0
  rw [ConcreteProjectiveFermatChartEquiv.chartToAffine_ratio_zero]
  simpa [J.x, J.quotientAlgHom,
    ConcreteProjectiveFermatChartEquiv.J.x,
    ConcreteProjectiveFermatChartEquiv.J.quotientAlgHom] using
      jacobianZeroEval_x K n

@[simp]
theorem chartZeroEval_v (n : ℕ) [NeZero n] :
    chartZeroEval K n (P.ratio K n 1 2) = 1 := by
  change jacobianZeroEval K n
    (ConcreteProjectiveFermatChartEquiv.chartToAffine K n
      (P.ratio K n 1 2)) = 1
  rw [ConcreteProjectiveFermatChartEquiv.chartToAffine_ratio_one]
  simpa [J.y, J.quotientAlgHom,
    ConcreteProjectiveFermatChartEquiv.J.y,
    ConcreteProjectiveFermatChartEquiv.J.quotientAlgHom] using
      jacobianZeroEval_y K n

/-- The maximal ideal of the actual homogeneous chart at `(0,1)`. -/
def chartZeroIdeal (n : ℕ) [NeZero n] : Ideal (P.Chart K n 2) :=
  RingHom.ker (chartZeroEval K n).toRingHom

instance chartZeroIdeal_isMaximal (n : ℕ) [NeZero n] :
    (chartZeroIdeal K n).IsMaximal := by
  apply RingHom.ker_isMaximal_of_surjective
  intro a
  exact ⟨algebraMap K (P.Chart K n 2) a, by simp [chartZeroEval]⟩

instance chartZeroIdeal_isPrime (n : ℕ) [NeZero n] :
    (chartZeroIdeal K n).IsPrime :=
  (chartZeroIdeal_isMaximal K n).isPrime

@[simp]
theorem chartEquiv_x (n : ℕ) :
    chartEquiv K n (J.x K n) = P.ratio K n 0 2 := by
  change ConcreteProjectiveFermatChartEquiv.affineToChart K n
    (ConcreteProjectiveFermatChartEquiv.J.x K n) = P.ratio K n 0 2
  exact ConcreteProjectiveFermatChartEquiv.affineToChart_x K n

@[simp]
theorem chartEquiv_y (n : ℕ) :
    chartEquiv K n (J.y K n) = P.ratio K n 1 2 := by
  change ConcreteProjectiveFermatChartEquiv.affineToChart K n
    (ConcreteProjectiveFermatChartEquiv.J.y K n) = P.ratio K n 1 2
  exact ConcreteProjectiveFermatChartEquiv.affineToChart_y K n

/-- The chart point ideal is the transport of the affine quotient point
ideal through the genuine chart equivalence. -/
theorem chartZeroIdeal_eq_map (n : ℕ) [NeZero n] :
    chartZeroIdeal K n =
      (jacobianZeroIdeal K n).map (chartEquiv K n).toRingHom := by
  ext z
  constructor
  · intro hz
    rw [Ideal.mem_map_iff_of_surjective
      (chartEquiv K n).toRingEquiv.toRingHom (chartEquiv K n).surjective]
    refine ⟨(chartEquiv K n).symm z, ?_, (chartEquiv K n).apply_symm_apply z⟩
    change jacobianZeroEval K n ((chartEquiv K n).symm z) = 0
    exact hz
  · intro hz
    rw [Ideal.mem_map_iff_of_surjective
      (chartEquiv K n).toRingEquiv.toRingHom (chartEquiv K n).surjective] at hz
    obtain ⟨a, ha, rfl⟩ := hz
    change jacobianZeroEval K n
      ((chartEquiv K n).symm (chartEquiv K n a)) = 0
    simpa [jacobianZeroIdeal, RingHom.mem_ker] using ha

/-- In the actual homogeneous chart ring, the point ideal is `(u,v-1)`. -/
theorem chartZeroIdeal_eq_span (n : ℕ) [NeZero n] :
    chartZeroIdeal K n =
      Ideal.span ({P.ratio K n 0 2, P.ratio K n 1 2 - 1} :
        Set (P.Chart K n 2)) := by
  rw [chartZeroIdeal_eq_map K n, jacobianZeroIdeal_eq_span K n,
    Ideal.map_span]
  simp only [Set.image_insert_eq, Set.image_singleton, map_sub, map_one]
  change Ideal.span ({chartEquiv K n (J.x K n),
      chartEquiv K n (J.y K n) - 1} : Set (P.Chart K n 2)) = _
  rw [chartEquiv_x, chartEquiv_y]

/-! ## Domain and Noetherian structure of the genuine chart -/

noncomputable instance jacobianRing_isDomain
    [CharZero K] (n : ℕ) [NeZero n] : IsDomain (J.Ring K n) := by
  let e :=
    ConcreteFermatPresentationEquiv.fermatAffinePresentationEquiv K n
  exact Function.Injective.isDomain e.toRingHom e.injective

noncomputable instance chartRing_isDomain
    [CharZero K] (n : ℕ) [NeZero n] : IsDomain (P.Chart K n 2) :=
  Function.Injective.isDomain (chartEquiv K n).symm.toRingHom
    (chartEquiv K n).symm.injective

noncomputable instance chartRing_isNoetherianRing (n : ℕ) :
    IsNoetherianRing (P.Chart K n 2) :=
  isNoetherianRing_of_ringEquiv (J.Ring K n) (chartEquiv K n).toRingEquiv

/-- The affine quotient coordinate `x` is nonzero. -/
theorem jacobian_x_ne_zero [CharZero K] {n : ℕ} (hn : 0 < n) :
    J.x K n ≠ 0 := by
  intro hx
  apply ConcreteFermatOpenRing.affineX_ne_zero K hn
  calc
    ConcreteFermatOpenRing.affineX K n =
        ConcreteFermatPresentationEquiv.fermatAffinePresentationEquiv K n
          (J.x K n) := by
      symm
      simpa [J.x, J.quotientAlgHom,
        ConcreteFermatPresentationEquiv.J.x,
        ConcreteFermatPresentationEquiv.J.quotientAlgHom] using
          ConcreteFermatPresentationEquiv.fermatAffinePresentationEquiv_apply_x K n
    _ = 0 := by rw [hx, map_zero]

/-- The homogeneous chart coordinate `u=X₀/X₂` is nonzero. -/
theorem chart_u_ne_zero [CharZero K] {n : ℕ} (hn : 0 < n) :
    P.ratio K n 0 2 ≠ 0 := by
  intro hu
  apply jacobian_x_ne_zero K hn
  apply (chartEquiv K n).injective
  rw [chartEquiv_x, hu, map_zero]

/-! ## The localized chart is a DVR with uniformizer `u` -/

/-- The honest local ring of the homogeneous `X₂` chart at `(0,1)`. -/
abbrev ZeroSourceLocalRing (n : ℕ) [NeZero n] :=
  Localization.AtPrime (chartZeroIdeal K n)

/-- The image of `u=X₀/X₂` in the boundary local ring. -/
def sourceUniformizer (n : ℕ) [NeZero n] : ZeroSourceLocalRing K n :=
  algebraMap (P.Chart K n 2) (ZeroSourceLocalRing K n) (P.ratio K n 0 2)

/-- The image of `v=X₁/X₂` in the boundary local ring. -/
def sourceV (n : ℕ) [NeZero n] : ZeroSourceLocalRing K n :=
  algebraMap (P.Chart K n 2) (ZeroSourceLocalRing K n) (P.ratio K n 1 2)

/-- The geometric sum `(v^n-1)/(v-1)` in the homogeneous chart. -/
def chartGeometricSum (n : ℕ) : P.Chart K n 2 :=
  ∑ i ∈ Finset.range n, P.ratio K n 1 2 ^ i

/-- At `(0,1)`, the geometric sum has residue `n`, hence is nonzero in
characteristic zero. -/
theorem chartZeroEval_geometricSum [CharZero K]
    (n : ℕ) [NeZero n] :
    chartZeroEval K n (chartGeometricSum K n) = (n : K) := by
  simp [chartGeometricSum]

theorem chartGeometricSum_not_mem_zeroIdeal [CharZero K]
    (n : ℕ) [NeZero n] :
    chartGeometricSum K n ∉ chartZeroIdeal K n := by
  intro h
  change chartZeroEval K n (chartGeometricSum K n) = 0 at h
  rw [chartZeroEval_geometricSum K n] at h
  exact (Nat.cast_ne_zero.mpr (NeZero.ne n)) h

/-- The Fermat equation turns the geometric-sum factorization into
`g(v-1)=-u^n`. -/
theorem chartGeometricSum_mul_v_sub_one (n : ℕ) :
    chartGeometricSum K n * (P.ratio K n 1 2 - 1) =
      -(P.ratio K n 0 2) ^ n := by
  rw [chartGeometricSum, geom_sum_mul]
  have h := ConcreteProjectiveFermatScheme.chartTwo_fermat_equation K n
  linear_combination h

/-- The image of the geometric sum is a unit in the boundary local ring. -/
theorem sourceGeometricSum_isUnit [CharZero K]
    (n : ℕ) [NeZero n] :
    IsUnit (algebraMap (P.Chart K n 2) (ZeroSourceLocalRing K n)
      (chartGeometricSum K n)) := by
  apply (IsLocalization.AtPrime.isUnit_to_map_iff
    (ZeroSourceLocalRing K n) (chartZeroIdeal K n) _).mpr
  simpa only [Ideal.mem_primeCompl_iff] using
    chartGeometricSum_not_mem_zeroIdeal K n

/-- The maximal ideal of the honest chart local ring is generated by the
image of `u`. -/
theorem source_maximalIdeal_eq_span_uniformizer
    [CharZero K] (n : ℕ) [NeZero n] :
    maximalIdeal (ZeroSourceLocalRing K n) =
      Ideal.span ({sourceUniformizer K n} : Set (ZeroSourceLocalRing K n)) := by
  apply le_antisymm
  · rw [← Localization.AtPrime.map_eq_maximalIdeal]
    rw [show (chartZeroIdeal K n).map
          (algebraMap (P.Chart K n 2) (ZeroSourceLocalRing K n)) =
        (Ideal.span ({P.ratio K n 0 2, P.ratio K n 1 2 - 1} :
          Set (P.Chart K n 2))).map
            (algebraMap (P.Chart K n 2) (ZeroSourceLocalRing K n)) from
      congrArg (fun I : Ideal (P.Chart K n 2) ↦
        I.map (algebraMap (P.Chart K n 2) (ZeroSourceLocalRing K n)))
          (chartZeroIdeal_eq_span K n), Ideal.map_span]
    apply Ideal.span_le.mpr
    rintro z ⟨a, ha, rfl⟩
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
    rcases ha with rfl | rfl
    · exact Ideal.subset_span (Set.mem_singleton _)
    · let I : Ideal (ZeroSourceLocalRing K n) :=
          Ideal.span ({sourceUniformizer K n} : Set (ZeroSourceLocalRing K n))
      have hu : sourceUniformizer K n ∈ I :=
        Ideal.subset_span (Set.mem_singleton _)
      have hupow : sourceUniformizer K n ^ n ∈ I :=
        I.pow_mem_of_mem hu n (Nat.pos_of_ne_zero (NeZero.ne n))
      have hneg : -(sourceUniformizer K n ^ n) ∈ I := I.neg_mem hupow
      have hrel := congrArg
        (algebraMap (P.Chart K n 2) (ZeroSourceLocalRing K n))
        (chartGeometricSum_mul_v_sub_one K n)
      have hmulg :
          algebraMap (P.Chart K n 2) (ZeroSourceLocalRing K n)
              (chartGeometricSum K n) * (sourceV K n - 1) ∈ I := by
        rw [map_mul, map_sub, map_one, map_neg, map_pow] at hrel
        exact hrel.symm ▸ hneg
      have hv : sourceV K n - 1 ∈ I :=
        (I.unit_mul_mem_iff_mem (sourceGeometricSum_isUnit K n)).mp hmulg
      simpa [sourceV] using hv
  · apply Ideal.span_le.mpr
    rintro z rfl
    apply (IsLocalization.AtPrime.to_map_mem_maximal_iff
      (ZeroSourceLocalRing K n) (chartZeroIdeal K n) _).mpr
    rw [chartZeroIdeal_eq_span K n]
    exact Ideal.subset_span (Set.mem_insert _ _)

/-- The boundary maximal ideal is nonzero. -/
theorem chartZeroIdeal_ne_bot [CharZero K]
    {n : ℕ} (hn : 0 < n) [NeZero n] :
    chartZeroIdeal K n ≠ ⊥ := by
  intro hbot
  apply chart_u_ne_zero K hn
  have huBot : P.ratio K n 0 2 ∈ (⊥ : Ideal (P.Chart K n 2)) := by
    rw [← hbot, chartZeroIdeal_eq_span K n]
    exact Ideal.subset_span (Set.mem_insert _ _)
  simpa only [Ideal.mem_bot] using huBot

/-- The image of `u` stays nonzero after localizing at the boundary point. -/
theorem sourceUniformizer_ne_zero [CharZero K]
    {n : ℕ} (hn : 0 < n) [NeZero n] :
    sourceUniformizer K n ≠ 0 := by
  simpa [sourceUniformizer] using
    (IsLocalization.injective (ZeroSourceLocalRing K n)
      (chartZeroIdeal K n).primeCompl_le_nonZeroDivisors).ne
        (chart_u_ne_zero K hn)

/-- The honest homogeneous-chart local ring at `(0,1)` is a DVR. -/
noncomputable instance zeroSourceLocalRing_isDiscreteValuationRing
    [CharZero K] (n : ℕ) [NeZero n] :
    IsDiscreteValuationRing (ZeroSourceLocalRing K n) := by
  have hn : 0 < n := Nat.pos_of_ne_zero (NeZero.ne n)
  have hnf : ¬ IsField (ZeroSourceLocalRing K n) :=
    IsLocalization.AtPrime.not_isField (P.Chart K n 2)
      (chartZeroIdeal_ne_bot K hn) (ZeroSourceLocalRing K n)
  apply ((IsDiscreteValuationRing.TFAE (ZeroSourceLocalRing K n) hnf).out 4 0).mp
  rw [source_maximalIdeal_eq_span_uniformizer K n]
  infer_instance

/-- The coordinate `u` is therefore a genuine DVR uniformizer. -/
theorem sourceUniformizer_irreducible [CharZero K]
    (n : ℕ) [NeZero n] :
    Irreducible (sourceUniformizer K n) := by
  exact IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal
    (sourceUniformizer K n)
      (sourceUniformizer_ne_zero K (Nat.pos_of_ne_zero (NeZero.ne n)))
      (source_maximalIdeal_eq_span_uniformizer K n)

/-! ## The target local ring at zero -/

/-- The target point ideal `(t)` in `K[t]`. -/
def targetZeroIdeal : Ideal K[X] := Ideal.span ({X} : Set K[X])

/-- The target ideal is the kernel of evaluation at zero. -/
theorem targetZeroIdeal_eq_ker_evalZero :
    targetZeroIdeal K = RingHom.ker (evalRingHom (0 : K)) := by
  rw [targetZeroIdeal, Polynomial.ker_evalRingHom]
  simp

instance targetZeroIdeal_isMaximal : (targetZeroIdeal K).IsMaximal := by
  rw [targetZeroIdeal_eq_ker_evalZero K]
  apply RingHom.ker_isMaximal_of_surjective
  intro a
  exact ⟨C a, by simp⟩

instance targetZeroIdeal_isPrime : (targetZeroIdeal K).IsPrime :=
  (targetZeroIdeal_isMaximal K).isPrime

/-- The actual target local ring `K[t]_(t)`. -/
abbrev ZeroTargetLocalRing := Localization.AtPrime (targetZeroIdeal K)

/-- The image of the polynomial variable `t` in `K[t]_(t)`. -/
def targetUniformizer : ZeroTargetLocalRing K :=
  algebraMap K[X] (ZeroTargetLocalRing K) X

theorem targetZeroIdeal_ne_bot : targetZeroIdeal K ≠ ⊥ := by
  intro hbot
  have hX : X ∈ (⊥ : Ideal K[X]) := by
    rw [← hbot, targetZeroIdeal]
    exact Ideal.subset_span (Set.mem_singleton _)
  exact X_ne_zero (by simpa only [Ideal.mem_bot] using hX)

/-- The maximal ideal of the target local ring is generated by `t`. -/
theorem target_maximalIdeal_eq_span_uniformizer :
    maximalIdeal (ZeroTargetLocalRing K) =
      Ideal.span ({targetUniformizer K} : Set (ZeroTargetLocalRing K)) := by
  rw [← Localization.AtPrime.map_eq_maximalIdeal]
  rw [show (targetZeroIdeal K).map
        (algebraMap K[X] (ZeroTargetLocalRing K)) =
      (Ideal.span ({X} : Set K[X])).map
        (algebraMap K[X] (ZeroTargetLocalRing K)) from
    congrArg (fun I : Ideal K[X] ↦
      I.map (algebraMap K[X] (ZeroTargetLocalRing K))) rfl,
    Ideal.map_span]
  simp [targetUniformizer]

/-- The target localization is a DVR. -/
noncomputable instance zeroTargetLocalRing_isDiscreteValuationRing :
    IsDiscreteValuationRing (ZeroTargetLocalRing K) := by
  have hnf : ¬ IsField (ZeroTargetLocalRing K) :=
    IsLocalization.AtPrime.not_isField K[X] (targetZeroIdeal_ne_bot K)
      (ZeroTargetLocalRing K)
  apply ((IsDiscreteValuationRing.TFAE (ZeroTargetLocalRing K) hnf).out 4 0).mp
  rw [target_maximalIdeal_eq_span_uniformizer K]
  infer_instance

/-- `t` is a genuine uniformizer of the target DVR. -/
theorem targetUniformizer_irreducible : Irreducible (targetUniformizer K) := by
  have ht : targetUniformizer K ≠ 0 :=
    by
      change algebraMap K[X] (ZeroTargetLocalRing K) X ≠ 0
      rw [← map_zero (algebraMap K[X] (ZeroTargetLocalRing K))]
      exact (IsLocalization.injective (ZeroTargetLocalRing K)
        (targetZeroIdeal K).primeCompl_le_nonZeroDivisors).ne X_ne_zero
  exact IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal
    (targetUniformizer K) ht (target_maximalIdeal_eq_span_uniformizer K)

/-! ## The localized power map and exact ramification index -/

/-- On the genuine homogeneous chart, the target coordinate is `u^n`. -/
def chartBeta (n : ℕ) : K[X] →ₐ[K] P.Chart K n 2 :=
  Polynomial.aeval (P.ratio K n 0 2 ^ n)

@[simp]
theorem chartBeta_X (n : ℕ) :
    chartBeta K n X = P.ratio K n 0 2 ^ n := by
  simp [chartBeta]

/-- The chart point `(0,1)` lies over the target point `t=0`. -/
theorem targetZeroIdeal_eq_comap_chartZeroIdeal
    (n : ℕ) [NeZero n] :
    targetZeroIdeal K =
      (chartZeroIdeal K n).comap (chartBeta K n).toRingHom := by
  have hcomp :
      (chartZeroEval K n).toRingHom.comp (chartBeta K n).toRingHom =
        evalRingHom (0 : K) := by
    apply Polynomial.ringHom_ext
    · intro a
      simp [chartBeta, chartZeroEval]
    · simp only [RingHom.comp_apply, coe_evalRingHom, eval_X]
      change chartZeroEval K n (chartBeta K n X) = 0
      rw [chartBeta_X, map_pow, chartZeroEval_u,
        zero_pow (NeZero.ne n)]
  calc
    targetZeroIdeal K = RingHom.ker (evalRingHom (0 : K)) :=
      targetZeroIdeal_eq_ker_evalZero K
    _ = RingHom.ker
        ((chartZeroEval K n).toRingHom.comp (chartBeta K n).toRingHom) := by
      rw [hcomp]
    _ = (RingHom.ker (chartZeroEval K n).toRingHom).comap
        (chartBeta K n).toRingHom :=
      (RingHom.comap_ker (chartZeroEval K n).toRingHom
        (chartBeta K n).toRingHom).symm
    _ = (chartZeroIdeal K n).comap (chartBeta K n).toRingHom := rfl

/-- The induced homomorphism of the two actual local rings. -/
def zeroLocalRingHom (n : ℕ) [NeZero n] :
    ZeroTargetLocalRing K →+* ZeroSourceLocalRing K n :=
  Localization.localRingHom (targetZeroIdeal K) (chartZeroIdeal K n)
    (chartBeta K n).toRingHom (targetZeroIdeal_eq_comap_chartZeroIdeal K n)

instance zeroLocalRingHom_isLocalHom (n : ℕ) [NeZero n] :
    IsLocalHom (zeroLocalRingHom K n) := by
  exact Localization.isLocalHom_localRingHom
    (targetZeroIdeal K) (chartZeroIdeal K n) (chartBeta K n).toRingHom
      (targetZeroIdeal_eq_comap_chartZeroIdeal K n)

/-- The localized map still sends `t` exactly to `u^n`. -/
theorem zeroLocalRingHom_targetUniformizer (n : ℕ) [NeZero n] :
    zeroLocalRingHom K n (targetUniformizer K) =
      sourceUniformizer K n ^ n := by
  rw [targetUniformizer, zeroLocalRingHom,
    Localization.localRingHom_to_map]
  simp [chartBeta, sourceUniformizer]

/-- The explicit algebra structure induced by the localized power map. -/
noncomputable instance zeroLocalAlgebra (n : ℕ) [NeZero n] :
    Algebra (ZeroTargetLocalRing K) (ZeroSourceLocalRing K n) :=
  (zeroLocalRingHom K n).toAlgebra

instance zeroLocalAlgebra_isLocalHom (n : ℕ) [NeZero n] :
    IsLocalHom (algebraMap (ZeroTargetLocalRing K) (ZeroSourceLocalRing K n)) := by
  change IsLocalHom (zeroLocalRingHom K n)
  infer_instance

/-- At the honest boundary stalk `(u,v)=(0,1)`, the normalized order,
extended maximal ideal, and Mathlib ramification index are all exactly the
power exponent `n`. -/
theorem zeroBoundary_exact_ramification [CharZero K]
    (n : ℕ) [NeZero n] :
    IsDiscreteValuationRing.addVal (ZeroSourceLocalRing K n)
        (algebraMap (ZeroTargetLocalRing K) (ZeroSourceLocalRing K n)
          (targetUniformizer K)) = n ∧
      (maximalIdeal (ZeroTargetLocalRing K)).map
          (algebraMap (ZeroTargetLocalRing K) (ZeroSourceLocalRing K n)) =
        maximalIdeal (ZeroSourceLocalRing K n) ^ n ∧
      (maximalIdeal (ZeroSourceLocalRing K n)).ramificationIdx
          (ZeroTargetLocalRing K) = n := by
  have hpower :
      algebraMap (ZeroTargetLocalRing K) (ZeroSourceLocalRing K n)
          (targetUniformizer K) =
        (1 : (ZeroSourceLocalRing K n)ˣ) * sourceUniformizer K n ^ n := by
    change zeroLocalRingHom K n (targetUniformizer K) = _
    simpa using zeroLocalRingHom_targetUniformizer K n
  exact LocalPowerRamificationIndex.local_power_law_exact_conclusions
    (R := ZeroTargetLocalRing K) (S := ZeroSourceLocalRing K n)
    (targetUniformizer_irreducible K) (sourceUniformizer_irreducible K n)
    (1 : (ZeroSourceLocalRing K n)ˣ) n hpower

/-! ## The actual affine-scheme stalk -/

/-- The prime-spectrum point of the genuine homogeneous chart. -/
def chartZeroPoint (n : ℕ) [NeZero n] :
    PrimeSpectrum (P.Chart K n 2) :=
  ⟨chartZeroIdeal K n, chartZeroIdeal_isPrime K n⟩

/-- The scheme stalk of `Spec` of the homogeneous chart is the local ring
used above.  Since E.10 identifies this `Spec` with the actual Proj standard
open, this records the scheme-theoretic rather than pointwise-coordinate
origin of the DVR. -/
noncomputable def chartZeroStalkIso (n : ℕ) [NeZero n] :
    (AlgebraicGeometry.Spec (CommRingCat.of (P.Chart K n 2))).presheaf.stalk
        (chartZeroPoint K n) ≅
      CommRingCat.of (ZeroSourceLocalRing K n) :=
  AlgebraicGeometry.Spec.stalkIso
    (CommRingCat.of (P.Chart K n 2)) (chartZeroPoint K n)

end

end ConcreteFermatBoundaryLocalRing
end IUTThreeClosures
