import IUTThreeClosures.FreyPellChebyshevIndexNineteenDyadicObstruction
import IUTThreeClosures.FreyPellChebyshevIndexSeventeenDyadicColemanCertificate

/-!
# Prime-nineteen Stoll--Gamma closure: scalar companion

The external Magma certificate implements Stoll's Lemma 2.4 recursion for
Gamma_2 generated by H1 and H9, proves the finite Corollary 3.2 shell cover,
and checks the Lemma 3.10 tail. The external Sage certificate verifies the
Coleman-log reductions and a unit minor; the companion Q5 linear-algebra
argument defines the exact annihilating differential.

This file checks only the copied finite scalar consequences. It does not
formalize Jacobians, Kummer maps, Selmer groups, Stoll's theorems, p-adic
halving, or Coleman integration.
-/

namespace IUTThreeClosures

private theorem pellChebyshev_two_indexNineteen (x : ℤ) :
    pellChebyshev 2 x = 2 * x ^ 2 - 1 := by
  rw [show 2 = 0 + 2 by norm_num, pellChebyshev_add_two]
  simp [pellChebyshev_zero, pellChebyshev_one]
  ring_nf

private theorem pellChebyshev_nine_indexNineteen (x : ℤ) :
    pellChebyshev 9 x =
      256 * x ^ 9 - 576 * x ^ 7 + 432 * x ^ 5 - 120 * x ^ 3 + 9 * x := by
  rw [show 9 = 3 * 3 by norm_num, pellChebyshev_mul]
  rw [pellChebyshev_three, pellChebyshev_three]
  ring

private theorem pellChebyshev_eighteen_indexNineteen (x : ℤ) :
    pellChebyshev 18 x =
      131072 * x ^ 18 - 589824 * x ^ 16 + 1105920 * x ^ 14 -
        1118208 * x ^ 12 + 658944 * x ^ 10 - 228096 * x ^ 8 +
          44352 * x ^ 6 - 4320 * x ^ 4 + 162 * x ^ 2 - 1 := by
  rw [show 18 = 2 * 9 by norm_num, pellChebyshev_mul]
  rw [pellChebyshev_two_indexNineteen, pellChebyshev_nine_indexNineteen]
  ring

/-- The first-kind nineteenth Chebyshev polynomial in the repository's Pell
normalization. -/
theorem pellChebyshev_nineteen (x : ℤ) :
    pellChebyshev 19 x =
      262144 * x ^ 19 - 1245184 * x ^ 17 + 2490368 * x ^ 15 -
        2723840 * x ^ 13 + 1770496 * x ^ 11 - 695552 * x ^ 9 +
          160512 * x ^ 7 - 20064 * x ^ 5 + 1140 * x ^ 3 - 19 * x := by
  rw [show 19 = 17 + 2 by norm_num, pellChebyshev_add_two]
  norm_num only [Nat.reduceAdd]
  rw [pellChebyshev_eighteen_indexNineteen, pellChebyshev_seventeen]
  ring

/-- Exact coordinate bridge between the Coleman model
`y_c^2=(4*T_19(x)+5)/2^20` and the monic dyadic model: `X=4x` and
`Y=2^19*y_c`. -/
theorem pellChebyshevNineteen_stollColemanMonicModelBridge (x : ℤ) :
    let t19 :=
      262144 * x ^ 19 - 1245184 * x ^ 17 + 2490368 * x ^ 15 -
        2723840 * x ^ 13 + 1770496 * x ^ 11 - 695552 * x ^ 9 +
        160512 * x ^ 7 - 20064 * x ^ 5 + 1140 * x ^ 3 - 19 * x
    let fm :=
      (4 * x) ^ 19 - 76 * (4 * x) ^ 17 + 2432 * (4 * x) ^ 15 -
        42560 * (4 * x) ^ 13 + 442624 * (4 * x) ^ 11 -
        2782208 * (4 * x) ^ 9 + 10272768 * (4 * x) ^ 7 -
        20545536 * (4 * x) ^ 5 + 18677760 * (4 * x) ^ 3 -
        4980736 * (4 * x) + 1310720
    fm = 2 ^ 18 * (4 * t19 + 5) := by
  dsimp
  ring

/-- The two Coleman points map to the monic points with ordinates 512 and
1536 under `Y=2^19*y_c`; here the Coleman denominator is `2^10`. -/
theorem pellChebyshevNineteen_stollColemanEndpointScaleLedger :
    (2 : ℤ) ^ 19 = 512 * 2 ^ 10 ∧
      3 * (2 : ℤ) ^ 19 = 1536 * 2 ^ 10 := by
  norm_num

/-- The three complete shell computations have maximum Gamma-divisibility
m+2, namely 5, 6, and 7. -/
theorem pellChebyshevNineteen_stollGammaShellMaxLedger :
    3 + 2 = 5 ∧ 4 + 2 = 6 ∧ 5 + 2 = 7 := by
  norm_num

/-- Odd units modulo 32 give balls of parameter radius m+5. Since the
computed maximum is n=m+2, this is exactly the n+3 threshold in Stoll
Corollary 3.2 over Q_2. -/
theorem pellChebyshevNineteen_stollGammaLocalConstancyLedger :
    3 + 5 = (3 + 2) + 3 ∧
      4 + 5 = (4 + 2) + 3 ∧
      5 + 5 = (5 + 2) + 3 := by
  norm_num

/-- There are sixteen odd residue representatives modulo 32 in every
shell, hence 48 finite representatives for m=3,4,5. -/
theorem pellChebyshevNineteen_stollGammaRepresentativeCountLedger :
    32 / 2 = 16 ∧ 3 * 16 = 48 := by
  norm_num

/-- The Lemma 3.10 tail condition is met at m=5, with equality:
2m-3 = n_(m,Gamma) = 7. -/
theorem pellChebyshevNineteen_stollGammaTailLedger :
    2 * 5 - 3 = 7 ∧ 7 ≤ 2 * 5 - 3 := by
  norm_num

/-- A closure generated by at most two directions cannot have full analytic
dimension in a nine-dimensional Jacobian. The Lie-theoretic inference is
external; this is its copied dimension inequality. -/
theorem pellChebyshevNineteen_stollGammaClosureDimensionLedger :
    (2 : ℕ) < 9 := by
  norm_num

/-- With D0=-2H1, the non-Weierstrass base-point correction under the
hyperelliptic involution is -i-2D0=-i+4H1. -/
theorem pellChebyshevNineteen_negativeBranchCorrectionLedger
    (i h1 : ℤ) :
    -i - 2 * (-2 * h1) = -i + 4 * h1 := by
  ring

/-- The correction 4H1 is invisible modulo two. -/
theorem pellChebyshevNineteen_negativeBranchModTwoLedger (h1 : ℤ) :
    (4 * h1) % 2 = 0 := by
  omega

/-- Characteristic zero is the final elementary step in the saturation
argument: a positive integral multiple of a rational Coleman integral can
vanish only when the integral itself vanishes. -/
theorem pellChebyshevNineteen_saturatedIntegralZeroLedger
    (n : ℕ) (hn : 0 < n) (integral : ℚ)
    (hzero : (n : ℚ) * integral = 0) :
    integral = 0 := by
  have hnq : (n : ℚ) ≠ 0 := by
    exact_mod_cast (Nat.ne_of_gt hn)
  exact (mul_eq_zero.mp hzero).resolve_left hnq

/-- Five rational anchors and one non-rational Weierstrass anchor account
for the six residue disks of the exact Coleman differential. -/
theorem pellChebyshevNineteen_stollGammaColemanDiskLedger :
    5 + 1 = 6 := by
  norm_num

/-- The first two normalized Coleman-log columns have determinant one
modulo five: `3*3-3*1 = 1 (mod 5)`. This is the unit minor used to solve
the two characteristic-zero annihilation equations. -/
theorem pellChebyshevNineteen_stollGammaColemanUnitMinorLedger :
    (3 * 3 - 3 * 1) % 5 = 1 := by
  norm_num

/-- The reduced numerator `1+3*x^8` is a unit on the three finite residue
types, with values 1,4,4; its leading coefficient gives value 3 at infinity. -/
theorem pellChebyshevNineteen_stollGammaColemanUnitValuesLedger :
    1 % 5 = 1 ∧
      (1 + 3) % 5 = 4 ∧
      (1 + 3 * 4 ^ 8) % 5 = 4 ∧
      3 % 5 = 3 := by
  norm_num

/-- The shifted-square polynomial in the coefficient form consumed by the
external target-disk computation. -/
def pellChebyshevNineteen_shiftSquarePolynomial (T : ℤ) : ℤ :=
  4 * (262144 * T ^ 19 - 1245184 * T ^ 17 + 2490368 * T ^ 15 -
    2723840 * T ^ 13 + 1770496 * T ^ 11 - 695552 * T ^ 9 +
      160512 * T ^ 7 - 20064 * T ^ 5 + 1140 * T ^ 3 - 19 * T) + 5

/-- Transparent Lean boundary for the frozen Magma/Sage rational-point
certificate on the actual Pell disk.  The external audit proves this
proposition unconditionally; Lean keeps it as an explicit hypothesis because
the Jacobian, Stoll recursion, and Coleman integration are not reimplemented
in the kernel. -/
def MagmaSageRationalTargetDiskCertificateIndexNineteen : Prop :=
  ∀ T y : ℤ,
    (T + 1) % 8 = 0 →
    y ^ 2 = pellChebyshevNineteen_shiftSquarePolynomial T →
      T = -1 ∨ T = 1

/-- The prime-nineteen shifted-square equation has the explicit genus-nine
polynomial model used by the frozen certificate. -/
theorem indexNineteen_genusNine_model (T y : ℤ)
    (h : y ^ 2 = 4 * pellChebyshev 19 T + 5) :
    y ^ 2 = pellChebyshevNineteen_shiftSquarePolynomial T := by
  rw [pellChebyshev_nineteen] at h
  simpa [pellChebyshevNineteen_shiftSquarePolynomial] using h

/-- Conditional only at the transparent Lean boundary, the certified target
disk contains no prime-nineteen shifted-square solution with base above one. -/
theorem no_indexNineteen_chebyshev_shiftSquare_in_targetDisk_of_external_certificate
    (hcert : MagmaSageRationalTargetDiskCertificateIndexNineteen)
    (T : ℤ) (hT : 1 < T) (htarget : (T + 1) % 8 = 0) :
    ¬ ∃ y : ℤ, y ^ 2 = 4 * pellChebyshev 19 T + 5 := by
  rintro ⟨y, hy⟩
  have hmodel := indexNineteen_genusNine_model T y hy
  rcases hcert T y htarget hmodel with h | h <;> omega

/-- The residue class `T = 23 (mod 24)` lies in the certified dyadic disk. -/
theorem no_indexNineteen_chebyshev_shiftSquare_in_pellResidue_of_external_certificate
    (hcert : MagmaSageRationalTargetDiskCertificateIndexNineteen)
    (T : ℤ) (hT : 1 < T) (hresidue : T % 24 = 23) :
    ¬ ∃ y : ℤ, y ^ 2 = 4 * pellChebyshev 19 T + 5 := by
  apply no_indexNineteen_chebyshev_shiftSquare_in_targetDisk_of_external_certificate
      hcert T hT
  omega

#print axioms pellChebyshev_nineteen
#print axioms pellChebyshevNineteen_stollGammaShellMaxLedger
#print axioms pellChebyshevNineteen_stollColemanMonicModelBridge
#print axioms pellChebyshevNineteen_stollColemanEndpointScaleLedger
#print axioms pellChebyshevNineteen_stollGammaLocalConstancyLedger
#print axioms pellChebyshevNineteen_stollGammaRepresentativeCountLedger
#print axioms pellChebyshevNineteen_stollGammaTailLedger
#print axioms pellChebyshevNineteen_stollGammaClosureDimensionLedger
#print axioms pellChebyshevNineteen_negativeBranchCorrectionLedger
#print axioms pellChebyshevNineteen_negativeBranchModTwoLedger
#print axioms pellChebyshevNineteen_saturatedIntegralZeroLedger
#print axioms pellChebyshevNineteen_stollGammaColemanDiskLedger
#print axioms pellChebyshevNineteen_stollGammaColemanUnitMinorLedger
#print axioms pellChebyshevNineteen_stollGammaColemanUnitValuesLedger
#print axioms indexNineteen_genusNine_model
#print axioms
  no_indexNineteen_chebyshev_shiftSquare_in_targetDisk_of_external_certificate
#print axioms
  no_indexNineteen_chebyshev_shiftSquare_in_pellResidue_of_external_certificate

end IUTThreeClosures
