import IUTThreeClosures.MaximalValuationRingHull
import Mathlib.NumberTheory.LocalField.Basic

/-!
# Haar-character normalization at a nonarchimedean local field

This module derives the local numerical normalization from actual Haar
measure and valuation-ring quotients.  It does not accept a component formula
or target estimate as input.
-/

namespace IUTThreeClosures
namespace HaarResidueNormalization

open MeasureTheory Set
open scoped ENNReal NNReal NormedField Pointwise Valued

universe u

open MaximalValuationRingHull TateCurvesTheta

variable {K : Type u}
variable [NontriviallyNormedField K] [ProperSpace K]
variable [MeasurableSpace K] [BorelSpace K]
variable [IsUltrametricDist K]

/-- Pull the normalized additive Haar measure on `K` back to its valuation
integer ring.  This is a construction, not a supplied local-volume datum. -/
noncomputable def inducedIntegerHaar : Measure 𝒪[K] :=
  (normalizedIntegerHaar (K := K)).comap Subtype.val

omit [ProperSpace K] in
private theorem valuationIntegers_measurable :
    MeasurableSet (𝒪[K] : Set K) := by
  rw [← normIntegralRegion_eq_valuationIntegers,
    normIntegralRegion_eq_closedBall]
  exact measurableSet_closedBall

/-- The pulled-back measure of a measurable subset of `𝒪_K` is the
ambient Haar measure of its coerced image in `K`. -/
theorem inducedIntegerHaar_apply (s : Set 𝒪[K]) (_hs : MeasurableSet s) :
    inducedIntegerHaar (K := K) s =
      normalizedIntegerHaar (K := K) (((↑) : 𝒪[K] → K) '' s) := by
  exact (MeasurableEmbedding.subtype_coe
    (valuationIntegers_measurable (K := K))).comap_apply _ _

/-- Restricting ambient additive Haar measure to the additive group of
valuation integers preserves translation invariance. -/
theorem inducedIntegerHaar_isAddLeftInvariant :
    (inducedIntegerHaar (K := K)).IsAddLeftInvariant := by
  letI : (normalizedIntegerHaar (K := K)).IsAddHaarMeasure := by
    unfold normalizedIntegerHaar
    infer_instance
  constructor
  intro a
  ext s hs
  rw [Measure.map_apply (by fun_prop) hs]
  rw [inducedIntegerHaar_apply _ (hs.preimage (by fun_prop)),
    inducedIntegerHaar_apply _ hs]
  have himage :
      ((↑) : 𝒪[K] → K) '' ((fun x => a + x) ⁻¹' s) =
        (fun x : K => (a : K) + x) ⁻¹' (((↑) : 𝒪[K] → K) '' s) := by
    ext x
    constructor
    · rintro ⟨y, hy, rfl⟩
      exact ⟨a + y, hy, by simp⟩
    · rintro ⟨z, hz, hzx⟩
      have hyx : (((z - a : 𝒪[K]) : K)) = x := by
        change (z : K) - (a : K) = x
        rw [sub_eq_iff_eq_add]
        simpa [add_comm] using hzx
      refine ⟨z - a, ?_, hyx⟩
      simpa using hz
  rw [himage, measure_preimage_add]

@[simp]
theorem inducedIntegerHaar_univ :
    inducedIntegerHaar (K := K) Set.univ = 1 := by
  rw [inducedIntegerHaar_apply _ MeasurableSet.univ]
  have himage :
      ((↑) : 𝒪[K] → K) '' Set.univ = (𝒪[K] : Set K) := by
    ext x
    simp
  rw [himage, ← normIntegralRegion_eq_valuationIntegers]
  exact normalizedIntegerHaar_apply_normIntegralRegion (K := K)

section Discrete

variable [IsDiscreteValuationRing 𝒪[K]] [Finite 𝓀[K]]

omit [ProperSpace K] [Finite 𝓀[K]] in
/-- A DVR uniformizer cuts out a measurable maximal ideal. -/
theorem maximalIdeal_measurable (π : 𝒪[K]) (hπ : Irreducible π) :
    MeasurableSet (𝓂[K] : Set 𝒪[K]) := by
  rw [hπ.maximalIdeal_eq_closedBall]
  exact measurableSet_closedBall

omit [ProperSpace K] [MeasurableSpace K] [BorelSpace K] [Finite 𝓀[K]] in
/-- The image in `K` of the maximal ideal generated by a DVR uniformizer is
the actual scalar image `π 𝒪_K`. -/
theorem coe_image_maximalIdeal_eq_scaledRegion
    (π : 𝒪[K]) (hπ : Irreducible π) :
    ((↑) : 𝒪[K] → K) '' (𝓂[K] : Set 𝒪[K]) =
      scaledRegion (π : K) (normIntegralRegion (K := K)) := by
  rw [scaled_normIntegralRegion_eq_normBall]
  ext x
  constructor
  · rintro ⟨y, hy, rfl⟩
    rw [hπ.maximalIdeal_eq_closedBall, Metric.mem_closedBall] at hy
    simpa [dist_eq_norm] using hy
  · intro hx
    have hπlt : ‖(π : K)‖ < 1 := by
      simpa using Valued.integer.norm_irreducible_lt_one hπ
    have hxO : ‖x‖ ≤ 1 := hx.trans hπlt.le
    let y : 𝒪[K] := ⟨x, Valued.integer.mem_iff.mpr hxO⟩
    refine ⟨y, ?_, rfl⟩
    rw [hπ.maximalIdeal_eq_closedBall, Metric.mem_closedBall]
    simpa [y, dist_eq_norm] using hx

/-- Regard a nonzero valuation integer as a unit of the ambient field. -/
def integerUnit (π : 𝒪[K]) (hπ : π ≠ 0) : Kˣ :=
  Units.mk0 (π : K) (by
    intro h
    apply hπ
    exact Subtype.ext h)

omit [ProperSpace K] [MeasurableSpace K] [BorelSpace K]
    [IsDiscreteValuationRing 𝒪[K]] [Finite 𝓀[K]] in
@[simp]
theorem integerUnit_coe (π : 𝒪[K]) (hπ : π ≠ 0) :
    ((integerUnit π hπ : Kˣ) : K) = (π : K) :=
  rfl

omit [ProperSpace K] [MeasurableSpace K] [BorelSpace K]
    [IsDiscreteValuationRing 𝒪[K]] [Finite 𝓀[K]] in
/-- The pointwise action of the ambient unit is the same concrete scalar
image used by `scaledRegion`. -/
theorem integerUnit_smul_normIntegralRegion
    (π : 𝒪[K]) (hπ : π ≠ 0) :
    integerUnit π hπ • normIntegralRegion (K := K) =
      scaledRegion (π : K) (normIntegralRegion (K := K)) := by
  ext x
  constructor
  · rintro ⟨y, hy, rfl⟩
    exact ⟨y, hy, by simp [integerUnit, smul_eq_mul]⟩
  · rintro ⟨y, hy, rfl⟩
    exact ⟨y, hy, by simp [integerUnit, smul_eq_mul]⟩

/-- Finite coset counting inside the compact additive group `𝒪_K`.
The coefficient is definitionally the cardinality of the residue field. -/
theorem residueCard_mul_inducedIntegerHaar_maximalIdeal
    (π : 𝒪[K]) (hπ : Irreducible π) :
    (Nat.card 𝓀[K] : ℝ≥0∞) *
        inducedIntegerHaar (K := K) (𝓂[K] : Set 𝒪[K]) = 1 := by
  let H : AddSubgroup 𝒪[K] := (𝓂[K]).toAddSubgroup
  letI : Finite (𝒪[K] ⧸ H) := by
    change Finite 𝓀[K]
    infer_instance
  letI : H.FiniteIndex := AddSubgroup.finiteIndex_of_finite_quotient
  letI : (inducedIntegerHaar (K := K)).IsAddLeftInvariant :=
    inducedIntegerHaar_isAddLeftInvariant (K := K)
  have hindex := H.index_mul_measure
    (maximalIdeal_measurable π hπ) (inducedIntegerHaar (K := K))
  change (Nat.card 𝓀[K] : ℝ≥0∞) *
      inducedIntegerHaar (K := K) (𝓂[K] : Set 𝒪[K]) =
        inducedIntegerHaar (K := K) Set.univ at hindex
  simpa using hindex

omit [Finite 𝓀[K]] in
/-- Haar scaling identifies the distributive character of a DVR uniformizer
with the pulled-back mass of the maximal ideal. -/
theorem distribHaarChar_integerUnit_eq_maximalIdealMeasure
    (π : 𝒪[K]) (hπ : Irreducible π) :
    ((distribHaarChar K (integerUnit π hπ.ne_zero) : ℝ≥0) : ℝ≥0∞) =
      inducedIntegerHaar (K := K) (𝓂[K] : Set 𝒪[K]) := by
  let μ : Measure K := normalizedIntegerHaar (K := K)
  letI : μ.IsAddHaarMeasure := by
    dsimp [μ, normalizedIntegerHaar]
    infer_instance
  have hscale := distribHaarChar_mul (μ := μ)
    (integerUnit π hπ.ne_zero) (normIntegralRegion (K := K))
  have hunit : μ (normIntegralRegion (K := K)) = 1 :=
    normalizedIntegerHaar_apply_normIntegralRegion (K := K)
  rw [hunit, mul_one] at hscale
  rw [inducedIntegerHaar_apply _ (maximalIdeal_measurable π hπ),
    coe_image_maximalIdeal_eq_scaledRegion π hπ,
    ← integerUnit_smul_normIntegralRegion π hπ.ne_zero]
  exact hscale

/-- The distributive Haar character of a DVR uniformizer is the inverse of
the residue-field cardinality. -/
theorem distribHaarChar_integerUnit_eq_residueCard_inv
    (π : 𝒪[K]) (hπ : Irreducible π) :
    distribHaarChar K (integerUnit π hπ.ne_zero) =
      (Nat.card 𝓀[K] : ℝ≥0)⁻¹ := by
  have hmul := residueCard_mul_inducedIntegerHaar_maximalIdeal π hπ
  rw [← distribHaarChar_integerUnit_eq_maximalIdealMeasure π hπ] at hmul
  have hmulNN :
      (Nat.card 𝓀[K] : ℝ≥0) *
          distribHaarChar K (integerUnit π hπ.ne_zero) = 1 := by
    exact_mod_cast hmul
  exact eq_inv_of_mul_eq_one_right hmulNN

/-- Real logarithmic form of the uniformizer normalization. -/
theorem log_distribHaarChar_integerUnit
    (π : 𝒪[K]) (hπ : Irreducible π) :
    Real.log ((distribHaarChar K (integerUnit π hπ.ne_zero) : ℝ≥0) : ℝ) =
      -Real.log (Nat.card 𝓀[K] : ℝ) := by
  rw [distribHaarChar_integerUnit_eq_residueCard_inv π hπ]
  simp only [NNReal.coe_inv, NNReal.coe_natCast, Real.log_inv]

end Discrete

end HaarResidueNormalization
end IUTThreeClosures
