/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.HonestPilotWitness

/-!
# Honest sources generated by countably many actual outputs

The vertical log-Kummer correspondence and the Ind3 family are naturally
indexed by integers, so a finite output type is unnecessarily restrictive.
A countable union of measurable regions is measurable. If all outputs lie in
one finite-positive envelope and one distinguished native output has positive
measure, their union is again a finite-positive region.

This module therefore constructs the consistent source layer for a countable
actual possible-image family. No real-valued volume is assigned to arbitrary
sets: every logarithm is the logarithm of the measure of a measurable region
whose measure is proved nonzero and finite.
-/

namespace IUTThreeClosures

open MeasureTheory

universe u v w

/-- A countable family of concrete finite-positive outputs, one common
finite-positive envelope, and one distinguished native q-output. -/
structure HonestCountableGeneratedSource
    (I : Type v) [Fintype I]
    (α : I → Type u)
    [∀ i, MeasurableSpace (α i)]
    (μ : ∀ i, Measure (α i)) :
    Type (max (u + 1) (v + 1) (w + 1)) where
  Output : Type w
  outputCountable : Countable Output
  realize : Output → ∀ i, FinitePositiveRegion (α i) (μ i)
  envelope : ∀ i, FinitePositiveRegion (α i) (μ i)
  realize_le_envelope :
    ∀ o i, (realize o i : Set (α i)) ⊆ (envelope i : Set (α i))
  native : Output
  qLog : ℝ
  qLog_pos : 0 < qLog
  nativeAverage :
    (∑ i, (realize native i).logVolume) / Fintype.card I = -qLog

namespace HonestCountableGeneratedSource

variable {I : Type v} [Fintype I]
variable {α : I → Type u} [∀ i, MeasurableSpace (α i)]
variable {μ : ∀ i, Measure (α i)}

instance (S : HonestCountableGeneratedSource.{u, v, w} I α μ) :
    Countable S.Output :=
  S.outputCountable

/-- The literal union of every countable actual output. Its measure is
positive because it contains the native output and finite because it is
contained in the common envelope. -/
noncomputable def theta
    (S : HonestCountableGeneratedSource.{u, v, w} I α μ)
    (i : I) : FinitePositiveRegion (α i) (μ i) where
  carrier := ⋃ o : S.Output, (S.realize o i : Set (α i))
  measurable := MeasurableSet.iUnion fun o => (S.realize o i).measurable
  measure_ne_zero := by
    intro hzero
    apply (S.realize S.native i).measure_ne_zero
    apply le_antisymm
    · calc
        μ i (S.realize S.native i).carrier ≤
            μ i (⋃ o : S.Output, (S.realize o i : Set (α i))) := by
          apply measure_mono
          intro x hx
          exact Set.mem_iUnion.mpr ⟨S.native, hx⟩
        _ = 0 := hzero
    · exact bot_le
  measure_ne_top := by
    intro htop
    apply (S.envelope i).measure_ne_top
    apply top_unique
    calc
      ⊤ = μ i (⋃ o : S.Output, (S.realize o i : Set (α i))) := htop.symm
      _ ≤ μ i (S.envelope i).carrier := by
        apply measure_mono
        intro x hx
        rcases Set.mem_iUnion.mp hx with ⟨o, hx⟩
        exact S.realize_le_envelope o i hx

/-- Every concrete output is definitionally contained in the generated theta
region. -/
theorem realize_le_theta
    (S : HonestCountableGeneratedSource.{u, v, w} I α μ)
    (o : S.Output) (i : I) :
    (S.realize o i : Set (α i)) ⊆ (S.theta i : Set (α i)) := by
  intro x hx
  change x ∈ ⋃ o : S.Output, (S.realize o i : Set (α i))
  exact Set.mem_iUnion.mpr ⟨o, hx⟩

/-- The countably generated source gives an honest procession witness. -/
noncomputable def toProcessionWitness
    (S : HonestCountableGeneratedSource.{u, v, w} I α μ) :
    HonestProcessionWitness I α μ where
  native := S.realize S.native
  theta := S.theta
  native_le_theta := S.realize_le_theta S.native
  qLHS := -S.qLog
  nativeAverage := S.nativeAverage

/-- Canonical procession average of the countably generated theta regions. -/
noncomputable def thetaAverage
    (S : HonestCountableGeneratedSource.{u, v, w} I α μ) : ℝ :=
  S.toProcessionWitness.thetaAverage

/-- The native q-reading is bounded by the countable possible-image union. -/
theorem neg_qLog_le_thetaAverage
    (S : HonestCountableGeneratedSource.{u, v, w} I α μ) :
    -S.qLog ≤ S.thetaAverage := by
  simpa [thetaAverage, toProcessionWitness] using
    S.toProcessionWitness.qLHS_le_thetaAverage

/-- Canonical theta coefficient of the countably generated honest source. -/
noncomputable def thetaCoefficient
    (S : HonestCountableGeneratedSource.{u, v, w} I α μ) : ℝ :=
  S.thetaAverage / S.qLog

/-- Countable actual possible images still give the numerical Corollary 3.12
lower bound. -/
theorem thetaCoefficient_ge_neg_one
    (S : HonestCountableGeneratedSource.{u, v, w} I α μ) :
    -1 ≤ S.thetaCoefficient := by
  rw [thetaCoefficient]
  apply (le_div_iff₀ S.qLog_pos).2
  simpa only [neg_mul, one_mul] using S.neg_qLog_le_thetaAverage

end HonestCountableGeneratedSource

end IUTThreeClosures
