/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import Mathlib

/-!
# Arbitrary Ind2 permutations at the volume quotient level

An arbitrary permutation of theta labels need not preserve every component
region.  Indeed, taking componentwise unions over all permutations can destroy
the q-spectrum, as shown by the counterexample already formalized in this
repository.  The printed proof of IUT III, Corollary 3.12, uses a weaker and
more natural fact: procession-normalized volume is invariant under label
permutation.

This module formalizes that distinction.

For a finite label type, the uniform average of a family of real component
volumes is invariant under every permutation.  More generally, a weighted
average is invariant under permutations preserving the weights.  We define the
orbit relation generated by arbitrary label permutations and prove that the
average descends to the quotient.

Thus unrestricted Ind2 may be handled after passing to the numerical coarse
space, even though it cannot be handled by a componentwise set envelope.  This
provides a second route beside the spectrum-preserving region model:

* use the spectrum-preserving model for componentwise region inclusions;
* use the permutation-orbit quotient for the exact volume statement appearing
  in Step (x) of Corollary 3.12.

No claim is made here that the genuine Hodge-theater Ind2 action is exactly the
abstract action below; that identification remains a source theorem.
-/

namespace IUTThreeClosures

open scoped BigOperators

universe u

namespace Ind2PermutationVolume

variable {ι : Type u} [Fintype ι]

/-- The unnormalized total component volume. -/
noncomputable def total (f : ι → ℝ) : ℝ :=
  ∑ i, f i

/-- Uniform procession-normalized volume.  The value is set to zero on an
empty label type; the nonempty case is the intended application. -/
noncomputable def average (f : ι → ℝ) : ℝ :=
  total f / Fintype.card ι

/-- Relabel a component family by a permutation. -/
def relabel (σ : Equiv.Perm ι) (f : ι → ℝ) : ι → ℝ :=
  fun i => f (σ i)

/-- Arbitrary permutations preserve the total component volume. -/
theorem total_relabel
    (σ : Equiv.Perm ι) (f : ι → ℝ) :
    total (relabel σ f) = total f := by
  classical
  unfold total relabel
  exact σ.sum_comp f

/-- Arbitrary permutations preserve the procession-normalized average. -/
theorem average_relabel
    (σ : Equiv.Perm ι) (f : ι → ℝ) :
    average (relabel σ f) = average f := by
  rw [average, average, total_relabel]

/-- Weighted component volume. -/
noncomputable def weightedTotal
    (weight volume : ι → ℝ) : ℝ :=
  ∑ i, weight i * volume i

/-- If a permutation preserves the weights, it preserves the weighted total
volume even when it moves the component regions themselves. -/
theorem weightedTotal_relabel
    (σ : Equiv.Perm ι)
    (weight volume : ι → ℝ)
    (hweight : ∀ i, weight (σ i) = weight i) :
    weightedTotal weight (relabel σ volume) =
      weightedTotal weight volume := by
  classical
  unfold weightedTotal relabel
  calc
    (∑ i, weight i * volume (σ i)) =
        ∑ i, weight (σ i) * volume (σ i) := by
          apply Finset.sum_congr rfl
          intro i hi
          rw [hweight]
    _ = ∑ i, weight i * volume i := by
          exact σ.sum_comp (fun i => weight i * volume i)

/-- Two component-volume families lie in the same Ind2 orbit when one is
obtained from the other by a permutation. -/
def OrbitRel (f g : ι → ℝ) : Prop :=
  ∃ σ : Equiv.Perm ι, g = relabel σ f

/-- The Ind2 orbit relation is an equivalence relation. -/
theorem orbitRel_equivalence : Equivalence (@OrbitRel ι _) where
  refl := by
    intro f
    exact ⟨Equiv.refl ι, rfl⟩
  symm := by
    intro f g h
    rcases h with ⟨σ, rfl⟩
    refine ⟨σ.symm, ?_⟩
    funext i
    simp [relabel]
  trans := by
    intro f g h h' k
    rcases h with ⟨σ, rfl⟩
    rcases h' with ⟨τ, rfl⟩
    refine ⟨σ.trans τ, ?_⟩
    funext i
    rfl

/-- Setoid of arbitrary Ind2 permutation orbits. -/
def orbitSetoid : Setoid (ι → ℝ) where
  r := OrbitRel
  iseqv := orbitRel_equivalence

/-- Numerical coarse space obtained by quotienting component families by
arbitrary Ind2 relabeling. -/
abbrev OrbitQuotient := Quotient (orbitSetoid (ι := ι))

/-- Uniform average descends to the arbitrary-permutation quotient. -/
noncomputable def quotientAverage : OrbitQuotient (ι := ι) → ℝ :=
  Quotient.lift average (by
    intro f g h
    rcases h with ⟨σ, rfl⟩
    exact average_relabel σ f)

@[simp]
theorem quotientAverage_mk (f : ι → ℝ) :
    quotientAverage (Quotient.mk (orbitSetoid (ι := ι)) f) =
      average f :=
  rfl

/-- A numerical observable invariant under relabeling descends to the Ind2
orbit quotient. -/
noncomputable def quotientObservable
    {β : Type*}
    (observable : (ι → ℝ) → β)
    (hinvariant :
      ∀ (σ : Equiv.Perm ι) (f : ι → ℝ),
        observable (relabel σ f) = observable f) :
    OrbitQuotient (ι := ι) → β :=
  Quotient.lift observable (by
    intro f g h
    rcases h with ⟨σ, rfl⟩
    exact hinvariant σ f)

/-- Componentwise equality is much stronger than the equality needed after
passing to the numerical quotient. -/
theorem average_eq_of_orbitRel
    {f g : ι → ℝ}
    (h : OrbitRel f g) :
    average f = average g := by
  rcases h with ⟨σ, rfl⟩
  exact (average_relabel σ f).symm

end Ind2PermutationVolume

end IUTThreeClosures
