/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.ActualTatePowerThetaSource

/-!
# Kummer values up to integral units give the same local power region

A local Kummer or theta value is normally determined only up to multiplication
by an integral unit.  This ambiguity does not change its fractional-ideal
region.  If

`x = u * q^n`, with `u ∈ Oˣ`,

then

`x O = q^n O`.

This elementary fact turns the source obligation “the output region is exactly
a Tate-power region” into the more natural Kummer statement “the output value
is an integral unit times a Tate-parameter power”.  The product-region and
holomorphic-hull theorems then apply automatically.
-/

set_option linter.checkUnivs false

namespace Iut

open scoped Pointwise

universe u

namespace ScalarPowerRegion

/-- Principal fractional-ideal region generated by one scalar. -/
def principalRegion
    {F : Type u} [Field F] (a : F) (O : Subring F) : Set F :=
  (fun x : F => a * x) '' (O : Set F)

/-- `aⁿ O` in the principal-region and power-region notations. -/
theorem principalRegion_pow_eq_powerRegion
    {F : Type u} [Field F] (a : F) (O : Subring F) (n : ℕ) :
    principalRegion (a ^ n) O = powerRegion a O n := rfl

/-- Multiplication of a generator by an integral unit does not change its
principal fractional-ideal region. -/
theorem unit_mul_principalRegion_eq
    {F : Type u} [Field F]
    {O : Subring F} (unit : Oˣ) (a : F) :
    principalRegion (((unit : O) : F) * a) O =
      principalRegion a O := by
  ext x
  constructor
  · rintro ⟨y, hy, rfl⟩
    refine ⟨((unit : O) : F) * y,
      O.mul_mem (unit : O).property hy, ?_⟩
    ring
  · rintro ⟨y, hy, rfl⟩
    let unitInv : O := (unit⁻¹ : Oˣ)
    refine ⟨(unitInv : F) * y,
      O.mul_mem unitInv.property hy, ?_⟩
    have hunit : ((unit : O) : F) * (unitInv : F) = 1 := by
      change (((unit : O) * unitInv : O) : F) = 1
      simp [unitInv]
    calc
      a * y = a * (1 * y) := by ring
      _ = a * ((((unit : O) : F) * (unitInv : F)) * y) := by rw [hunit]
      _ = (((unit : O) : F) * a) * ((unitInv : F) * y) := by ring

/-- Source datum saying that one local Kummer value is an integral unit times
a power of a distinguished scalar. -/
structure UnitTimesPowerData
    {F : Type u} [Field F] (O : Subring F) (q value : F) where
  unit : Oˣ
  power : ℕ
  value_eq : value = ((unit : O) : F) * q ^ power

namespace UnitTimesPowerData

/-- A Kummer value represented up to an integral unit generates exactly the
corresponding distinguished-scalar power region. -/
theorem principalRegion_eq_powerRegion
    {F : Type u} [Field F]
    {O : Subring F} {q value : F}
    (K : UnitTimesPowerData O q value) :
    principalRegion value O = powerRegion q O K.power := by
  rw [K.value_eq, unit_mul_principalRegion_eq K.unit]
  rfl

end UnitTimesPowerData

end ScalarPowerRegion

end Iut

namespace IUTThreeClosures

open Iut TateCurvesTheta
open scoped Pointwise

universe u v w

variable {AG : AnabelianGeometry.{u}} {TG : TemperedGeometry AG}
variable {D : InitialThetaData AG TG}
variable {G : GeneratedRHSData.{u, v, w} D}

section NormedSummands

variable [∀ (i : Fin G.container.proc.length) (p : Nat.Primes)
  (c : G.container.Components i (.finite p)),
    NormedField ((G.container.packet i (.finite p)).Summand c)]

/-- Actual generated outputs described by concrete Kummer values.  The only
valuation-theoretic source statement is that each value is an integral unit
times a power of the actual Tate parameter. -/
structure GeneratedTateKummerOutputData
    (G : GeneratedRHSData.{u, v, w} D) :
    Type (max (u + 1) (v + 1) (w + 1)) where
  tate :
    (i : Fin G.container.proc.length) →
    (p : Nat.Primes) →
    (c : G.container.Components i (.finite p)) →
      TateParameter ((G.container.packet i (.finite p)).Summand c)
  integral_eq_normIntegral : ∀ i p c,
    ((G.container.packet i (.finite p)).integral c :
      Set ((G.container.packet i (.finite p)).Summand c)) =
        normIntegralRegion
          (K := (G.container.packet i (.finite p)).Summand c)
  /-- Concrete Kummer/theta scalar produced by each output. -/
  value :
    (o : G.outputs.Output) →
    (i : Fin G.container.proc.length) →
    (p : Nat.Primes) →
    (c : G.container.Components i (.finite p)) →
      (G.container.packet i (.finite p)).Summand c
  /-- Unit-times-Tate-power description of the concrete value. -/
  value_decomposition : ∀ o i p c,
    ScalarPowerRegion.UnitTimesPowerData
      ((G.container.packet i (.finite p)).integral c)
      ((tate i p c).q :
        (G.container.packet i (.finite p)).Summand c)
      (value o i p c)
  /-- The concrete output region is the product of the principal regions of
  the concrete Kummer values. -/
  realize_finite : ∀ o i p,
    (G.outputs.realize o i).region (.finite p) =
      (G.container.packet i (.finite p)).productRegion fun c =>
        ScalarPowerRegion.principalRegion
          (value o i p c)
          ((G.container.packet i (.finite p)).integral c)

namespace GeneratedTateKummerOutputData

/-- The Kummer unit-times-power theorem constructs the actual Tate-power
source required by the componentwise-minimum hull calculation. -/
noncomputable def toTatePower
    (K : GeneratedTateKummerOutputData G) :
    GeneratedTatePowerThetaHullData G where
  tate := K.tate
  integral_eq_normIntegral := K.integral_eq_normIntegral
  power o i p c := (K.value_decomposition o i p c).power
  realize_finite := by
    intro o i p
    rw [K.realize_finite o i p]
    unfold ScalarPowerRegion.packetScalarPowerRegion
    ext x
    constructor
    · intro hx c
      rw [(K.value_decomposition o i p c).principalRegion_eq_powerRegion]
      exact hx c
    · intro hx c
      rw [(K.value_decomposition o i p c).principalRegion_eq_powerRegion]
      exact hx c

/-- Consequently the actual public theta hull is the product of the
componentwise-minimum powers occurring in the Kummer decompositions. -/
theorem thetaHull_finite_eq_minimumKummerPowers
    (K : GeneratedTateKummerOutputData G)
    (i : Fin G.container.proc.length)
    (p : Nat.Primes) :
    ((G.toRHSData).thetaHull i).region (.finite p) =
      ScalarPowerRegion.packetScalarPowerRegion i p
        (fun c => ((K.tate i p c).q :
          (G.container.packet i (.finite p)).Summand c))
        (K.toTatePower.toScalarPower.minimumPower i p) :=
  K.toTatePower.thetaHull_finite_eq_minimumTatePowers i p

end GeneratedTateKummerOutputData

end NormedSummands

end IUTThreeClosures
