/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.ABCMixedFullCampana20260831

/-!
# A strict Pell upgrade gate for the mixed-full counterexample route

The mathematical proofs precede this file in
`research/ABC_COUNTEREXAMPLE_CAMPANA_ESCAPE_2026_08_31.md`.

The Pell equation `x^2 - 8*y^2 = 1` gives the primitive adjacent abc point

`(1, 8*y^2, x^2)`.

Both nontrivial endpoints are always squarefull.  If the Pell root `y` is
itself squarefull, then `8*y^2` is cubefull, so the point has the strict
mixed-full signature `(7,3,2)`, whose reciprocal sum is `41/42`.  An
unbounded family of such squarefull-root Pell data would therefore disprove
the unchanged standard `ABCConjecture`.

This file proves the deterministic implication only.  It does not assert
that an unbounded squarefull-root Pell family exists.

The Darmon--Granville kernel-escape argument, the Mason--Stothers polynomial
obstruction, the sharper `3/4` radical slope, and the Lucas--Wieferich analysis
remain paper-only; none is represented here by an axiom.
-/

namespace IUTThreeClosures
namespace PellCampanaCounterexample20260831

open KFullRadicalCompression
open ABCMixedFullCampana20260831

noncomputable section

/-! ## The integral Pell orbit -/

/-- The positive Pell orbit generated by `3 + sqrt 8`, including its
index-zero unit. -/
def pellOrbit : ℕ → ℕ × ℕ
  | 0 => (1, 0)
  | n + 1 =>
      (3 * (pellOrbit n).1 + 8 * (pellOrbit n).2,
        (pellOrbit n).1 + 3 * (pellOrbit n).2)

@[simp] theorem pellOrbit_zero : pellOrbit 0 = (1, 0) := rfl

@[simp] theorem pellOrbit_succ (n : ℕ) :
    pellOrbit (n + 1) =
      (3 * (pellOrbit n).1 + 8 * (pellOrbit n).2,
        (pellOrbit n).1 + 3 * (pellOrbit n).2) := rfl

/-- The Pell norm is preserved exactly by the integral recurrence. -/
theorem pellOrbit_norm (n : ℕ) :
    1 + 8 * (pellOrbit n).2 ^ 2 = (pellOrbit n).1 ^ 2 := by
  induction n with
  | zero => norm_num [pellOrbit]
  | succ n ih =>
      rw [pellOrbit_succ]
      dsimp only
      nlinarith

/-- The first Pell coordinate is always positive. -/
theorem pellOrbit_fst_pos (n : ℕ) : 0 < (pellOrbit n).1 := by
  induction n with
  | zero => norm_num [pellOrbit]
  | succ n ih =>
      rw [pellOrbit_succ]
      dsimp only
      omega

/-- The second coordinate strictly increases at every step. -/
theorem pellOrbit_snd_lt_snd_succ (n : ℕ) :
    (pellOrbit n).2 < (pellOrbit (n + 1)).2 := by
  rw [pellOrbit_succ]
  dsimp only
  have hx := pellOrbit_fst_pos n
  omega

/-- The Pell root dominates its index. -/
theorem pellOrbit_index_le_snd (n : ℕ) :
    n ≤ (pellOrbit n).2 := by
  induction n with
  | zero => simp [pellOrbit]
  | succ n ih =>
      rw [pellOrbit_succ]
      dsimp only
      have hx := pellOrbit_fst_pos n
      omega

/-- The first Pell coordinate is larger than the second away from index zero. -/
theorem pellOrbit_snd_lt_fst_succ (n : ℕ) :
    (pellOrbit (n + 1)).2 < (pellOrbit (n + 1)).1 := by
  have hnorm := pellOrbit_norm (n + 1)
  have hy : 0 < (pellOrbit (n + 1)).2 := by
    have h := pellOrbit_snd_lt_snd_succ n
    omega
  nlinarith

/-- The Pell first coordinates are arithmetically unbounded. -/
theorem pellOrbit_fst_unbounded (B : ℕ) :
    ∃ n : ℕ, B < (pellOrbit n).1 := by
  refine ⟨B + 1, ?_⟩
  have hindex := pellOrbit_index_le_snd (B + 1)
  have hlt := pellOrbit_snd_lt_fst_succ B
  omega

/-! ## Fullness transfer -/

/-- The unit is `k`-full for every exponent. -/
theorem one_isKFull (k : ℕ) : IsKFull k 1 := by
  refine ⟨by norm_num, ?_⟩
  intro p hp hpdvd
  exact False.elim (hp.not_dvd_one hpdvd)

/-- Every nonzero exact `k`th power is `k`-full. -/
theorem power_isKFull {x k : ℕ} (hx : x ≠ 0) :
    IsKFull k (x ^ k) := by
  apply (IsKFull.iff_prime_pow_dvd (pow_ne_zero k hx)).2
  intro p hp hppow
  have hpx : p ∣ x := hp.dvd_of_dvd_pow hppow
  exact pow_dvd_pow_of_dvd hpx k

/-- `8*y^2` is squarefull for every nonzero `y`. -/
theorem eight_mul_sq_isTwoFull {y : ℕ} (hy : y ≠ 0) :
    IsKFull 2 (8 * y ^ 2) := by
  have hne : 8 * y ^ 2 ≠ 0 :=
    mul_ne_zero (by norm_num) (pow_ne_zero 2 hy)
  apply (IsKFull.iff_prime_pow_dvd hne).2
  intro p hp hpdvd
  rcases hp.dvd_mul.mp hpdvd with hp8 | hpy2
  · have hp2 : p ∣ 2 := by
      apply hp.dvd_of_dvd_pow
      simpa only [show (8 : ℕ) = 2 ^ 3 by norm_num] using hp8
    have hpeq : p = 2 :=
      (Nat.dvd_prime Nat.prime_two).mp hp2 |>.resolve_left hp.ne_one
    subst p
    exact dvd_mul_of_dvd_left (by norm_num : 2 ^ 2 ∣ 8) (y ^ 2)
  · have hpy : p ∣ y := hp.dvd_of_dvd_pow hpy2
    exact dvd_mul_of_dvd_right (pow_dvd_pow_of_dvd hpy 2) 8

/-- A squarefull Pell root upgrades `8*y^2` from squarefull to cubefull. -/
theorem eight_mul_sq_isThreeFull {y : ℕ}
    (hy : IsKFull 2 y) :
    IsKFull 3 (8 * y ^ 2) := by
  have hne : 8 * y ^ 2 ≠ 0 :=
    mul_ne_zero (by norm_num) (pow_ne_zero 2 hy.ne_zero)
  apply (IsKFull.iff_prime_pow_dvd hne).2
  intro p hp hpdvd
  rcases hp.dvd_mul.mp hpdvd with hp8 | hpy2
  · have hp2 : p ∣ 2 := by
      apply hp.dvd_of_dvd_pow
      simpa only [show (8 : ℕ) = 2 ^ 3 by norm_num] using hp8
    have hpeq : p = 2 :=
      (Nat.dvd_prime Nat.prime_two).mp hp2 |>.resolve_left hp.ne_one
    subst p
    exact dvd_mul_of_dvd_left (by norm_num : 2 ^ 3 ∣ 8) (y ^ 2)
  · have hpy : p ∣ y := hp.dvd_of_dvd_pow hpy2
    have hp2y : p ^ 2 ∣ y :=
      (IsKFull.iff_prime_pow_dvd hy.ne_zero).1 hy p hp hpy
    have hp4y2 : p ^ 4 ∣ y ^ 2 := by
      calc
        p ^ 4 = (p ^ 2) ^ 2 := by ring
        _ ∣ y ^ 2 := pow_dvd_pow_of_dvd hp2y 2
    have hp3y2 : p ^ 3 ∣ y ^ 2 :=
      (pow_dvd_pow p (by omega : 3 ≤ 4)).trans hp4y2
    exact dvd_mul_of_dvd_right hp3y2 8

/-! ## The strict `(7,3,2)` Pell gate -/

/-- One squarefull-root Pell solution, with all arithmetic hypotheses made
explicit. -/
structure Datum where
  x : ℕ
  y : ℕ
  x_pos : 0 < x
  y_pos : 0 < y
  equation : 1 + 8 * y ^ 2 = x ^ 2
  y_twoFull : IsKFull 2 y

namespace Datum

/-- The primitive adjacent abc point `(1,8*y^2,x^2)`. -/
def point (D : Datum) : ABCPoint where
  a := 1
  b := 8 * D.y ^ 2
  c := D.x ^ 2
  a_pos := by norm_num
  b_pos := mul_pos (by norm_num) (pow_pos D.y_pos 2)
  c_pos := pow_pos D.x_pos 2
  sum_eq := D.equation
  pairwise_coprime := by
    have hsucc : 8 * D.y ^ 2 + 1 = D.x ^ 2 := by
      calc
        8 * D.y ^ 2 + 1 = 1 + 8 * D.y ^ 2 := by omega
        _ = D.x ^ 2 := D.equation
    rw [← hsucc]
    simp [PairwiseCoprimeABC]

@[simp] theorem point_a (D : Datum) : D.point.a = 1 := rfl
@[simp] theorem point_b (D : Datum) : D.point.b = 8 * D.y ^ 2 := rfl
@[simp] theorem point_c (D : Datum) : D.point.c = D.x ^ 2 := rfl

/-- The unit endpoint is 7-full. -/
theorem a_sevenFull (D : Datum) : IsKFull 7 D.point.a := by
  simpa [point] using one_isKFull 7

/-- The squarefull-root hypothesis makes the middle endpoint 3-full. -/
theorem b_threeFull (D : Datum) : IsKFull 3 D.point.b := by
  simpa [point] using eight_mul_sq_isThreeFull D.y_twoFull

/-- The square endpoint is 2-full. -/
theorem c_twoFull (D : Datum) : IsKFull 2 D.point.c := by
  simpa [point] using power_isKFull (k := 2) D.x_pos.ne'

/-- Each datum lies in the strict mixed-full signature `(7,3,2)`. -/
theorem point_mixedFull (D : Datum) : MixedFull D.point 7 3 2 :=
  ⟨D.a_sevenFull, D.b_threeFull, D.c_twoFull⟩

end Datum

/-- The reciprocal sum of the Pell upgrade signature is `41/42 < 1`. -/
theorem signature_732_subcritical : mixedFullSlope 7 3 2 < 1 := by
  norm_num [mixedFullSlope]

/-- An unbounded family of squarefull-root Pell data is a strict disproof of
the standard abc conjecture. -/
theorem not_abcConjecture_of_unbounded_squarefullPell_family
    (D : ℕ → Datum)
    (hunbounded :
      ∀ B : ℝ, ∃ n : ℕ, B < (D n).point.height) :
    ¬ ABCConjecture := by
  apply not_abcConjecture_of_unbounded_mixedFull_family
    (fun n => (D n).point)
    (p := 7) (q := 3) (r := 2)
    (by norm_num) (by norm_num) (by norm_num)
    signature_732_subcritical
  · exact fun n => (D n).point_mixedFull
  · exact hunbounded

#print axioms pellOrbit_norm
#print axioms pellOrbit_index_le_snd
#print axioms pellOrbit_fst_unbounded
#print axioms eight_mul_sq_isTwoFull
#print axioms eight_mul_sq_isThreeFull
#print axioms Datum.point_mixedFull
#print axioms not_abcConjecture_of_unbounded_squarefullPell_family

end

end PellCampanaCounterexample20260831
end IUTThreeClosures
