/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.PellAdjacentFactorCounterexample20260831

/-!
# Square-root descent for the squarefull Pell counterexample route

The mathematical proof appears first in Proposition 3.2 of
`research/ABC_PELL_ADJACENT_FACTOR_GATE_2026_08_31.md`.

Writing `(1 + sqrt 2)^n = A_n + B_n sqrt 2`, the Pell orbit generated by
`3 + sqrt 8` has coordinates

`x_n = A_n^2 + 2*B_n^2`, `y_n = A_n*B_n`.

The coordinates `A_n,B_n` are coprime.  Hence `y_n` is squarefull exactly
when both square-root coordinates are squarefull.  No assertion that this
happens at an unbounded set of indices is made here.
-/

namespace IUTThreeClosures
namespace PellSquareRootDescent20260831

open KFullRadicalCompression
open PellCampanaCounterexample20260831

noncomputable section

/-- Natural coordinates of `(1 + sqrt 2)^n`. -/
def sqrtTwoOrbit : ℕ → ℕ × ℕ
  | 0 => (1, 0)
  | n + 1 =>
      ((sqrtTwoOrbit n).1 + 2 * (sqrtTwoOrbit n).2,
        (sqrtTwoOrbit n).1 + (sqrtTwoOrbit n).2)

@[simp] theorem sqrtTwoOrbit_zero : sqrtTwoOrbit 0 = (1, 0) := rfl

@[simp] theorem sqrtTwoOrbit_succ (n : ℕ) :
    sqrtTwoOrbit (n + 1) =
      ((sqrtTwoOrbit n).1 + 2 * (sqrtTwoOrbit n).2,
        (sqrtTwoOrbit n).1 + (sqrtTwoOrbit n).2) := rfl

/-- The first square-root coordinate is always positive. -/
theorem sqrtTwoOrbit_fst_pos (n : ℕ) : 0 < (sqrtTwoOrbit n).1 := by
  induction n with
  | zero => norm_num [sqrtTwoOrbit]
  | succ n ih =>
      rw [sqrtTwoOrbit_succ]
      exact Nat.add_pos_left ih _

/-- The second coordinate is positive away from the zeroth orbit point. -/
theorem sqrtTwoOrbit_snd_pos_succ (n : ℕ) :
    0 < (sqrtTwoOrbit (n + 1)).2 := by
  rw [sqrtTwoOrbit_succ]
  exact Nat.add_pos_left (sqrtTwoOrbit_fst_pos n) _

/-- The determinant-minus-one update preserves coprimality. -/
theorem sqrtTwoOrbit_coprime (n : ℕ) :
    Nat.Coprime (sqrtTwoOrbit n).1 (sqrtTwoOrbit n).2 := by
  induction n with
  | zero => norm_num [sqrtTwoOrbit]
  | succ n ih =>
      rw [sqrtTwoOrbit_succ]
      rw [show (sqrtTwoOrbit n).1 + 2 * (sqrtTwoOrbit n).2 =
        (sqrtTwoOrbit n).1 + (sqrtTwoOrbit n).2 +
          (sqrtTwoOrbit n).2 by omega]
      rw [Nat.coprime_self_add_left, Nat.coprime_add_self_right]
      exact ih.symm

/-- The signed norm of the square-root orbit alternates. -/
theorem sqrtTwoOrbit_norm (n : ℕ) :
    ((sqrtTwoOrbit n).1 : ℤ) ^ 2 -
        2 * ((sqrtTwoOrbit n).2 : ℤ) ^ 2 = (-1 : ℤ) ^ n := by
  induction n with
  | zero => norm_num [sqrtTwoOrbit]
  | succ n ih =>
      rw [sqrtTwoOrbit_succ]
      simp only [Nat.cast_add, Nat.cast_mul,
        Nat.cast_ofNat, pow_succ]
      rw [← ih]
      ring

/-- The even-index norm-one identity in natural-number form. -/
theorem sqrtTwoOrbit_norm_even (n : ℕ) :
    (sqrtTwoOrbit (2 * n)).1 ^ 2 =
      1 + 2 * (sqrtTwoOrbit (2 * n)).2 ^ 2 := by
  have h := sqrtTwoOrbit_norm (2 * n)
  norm_num [pow_mul] at h
  exact_mod_cast (show
    ((sqrtTwoOrbit (2 * n)).1 : ℤ) ^ 2 =
      1 + 2 * ((sqrtTwoOrbit (2 * n)).2 : ℤ) ^ 2 by linarith)

/-- The odd-index norm-minus-one identity in natural-number form. -/
theorem sqrtTwoOrbit_norm_odd (n : ℕ) :
    1 + (sqrtTwoOrbit (2 * n + 1)).1 ^ 2 =
      2 * (sqrtTwoOrbit (2 * n + 1)).2 ^ 2 := by
  have h := sqrtTwoOrbit_norm (2 * n + 1)
  have hsign : (-1 : ℤ) ^ (2 * n + 1) = -1 := by
    rw [pow_add, pow_mul]
    norm_num
  rw [hsign] at h
  exact_mod_cast (show
    1 + ((sqrtTwoOrbit (2 * n + 1)).1 : ℤ) ^ 2 =
      2 * ((sqrtTwoOrbit (2 * n + 1)).2 : ℤ) ^ 2 by linarith)

/-- Squaring the `sqrt 2` orbit gives exactly the existing `sqrt 8` Pell
orbit. -/
theorem pellOrbit_eq_sqrtTwo_square (n : ℕ) :
    pellOrbit n =
      ((sqrtTwoOrbit n).1 ^ 2 + 2 * (sqrtTwoOrbit n).2 ^ 2,
        (sqrtTwoOrbit n).1 * (sqrtTwoOrbit n).2) := by
  induction n with
  | zero => norm_num [pellOrbit, sqrtTwoOrbit]
  | succ n ih =>
      rw [pellOrbit_succ, sqrtTwoOrbit_succ, ih]
      apply Prod.ext <;> dsimp <;> ring

/-- At even index the lower adjacent factor is twice a square and the upper
factor is a square. -/
theorem even_adjacent_square_shapes (n : ℕ) :
    let A := (sqrtTwoOrbit (2 * n)).1
    let B := (sqrtTwoOrbit (2 * n)).2
    (pellOrbit (2 * n)).1 = 2 * (2 * B ^ 2) + 1 ∧
      A ^ 2 = 2 * B ^ 2 + 1 := by
  dsimp only
  have horbit := congrArg Prod.fst (pellOrbit_eq_sqrtTwo_square (2 * n))
  have hnorm := sqrtTwoOrbit_norm_even n
  constructor <;> nlinarith

/-- At odd index the lower adjacent factor is a square and the upper factor
is twice a square. -/
theorem odd_adjacent_square_shapes (n : ℕ) :
    let A := (sqrtTwoOrbit (2 * n + 1)).1
    let B := (sqrtTwoOrbit (2 * n + 1)).2
    (pellOrbit (2 * n + 1)).1 = 2 * A ^ 2 + 1 ∧
      2 * B ^ 2 = A ^ 2 + 1 := by
  dsimp only
  have horbit := congrArg Prod.fst
    (pellOrbit_eq_sqrtTwo_square (2 * n + 1))
  have hnorm := sqrtTwoOrbit_norm_odd n
  constructor <;> nlinarith

/-! ## Squarefullness of a coprime product -/

/-- A product of two nonzero `k`-full integers is `k`-full. -/
theorem isKFull_mul {k a b : ℕ} (ha : IsKFull k a) (hb : IsKFull k b) :
    IsKFull k (a * b) := by
  apply (IsKFull.iff_prime_pow_dvd (mul_ne_zero ha.ne_zero hb.ne_zero)).2
  intro p hp hpab
  rcases hp.dvd_mul.mp hpab with hpa | hpb
  · exact dvd_mul_of_dvd_left
      ((IsKFull.iff_prime_pow_dvd ha.ne_zero).1 ha p hp hpa) b
  · exact dvd_mul_of_dvd_right
      ((IsKFull.iff_prime_pow_dvd hb.ne_zero).1 hb p hp hpb) a

/-- For coprime nonzero factors, `k`-fullness of their product descends to
each factor. -/
theorem isKFull_factors_of_coprime_product
    {k a b : ℕ} (ha : a ≠ 0) (hb : b ≠ 0)
    (hcoprime : Nat.Coprime a b) (hab : IsKFull k (a * b)) :
    IsKFull k a ∧ IsKFull k b := by
  have hproduct :=
    (IsKFull.iff_prime_pow_dvd (mul_ne_zero ha hb)).1 hab
  constructor
  · apply (IsKFull.iff_prime_pow_dvd ha).2
    intro p hp hpa
    have hpk : p ^ k ∣ a * b :=
      hproduct p hp (dvd_mul_of_dvd_left hpa b)
    have hpcoprime : (p ^ k).Coprime b :=
      (Nat.Coprime.of_dvd_left hpa hcoprime).pow_left k
    exact hpcoprime.dvd_of_dvd_mul_right hpk
  · apply (IsKFull.iff_prime_pow_dvd hb).2
    intro p hp hpb
    have hpk : p ^ k ∣ a * b :=
      hproduct p hp (dvd_mul_of_dvd_right hpb a)
    have hpcoprime : (p ^ k).Coprime a :=
      (Nat.Coprime.of_dvd_left hpb hcoprime.symm).pow_left k
    exact hpcoprime.dvd_of_dvd_mul_left hpk

/-- The missing squarefull-root premise is exactly simultaneous
squarefullness of the two coprime square-root coordinates. -/
theorem pellOrbit_snd_twoFull_iff (n : ℕ) :
    IsKFull 2 (pellOrbit (n + 1)).2 ↔
      IsKFull 2 (sqrtTwoOrbit (n + 1)).1 ∧
        IsKFull 2 (sqrtTwoOrbit (n + 1)).2 := by
  have hA := sqrtTwoOrbit_fst_pos (n + 1)
  have hB := sqrtTwoOrbit_snd_pos_succ n
  have hcoprime := sqrtTwoOrbit_coprime (n + 1)
  rw [pellOrbit_eq_sqrtTwo_square]
  constructor
  · exact isKFull_factors_of_coprime_product hA.ne' hB.ne'
      hcoprime
  · rintro ⟨ha, hb⟩
    exact isKFull_mul ha hb

#print axioms sqrtTwoOrbit_coprime
#print axioms sqrtTwoOrbit_norm
#print axioms pellOrbit_eq_sqrtTwo_square
#print axioms even_adjacent_square_shapes
#print axioms odd_adjacent_square_shapes
#print axioms isKFull_mul
#print axioms isKFull_factors_of_coprime_product
#print axioms pellOrbit_snd_twoFull_iff

end

end PellSquareRootDescent20260831
end IUTThreeClosures
