/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.GeneratedOutputHullEnvelope

/-!
# Possible-image coverage from generators

The full collection of possible images should not be represented by an
unrelated output type with an arbitrary realization map.  It is generated from
an ordinary branch by the three indeterminacy operations.  This module records
that closure directly.

A possible-image expression is a finite word in Ind1, Ind2 and Ind3 applied to
an ordinary output.  If an explicit hull envelope contains every ordinary
output and each generator preserves containment in that envelope, then every
possible image lies in the envelope.  The public theta-hull containment then
follows from `GeneratedOutputHullEnvelope.thetaHull_le_envelope`.

This theorem separates two issues cleanly:

* formal closure under arbitrary finite compositions is proved here;
* the genuine IUT source theorem must identify its ordinary images and prove
  preservation of the explicit envelope by each actual Ind1/Ind2/Ind3
  generator.

No final component estimate, volume, height inequality or abc statement is an
input.
-/

namespace IUTThreeClosures

universe u v w x

/-- Formal words generated by the three possible-image indeterminacies. -/
inductive PossibleImageWord
    (Ordinary : Type u) (Ind1 : Type v) (Ind2 : Type w) (Ind3 : Type x) :
    Type (max u v w x)
  | ordinary : Ordinary → PossibleImageWord Ordinary Ind1 Ind2 Ind3
  | ind1 : Ind1 → PossibleImageWord Ordinary Ind1 Ind2 Ind3 →
      PossibleImageWord Ordinary Ind1 Ind2 Ind3
  | ind2 : Ind2 → PossibleImageWord Ordinary Ind1 Ind2 Ind3 →
      PossibleImageWord Ordinary Ind1 Ind2 Ind3
  | ind3 : Ind3 → PossibleImageWord Ordinary Ind1 Ind2 Ind3 →
      PossibleImageWord Ordinary Ind1 Ind2 Ind3

namespace PossibleImageWord

variable {Ordinary : Type u} {Ind1 : Type v} {Ind2 : Type w} {Ind3 : Type x}
variable {α : Type*}

/-- Realize a possible-image word by recursively applying the three region
transformations to an ordinary region. -/
def realize
    (ordinaryRegion : Ordinary → Set α)
    (act1 : Ind1 → Set α → Set α)
    (act2 : Ind2 → Set α → Set α)
    (act3 : Ind3 → Set α → Set α) :
    PossibleImageWord Ordinary Ind1 Ind2 Ind3 → Set α
  | .ordinary o => ordinaryRegion o
  | .ind1 a W => act1 a (W.realize ordinaryRegion act1 act2 act3)
  | .ind2 a W => act2 a (W.realize ordinaryRegion act1 act2 act3)
  | .ind3 a W => act3 a (W.realize ordinaryRegion act1 act2 act3)

/-- Generator-by-generator preservation proves coverage for every finite
possible-image word. -/
theorem realize_subset_envelope
    (ordinaryRegion : Ordinary → Set α)
    (act1 : Ind1 → Set α → Set α)
    (act2 : Ind2 → Set α → Set α)
    (act3 : Ind3 → Set α → Set α)
    (envelope : Set α)
    (hordinary : ∀ o, ordinaryRegion o ⊆ envelope)
    (h1 : ∀ a U, U ⊆ envelope → act1 a U ⊆ envelope)
    (h2 : ∀ a U, U ⊆ envelope → act2 a U ⊆ envelope)
    (h3 : ∀ a U, U ⊆ envelope → act3 a U ⊆ envelope) :
    ∀ W : PossibleImageWord Ordinary Ind1 Ind2 Ind3,
      W.realize ordinaryRegion act1 act2 act3 ⊆ envelope := by
  intro W
  induction W with
  | ordinary o => exact hordinary o
  | ind1 a W ih => exact h1 a _ ih
  | ind2 a W ih => exact h2 a _ ih
  | ind3 a W ih => exact h3 a _ ih

/-- The union of all finitely generated possible images is contained in the
same envelope. -/
theorem union_realize_subset_envelope
    (ordinaryRegion : Ordinary → Set α)
    (act1 : Ind1 → Set α → Set α)
    (act2 : Ind2 → Set α → Set α)
    (act3 : Ind3 → Set α → Set α)
    (envelope : Set α)
    (hordinary : ∀ o, ordinaryRegion o ⊆ envelope)
    (h1 : ∀ a U, U ⊆ envelope → act1 a U ⊆ envelope)
    (h2 : ∀ a U, U ⊆ envelope → act2 a U ⊆ envelope)
    (h3 : ∀ a U, U ⊆ envelope → act3 a U ⊆ envelope) :
    (⋃ W : PossibleImageWord Ordinary Ind1 Ind2 Ind3,
      W.realize ordinaryRegion act1 act2 act3) ⊆ envelope := by
  intro y hy
  rcases Set.mem_iUnion.mp hy with ⟨W, hy⟩
  exact realize_subset_envelope ordinaryRegion act1 act2 act3 envelope
    hordinary h1 h2 h3 W hy

end PossibleImageWord

end IUTThreeClosures
