/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.PossibleImageGeneratorClosure

/-!
# Native-image inclusion and multiradial-envelope containment

The source-level relation needed by the honest Corollary 3.12 route has two
logically distinct parts:

1. the distinguished native q-pilot branch is one of the actual possible
   images;
2. every possible image generated by the three indeterminacies is contained in
   one explicit multiradial envelope.

The published IUT III source uses isomorphism/reindexing for Ind1 and Ind2 and
upper semi-compatibility for Ind3.  It therefore does not require a global
classification of every possible image as one exact q-power word.  This module
records the correct generator presentation and proves the two set-theoretic
consequences once and for all.

No volume, coefficient, height inequality, initial-theta existence theorem or
abc statement is a field of this structure.  To apply the theorem to genuine
IUT objects one must still construct the ordinary images and the actual Ind1,
Ind2 and Ind3 region transformations and prove the four displayed envelope
properties.
-/

namespace IUTThreeClosures

universe u v w x y

/-- A source presentation of a possible-image family by one ordinary family
and the three actual indeterminacy operations. -/
structure PresentedPossibleImageSystem (α : Type y) :
    Type (max (u + 1) (v + 1) (w + 1) (x + 1) (y + 1)) where
  /-- Ordinary theta-pilot branches before the three indeterminacies. -/
  Ordinary : Type u
  /-- Ind1 operations, e.g. procession isomorphisms/reindexings. -/
  Ind1 : Type v
  /-- Ind2 operations, e.g. local spectral-factor automorphisms. -/
  Ind2 : Type w
  /-- Ind3 operations, used only through upper semi-compatible region maps. -/
  Ind3 : Type x
  /-- Region of an ordinary branch. -/
  ordinaryRegion : Ordinary → Set α
  /-- Region transformation induced by Ind1. -/
  act1 : Ind1 → Set α → Set α
  /-- Region transformation induced by Ind2. -/
  act2 : Ind2 → Set α → Set α
  /-- Region transformation induced by Ind3. -/
  act3 : Ind3 → Set α → Set α
  /-- The distinguished native q-pilot ordinary branch. -/
  native : Ordinary
  /-- The explicit multiradial envelope used for the component upper bound. -/
  envelope : Set α
  /-- Every ordinary branch is contained in the explicit envelope. -/
  ordinary_le_envelope : ∀ o, ordinaryRegion o ⊆ envelope
  /-- Ind1 preserves containment in the envelope. -/
  ind1_preserves_envelope :
    ∀ a U, U ⊆ envelope → act1 a U ⊆ envelope
  /-- Ind2 preserves containment in the envelope. -/
  ind2_preserves_envelope :
    ∀ a U, U ⊆ envelope → act2 a U ⊆ envelope
  /-- Ind3 is upper semi-compatible with the envelope. -/
  ind3_preserves_envelope :
    ∀ a U, U ⊆ envelope → act3 a U ⊆ envelope

namespace PresentedPossibleImageSystem

variable {α : Type y}

/-- The actual output type presented by arbitrary finite compositions of the
three source indeterminacies. -/
abbrev Output
    (S : PresentedPossibleImageSystem.{u, v, w, x, y} α) :=
  PossibleImageWord S.Ordinary S.Ind1 S.Ind2 S.Ind3

/-- Region realized by a presented possible image. -/
def realization
    (S : PresentedPossibleImageSystem.{u, v, w, x, y} α)
    (o : S.Output) : Set α :=
  o.realize S.ordinaryRegion S.act1 S.act2 S.act3

/-- Literal union of all presented possible-image regions. -/
def possibleUnion
    (S : PresentedPossibleImageSystem.{u, v, w, x, y} α) : Set α :=
  ⋃ o : S.Output, S.realization o

/-- Region of the distinguished native q-pilot branch. -/
def nativeRegion
    (S : PresentedPossibleImageSystem.{u, v, w, x, y} α) : Set α :=
  S.ordinaryRegion S.native

/-- The native q-pilot image belongs to the actual possible-image union.

This is the exact source statement needed for the lower-bound half of the
honest Corollary 3.12 argument. -/
theorem actualNativeImage
    (S : PresentedPossibleImageSystem.{u, v, w, x, y} α) :
    S.nativeRegion ⊆ S.possibleUnion := by
  intro z hz
  change z ∈ ⋃ o : S.Output, S.realization o
  exact Set.mem_iUnion.mpr
    ⟨PossibleImageWord.ordinary S.native, hz⟩

/-- Every finitely generated possible image is contained in the explicit
multiradial envelope. -/
theorem realization_le_envelope
    (S : PresentedPossibleImageSystem.{u, v, w, x, y} α)
    (o : S.Output) :
    S.realization o ⊆ S.envelope := by
  exact PossibleImageWord.realize_subset_envelope
    S.ordinaryRegion S.act1 S.act2 S.act3 S.envelope
    S.ordinary_le_envelope S.ind1_preserves_envelope
    S.ind2_preserves_envelope S.ind3_preserves_envelope o

/-- The literal union of all actual presented possible images lies in the
explicit multiradial envelope.

This is the source statement needed before applying local Haar/radial volume
upper bounds in IUT IV. -/
theorem actualPossibleImageEnvelope
    (S : PresentedPossibleImageSystem.{u, v, w, x, y} α) :
    S.possibleUnion ⊆ S.envelope := by
  exact PossibleImageWord.union_realize_subset_envelope
    S.ordinaryRegion S.act1 S.act2 S.act3 S.envelope
    S.ordinary_le_envelope S.ind1_preserves_envelope
    S.ind2_preserves_envelope S.ind3_preserves_envelope

/-- The two source relations packaged together. -/
theorem sourceRelations
    (S : PresentedPossibleImageSystem.{u, v, w, x, y} α) :
    S.nativeRegion ⊆ S.possibleUnion ∧
      S.possibleUnion ⊆ S.envelope :=
  ⟨S.actualNativeImage, S.actualPossibleImageEnvelope⟩

end PresentedPossibleImageSystem

end IUTThreeClosures
