/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.SL2ImageClosure

/-!
# One nonzero transvection generates a full root subgroup over `ZMod ell`

Over the prime field `ZMod ell`, the additive group is generated by `1`.  More
generally, multiplication by any nonzero scalar is bijective.  Hence powers of
one nontrivial upper or lower transvection generate the entire corresponding
root subgroup.

This module proves that fact directly in the explicit two-by-two matrix model.
Combined with `TransvectionConjugation`, one Tate-inertia transvection and one
image element moving its fixed line produce a nonzero opposite transvection.
The present theorem then yields all upper and lower transvections, and
`SL2ImageClosure` yields containment of every determinant-one matrix.
-/

namespace IUTThreeClosures

namespace SL2ElementaryGeneration
namespace Mat2

/-- Multiplication of upper transvections adds their parameters. -/
theorem upper_mul_upper
    {F : Type*} [Field F]
    (a b : F) :
    mul (upper a) (upper b) = upper (a + b) := by
  ext <;> simp [mul, upper]

/-- Multiplication of lower transvections adds their parameters. -/
theorem lower_mul_lower
    {F : Type*} [Field F]
    (a b : F) :
    mul (lower a) (lower b) = lower (a + b) := by
  ext <;> simp [mul, lower]

/-- A multiplicatively closed matrix set containing `lower 0` and `lower s`
contains every natural multiple of `s`. -/
theorem lower_natCast_mul_mem
    {F : Type*} [Field F]
    {S : Set (Mat2 F)}
    (hmul : ∀ {A B : Mat2 F}, A ∈ S → B ∈ S → mul A B ∈ S)
    {s : F}
    (hzero : lower 0 ∈ S)
    (hs : lower s ∈ S)
    (n : ℕ) :
    lower ((n : F) * s) ∈ S := by
  induction n with
  | zero => simpa using hzero
  | succ n ih =>
      have hprod := hmul ih hs
      rw [lower_mul_lower] at hprod
      convert hprod using 1
      push_cast
      ring

/-- The analogous statement for upper transvections. -/
theorem upper_natCast_mul_mem
    {F : Type*} [Field F]
    {S : Set (Mat2 F)}
    (hmul : ∀ {A B : Mat2 F}, A ∈ S → B ∈ S → mul A B ∈ S)
    {s : F}
    (hzero : upper 0 ∈ S)
    (hs : upper s ∈ S)
    (n : ℕ) :
    upper ((n : F) * s) ∈ S := by
  induction n with
  | zero => simpa using hzero
  | succ n ih =>
      have hprod := hmul ih hs
      rw [upper_mul_upper] at hprod
      convert hprod using 1
      push_cast
      ring

/-- Over a prime field, one nonzero lower transvection generates the entire
lower root subgroup. -/
theorem all_lower_mem_of_one_nonzero
    {ell : ℕ}
    [Fact ell.Prime]
    {S : Set (Mat2 (ZMod ell))}
    (hmul :
      ∀ {A B : Mat2 (ZMod ell)}, A ∈ S → B ∈ S → mul A B ∈ S)
    (hzero : lower 0 ∈ S)
    {s : ZMod ell}
    (hs_ne : s ≠ 0)
    (hs : lower s ∈ S) :
    ∀ t : ZMod ell, lower t ∈ S := by
  intro t
  let q : ZMod ell := t / s
  have hqcast : (q.val : ZMod ell) = q :=
    ZMod.natCast_zmod_val q
  have hmem := lower_natCast_mul_mem
    hmul hzero hs q.val
  have hparam : (q.val : ZMod ell) * s = t := by
    rw [hqcast]
    exact div_mul_cancel₀ t hs_ne
  simpa [hparam] using hmem

/-- Over a prime field, one nonzero upper transvection generates the entire
upper root subgroup. -/
theorem all_upper_mem_of_one_nonzero
    {ell : ℕ}
    [Fact ell.Prime]
    {S : Set (Mat2 (ZMod ell))}
    (hmul :
      ∀ {A B : Mat2 (ZMod ell)}, A ∈ S → B ∈ S → mul A B ∈ S)
    (hzero : upper 0 ∈ S)
    {s : ZMod ell}
    (hs_ne : s ≠ 0)
    (hs : upper s ∈ S) :
    ∀ t : ZMod ell, upper t ∈ S := by
  intro t
  let q : ZMod ell := t / s
  have hqcast : (q.val : ZMod ell) = q :=
    ZMod.natCast_zmod_val q
  have hmem := upper_natCast_mul_mem
    hmul hzero hs q.val
  have hparam : (q.val : ZMod ell) * s = t := by
    rw [hqcast]
    exact div_mul_cancel₀ t hs_ne
  simpa [hparam] using hmem

/-- One nonzero transvection in each opposite root subgroup forces containment
of every determinant-one matrix over the prime field. -/
theorem detOne_mem_of_two_nonzero_transvections
    {ell : ℕ}
    [Fact ell.Prime]
    {S : Set (Mat2 (ZMod ell))}
    (hmul :
      ∀ {A B : Mat2 (ZMod ell)}, A ∈ S → B ∈ S → mul A B ∈ S)
    (hupperZero : upper 0 ∈ S)
    (hlowerZero : lower 0 ∈ S)
    {u l : ZMod ell}
    (hu_ne : u ≠ 0)
    (hl_ne : l ≠ 0)
    (hu : upper u ∈ S)
    (hl : lower l ∈ S)
    (A : Mat2 (ZMod ell))
    (hdet : det A = 1) :
    A ∈ S := by
  have hupper := all_upper_mem_of_one_nonzero
    hmul hupperZero hu_ne hu
  have hlower := all_lower_mem_of_one_nonzero
    hmul hlowerZero hl_ne hl
  exact detOne_mem_of_contains_transvections
    hupper hlower hmul A hdet

end Mat2
end SL2ElementaryGeneration

end IUTThreeClosures
