/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.RadialIntegerActionLocalSlices

/-!
# The topological orbit quotient of a radial integer action

For a radial integer action, define the orbit equivalence relation and its
quotient topology.  The explicit width-`1/3` slices from the preceding module
have two decisive properties:

* the quotient projection is injective on each slice;
* the image of each slice is open in the quotient.

Thus the orbit quotient has explicit local charts obtained from the source
space.  This is the ordinary topological quotient theorem needed before a
Berkovich/analytic enhancement is attempted.
-/

namespace IUTThreeClosures

namespace RadialIntegerAction

variable {X : Type*} [TopologicalSpace X]
variable (A : RadialIntegerAction X)

/-- Every integer translate is a homeomorphism. -/
noncomputable def translateHomeomorph (n : ℤ) : X ≃ₜ X where
  toFun := A.act n
  invFun := A.act (-n)
  left_inv x := A.act_neg_cancel n x
  right_inv x := by
    rw [← A.act_add, add_neg_cancel, A.act_zero]
  continuous_toFun := A.continuous_act n
  continuous_invFun := A.continuous_act (-n)

/-- The orbit equivalence relation generated by the integer action. -/
def orbitSetoid : Setoid X where
  r x y := ∃ n : ℤ, A.act n x = y
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro x
      exact ⟨0, A.act_zero x⟩
    · intro x y hxy
      rcases hxy with ⟨n, hn⟩
      refine ⟨-n, ?_⟩
      calc
        A.act (-n) y = A.act (-n) (A.act n x) := by rw [hn]
        _ = x := A.act_neg_cancel n x
    · intro x y z hxy hyz
      rcases hxy with ⟨n, hn⟩
      rcases hyz with ⟨m, hm⟩
      refine ⟨m + n, ?_⟩
      rw [A.act_add, hn, hm]

/-- The ordinary set-theoretic orbit quotient, equipped by Mathlib with the
coinduced quotient topology. -/
abbrev OrbitQuotient := Quotient A.orbitSetoid

/-- The canonical orbit projection. -/
def quotientMap : X → A.OrbitQuotient :=
  Quotient.mk'

/-- The orbit projection is continuous by construction of the quotient
topology. -/
theorem continuous_quotientMap : Continuous A.quotientMap :=
  continuous_coinduced_rng

/-- Saturation of a subset under all integer translates. -/
def saturation (s : Set X) : Set X :=
  ⋃ n : ℤ, A.act n '' s

/-- The saturation of an open set is open. -/
theorem isOpen_saturation {s : Set X} (hs : IsOpen s) :
    IsOpen (A.saturation s) := by
  apply isOpen_iUnion
  intro n
  exact (A.translateHomeomorph n).isOpenMap s hs

/-- The inverse image of a quotient image is exactly the orbit saturation. -/
theorem preimage_image_quotientMap (s : Set X) :
    A.quotientMap ⁻¹' (A.quotientMap '' s) = A.saturation s := by
  ext z
  constructor
  · intro hz
    rcases hz with ⟨y, hy, hqy⟩
    have hrel : A.orbitSetoid.Rel z y := Quotient.exact hqy
    rcases hrel with ⟨n, hn⟩
    refine Set.mem_iUnion.2 ⟨-n, ?_⟩
    refine ⟨y, hy, ?_⟩
    calc
      A.act (-n) y = A.act (-n) (A.act n z) := by rw [hn]
      _ = z := A.act_neg_cancel n z
  · intro hz
    rcases Set.mem_iUnion.1 hz with ⟨n, hn⟩
    rcases hn with ⟨y, hy, rfl⟩
    refine ⟨y, hy, ?_⟩
    exact Quotient.sound ⟨n, rfl⟩ |>.symm

/-- The quotient projection is injective on every canonical radial slice. -/
theorem quotientMap_injOn_slice (x : X) :
    Set.InjOn A.quotientMap (A.slice x) := by
  intro y hy z hz hq
  have hrel : A.orbitSetoid.Rel y z := Quotient.exact hq
  rcases hrel with ⟨n, hn⟩
  have hny : A.act n y ∈ A.slice x := by
    rw [hn]
    exact hz
  have hfixed : A.act n y = y :=
    A.act_eq_of_mem_slice x y n hy hny
  exact hfixed.symm.trans hn

/-- The image of every canonical radial slice is open in the quotient. -/
theorem isOpen_quotientMap_image_slice (x : X) :
    IsOpen (A.quotientMap '' A.slice x) := by
  change IsOpen
    (A.quotientMap ⁻¹' (A.quotientMap '' A.slice x))
  rw [A.preimage_image_quotientMap]
  exact A.isOpen_saturation (A.isOpen_slice x)

/-- Every quotient point has an open neighborhood represented injectively by
an open source slice. -/
theorem quotient_has_open_injective_chart
    (q : A.OrbitQuotient) :
    ∃ x : X,
      A.quotientMap x = q ∧
      IsOpen (A.slice x) ∧
      x ∈ A.slice x ∧
      Set.InjOn A.quotientMap (A.slice x) ∧
      IsOpen (A.quotientMap '' A.slice x) := by
  refine Quotient.inductionOn q ?_
  intro x
  exact ⟨x, rfl, A.isOpen_slice x, A.mem_slice_self x,
    A.quotientMap_injOn_slice x,
    A.isOpen_quotientMap_image_slice x⟩

end RadialIntegerAction

end IUTThreeClosures
