import IUTThreeClosures.RepeatedLabelProcessionOvercount

#print axioms IUTThreeClosures.product_weight_additive_marginal
#print axioms IUTThreeClosures.product_weight_separable_additive_marginal
#print axioms Iut.PrimePowerQPilotRegion.packetVol_additiveLabelOrders
#print axioms Iut.PrimePowerQPilotRegion.packetVol_scaledLabelOrders
#print axioms
  IUTThreeClosures.RepeatedLabelProcessionOvercount.repeatedLabelSquareMass_formula
#print axioms
  IUTThreeClosures.RepeatedLabelProcessionOvercount.distinguishedIncrementSquareMass_eq_terminalCapsuleSquareMass
#print axioms
  IUTThreeClosures.RepeatedLabelProcessionOvercount.repeatedLabelAverageCoefficient_sub_distinguished
#print axioms
  IUTThreeClosures.RepeatedLabelProcessionOvercount.repeatedLabelProcessionAverage_eq_processionAverage_iff
#print axioms
  IUTThreeClosures.RepeatedLabelProcessionOvercount.repeatedLabelProcessionAverage_lt_processionAverage
