/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.ABCMixedFullCampana20260831
import IUTThreeClosures.FreyIsogenyConductorSharpness20260831
import IUTThreeClosures.IUTFiniteProductProjectionSpan20260831
import IUTThreeClosures.ABCThreePrimeSignatures20260831
import IUTThreeClosures.ABCSubcriticalLocusUniformity20260831
import IUTThreeClosures.PellCampanaCounterexample20260831

/-! Declaration types and kernel dependencies for the dual-route
continuation. This file supplies no proof of ABCConjecture or its negation. -/

set_option linter.style.longLine false

#print IUTThreeClosures.ABCConjecture

-- ABCMixedFullCampana20260831
#check IUTThreeClosures.ABCMixedFullCampana20260831.mixedFullSlope_nonneg
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.mixedFullSlope_nonneg
#check IUTThreeClosures.ABCMixedFullCampana20260831.mixedFullSlope_eq_pairSum_div_product
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.mixedFullSlope_eq_pairSum_div_product
#check IUTThreeClosures.ABCMixedFullCampana20260831.mixedFullSlope_lt_one_iff_pairSum_lt_product
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.mixedFullSlope_lt_one_iff_pairSum_lt_product
#check IUTThreeClosures.ABCMixedFullCampana20260831.radical_pow_pqr_le_c_pow_pairSum
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.radical_pow_pqr_le_c_pow_pairSum
#check IUTThreeClosures.ABCMixedFullCampana20260831.conductor_le_mixedFullSlope_mul_height
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.conductor_le_mixedFullSlope_mul_height
#check IUTThreeClosures.ABCMixedFullCampana20260831.exists_positive_epsilon_of_mixedFullSlope_lt_one
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.exists_positive_epsilon_of_mixedFullSlope_lt_one
#check IUTThreeClosures.ABCMixedFullCampana20260831.abcConjecture_implies_mixedFull_height_bound
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.abcConjecture_implies_mixedFull_height_bound
#check IUTThreeClosures.ABCMixedFullCampana20260831.not_abcConjecture_of_unbounded_mixedFull_family
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.not_abcConjecture_of_unbounded_mixedFull_family
#check IUTThreeClosures.ABCMixedFullCampana20260831.mixedFullSlope
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.mixedFullSlope
#check IUTThreeClosures.ABCMixedFullCampana20260831.MixedFull
#print axioms IUTThreeClosures.ABCMixedFullCampana20260831.MixedFull

-- FreyIsogenyConductorSharpness20260831
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpointC_eq_two_halfEndpointNat
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpointC_eq_two_halfEndpointNat
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.oddEndpoint_eq_two_half_sub_one
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.oddEndpoint_eq_two_half_sub_one
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpointC_sub_one_eq_oddEndpoint
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpointC_sub_one_eq_oddEndpoint
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.halfEndpointNat_pos
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.halfEndpointNat_pos
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.oddEndpoint_pos
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.oddEndpoint_pos
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.two_coprime_halfEndpointNat
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.two_coprime_halfEndpointNat
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.two_half_coprime_oddEndpoint
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.two_half_coprime_oddEndpoint
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.half_coprime_oddEndpoint
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.half_coprime_oddEndpoint
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.oddEndpoint_coprime_half
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.oddEndpoint_coprime_half
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.radical_two
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.radical_two
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.minimumJDenominator_radical
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.minimumJDenominator_radical
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpoint_radical_eq_two_minimum_denominator_radical
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpoint_radical_eq_two_minimum_denominator_radical
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.reducedDenominator_zeroKernel_eq_minimumJDenominator
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.reducedDenominator_zeroKernel_eq_minimumJDenominator
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.familyCurve_zeroKernel_den
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.familyCurve_zeroKernel_den
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpoint_radical_eq_two_actual_j_den_radical
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpoint_radical_eq_two_actual_j_den_radical
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerIndex_mul_896
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerIndex_mul_896
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpointC_powerIndex
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.endpointC_powerIndex
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerIndex_pos
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerIndex_pos
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.radical_897
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.radical_897
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.radical_897_pow
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.radical_897_pow
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerEndpoint_coprime_odd
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerEndpoint_coprime_odd
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.two_coprime_897_pow
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.two_coprime_897_pow
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerEndpoint_radical
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerEndpoint_radical
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.power_conductorProxy
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.power_conductorProxy
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.power_conductorProxy_lt
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.power_conductorProxy_lt
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerEndpoint_log
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerEndpoint_log
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerFamily_subcritical_gap
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerFamily_subcritical_gap
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.exists_powerFamily_gap_gt
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.exists_powerFamily_gap_gt
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.halfEndpointNat
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.halfEndpointNat
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.oddEndpoint
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.oddEndpoint
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.minimumJDenominator
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.minimumJDenominator
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.conductorProxy
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.conductorProxy
#check IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerIndex
#print axioms IUTThreeClosures.FreyIsogenyConductorSharpness20260831.powerIndex

-- IUTFiniteProductProjectionSpan20260831
#check IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.mem_coordinateSpan_of_mem_productSpan
#print axioms IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.mem_coordinateSpan_of_mem_productSpan
#check IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.mem_productSpan_of_forall_mem_coordinateSpan
#print axioms IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.mem_productSpan_of_forall_mem_coordinateSpan
#check IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.mem_productSpan_iff
#print axioms IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.mem_productSpan_iff
#check IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.mem_productSpan_of_mem_coordinateProduct
#print axioms IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.mem_productSpan_of_mem_coordinateProduct
#check IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.finite_weighted_sum_mono
#print axioms IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.finite_weighted_sum_mono
#check IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.coordinateSpan
#print axioms IUTThreeClosures.IUTFiniteProductProjectionSpan20260831.coordinateSpan

-- ABCThreePrimeSignatures20260831
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.left_eq_one_of_mul_eq_prime_sq_of_lt
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.left_eq_one_of_mul_eq_prime_sq_of_lt
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.factors_eq_of_mul_eq_prime_sq
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.factors_eq_of_mul_eq_prime_sq
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.prime_not_square
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.prime_not_square
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.consecutive_primes
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.consecutive_primes
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.prime_sq_eq_prime_add_one
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.prime_sq_eq_prime_add_one
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.prime_sq_add_one_eq_prime
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.prime_sq_add_one_eq_prime
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.square_add_cube_ne_cube
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.square_add_cube_ne_cube
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.cube_add_cube_ne_prime_square_of_gt_one
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.cube_add_cube_ne_prime_square_of_gt_one
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.cube_add_cube_ne_square
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.cube_add_cube_ne_square
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.square_add_cube_ne_sixth
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.square_add_cube_ne_sixth
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.square_add_sixth_ne_cube
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.square_add_sixth_ne_cube
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.cube_add_sixth_ne_square
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.cube_add_sixth_ne_square
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.no_prime_signature_233
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.no_prime_signature_233
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.no_prime_signature_236_output_sixth
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.no_prime_signature_236_output_sixth
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.no_prime_signature_236_output_cube
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.no_prime_signature_236_output_cube
#check IUTThreeClosures.ABCThreePrimeSignatures20260831.no_prime_signature_236_output_square
#print axioms IUTThreeClosures.ABCThreePrimeSignatures20260831.no_prime_signature_236_output_square

-- ABCSubcriticalLocusUniformity20260831
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.subcriticalLociHaveBoundedHeight_of_abcConjecture
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.subcriticalLociHaveBoundedHeight_of_abcConjecture
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.abcConjecture_of_subcriticalLociHaveBoundedHeight
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.abcConjecture_of_subcriticalLociHaveBoundedHeight
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.abcConjecture_iff_subcriticalLociHaveBoundedHeight
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.abcConjecture_iff_subcriticalLociHaveBoundedHeight
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.finset_eq_empty_of_card_cast_lt_one
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.finset_eq_empty_of_card_cast_lt_one
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.pointwise_fiber_card_le_target
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.pointwise_fiber_card_le_target
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.sources_eq_empty_of_pointwise_oversized_fiber
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.sources_eq_empty_of_pointwise_oversized_fiber
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.height_le_of_amplification_log_count
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.height_le_of_amplification_log_count
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseHeight_succ
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseHeight_succ
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseHeight_strictMono
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseHeight_strictMono
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.mem_superSparseIndicesUpTo
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.mem_superSparseIndicesUpTo
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseIndicesUpTo_card_le_log_log
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseIndicesUpTo_card_le_log_log
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.index_succ_sq_le_superSparseHeight
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.index_succ_sq_le_superSparseHeight
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseIndicesUpTo_card_sq_le
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseIndicesUpTo_card_sq_le
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparsePrefix_card
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparsePrefix_card
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparsePrefix_le_final
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparsePrefix_le_final
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparsePrefix_card_unbounded
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparsePrefix_card_unbounded
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.SubcriticalLociHaveBoundedHeight
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.SubcriticalLociHaveBoundedHeight
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseHeight
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseHeight
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseIndicesUpTo
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparseIndicesUpTo
#check IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparsePrefix
#print axioms IUTThreeClosures.ABCSubcriticalLocusUniformity20260831.superSparsePrefix

-- PellCampanaCounterexample20260831
#check IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_zero
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_zero
#check IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_succ
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_succ
#check IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_norm
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_norm
#check IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_fst_pos
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_fst_pos
#check IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_snd_lt_snd_succ
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_snd_lt_snd_succ
#check IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_index_le_snd
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_index_le_snd
#check IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_snd_lt_fst_succ
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_snd_lt_fst_succ
#check IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_fst_unbounded
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit_fst_unbounded
#check IUTThreeClosures.PellCampanaCounterexample20260831.one_isKFull
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.one_isKFull
#check IUTThreeClosures.PellCampanaCounterexample20260831.power_isKFull
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.power_isKFull
#check IUTThreeClosures.PellCampanaCounterexample20260831.eight_mul_sq_isTwoFull
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.eight_mul_sq_isTwoFull
#check IUTThreeClosures.PellCampanaCounterexample20260831.eight_mul_sq_isThreeFull
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.eight_mul_sq_isThreeFull
#check IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point_a
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point_a
#check IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point_b
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point_b
#check IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point_c
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point_c
#check IUTThreeClosures.PellCampanaCounterexample20260831.Datum.a_sevenFull
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.Datum.a_sevenFull
#check IUTThreeClosures.PellCampanaCounterexample20260831.Datum.b_threeFull
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.Datum.b_threeFull
#check IUTThreeClosures.PellCampanaCounterexample20260831.Datum.c_twoFull
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.Datum.c_twoFull
#check IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point_mixedFull
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point_mixedFull
#check IUTThreeClosures.PellCampanaCounterexample20260831.signature_732_subcritical
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.signature_732_subcritical
#check IUTThreeClosures.PellCampanaCounterexample20260831.not_abcConjecture_of_unbounded_squarefullPell_family
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.not_abcConjecture_of_unbounded_squarefullPell_family
#check IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.pellOrbit
#check IUTThreeClosures.PellCampanaCounterexample20260831.Datum
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.Datum
#check IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point
#print axioms IUTThreeClosures.PellCampanaCounterexample20260831.Datum.point

