/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.PellAdjacentFactorCounterexample20260831
import IUTThreeClosures.PellSquareRootDescent20260831
import IUTThreeClosures.HallSquarefullCounterexample20260831
import IUTThreeClosures.AffineShearAmplification20260831

/-! Declaration types and kernel dependencies for the balanced-persistence
continuation.  This audit supplies neither `ABCConjecture` nor its negation. -/

set_option linter.style.longLine false

#print IUTThreeClosures.ABCConjecture

-- PellAdjacentFactorCounterexample20260831
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.exists_pell_half_factors
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.exists_pell_half_factors
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.pell_half_factor_unique
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.pell_half_factor_unique
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.exists_datum_of_pellDatum
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.exists_datum_of_pellDatum
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_a
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_a
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_b
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_b
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_c
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_c
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_height
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_height
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_radical_sq_le_four_mul_c
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_radical_sq_le_four_mul_c
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_conductor_le_half_height_add_log_two
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.point_conductor_le_half_height_add_log_two
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.left_factor_isFourFull_of_even_twoFull
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.left_factor_isFourFull_of_even_twoFull
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.r_fourFull_of_even
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.r_fourFull_of_even
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.s_fourFull_of_even
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.Datum.s_fourFull_of_even
#check IUTThreeClosures.PellAdjacentFactorCounterexample20260831.not_abcConjecture_of_unbounded_adjacentPell_family
#print axioms IUTThreeClosures.PellAdjacentFactorCounterexample20260831.not_abcConjecture_of_unbounded_adjacentPell_family

-- PellSquareRootDescent20260831
#check IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit
#check IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_zero
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_zero
#check IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_succ
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_succ
#check IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_fst_pos
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_fst_pos
#check IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_snd_pos_succ
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_snd_pos_succ
#check IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_coprime
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_coprime
#check IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_norm
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_norm
#check IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_norm_even
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_norm_even
#check IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_norm_odd
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.sqrtTwoOrbit_norm_odd
#check IUTThreeClosures.PellSquareRootDescent20260831.pellOrbit_eq_sqrtTwo_square
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.pellOrbit_eq_sqrtTwo_square
#check IUTThreeClosures.PellSquareRootDescent20260831.even_adjacent_square_shapes
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.even_adjacent_square_shapes
#check IUTThreeClosures.PellSquareRootDescent20260831.odd_adjacent_square_shapes
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.odd_adjacent_square_shapes
#check IUTThreeClosures.PellSquareRootDescent20260831.isKFull_mul
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.isKFull_mul
#check IUTThreeClosures.PellSquareRootDescent20260831.isKFull_factors_of_coprime_product
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.isKFull_factors_of_coprime_product
#check IUTThreeClosures.PellSquareRootDescent20260831.pellOrbit_snd_twoFull_iff
#print axioms IUTThreeClosures.PellSquareRootDescent20260831.pellOrbit_snd_twoFull_iff

-- HallSquarefullCounterexample20260831
#check IUTThreeClosures.HallSquarefullCounterexample20260831.Datum
#print axioms IUTThreeClosures.HallSquarefullCounterexample20260831.Datum
#check IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point
#print axioms IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point
#check IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_a
#print axioms IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_a
#check IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_b
#print axioms IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_b
#check IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_c
#print axioms IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_c
#check IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_radical_le
#print axioms IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_radical_le
#check IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_radical_pow_twelve_lt_height_pow_eleven
#print axioms IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_radical_pow_twelve_lt_height_pow_eleven
#check IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_conductor_lt_eleven_twelfths_height
#print axioms IUTThreeClosures.HallSquarefullCounterexample20260831.Datum.point_conductor_lt_eleven_twelfths_height
#check IUTThreeClosures.HallSquarefullCounterexample20260831.not_abcConjecture_of_unbounded_Hall_squarefull_family
#print axioms IUTThreeClosures.HallSquarefullCounterexample20260831.not_abcConjecture_of_unbounded_Hall_squarefull_family

-- AffineShearAmplification20260831
#check IUTThreeClosures.AffineShearAmplification20260831.Seed
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.P
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.P
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.U
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.U
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.V
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.V
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.W
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.W
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.P_pos
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.P_pos
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.a_dvd_P
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.a_dvd_P
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.b_dvd_P
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.b_dvd_P
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.c_dvd_P
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.c_dvd_P
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.one_add_P_mul_coprime_P
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.one_add_P_mul_coprime_P
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.U_coprime_P
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.U_coprime_P
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.V_coprime_P
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.V_coprime_P
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.W_coprime_P
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.W_coprime_P
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.V_eq_U_add
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.V_eq_U_add
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.W_eq_U_add
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.W_eq_U_add
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.V_eq_W_add
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.V_eq_W_add
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.shear_equation
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.shear_equation
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.V_coprime_k
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.V_coprime_k
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.W_coprime_k
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.W_coprime_k
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.U_coprime_V
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.U_coprime_V
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.U_coprime_W
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.U_coprime_W
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.V_coprime_W
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.V_coprime_W
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.A
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.A
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.B
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.B
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.C
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.C
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.A_pos
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.A_pos
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.B_pos
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.B_pos
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.C_pos
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.C_pos
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.A_add_B_eq_C
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.A_add_B_eq_C
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.A_coprime_B
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.A_coprime_B
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.B_coprime_C
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.B_coprime_C
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.C_coprime_A
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.C_coprime_A
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.point
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.point
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.point_a
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.point_a
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.point_b
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.point_b
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.point_c
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.Parameter.point_c
#check IUTThreeClosures.AffineShearAmplification20260831.Seed.shear_parameter_injective
#print axioms IUTThreeClosures.AffineShearAmplification20260831.Seed.shear_parameter_injective
