/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import Mathlib

/-!
# Elementary generation of two-dimensional special linear matrices

The uniform large-image route reduces the finite-group input to a standard
fact: once the mod-`ell` image contains every upper and lower elementary
transvection, it contains `SL₂(F_ell)`.

To keep the proof independent of a particular matrix-group API, this module
uses an explicit four-coordinate model of a two-by-two matrix over a field.
It defines the predicate generated by arbitrary upper and lower unipotent
matrices and proves that every determinant-one matrix satisfies it.

The proof is constructive Gaussian elimination.

* If the upper-left entry `a` is nonzero, then

  `A = L(c/a) * diag(a,a⁻¹) * U(b/a)`.

* The diagonal matrix is itself elementary because

  `diag(t,t⁻¹) = w(t) * w(-1)`,

  where

  `w(t) = U(t) * L(-t⁻¹) * U(t)`.

* If `a = 0`, left multiplication by `w(1)` produces a matrix with nonzero
  upper-left entry; multiplication by `w(-1)` recovers the original matrix.

This avoids invoking the full Dickson classification.  In the Galois-image
application, the remaining group-theoretic task is to obtain all upper and
lower transvections from irreducibility and one Tate-inertia transvection over
the prime field.
-/

namespace IUTThreeClosures

universe u

namespace SL2ElementaryGeneration

/-- An explicit two-by-two matrix. -/
structure Mat2 (F : Type u) where
  a : F
  b : F
  c : F
  d : F
  deriving Repr

namespace Mat2

variable {F : Type u}

@[ext]
theorem ext {A B : Mat2 F}
    (ha : A.a = B.a)
    (hb : A.b = B.b)
    (hc : A.c = B.c)
    (hd : A.d = B.d) : A = B := by
  cases A
  cases B
  simp_all

variable [Field F]

/-- Matrix multiplication. -/
def mul (A B : Mat2 F) : Mat2 F where
  a := A.a * B.a + A.b * B.c
  b := A.a * B.b + A.b * B.d
  c := A.c * B.a + A.d * B.c
  d := A.c * B.b + A.d * B.d

/-- The determinant. -/
def det (A : Mat2 F) : F :=
  A.a * A.d - A.b * A.c

/-- Upper elementary transvection. -/
def upper (x : F) : Mat2 F where
  a := 1
  b := x
  c := 0
  d := 1

/-- Lower elementary transvection. -/
def lower (x : F) : Mat2 F where
  a := 1
  b := 0
  c := x
  d := 1

/-- The diagonal torus element `diag(t,t⁻¹)`. -/
def diagonal (t : F) : Mat2 F where
  a := t
  b := 0
  c := 0
  d := t⁻¹

/-- The Weyl element constructed from three elementary transvections. -/
def weyl (t : F) : Mat2 F :=
  mul (mul (upper t) (lower (-t⁻¹))) (upper t)

/-- Syntactic closure under multiplication of all upper and lower elementary
transvections. -/
inductive ElementaryGenerated : Mat2 F → Prop
  | upper (x : F) : ElementaryGenerated (upper x)
  | lower (x : F) : ElementaryGenerated (lower x)
  | mul {A B : Mat2 F} :
      ElementaryGenerated A →
      ElementaryGenerated B →
      ElementaryGenerated (mul A B)

namespace ElementaryGenerated

/-- Every Weyl element is elementary-generated. -/
theorem weyl (t : F) : ElementaryGenerated (Mat2.weyl t) := by
  exact .mul (.mul (.upper t) (.lower (-t⁻¹))) (.upper t)

end ElementaryGenerated

/-- Explicit formula for the Weyl element. -/
theorem weyl_eq (t : F) :
    weyl t =
      { a := 0, b := t, c := -t⁻¹, d := 0 } := by
  ext <;> simp [weyl, mul, upper, lower] <;> ring

/-- The diagonal torus is generated by elementary transvections. -/
theorem diagonal_elementaryGenerated
    {t : F} (ht : t ≠ 0) :
    ElementaryGenerated (diagonal t) := by
  have hw :
      ElementaryGenerated (mul (weyl t) (weyl (-1))) :=
    .mul (.weyl t) (.weyl (-1))
  have heq : mul (weyl t) (weyl (-1)) = diagonal t := by
    rw [weyl_eq, weyl_eq]
    ext <;> simp [mul, diagonal, ht] <;> field_simp [ht]
  rw [← heq]
  exact hw

/-- Gaussian decomposition when the upper-left entry is nonzero. -/
theorem gaussian_decomposition
    (A : Mat2 F)
    (ha : A.a ≠ 0)
    (hdet : det A = 1) :
    mul (mul (lower (A.c / A.a)) (diagonal A.a))
        (upper (A.b / A.a)) = A := by
  ext
  · simp [mul, lower, diagonal, upper, ha]
  · simp [mul, lower, diagonal, upper, ha]
  · simp [mul, lower, diagonal, upper, ha]
  · simp only [mul, lower, diagonal, upper]
    dsimp
    field_simp [ha]
    linear_combination hdet

/-- Every determinant-one matrix with nonzero upper-left entry is generated by
upper and lower transvections. -/
theorem elementaryGenerated_of_det_one_of_a_ne_zero
    (A : Mat2 F)
    (ha : A.a ≠ 0)
    (hdet : det A = 1) :
    ElementaryGenerated A := by
  have hgen :
      ElementaryGenerated
        (mul (mul (lower (A.c / A.a)) (diagonal A.a))
          (upper (A.b / A.a))) := by
    exact .mul
      (.mul (.lower (A.c / A.a))
        (diagonal_elementaryGenerated ha))
      (.upper (A.b / A.a))
  rw [gaussian_decomposition A ha hdet] at hgen
  exact hgen

/-- Left multiplication by `w(1)` exchanges the two rows up to sign. -/
theorem weyl_one_mul (A : Mat2 F) :
    mul (weyl 1) A =
      { a := A.c, b := A.d, c := -A.a, d := -A.b } := by
  rw [weyl_eq]
  ext <;> simp [mul]

/-- Multiplication by `w(-1)` reverses the preceding row exchange. -/
theorem weyl_neg_one_mul_weyl_one_mul (A : Mat2 F) :
    mul (weyl (-1)) (mul (weyl 1) A) = A := by
  rw [weyl_one_mul, weyl_eq]
  ext <;> simp [mul]

/-- The row-exchanged matrix preserves determinant. -/
theorem det_weyl_one_mul (A : Mat2 F) :
    det (mul (weyl 1) A) = det A := by
  rw [weyl_one_mul]
  simp [det]
  ring

/-- Every determinant-one two-by-two matrix is generated by upper and lower
transvections. -/
theorem elementaryGenerated_of_det_one
    (A : Mat2 F)
    (hdet : det A = 1) :
    ElementaryGenerated A := by
  by_cases ha : A.a = 0
  · have hc : A.c ≠ 0 := by
      intro hc
      have : det A = 0 := by simp [det, ha, hc]
      rw [this] at hdet
      exact zero_ne_one hdet
    let B : Mat2 F := mul (weyl 1) A
    have hBa : B.a ≠ 0 := by
      simpa [B, weyl_one_mul] using hc
    have hBdet : det B = 1 := by
      simpa [B, det_weyl_one_mul] using hdet
    have hBgen : ElementaryGenerated B :=
      elementaryGenerated_of_det_one_of_a_ne_zero B hBa hBdet
    have hgen : ElementaryGenerated (mul (weyl (-1)) B) :=
      .mul (.weyl (-1)) hBgen
    have heq : mul (weyl (-1)) B = A := by
      simpa [B] using weyl_neg_one_mul_weyl_one_mul A
    rw [heq] at hgen
    exact hgen
  · exact elementaryGenerated_of_det_one_of_a_ne_zero A ha hdet

end Mat2

end SL2ElementaryGeneration

end IUTThreeClosures
