/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.SpectrumPreservingInd2Envelope

/-!
# Source-faithful fiberwise Ind2: the radial shadow

Theorem 3.11(i) of IUT III describes Indeterminacy (Ind2) as independent
copies of the local isomorphism action on the direct summands of each fixed
`j + 1` tensor factor.  In particular, Ind2 acts *inside* the summands
belonging to one theta label; it is not an arbitrary permutation of the theta
label set.

This module records the corresponding radial shadow.  A fiberwise Ind2 choice
contains, for every fixed label `j`, a permutation of the auxiliary summand
fiber over `j`.  The label itself is unchanged.  Consequently the Tate radius
at `j` is governed by `labelNat j ^ 2`; Ind3 may only enlarge the exponent and
shrink the region, while norm-one Ind1 leaves the principal region unchanged.

The main theorem is joint at packet level: the literal union over all
fiberwise choices is exactly the native squared-label Tate packet.  One
ordinary choice realizes every coordinate simultaneously.  Thus the
spectrum-preserving condition of the preceding audit is no longer supplied as
a proposition: it follows by construction from the source-faithful type of
Ind2.

This is only the normalized radial shadow of the direct-summand action.  It
does not identify the full IUT III possible image with this packet and does not
assert a volume, IUT IV, Szpiro, or abc estimate.
-/

set_option linter.checkUnivs false

namespace IUTThreeClosures

open Iut TateCurvesTheta
open scoped Pointwise

universe v w x

variable {K : Type v} [NormedField K]
variable {Label : Type w}
variable {Fiber : Label → Type x}

namespace FiberwiseThetaIndeterminacyChoice

/-- Radial shadow of the source-faithful indeterminacies.  Ind2 acts inside the
summand fiber attached to each fixed theta label. -/
structure Choice
    (K : Type v) [NormedField K]
    (Label : Type w)
    (Fiber : Label → Type x) where
  ind1 : NormOneKummerUnit K
  ind2 : ∀ j : Label, Equiv.Perm (Fiber j)
  ind3 : Label → ℕ

/-- Ordinary source-faithful choice. -/
def ordinary : Choice K Label Fiber where
  ind1 := NormOneKummerUnit.one
  ind2 := fun j => Equiv.refl (Fiber j)
  ind3 := fun _ => 0

/-- The radial exponent is label-fixed; the fiberwise Ind2 action does not
enter it. -/
def outputPower
    (labelNat : Label → ℕ)
    (C : Choice K Label Fiber)
    (j : Label) : ℕ :=
  (labelNat j) ^ 2 + C.ind3 j

/-- Kummer output value in the normalized radial shadow. -/
noncomputable def outputValue
    (t : TateParameter K)
    (labelNat : Label → ℕ)
    (C : Choice K Label Fiber)
    (j : Label) : K :=
  (C.ind1.unit : K) * (t.q : K) ^ outputPower labelNat C j

/-- Exact norm of the radial-shadow output. -/
theorem norm_outputValue
    (t : TateParameter K)
    (labelNat : Label → ℕ)
    (C : Choice K Label Fiber)
    (j : Label) :
    ‖outputValue t labelNat C j‖ =
      ‖(t.q : K)‖ ^ outputPower labelNat C j := by
  unfold outputValue
  rw [norm_mul, C.ind1.norm_eq_one, one_mul, norm_pow]

/-- Principal region generated by the radial-shadow output. -/
def outputRegion
    (t : TateParameter K)
    (labelNat : Label → ℕ)
    (C : Choice K Label Fiber)
    (j : Label) : Set K :=
  scaledRegion (outputValue t labelNat C j)
    (normIntegralRegion (K := K))

/-- Norm-one Ind1 does not change the Tate-power region. -/
theorem outputRegion_eq_qPowerRegion
    (t : TateParameter K)
    (labelNat : Label → ℕ)
    (C : Choice K Label Fiber)
    (j : Label) :
    outputRegion t labelNat C j =
      t.qPowerRegion (outputPower labelNat C j) := by
  unfold outputRegion TateParameter.qPowerRegion
  apply scaledRegion_eq_of_norm_eq
  · exact pow_ne_zero _ t.q.ne_zero
  · simpa only [norm_pow] using
      norm_outputValue t labelNat C j

/-- Fiberwise Ind2 and Ind3 never enlarge the native squared-label region. -/
theorem outputRegion_subset_native
    (t : TateParameter K)
    (labelNat : Label → ℕ)
    (C : Choice K Label Fiber)
    (j : Label) :
    outputRegion t labelNat C j ⊆
      t.qPowerRegion ((labelNat j) ^ 2) := by
  rw [outputRegion_eq_qPowerRegion]
  exact t.qPowerRegion_antitone
    (Nat.le_add_right ((labelNat j) ^ 2) (C.ind3 j))

/-- Complete packet attached to one fiberwise choice. -/
def packetRegion
    (t : TateParameter K)
    (labelNat : Label → ℕ)
    (C : Choice K Label Fiber) : Set (Label → K) :=
  {a | ∀ j, a j ∈ outputRegion t labelNat C j}

/-- Native squared-label Tate packet. -/
def nativePacketRegion
    (t : TateParameter K)
    (labelNat : Label → ℕ) : Set (Label → K) :=
  {a | ∀ j, a j ∈ t.qPowerRegion ((labelNat j) ^ 2)}

/-- Literal union over all complete source-faithful radial-shadow packets. -/
def packetChoiceUnion
    (t : TateParameter K)
    (labelNat : Label → ℕ) : Set (Label → K) :=
  ⋃ C : Choice K Label Fiber,
    packetRegion t labelNat C

/-- Every complete fiberwise packet lies in the native packet. -/
theorem packetRegion_subset_nativePacketRegion
    (t : TateParameter K)
    (labelNat : Label → ℕ)
    (C : Choice K Label Fiber) :
    packetRegion t labelNat C ⊆
      nativePacketRegion t labelNat := by
  intro a ha j
  exact outputRegion_subset_native t labelNat C j (ha j)

/-- The ordinary fiberwise choice realizes the whole native packet exactly. -/
theorem ordinary_packetRegion
    (t : TateParameter K)
    (labelNat : Label → ℕ) :
    packetRegion t labelNat (ordinary : Choice K Label Fiber) =
      nativePacketRegion t labelNat := by
  ext a
  constructor
  · intro ha j
    have hj := ha j
    rw [outputRegion_eq_qPowerRegion] at hj
    simpa [ordinary, outputPower] using hj
  · intro ha j
    rw [outputRegion_eq_qPowerRegion]
    simpa [ordinary, outputPower] using ha j

/-- **Source-faithful radial packet theorem.**  Because Ind2 is fiberwise over
a fixed theta label, the literal union of complete packets is exactly the
native squared-label Tate packet. -/
theorem packetChoiceUnion_eq_nativePacketRegion
    (t : TateParameter K)
    (labelNat : Label → ℕ) :
    packetChoiceUnion (Fiber := Fiber) t labelNat =
      nativePacketRegion t labelNat := by
  apply Set.Subset.antisymm
  · intro a ha
    rcases Set.mem_iUnion.mp ha with ⟨C, haC⟩
    exact packetRegion_subset_nativePacketRegion t labelNat C haC
  · intro a ha
    apply Set.mem_iUnion.mpr
    refine ⟨ordinary (K := K) (Label := Label) (Fiber := Fiber), ?_⟩
    rw [ordinary_packetRegion t labelNat]
    exact ha

#print axioms norm_outputValue
#print axioms outputRegion_eq_qPowerRegion
#print axioms outputRegion_subset_native
#print axioms packetRegion_subset_nativePacketRegion
#print axioms ordinary_packetRegion
#print axioms packetChoiceUnion_eq_nativePacketRegion

end FiberwiseThetaIndeterminacyChoice

end IUTThreeClosures
