/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.SourceFaithfulFinalCapsuleRadialVolume

/-!
# Source-faithful Ind2 on the complete direct-summand packet

The preceding radial-shadow theorem kept one radial coordinate for each final-
capsule label.  IUT III, Theorem 3.11(i), acts one level deeper: for every fixed
theta label it applies independent copies of the local isomorphism action to
the direct summands of the corresponding tensor factors.

This file retains that summand fiber explicitly.  Ind2 is a permutation inside
the fiber over a fixed final-capsule label; it never moves a summand to a
different theta label.  Norm-one Ind1 data and nonnegative Ind3 exponents are
allowed independently on the summands and are reindexed by the fiberwise Ind2
permutation.

The main theorem is a literal equality of complete dependent packet unions.
The union over all source-faithful summand choices is exactly the native packet
in which every summand over a label `j` has Tate radius `q^(j^2)`.  Thus the
full direct-summand permutation itself introduces no radial enlargement.  The
proof is joint: one ordinary choice realizes all summands simultaneously.

No component-volume estimate, holomorphic-hull comparison, IUT IV inequality,
or abc statement is assumed.
-/

set_option linter.checkUnivs false

namespace IUTThreeClosures

open Iut TateCurvesTheta
open scoped Pointwise

universe x

namespace FinalCapsule

/-- Source-faithful indeterminacy data on the direct summands above each fixed
final-capsule label. -/
structure DirectSummandChoice
    (D : FinalCapsule)
    (Fiber : D.Label → Type x) where
  /-- Norm-one Kummer ambiguity, independently on every summand. -/
  ind1 : ∀ j : D.Label, Fiber j → NormOneKummerUnit (D.field j)
  /-- Ind2 acts inside the summand fiber over the fixed theta label `j`. -/
  ind2 : ∀ j : D.Label, Equiv.Perm (Fiber j)
  /-- Nonnegative Ind3 exponent attached to each source summand. -/
  ind3 : ∀ j : D.Label, Fiber j → ℕ

/-- The ordinary choice on every direct summand. -/
def ordinaryDirectSummandChoice
    (D : FinalCapsule)
    (Fiber : D.Label → Type x) :
    DirectSummandChoice D Fiber where
  ind1 := fun _ _ => NormOneKummerUnit.one
  ind2 := fun j => Equiv.refl (Fiber j)
  ind3 := fun _ _ => 0

/-- Output exponent at a target summand.  Ind2 only reindexes the summand-
specific Ind3 datum; the squared theta label is fixed. -/
def directSummandOutputPower
    (D : FinalCapsule)
    {Fiber : D.Label → Type x}
    (C : DirectSummandChoice D Fiber)
    (j : D.Label)
    (f : Fiber j) : ℕ :=
  (D.labelInteger j) ^ 2 + C.ind3 j (C.ind2 j f)

/-- Kummer output value at one target summand. -/
noncomputable def directSummandOutputValue
    (D : FinalCapsule)
    {Fiber : D.Label → Type x}
    (C : DirectSummandChoice D Fiber)
    (j : D.Label)
    (f : Fiber j) : D.field j :=
  (((C.ind1 j (C.ind2 j f)).unit : D.field j) *
    ((D.qParam j).q : D.field j) ^
      directSummandOutputPower D C j f)

/-- Exact norm of a direct-summand output. -/
theorem norm_directSummandOutputValue
    (D : FinalCapsule)
    {Fiber : D.Label → Type x}
    (C : DirectSummandChoice D Fiber)
    (j : D.Label)
    (f : Fiber j) :
    ‖directSummandOutputValue D C j f‖ =
      ‖((D.qParam j).q : D.field j)‖ ^
        directSummandOutputPower D C j f := by
  unfold directSummandOutputValue
  rw [norm_mul, (C.ind1 j (C.ind2 j f)).norm_eq_one,
    one_mul, norm_pow]

/-- Principal region generated by one direct-summand output. -/
def directSummandOutputRegion
    (D : FinalCapsule)
    {Fiber : D.Label → Type x}
    (C : DirectSummandChoice D Fiber)
    (j : D.Label)
    (f : Fiber j) : Set (D.field j) :=
  scaledRegion (directSummandOutputValue D C j f)
    (normIntegralRegion (K := D.field j))

/-- Norm-one Ind1 reduces the direct-summand region to the Tate-power region
with its source-faithful exponent. -/
theorem directSummandOutputRegion_eq_qPowerRegion
    (D : FinalCapsule)
    {Fiber : D.Label → Type x}
    (C : DirectSummandChoice D Fiber)
    (j : D.Label)
    (f : Fiber j) :
    directSummandOutputRegion D C j f =
      (D.qParam j).qPowerRegion
        (directSummandOutputPower D C j f) := by
  unfold directSummandOutputRegion TateParameter.qPowerRegion
  apply scaledRegion_eq_of_norm_eq
  · exact pow_ne_zero _ (D.qParam j).q.ne_zero
  · simpa only [norm_pow] using
      norm_directSummandOutputValue D C j f

/-- Every source-faithful summand output is contained in the native squared-
label Tate region. -/
theorem directSummandOutputRegion_subset_native
    (D : FinalCapsule)
    {Fiber : D.Label → Type x}
    (C : DirectSummandChoice D Fiber)
    (j : D.Label)
    (f : Fiber j) :
    directSummandOutputRegion D C j f ⊆
      (D.qParam j).qPowerRegion ((D.labelInteger j) ^ 2) := by
  rw [directSummandOutputRegion_eq_qPowerRegion]
  exact (D.qParam j).qPowerRegion_antitone
    (Nat.le_add_right ((D.labelInteger j) ^ 2)
      (C.ind3 j (C.ind2 j f)))

/-- Complete native packet with every direct summand retained. -/
def nativeDirectSummandPacket
    (D : FinalCapsule)
    (Fiber : D.Label → Type x) :
    Set (∀ j : D.Label, Fiber j → D.field j) :=
  {a | ∀ j f,
    a j f ∈
      (D.qParam j).qPowerRegion ((D.labelInteger j) ^ 2)}

/-- Complete direct-summand packet attached to one source-faithful choice. -/
def directSummandPacket
    (D : FinalCapsule)
    {Fiber : D.Label → Type x}
    (C : DirectSummandChoice D Fiber) :
    Set (∀ j : D.Label, Fiber j → D.field j) :=
  {a | ∀ j f, a j f ∈ directSummandOutputRegion D C j f}

/-- Literal union over all complete source-faithful direct-summand packets. -/
def directSummandPacketUnion
    (D : FinalCapsule)
    (Fiber : D.Label → Type x) :
    Set (∀ j : D.Label, Fiber j → D.field j) :=
  ⋃ C : DirectSummandChoice D Fiber,
    directSummandPacket D C

/-- Every complete source-faithful summand packet lies in the native packet. -/
theorem directSummandPacket_subset_nativeDirectSummandPacket
    (D : FinalCapsule)
    {Fiber : D.Label → Type x}
    (C : DirectSummandChoice D Fiber) :
    directSummandPacket D C ⊆
      nativeDirectSummandPacket D Fiber := by
  intro a ha j f
  exact directSummandOutputRegion_subset_native D C j f (ha j f)

/-- The ordinary choice realizes all native direct-summand regions
simultaneously. -/
theorem ordinaryDirectSummandPacket
    (D : FinalCapsule)
    (Fiber : D.Label → Type x) :
    directSummandPacket D (ordinaryDirectSummandChoice D Fiber) =
      nativeDirectSummandPacket D Fiber := by
  ext a
  constructor
  · intro ha j f
    have hjf := ha j f
    rw [directSummandOutputRegion_eq_qPowerRegion] at hjf
    simpa [ordinaryDirectSummandChoice, directSummandOutputPower] using hjf
  · intro ha j f
    rw [directSummandOutputRegion_eq_qPowerRegion]
    simpa [ordinaryDirectSummandChoice, directSummandOutputPower] using ha j f

/-- **Complete direct-summand Ind2 theorem.**  The literal union over all
fiberwise source-faithful Ind1/Ind2/Ind3 choices is exactly the native
squared-label direct-summand packet. -/
theorem directSummandPacketUnion_eq_nativeDirectSummandPacket
    (D : FinalCapsule)
    (Fiber : D.Label → Type x) :
    directSummandPacketUnion D Fiber =
      nativeDirectSummandPacket D Fiber := by
  apply Set.Subset.antisymm
  · intro a ha
    rcases Set.mem_iUnion.mp ha with ⟨C, haC⟩
    exact directSummandPacket_subset_nativeDirectSummandPacket D C haC
  · intro a ha
    apply Set.mem_iUnion.mpr
    refine ⟨ordinaryDirectSummandChoice D Fiber, ?_⟩
    rw [ordinaryDirectSummandPacket D Fiber]
    exact ha

#print axioms norm_directSummandOutputValue
#print axioms directSummandOutputRegion_eq_qPowerRegion
#print axioms directSummandOutputRegion_subset_native
#print axioms directSummandPacket_subset_nativeDirectSummandPacket
#print axioms ordinaryDirectSummandPacket
#print axioms directSummandPacketUnion_eq_nativeDirectSummandPacket

end FinalCapsule

end IUTThreeClosures
