/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import Mathlib.Analysis.Normed.Unbundled.SpectralNorm

/-!
# Spectral-norm preservation under Ind2 field automorphisms

The local automorphisms occurring in the Ind2 ambiguity should not be modeled
as arbitrary permutations of packet regions. On a finite algebraic extension
of the rational local base field they are algebra automorphisms, and the
canonical spectral norm is invariant under every such automorphism.

This module proves the corresponding set-level statements. The spectral
integer region is preserved exactly, and a principal region generated by `a`
is transported to the principal region generated by `σ(a)`. Hence an Ind2
operation does not introduce a new radius; it only replaces a generator by a
conjugate of the same spectral norm.

The measure statement is then reduced to uniqueness of normalized additive
Haar measure on the preserved spectral integer region. No volume bound,
coefficient, height inequality, or abc statement is assumed here.
-/

namespace IUTThreeClosures

universe u v

variable (K : Type u) [NormedField K]
variable (L : Type v) [Field L] [Algebra K L] [Algebra.IsAlgebraic K L]

/-- The canonical spectral integer region of an algebraic extension. -/
def spectralIntegralRegion : Set L :=
  {x | spectralNorm K L x ≤ 1}

/-- A base-field algebra automorphism preserves the spectral integer region
pointwise. -/
theorem mem_spectralIntegralRegion_algEquiv
    (σ : L ≃ₐ[K] L) (x : L) :
    x ∈ spectralIntegralRegion K L ↔
      σ x ∈ spectralIntegralRegion K L := by
  change spectralNorm K L x ≤ 1 ↔ spectralNorm K L (σ x) ≤ 1
  rw [spectralNorm_eq_of_equiv σ x]

/-- Exact preimage invariance of the spectral integer region. -/
theorem preimage_spectralIntegralRegion_algEquiv
    (σ : L ≃ₐ[K] L) :
    σ ⁻¹' spectralIntegralRegion K L = spectralIntegralRegion K L := by
  ext x
  exact (mem_spectralIntegralRegion_algEquiv K L σ x).symm

/-- Exact image invariance of the spectral integer region. -/
theorem image_spectralIntegralRegion_algEquiv
    (σ : L ≃ₐ[K] L) :
    σ '' spectralIntegralRegion K L = spectralIntegralRegion K L := by
  ext y
  constructor
  · rintro ⟨x, hx, rfl⟩
    exact (mem_spectralIntegralRegion_algEquiv K L σ x).mp hx
  · intro hy
    refine ⟨σ.symm y, ?_, by simp⟩
    exact (mem_spectralIntegralRegion_algEquiv K L σ.symm y).mp hy

/-- Principal spectral region generated by one nonzero local scalar. -/
def spectralPrincipalRegion (a : L) : Set L :=
  {x | ∃ z ∈ spectralIntegralRegion K L, x = a * z}

/-- An Ind2 automorphism carries a principal region to the principal region of
the conjugate generator. -/
theorem image_spectralPrincipalRegion_algEquiv
    (σ : L ≃ₐ[K] L) (a : L) :
    σ '' spectralPrincipalRegion K L a =
      spectralPrincipalRegion K L (σ a) := by
  ext y
  constructor
  · rintro ⟨x, ⟨z, hz, rfl⟩, rfl⟩
    refine ⟨σ z, ?_, by simp⟩
    exact (mem_spectralIntegralRegion_algEquiv K L σ z).mp hz
  · rintro ⟨z, hz, rfl⟩
    refine ⟨a * σ.symm z, ?_, by simp⟩
    refine ⟨σ.symm z, ?_, rfl⟩
    exact (mem_spectralIntegralRegion_algEquiv K L σ.symm z).mp hz

/-- The same transport formula for a power-generated local theta region. -/
theorem image_spectralPowerRegion_algEquiv
    (σ : L ≃ₐ[K] L) (q : L) (n : ℕ) :
    σ '' spectralPrincipalRegion K L (q ^ n) =
      spectralPrincipalRegion K L ((σ q) ^ n) := by
  simpa using image_spectralPrincipalRegion_algEquiv K L σ (q ^ n)

/-- Ind2 preserves the radius of every power generator. -/
theorem spectralNorm_algEquiv_pow
    (σ : L ≃ₐ[K] L) (q : L) (n : ℕ) :
    spectralNorm K L (σ (q ^ n)) = spectralNorm K L (q ^ n) := by
  exact (spectralNorm_eq_of_equiv σ (q ^ n)).symm

end IUTThreeClosures
