/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.SteinbergIntegerFiniteChain20260902
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-!
# A generated five-term relation and its finite-boundary bridge

The preceding Steinberg files prove the five-term identity coefficientwise
and prove the analytic estimate for a finite rational-cell chain once its
exact exterior boundary is known.  This file supplies the missing algebraic
middle layer.  It forms the free integral module on finite divisor symbols,
defines the boundary as a genuine linear map, lets the five-term generators
span a submodule, and proves that this entire generated submodule lies in the
kernel of the boundary map.

No boundary equality is a field of the generated relation.  Instead, the
boundary equality used by `FiniteRationalCellChain` is derived from membership
in the five-term span.  The separate positive-realization structure records
the five individual symbol identifications needed to turn an algebraic
divisor generator into five actual positive rational cells.  Constructing
enough such positive realizations to fill arbitrary targets remains open.
-/

namespace IUTThreeClosures
namespace SteinbergFiveTermBoundaryBridge20260903

open SteinbergValuationContactSurface20260902
open SteinbergIntegerFiniteChain20260902

noncomputable section

/-! ## The free integral chain and its boundary -/

/-- A formal Steinberg symbol consists of the divisor of a rational value
and the divisor of its complement.  At this algebraic level both entries are
arbitrary finite integral divisors. -/
structure DivisorSymbol where
  valueDivisor : FiniteDivisor
  complementDivisor : FiniteDivisor

@[ext] theorem DivisorSymbol.ext {s t : DivisorSymbol}
    (hvalue : s.valueDivisor = t.valueDivisor)
    (hcomplement : s.complementDivisor = t.complementDivisor) : s = t := by
  cases s
  cases t
  simp_all

/-- The free integral chain module on divisor symbols. -/
abbrev DivisorSymbolChain := DivisorSymbol →₀ ℤ

/-- Exterior boundary of one divisor symbol. -/
def symbolBoundary (s : DivisorSymbol) : FiniteExteriorSurface :=
  finiteWedge s.valueDivisor s.complementDivisor

/-- Linear extension of the symbol boundary to the free integral chain. -/
def chainBoundary : DivisorSymbolChain →ₗ[ℤ] FiniteExteriorSurface :=
  Finsupp.linearCombination ℤ symbolBoundary

/-- Sum of the coefficients of a formal symbol chain. -/
def chainAugmentation : DivisorSymbolChain →ₗ[ℤ] ℤ :=
  Finsupp.linearCombination ℤ (fun _ => 1)

@[simp] theorem chainBoundary_single (s : DivisorSymbol) (n : ℤ) :
    chainBoundary (Finsupp.single s n) = n • symbolBoundary s := by
  simp [chainBoundary]

@[simp] theorem chainAugmentation_single (s : DivisorSymbol) (n : ℤ) :
    chainAugmentation (Finsupp.single s n) = n := by
  simp [chainAugmentation]

/-- The five formal symbols in the coefficientwise Steinberg identity. -/
def fiveTermChain (X U Y V Z : FiniteDivisor) : DivisorSymbolChain :=
  Finsupp.single ⟨X, U⟩ 1 -
    Finsupp.single ⟨Y, V⟩ 1 +
    Finsupp.single ⟨Y - X, Z - X⟩ 1 -
    Finsupp.single ⟨Y + U - X - V, Z - X - V⟩ 1 +
    Finsupp.single ⟨U - V, Z - V⟩ 1

/-- The signed five-term generator always has augmentation one.  This
remains true when some or all of its five symbols coincide. -/
theorem fiveTermChain_augmentation
    (X U Y V Z : FiniteDivisor) :
    chainAugmentation (fiveTermChain X U Y V Z) = 1 := by
  simp [fiveTermChain]

/-- Consequently no five-term generator is literally zero in the free
symbol chain. -/
theorem fiveTermChain_ne_zero
    (X U Y V Z : FiniteDivisor) :
    fiveTermChain X U Y V Z ≠ 0 := by
  intro h
  have ha := congrArg chainAugmentation h
  rw [fiveTermChain_augmentation] at ha
  simp at ha

/-- Every algebraic five-term generator has zero exterior boundary. -/
theorem fiveTermChain_boundary
    (X U Y V Z : FiniteDivisor) :
    chainBoundary (fiveTermChain X U Y V Z) = 0 := by
  ext pq
  rcases pq with ⟨p, q⟩
  simp only [fiveTermChain, map_add, map_sub, chainBoundary_single, one_smul]
  change
    finiteWedge X U (p, q) - finiteWedge Y V (p, q) +
        finiteWedge (Y - X) (Z - X) (p, q) -
        finiteWedge (Y + U - X - V) (Z - X - V) (p, q) +
        finiteWedge (U - V) (Z - V) (p, q) = 0
  simpa only [finiteWedge_apply, wedgeCoefficient, Finsupp.coe_add,
    Finsupp.coe_sub, Pi.add_apply, Pi.sub_apply] using
      steinberg_fiveTerm_surface (X : DivisorVector) U Y V Z p q

/-! ## The relation generated by all five-term moves -/

/-- The set of all algebraic five-term generators. -/
def fiveTermGenerators : Set DivisorSymbolChain :=
  {c | ∃ X U Y V Z : FiniteDivisor, c = fiveTermChain X U Y V Z}

/-- The integral submodule generated by the five-term moves.  Membership is
the precise finite linear-generation certificate used below. -/
def fiveTermRelation : Submodule ℤ DivisorSymbolChain :=
  Submodule.span ℤ fiveTermGenerators

theorem fiveTermGenerator_mem
    (X U Y V Z : FiniteDivisor) :
    fiveTermChain X U Y V Z ∈ fiveTermRelation := by
  apply Submodule.subset_span
  exact ⟨X, U, Y, V, Z, rfl⟩

/-- The five-term relation is genuinely nontrivial as a submodule of the
free symbol chain.  This follows from the augmentation obstruction, not
from a failure of the boundary identity. -/
theorem fiveTermRelation_ne_bot : fiveTermRelation ≠ ⊥ := by
  intro hbot
  have hmem := fiveTermGenerator_mem (0 : FiniteDivisor) 0 0 0 0
  rw [hbot] at hmem
  have hz : fiveTermChain 0 0 0 0 0 = 0 := by
    simpa using hmem
  exact fiveTermChain_ne_zero 0 0 0 0 0 hz

/-- The generated five-term submodule lies in the kernel of the genuine
boundary map. -/
theorem fiveTermRelation_le_ker :
    fiveTermRelation ≤ LinearMap.ker chainBoundary := by
  rw [fiveTermRelation, Submodule.span_le]
  rintro c ⟨X, U, Y, V, Z, rfl⟩
  exact LinearMap.mem_ker.mpr (fiveTermChain_boundary X U Y V Z)

/-- Two formal chains are five-term equivalent when their difference is in
the generated five-term submodule. -/
def FiveTermEquivalent (c d : DivisorSymbolChain) : Prop :=
  c - d ∈ fiveTermRelation

theorem fiveTermEquivalent_refl (c : DivisorSymbolChain) :
    FiveTermEquivalent c c := by
  simp [FiveTermEquivalent]

theorem fiveTermEquivalent_symm {c d : DivisorSymbolChain}
    (h : FiveTermEquivalent c d) : FiveTermEquivalent d c := by
  have hneg : -(c - d) ∈ fiveTermRelation :=
    fiveTermRelation.neg_mem h
  simpa [FiveTermEquivalent, neg_sub] using hneg

theorem fiveTermEquivalent_trans {c d e : DivisorSymbolChain}
    (hcd : FiveTermEquivalent c d) (hde : FiveTermEquivalent d e) :
    FiveTermEquivalent c e := by
  have hadd := fiveTermRelation.add_mem hcd hde
  simpa [FiveTermEquivalent, sub_eq_add_neg, add_assoc] using hadd

/-- Generated five-term equivalence preserves the exterior boundary.  This
is the principal no-smuggling theorem: it follows from span membership. -/
theorem chainBoundary_eq_of_fiveTermEquivalent
    {c d : DivisorSymbolChain} (h : FiveTermEquivalent c d) :
    chainBoundary c = chainBoundary d := by
  have hk : c - d ∈ LinearMap.ker chainBoundary :=
    fiveTermRelation_le_ker h
  have hz : chainBoundary (c - d) = 0 := LinearMap.mem_ker.mp hk
  rw [map_sub] at hz
  exact sub_eq_zero.mp hz

/-! ## Actual positive rational cells -/

/-- The divisor symbol of an actual positive reduced rational cell. -/
def cellSymbol (P : PositiveRationalCell) : DivisorSymbol where
  valueDivisor := finiteValuationDivisor P.left -
    finiteValuationDivisor P.total
  complementDivisor := finiteValuationDivisor P.middle -
    finiteValuationDivisor P.total

/-- The corresponding basis vector in the free symbol chain. -/
def cellChain (P : PositiveRationalCell) : DivisorSymbolChain :=
  Finsupp.single (cellSymbol P) 1

/-- The free-chain boundary of a positive rational cell is exactly its
previously defined finite contact surface. -/
theorem chainBoundary_cellChain (P : PositiveRationalCell) :
    chainBoundary (cellChain P) = P.surface := by
  simp [cellChain, cellSymbol, symbolBoundary, PositiveRationalCell.surface,
    finiteContact]

/-- The chain encoding of a finite signed family of positive rational
cells, before any boundary equation is known. -/
def encodedCellSum {I : Type*} [Fintype I]
    (cell : I → PositiveRationalCell) (coefficient : I → ℤ) :
    DivisorSymbolChain :=
  ∑ j, coefficient j • cellChain (cell j)

theorem chainBoundary_encodedCellSum
    {I : Type*} [Fintype I]
    (cell : I → PositiveRationalCell) (coefficient : I → ℤ) :
    chainBoundary (encodedCellSum cell coefficient) =
      ∑ j, coefficient j • (cell j).surface := by
  simp [encodedCellSum, chainBoundary_cellChain]

/-- A finite rational filling certified by the broad algebraic divisor
five-term relation.  Its generators need not themselves be positively
realized.  Unlike `FiniteRationalCellChain`, this structure has no
boundary-equality field. -/
structure AlgebraicallyGeneratedRationalFilling (I : Type*) [Fintype I] where
  target : PositiveRationalCell
  cell : I → PositiveRationalCell
  coefficient : I → ℤ
  generated : FiveTermEquivalent (cellChain target)
    (encodedCellSum cell coefficient)

namespace AlgebraicallyGeneratedRationalFilling

/-- The exact finite-support boundary is derived from the generation
certificate. -/
theorem boundary {I : Type*} [Fintype I]
    (Gamma : AlgebraicallyGeneratedRationalFilling I) :
    Gamma.target.surface = ∑ j, Gamma.coefficient j • (Gamma.cell j).surface := by
  have h := chainBoundary_eq_of_fiveTermEquivalent Gamma.generated
  rw [chainBoundary_cellChain, chainBoundary_encodedCellSum] at h
  exact h

/-- Forget the generation certificate only after deriving the exact
boundary required by the earlier finite-chain theorem. -/
def toFiniteRationalCellChain {I : Type*} [Fintype I]
    (Gamma : AlgebraicallyGeneratedRationalFilling I) : FiniteRationalCellChain I where
  target := Gamma.target
  cell := Gamma.cell
  coefficient := Gamma.coefficient
  boundary := Gamma.boundary

/-- A generated five-term filling inherits the concrete calibrated boundary
estimate without adding an equality premise. -/
theorem boundary_le_calibratedCost {I : Type*} [Fintype I]
    (Gamma : AlgebraicallyGeneratedRationalFilling I) :
    Gamma.target.logWeightedNorm ≤
      (1 / 2 : ℝ) *
        ((∑ j, |(Gamma.coefficient j : ℝ)| *
            ((Gamma.cell j).mixedCost + (Gamma.cell j).coherentCost)) +
          ∑ j, |(Gamma.coefficient j : ℝ)| *
            (Gamma.cell j).residualCost) := by
  exact Gamma.toFiniteRationalCellChain.boundary_le_calibratedCost

end AlgebraicallyGeneratedRationalFilling

/-! ## Positive realizations of individual generators -/

/-- Data witnessing that the five formal divisor symbols of an algebraic
generator are individually realized by positive reduced rational cells.
These five identifications are local semantic premises; their signed
boundary equality is proved below and is not a structure field. -/
structure PositiveFiveTermRealization where
  xDivisor : FiniteDivisor
  oneSubXDivisor : FiniteDivisor
  yDivisor : FiniteDivisor
  oneSubYDivisor : FiniteDivisor
  xSubYDivisor : FiniteDivisor
  first : PositiveRationalCell
  second : PositiveRationalCell
  third : PositiveRationalCell
  fourth : PositiveRationalCell
  fifth : PositiveRationalCell
  first_symbol : cellSymbol first = ⟨xDivisor, oneSubXDivisor⟩
  second_symbol : cellSymbol second = ⟨yDivisor, oneSubYDivisor⟩
  third_symbol : cellSymbol third =
    ⟨yDivisor - xDivisor, xSubYDivisor - xDivisor⟩
  fourth_symbol : cellSymbol fourth =
    ⟨yDivisor + oneSubXDivisor - xDivisor - oneSubYDivisor,
      xSubYDivisor - xDivisor - oneSubYDivisor⟩
  fifth_symbol : cellSymbol fifth =
    ⟨oneSubXDivisor - oneSubYDivisor,
      xSubYDivisor - oneSubYDivisor⟩

namespace PositiveFiveTermRealization

/-- Signed actual-cell chain attached to a positive realization. -/
def realizedChain (R : PositiveFiveTermRealization) : DivisorSymbolChain :=
  cellChain R.first - cellChain R.second + cellChain R.third -
    cellChain R.fourth + cellChain R.fifth

theorem realizedChain_eq_fiveTermChain (R : PositiveFiveTermRealization) :
    R.realizedChain = fiveTermChain R.xDivisor R.oneSubXDivisor
      R.yDivisor R.oneSubYDivisor R.xSubYDivisor := by
  simp only [realizedChain, cellChain, R.first_symbol, R.second_symbol,
    R.third_symbol, R.fourth_symbol, R.fifth_symbol]
  rfl

theorem realizedChain_mem_fiveTermRelation (R : PositiveFiveTermRealization) :
    R.realizedChain ∈ fiveTermRelation := by
  rw [R.realizedChain_eq_fiveTermChain]
  exact fiveTermGenerator_mem R.xDivisor R.oneSubXDivisor R.yDivisor
    R.oneSubYDivisor R.xSubYDivisor

/-- Every positively realized five-term move has zero actual divisor
surface boundary. -/
theorem realized_surface_boundary (R : PositiveFiveTermRealization) :
    R.first.surface - R.second.surface + R.third.surface -
        R.fourth.surface + R.fifth.surface = 0 := by
  have h := fiveTermChain_boundary R.xDivisor R.oneSubXDivisor R.yDivisor
    R.oneSubYDivisor R.xSubYDivisor
  rw [← R.realizedChain_eq_fiveTermChain] at h
  simpa [realizedChain, map_add, map_sub, chainBoundary_cellChain] using h

/-- The four cells on the right-hand side after solving a realized
five-term relation for its first cell. -/
def fillerCell (R : PositiveFiveTermRealization) :
    Fin 4 → PositiveRationalCell :=
  ![R.second, R.third, R.fourth, R.fifth]

/-- Coefficients `(+1,-1,+1,-1)` in that solved relation. -/
def fillerCoefficient (_R : PositiveFiveTermRealization) : Fin 4 → ℤ :=
  ![1, -1, 1, -1]

theorem encodedFiller_eq (R : PositiveFiveTermRealization) :
    encodedCellSum R.fillerCell R.fillerCoefficient =
      cellChain R.second - cellChain R.third + cellChain R.fourth -
        cellChain R.fifth := by
  simp [encodedCellSum, fillerCell, fillerCoefficient, Fin.sum_univ_succ]
  abel

/-- Every positively realized generator therefore gives an actual
generated rational filling, with no boundary equality supplied as data. -/
def toAlgebraicallyGeneratedRationalFilling (R : PositiveFiveTermRealization) :
    AlgebraicallyGeneratedRationalFilling (Fin 4) where
  target := R.first
  cell := R.fillerCell
  coefficient := R.fillerCoefficient
  generated := by
    unfold FiveTermEquivalent
    rw [R.encodedFiller_eq]
    have heq : cellChain R.first -
        (cellChain R.second - cellChain R.third + cellChain R.fourth -
          cellChain R.fifth) = R.realizedChain := by
      unfold realizedChain
      abel
    rw [heq]
    exact R.realizedChain_mem_fiveTermRelation

/-- The exact surface equality for a realized positive move is now also an
instance of the general generated-filling bridge. -/
theorem generatedFilling_boundary (R : PositiveFiveTermRealization) :
    R.first.surface =
      ∑ j, R.fillerCoefficient j • (R.fillerCell j).surface :=
  R.toAlgebraicallyGeneratedRationalFilling.boundary

end PositiveFiveTermRealization

/-! ## The relation generated only by positively realized moves -/

/-- Actual positive five-term generators, each of whose five formal symbols
has been identified with a positive reduced rational cell. -/
def positiveFiveTermGenerators : Set DivisorSymbolChain :=
  {c | ∃ R : PositiveFiveTermRealization, c = R.realizedChain}

/-- The integral span of actual positive five-term moves. -/
def positiveFiveTermRelation : Submodule ℤ DivisorSymbolChain :=
  Submodule.span ℤ positiveFiveTermGenerators

theorem positiveFiveTermGenerator_mem (R : PositiveFiveTermRealization) :
    R.realizedChain ∈ positiveFiveTermRelation := by
  apply Submodule.subset_span
  exact ⟨R, rfl⟩

/-- Every positive relation is, after forgetting realizability, an
algebraic five-term relation. -/
theorem positiveFiveTermRelation_le_algebraic :
    positiveFiveTermRelation ≤ fiveTermRelation := by
  rw [positiveFiveTermRelation, Submodule.span_le]
  rintro c ⟨R, rfl⟩
  exact R.realizedChain_mem_fiveTermRelation

/-- Therefore the full submodule generated by actual positive moves lies in
the kernel of the exterior boundary. -/
theorem positiveFiveTermRelation_le_ker :
    positiveFiveTermRelation ≤ LinearMap.ker chainBoundary :=
  fun _ h => fiveTermRelation_le_ker (positiveFiveTermRelation_le_algebraic h)

/-- Equivalence generated only by positively realized rational moves. -/
def PositiveFiveTermEquivalent (c d : DivisorSymbolChain) : Prop :=
  c - d ∈ positiveFiveTermRelation

theorem chainBoundary_eq_of_positiveFiveTermEquivalent
    {c d : DivisorSymbolChain} (h : PositiveFiveTermEquivalent c d) :
    chainBoundary c = chainBoundary d := by
  have hk : c - d ∈ LinearMap.ker chainBoundary :=
    positiveFiveTermRelation_le_ker h
  have hz : chainBoundary (c - d) = 0 := LinearMap.mem_ker.mp hk
  rw [map_sub] at hz
  exact sub_eq_zero.mp hz

/-- A finite rational filling whose generation certificate uses only
positive realized five-term moves.  No boundary equality is stored. -/
structure PositivelyGeneratedRationalFilling (I : Type*) [Fintype I] where
  target : PositiveRationalCell
  cell : I → PositiveRationalCell
  coefficient : I → ℤ
  generated : PositiveFiveTermEquivalent (cellChain target)
    (encodedCellSum cell coefficient)

namespace PositivelyGeneratedRationalFilling

theorem boundary {I : Type*} [Fintype I]
    (Gamma : PositivelyGeneratedRationalFilling I) :
    Gamma.target.surface = ∑ j, Gamma.coefficient j • (Gamma.cell j).surface := by
  have h := chainBoundary_eq_of_positiveFiveTermEquivalent Gamma.generated
  rw [chainBoundary_cellChain, chainBoundary_encodedCellSum] at h
  exact h

/-- Forget the generation certificate only after deriving its boundary. -/
def toFiniteRationalCellChain {I : Type*} [Fintype I]
    (Gamma : PositivelyGeneratedRationalFilling I) : FiniteRationalCellChain I where
  target := Gamma.target
  cell := Gamma.cell
  coefficient := Gamma.coefficient
  boundary := Gamma.boundary

theorem boundary_le_calibratedCost {I : Type*} [Fintype I]
    (Gamma : PositivelyGeneratedRationalFilling I) :
    Gamma.target.logWeightedNorm ≤
      (1 / 2 : ℝ) *
        ((∑ j, |(Gamma.coefficient j : ℝ)| *
            ((Gamma.cell j).mixedCost + (Gamma.cell j).coherentCost)) +
          ∑ j, |(Gamma.coefficient j : ℝ)| *
            (Gamma.cell j).residualCost) := by
  exact Gamma.toFiniteRationalCellChain.boundary_le_calibratedCost

end PositivelyGeneratedRationalFilling

namespace PositiveFiveTermRealization

/-- Solving one actual positive five-term generator for its first cell gives
a filling certified in the genuinely positive generated relation. -/
def toPositivelyGeneratedRationalFilling (R : PositiveFiveTermRealization) :
    PositivelyGeneratedRationalFilling (Fin 4) where
  target := R.first
  cell := R.fillerCell
  coefficient := R.fillerCoefficient
  generated := by
    unfold PositiveFiveTermEquivalent
    rw [R.encodedFiller_eq]
    have heq : cellChain R.first -
        (cellChain R.second - cellChain R.third + cellChain R.fourth -
          cellChain R.fifth) = R.realizedChain := by
      unfold realizedChain
      abel
    rw [heq]
    exact positiveFiveTermGenerator_mem R

end PositiveFiveTermRealization

@[simp] theorem finiteValuationDivisor_one : finiteValuationDivisor 1 = 0 := by
  ext p
  simp

theorem finiteValuationDivisor_mul {m n : ℕ} (hm : m ≠ 0) (hn : n ≠ 0) :
    finiteValuationDivisor (m * n) =
      finiteValuationDivisor m + finiteValuationDivisor n := by
  ext p
  simp [Nat.factorization_mul hm hn]

/-! ## A parameterized family of actual positive rational generators -/

/-- Arithmetic data for two reduced fractions `y=b/c < x=a/c` whose five
classical five-term transforms are all displayed in reduced positive form.
The five coprimality fields are exactly the reducedness conditions for the
five cells; no surface or boundary equality is included. -/
structure CommonDenominatorFiveTermData where
  a : ℕ
  b : ℕ
  c : ℕ
  b_pos : 0 < b
  b_lt_a : b < a
  a_lt_c : a < c
  first_reduced : Nat.Coprime a (c - a)
  second_reduced : Nat.Coprime b (c - b)
  third_reduced : Nat.Coprime b (a - b)
  fourth_reduced : Nat.Coprime (b * (c - a)) (c * (a - b))
  fifth_reduced : Nat.Coprime (c - a) (a - b)

namespace CommonDenominatorFiveTermData

theorem a_pos (D : CommonDenominatorFiveTermData) : 0 < D.a :=
  lt_trans D.b_pos D.b_lt_a

theorem c_pos (D : CommonDenominatorFiveTermData) : 0 < D.c :=
  lt_trans D.a_pos D.a_lt_c

theorem b_lt_c (D : CommonDenominatorFiveTermData) : D.b < D.c :=
  lt_trans D.b_lt_a D.a_lt_c

theorem c_sub_a_pos (D : CommonDenominatorFiveTermData) : 0 < D.c - D.a :=
  Nat.sub_pos_of_lt D.a_lt_c

theorem c_sub_b_pos (D : CommonDenominatorFiveTermData) : 0 < D.c - D.b :=
  Nat.sub_pos_of_lt D.b_lt_c

theorem a_sub_b_pos (D : CommonDenominatorFiveTermData) : 0 < D.a - D.b :=
  Nat.sub_pos_of_lt D.b_lt_a

/-- The cell `x=a/c`. -/
def firstCell (D : CommonDenominatorFiveTermData) : PositiveRationalCell where
  left := D.a
  middle := D.c - D.a
  total := D.c
  left_pos := D.a_pos
  middle_pos := D.c_sub_a_pos
  sum_eq := Nat.add_sub_of_le (Nat.le_of_lt D.a_lt_c)
  reduced := D.first_reduced

/-- The cell `y=b/c`. -/
def secondCell (D : CommonDenominatorFiveTermData) : PositiveRationalCell where
  left := D.b
  middle := D.c - D.b
  total := D.c
  left_pos := D.b_pos
  middle_pos := D.c_sub_b_pos
  sum_eq := Nat.add_sub_of_le (Nat.le_of_lt D.b_lt_c)
  reduced := D.second_reduced

/-- The cell `y/x=b/a`. -/
def thirdCell (D : CommonDenominatorFiveTermData) : PositiveRationalCell where
  left := D.b
  middle := D.a - D.b
  total := D.a
  left_pos := D.b_pos
  middle_pos := D.a_sub_b_pos
  sum_eq := Nat.add_sub_of_le (Nat.le_of_lt D.b_lt_a)
  reduced := D.third_reduced

theorem fourth_sum (D : CommonDenominatorFiveTermData) :
    D.b * (D.c - D.a) + D.c * (D.a - D.b) =
      D.a * (D.c - D.b) := by
  have hca : D.c - D.a + D.a = D.c :=
    Nat.sub_add_cancel (Nat.le_of_lt D.a_lt_c)
  have hab : D.a - D.b + D.b = D.a :=
    Nat.sub_add_cancel (Nat.le_of_lt D.b_lt_a)
  have hcb : D.c - D.b + D.b = D.c :=
    Nat.sub_add_cancel (Nat.le_of_lt D.b_lt_c)
  nlinarith

/-- The cell `y(1-x)/(x(1-y)) = b(c-a)/(a(c-b))`. -/
def fourthCell (D : CommonDenominatorFiveTermData) : PositiveRationalCell where
  left := D.b * (D.c - D.a)
  middle := D.c * (D.a - D.b)
  total := D.a * (D.c - D.b)
  left_pos := mul_pos D.b_pos D.c_sub_a_pos
  middle_pos := mul_pos D.c_pos D.a_sub_b_pos
  sum_eq := D.fourth_sum
  reduced := D.fourth_reduced

theorem fifth_sum (D : CommonDenominatorFiveTermData) :
    (D.c - D.a) + (D.a - D.b) = D.c - D.b := by
  exact Nat.sub_add_sub_cancel (Nat.le_of_lt D.a_lt_c)
    (Nat.le_of_lt D.b_lt_a)

/-- The cell `(1-x)/(1-y)=(c-a)/(c-b)`. -/
def fifthCell (D : CommonDenominatorFiveTermData) : PositiveRationalCell where
  left := D.c - D.a
  middle := D.a - D.b
  total := D.c - D.b
  left_pos := D.c_sub_a_pos
  middle_pos := D.a_sub_b_pos
  sum_eq := D.fifth_sum
  reduced := D.fifth_reduced

/-- The algebraic divisor inputs attached to `x`, `1-x`, `y`, `1-y`, and
`x-y`, respectively. -/
def xDivisor (D : CommonDenominatorFiveTermData) : FiniteDivisor :=
  finiteValuationDivisor D.a - finiteValuationDivisor D.c

def oneSubXDivisor (D : CommonDenominatorFiveTermData) : FiniteDivisor :=
  finiteValuationDivisor (D.c - D.a) - finiteValuationDivisor D.c

def yDivisor (D : CommonDenominatorFiveTermData) : FiniteDivisor :=
  finiteValuationDivisor D.b - finiteValuationDivisor D.c

def oneSubYDivisor (D : CommonDenominatorFiveTermData) : FiniteDivisor :=
  finiteValuationDivisor (D.c - D.b) - finiteValuationDivisor D.c

def xSubYDivisor (D : CommonDenominatorFiveTermData) : FiniteDivisor :=
  finiteValuationDivisor (D.a - D.b) - finiteValuationDivisor D.c

theorem firstCell_symbol (D : CommonDenominatorFiveTermData) :
    cellSymbol D.firstCell = ⟨D.xDivisor, D.oneSubXDivisor⟩ := by
  rfl

theorem secondCell_symbol (D : CommonDenominatorFiveTermData) :
    cellSymbol D.secondCell = ⟨D.yDivisor, D.oneSubYDivisor⟩ := by
  rfl

theorem thirdCell_symbol (D : CommonDenominatorFiveTermData) :
    cellSymbol D.thirdCell =
      ⟨D.yDivisor - D.xDivisor, D.xSubYDivisor - D.xDivisor⟩ := by
  apply DivisorSymbol.ext <;>
    simp only [cellSymbol, thirdCell, yDivisor, xDivisor,
      xSubYDivisor]
  · abel
  · abel

theorem fourthCell_symbol (D : CommonDenominatorFiveTermData) :
    cellSymbol D.fourthCell =
      ⟨D.yDivisor + D.oneSubXDivisor - D.xDivisor - D.oneSubYDivisor,
        D.xSubYDivisor - D.xDivisor - D.oneSubYDivisor⟩ := by
  apply DivisorSymbol.ext
  · simp only [cellSymbol, fourthCell, yDivisor, oneSubXDivisor, xDivisor,
      oneSubYDivisor]
    rw [finiteValuationDivisor_mul D.b_pos.ne' D.c_sub_a_pos.ne',
      finiteValuationDivisor_mul D.a_pos.ne' D.c_sub_b_pos.ne']
    abel
  · simp only [cellSymbol, fourthCell, xSubYDivisor, xDivisor,
      oneSubYDivisor]
    rw [finiteValuationDivisor_mul D.c_pos.ne' D.a_sub_b_pos.ne',
      finiteValuationDivisor_mul D.a_pos.ne' D.c_sub_b_pos.ne']
    abel

theorem fifthCell_symbol (D : CommonDenominatorFiveTermData) :
    cellSymbol D.fifthCell =
      ⟨D.oneSubXDivisor - D.oneSubYDivisor,
        D.xSubYDivisor - D.oneSubYDivisor⟩ := by
  apply DivisorSymbol.ext <;>
    simp only [cellSymbol, fifthCell, oneSubXDivisor, oneSubYDivisor,
      xSubYDivisor]
  · abel
  · abel

/-- Every datum in this arithmetic family produces an actual positive
five-term realization; the exterior relation is a theorem, not a premise. -/
noncomputable def toPositiveFiveTermRealization
    (D : CommonDenominatorFiveTermData) : PositiveFiveTermRealization where
  xDivisor := D.xDivisor
  oneSubXDivisor := D.oneSubXDivisor
  yDivisor := D.yDivisor
  oneSubYDivisor := D.oneSubYDivisor
  xSubYDivisor := D.xSubYDivisor
  first := D.firstCell
  second := D.secondCell
  third := D.thirdCell
  fourth := D.fourthCell
  fifth := D.fifthCell
  first_symbol := D.firstCell_symbol
  second_symbol := D.secondCell_symbol
  third_symbol := D.thirdCell_symbol
  fourth_symbol := D.fourthCell_symbol
  fifth_symbol := D.fifthCell_symbol

theorem actual_fiveTerm_surface_boundary
    (D : CommonDenominatorFiveTermData) :
    D.firstCell.surface - D.secondCell.surface + D.thirdCell.surface -
        D.fourthCell.surface + D.fifthCell.surface = 0 :=
  D.toPositiveFiveTermRealization.realized_surface_boundary

/-- The parameterized actual generator automatically yields a generated
four-cell filling of its first cell. -/
noncomputable def toAlgebraicallyGeneratedRationalFilling
    (D : CommonDenominatorFiveTermData) : AlgebraicallyGeneratedRationalFilling (Fin 4) :=
  D.toPositiveFiveTermRealization.toAlgebraicallyGeneratedRationalFilling

/-- The same arithmetic datum gives a filling in the smaller relation
generated only by actual positive moves. -/
noncomputable def toPositivelyGeneratedRationalFilling
    (D : CommonDenominatorFiveTermData) : PositivelyGeneratedRationalFilling (Fin 4) :=
  D.toPositiveFiveTermRealization.toPositivelyGeneratedRationalFilling

end CommonDenominatorFiveTermData

/-- Every odd denominator `c ≥ 3` supplies an actual member of the
common-denominator family, with `a=2` and `b=1`.  Hence the positive
realization construction is a parameterized family rather than an isolated
certificate. -/
def oddDenominatorFiveTermData (c : ℕ) (hc : 3 ≤ c) (hodd : Odd c) :
    CommonDenominatorFiveTermData where
  a := 2
  b := 1
  c := c
  b_pos := by norm_num
  b_lt_a := by norm_num
  a_lt_c := by omega
  first_reduced := by
    have hoddSub : Odd (c - 2) := by
      rcases hodd with ⟨k, hk⟩
      use k - 1
      omega
    exact hoddSub.coprime_two_left
  second_reduced := by simp
  third_reduced := by norm_num
  fourth_reduced := by
    have hoddSub : Odd (c - 2) := by
      rcases hodd with ⟨k, hk⟩
      use k - 1
      omega
    simp only [Nat.one_mul, Nat.reduceSubDiff, Nat.mul_one]
    have hsum : c - 2 + 2 = c := Nat.sub_add_cancel (by omega)
    rw [← hsum]
    exact Nat.coprime_self_add_right.mpr hoddSub.coprime_two_right
  fifth_reduced := by simp

theorem oddDenominator_actual_fiveTerm_surface_boundary
    (c : ℕ) (hc : 3 ≤ c) (hodd : Odd c) :
    let D := oddDenominatorFiveTermData c hc hodd
    D.firstCell.surface - D.secondCell.surface + D.thirdCell.surface -
        D.fourthCell.surface + D.fifthCell.surface = 0 := by
  exact (oddDenominatorFiveTermData c hc hodd).actual_fiveTerm_surface_boundary

/-! ## A nonvacuous positive rational five-term move -/

/-- The cell representing `1/2`. -/
def oneHalfCell : PositiveRationalCell where
  left := 1
  middle := 1
  total := 2
  left_pos := by norm_num
  middle_pos := by norm_num
  sum_eq := by norm_num
  reduced := by norm_num

/-- The cell representing `1/6`. -/
def oneSixthCell : PositiveRationalCell where
  left := 1
  middle := 5
  total := 6
  left_pos := by norm_num
  middle_pos := by norm_num
  sum_eq := by norm_num
  reduced := by norm_num

/-- The cell representing `1/3`. -/
def oneThirdCell : PositiveRationalCell where
  left := 1
  middle := 2
  total := 3
  left_pos := by norm_num
  middle_pos := by norm_num
  sum_eq := by norm_num
  reduced := by norm_num

/-- The cell representing `1/5`. -/
def oneFifthCell : PositiveRationalCell where
  left := 1
  middle := 4
  total := 5
  left_pos := by norm_num
  middle_pos := by norm_num
  sum_eq := by norm_num
  reduced := by norm_num

/-- The cell representing `3/5`. -/
def threeFifthsCell : PositiveRationalCell where
  left := 3
  middle := 2
  total := 5
  left_pos := by norm_num
  middle_pos := by norm_num
  sum_eq := by norm_num
  reduced := by norm_num

theorem cellSymbol_oneHalf : cellSymbol oneHalfCell =
    ⟨-finiteValuationDivisor 2, -finiteValuationDivisor 2⟩ := by
  apply DivisorSymbol.ext
  · ext p
    simp [cellSymbol, oneHalfCell]
  · ext p
    simp [cellSymbol, oneHalfCell]

theorem cellSymbol_oneSixth : cellSymbol oneSixthCell =
    ⟨-(finiteValuationDivisor 2 + finiteValuationDivisor 3),
      finiteValuationDivisor 5 -
        (finiteValuationDivisor 2 + finiteValuationDivisor 3)⟩ := by
  have h6 : finiteValuationDivisor 6 =
      finiteValuationDivisor 2 + finiteValuationDivisor 3 := by
    simpa using finiteValuationDivisor_mul
      (m := 2) (n := 3) (by norm_num) (by norm_num)
  apply DivisorSymbol.ext
  · change finiteValuationDivisor 1 - finiteValuationDivisor 6 = _
    rw [h6, finiteValuationDivisor_one]
    simp
  · change finiteValuationDivisor 5 - finiteValuationDivisor 6 = _
    rw [h6]

theorem cellSymbol_oneThird : cellSymbol oneThirdCell =
    ⟨-finiteValuationDivisor 3,
      finiteValuationDivisor 2 - finiteValuationDivisor 3⟩ := by
  apply DivisorSymbol.ext
  · ext p
    simp [cellSymbol, oneThirdCell]
  · ext p
    simp [cellSymbol, oneThirdCell]

theorem cellSymbol_oneFifth : cellSymbol oneFifthCell =
    ⟨-finiteValuationDivisor 5,
      finiteValuationDivisor 2 + finiteValuationDivisor 2 -
        finiteValuationDivisor 5⟩ := by
  have h4 : finiteValuationDivisor 4 =
      finiteValuationDivisor 2 + finiteValuationDivisor 2 := by
    simpa using finiteValuationDivisor_mul
      (m := 2) (n := 2) (by norm_num) (by norm_num)
  apply DivisorSymbol.ext
  · ext p
    simp [cellSymbol, oneFifthCell]
  · change finiteValuationDivisor 4 - finiteValuationDivisor 5 = _
    rw [h4]

theorem cellSymbol_threeFifths : cellSymbol threeFifthsCell =
    ⟨finiteValuationDivisor 3 - finiteValuationDivisor 5,
      finiteValuationDivisor 2 - finiteValuationDivisor 5⟩ := by
  apply DivisorSymbol.ext
  · rfl
  · rfl

/-- A fully positive, reduced, nonvacuous realization of the classical
five-term move with `x=1/2` and `y=1/6`.  Its five arguments are
`1/2, 1/6, 1/3, 1/5, 3/5`. -/
noncomputable def halfSixthRealization : PositiveFiveTermRealization where
  xDivisor := -finiteValuationDivisor 2
  oneSubXDivisor := -finiteValuationDivisor 2
  yDivisor := -(finiteValuationDivisor 2 + finiteValuationDivisor 3)
  oneSubYDivisor := finiteValuationDivisor 5 -
    (finiteValuationDivisor 2 + finiteValuationDivisor 3)
  xSubYDivisor := -finiteValuationDivisor 3
  first := oneHalfCell
  second := oneSixthCell
  third := oneThirdCell
  fourth := oneFifthCell
  fifth := threeFifthsCell
  first_symbol := cellSymbol_oneHalf
  second_symbol := cellSymbol_oneSixth
  third_symbol := by
    rw [cellSymbol_oneThird]
    apply DivisorSymbol.ext <;> abel_nf
  fourth_symbol := by
    rw [cellSymbol_oneFifth]
    apply DivisorSymbol.ext <;> abel_nf
  fifth_symbol := by
    rw [cellSymbol_threeFifths]
    apply DivisorSymbol.ext <;> abel_nf

/-- Concrete actual-cell five-term surface identity a
`(x,y)=(1/2,1/6)`. -/
theorem halfSixth_surface_boundary :
    oneHalfCell.surface - oneSixthCell.surface + oneThirdCell.surface -
        oneFifthCell.surface + threeFifthsCell.surface = 0 :=
  halfSixthRealization.realized_surface_boundary

theorem cellSymbol_oneHalf_ne_oneSixth :
    cellSymbol oneHalfCell ≠ cellSymbol oneSixthCell := by
  rw [cellSymbol_oneHalf, cellSymbol_oneSixth]
  intro h
  have hv := congrArg (fun s : DivisorSymbol => s.valueDivisor 3) h
  norm_num [finiteValuationDivisor_apply] at hv

theorem cellSymbol_oneHalf_ne_oneThird :
    cellSymbol oneHalfCell ≠ cellSymbol oneThirdCell := by
  rw [cellSymbol_oneHalf, cellSymbol_oneThird]
  intro h
  have hv := congrArg (fun s : DivisorSymbol => s.valueDivisor 2) h
  norm_num [finiteValuationDivisor_apply] at hv

theorem cellSymbol_oneHalf_ne_oneFifth :
    cellSymbol oneHalfCell ≠ cellSymbol oneFifthCell := by
  rw [cellSymbol_oneHalf, cellSymbol_oneFifth]
  intro h
  have hv := congrArg (fun s : DivisorSymbol => s.valueDivisor 2) h
  norm_num [finiteValuationDivisor_apply] at hv

theorem cellSymbol_oneHalf_ne_threeFifths :
    cellSymbol oneHalfCell ≠ cellSymbol threeFifthsCell := by
  rw [cellSymbol_oneHalf, cellSymbol_threeFifths]
  intro h
  have hv := congrArg (fun s : DivisorSymbol => s.valueDivisor 2) h
  norm_num [finiteValuationDivisor_apply] at hv

/-- The concrete positive five-term move is nonzero as a formal free chain:
its coefficient at the `1/2` symbol is one. -/
theorem halfSixth_realizedChain_apply_oneHalf :
    halfSixthRealization.realizedChain (cellSymbol oneHalfCell) = 1 := by
  change (cellChain oneHalfCell - cellChain oneSixthCell +
      cellChain oneThirdCell - cellChain oneFifthCell +
        cellChain threeFifthsCell) (cellSymbol oneHalfCell) = 1
  simp [cellChain,
    cellSymbol_oneHalf_ne_oneSixth, cellSymbol_oneHalf_ne_oneThird,
    cellSymbol_oneHalf_ne_oneFifth, cellSymbol_oneHalf_ne_threeFifths]

theorem halfSixth_realizedChain_ne_zero :
    halfSixthRealization.realizedChain ≠ 0 := by
  intro h
  have happ := congrArg (fun c : DivisorSymbolChain =>
    c (cellSymbol oneHalfCell)) h
  rw [halfSixth_realizedChain_apply_oneHalf] at happ
  simp at happ

/-- Thus even on a genuine positive reduced five-term move, the formal
five-term chain is not literally zero.  Only its exterior boundary is zero. -/
theorem positive_realizedChain_not_always_zero :
    ¬ ∀ R : PositiveFiveTermRealization, R.realizedChain = 0 := by
  intro h
  exact halfSixth_realizedChain_ne_zero (h halfSixthRealization)

/-- The concrete positive move belongs to the actual generated relation. -/
theorem halfSixth_realizedChain_mem_positiveFiveTermRelation :
    halfSixthRealization.realizedChain ∈ positiveFiveTermRelation :=
  positiveFiveTermGenerator_mem halfSixthRealization

/-- Hence even the submodule generated only by actual positive reduced
moves is nontrivial. -/
theorem positiveFiveTermRelation_ne_bot : positiveFiveTermRelation ≠ ⊥ := by
  intro hbot
  have hmem := halfSixth_realizedChain_mem_positiveFiveTermRelation
  rw [hbot] at hmem
  have hz : halfSixthRealization.realizedChain = 0 := by
    simpa using hmem
  exact halfSixth_realizedChain_ne_zero hz

/-! ## Exact counterexample to two overstrong shortcuts -/

/-- The zero divisor symbol. -/
def zeroSymbol : DivisorSymbol := ⟨0, 0⟩

/-- With all five divisor inputs zero, the formal generator is a nonzero
basis chain even though its exterior boundary vanishes. -/
theorem fiveTermChain_all_zero_eq_single :
    fiveTermChain 0 0 0 0 0 = Finsupp.single zeroSymbol 1 := by
  classical
  simp [fiveTermChain, zeroSymbol]

theorem fiveTermChain_all_zero_ne_zero :
    fiveTermChain 0 0 0 0 0 ≠ 0 := by
  rw [fiveTermChain_all_zero_eq_single]
  simp

theorem not_all_fiveTermChains_eq_zero :
    ¬ ∀ X U Y V Z : FiniteDivisor, fiveTermChain X U Y V Z = 0 := by
  intro h
  exact fiveTermChain_all_zero_ne_zero (h 0 0 0 0 0)

theorem fiveTermChain_all_zero_equivalent_zero :
    FiveTermEquivalent (fiveTermChain 0 0 0 0 0) 0 := by
  unfold FiveTermEquivalent
  simpa using fiveTermGenerator_mem (0 : FiniteDivisor) 0 0 0 0

theorem fiveTermEquivalent_does_not_imply_chain_equality :
    ¬ ∀ c d : DivisorSymbolChain, FiveTermEquivalent c d → c = d := by
  intro h
  exact fiveTermChain_all_zero_ne_zero
    (h (fiveTermChain 0 0 0 0 0) 0 fiveTermChain_all_zero_equivalent_zero)

/-- Consequently the boundary map on the free symbol chain is not
injective.  This refutes the precise shortcut which tries to identify formal
chain equality with exterior-boundary equality. -/
theorem chainBoundary_not_injective : ¬ Function.Injective chainBoundary := by
  intro hinj
  have heq : fiveTermChain 0 0 0 0 0 = 0 := by
    apply hinj
    rw [fiveTermChain_boundary]
    exact map_zero chainBoundary
  exact fiveTermChain_all_zero_ne_zero heq

end
end SteinbergFiveTermBoundaryBridge20260903
end IUTThreeClosures
