/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.SteinbergValuationContactSurface20260902
import Mathlib.Algebra.GCDMonoid.Finset
import Mathlib.Data.Nat.Factorization.Root

/-!
# Integer exponent gcds and concrete finite Steinberg chains

This companion closes the arithmetic bridge in S-I2 and the exact-boundary
finite-support part of S-I4.  It deliberately does not define or prove that a
chain is generated by successive rational five-term moves.  The concrete
filling theorem assumes the exact finite-support surface equality which is
the only consequence of such generation needed by the automatic boundary
estimate.  The analytic Gate VF bounds remain open.
-/

namespace IUTThreeClosures
namespace SteinbergIntegerFiniteChain20260902

open SteinbergValuationContactSurface20260902

noncomputable section

/-- The gcd of the positive prime exponents of `n`, before the unit convention. -/
def rawExponentGCD (n : ℕ) : ℕ :=
  n.factorization.support.gcd n.factorization

/-- The gcd of the positive prime exponents, with the convention `g(1)=1`. -/
def exponentGCD (n : ℕ) : ℕ :=
  if n = 1 then 1 else rawExponentGCD n

/-- The canonical base obtained by dividing every positive prime exponent by `g(n)`. -/
def primitiveBase (n : ℕ) : ℕ :=
  Nat.floorRoot (exponentGCD n) n

@[simp] theorem exponentGCD_one : exponentGCD 1 = 1 := by
  simp [exponentGCD]

@[simp] theorem primitiveBase_one : primitiveBase 1 = 1 := by
  simp [primitiveBase]

theorem exists_factorization_support_of_one_lt {n : ℕ} (hn : 1 < n) :
    ∃ p ∈ n.factorization.support, n.factorization p ≠ 0 := by
  obtain ⟨p, hp, hpdvd⟩ := Nat.exists_prime_and_dvd hn.ne'
  have hn0 : n ≠ 0 := Nat.ne_of_gt (lt_trans Nat.zero_lt_one hn)
  have hpmem : p ∈ n.primeFactors := (Nat.mem_primeFactors.mpr ⟨hp, hpdvd, hn0⟩)
  have hpsupp : p ∈ n.factorization.support := by
    simpa only [Nat.support_factorization] using hpmem
  exact ⟨p, hpsupp, Finsupp.mem_support_iff.mp hpsupp⟩

theorem rawExponentGCD_pos {n : ℕ} (hn : 1 < n) :
    0 < rawExponentGCD n := by
  rw [Nat.pos_iff_ne_zero, rawExponentGCD, Finset.gcd_ne_zero_iff]
  exact exists_factorization_support_of_one_lt hn

theorem exponentGCD_pos {n : ℕ} (hn : 0 < n) :
    0 < exponentGCD n := by
  by_cases h1 : n = 1
  · simp [h1]
  · rw [exponentGCD, if_neg h1]
    exact rawExponentGCD_pos (Nat.one_lt_iff_ne_zero_and_ne_one.mpr ⟨hn.ne', h1⟩)

theorem exponentGCD_dvd_factorization {n p : ℕ} :
    exponentGCD n ∣ n.factorization p := by
  by_cases h1 : n = 1
  · simp [h1]
  · rw [exponentGCD, if_neg h1]
    by_cases hp : p ∈ n.factorization.support
    · exact Finset.gcd_dvd hp
    · rw [Finsupp.notMem_support_iff.mp hp]
      exact dvd_zero _

theorem primitiveBase_factorization (n : ℕ) :
    (primitiveBase n).factorization = n.factorization ⌊/⌋ exponentGCD n := by
  exact Nat.factorization_floorRoot _ _

theorem primitiveBase_pow_exponentGCD {n : ℕ} (hn : 0 < n) :
    primitiveBase n ^ exponentGCD n = n := by
  apply Nat.eq_of_factorization_eq'
  · exact pow_ne_zero _ (Nat.floorRoot_ne_zero.mpr
      ⟨(exponentGCD_pos hn).ne', hn.ne'⟩)
  · exact hn.ne'
  · rw [Nat.factorization_pow, primitiveBase_factorization n]
    ext p
    simp only [Finsupp.smul_apply, nsmul_eq_mul, Finsupp.floorDiv_apply,
      Nat.floorDiv_eq_div]
    exact Nat.mul_div_cancel' exponentGCD_dvd_factorization

theorem exponentGCD_power_decomposition {n : ℕ} (hn : 0 < n) :
    n = primitiveBase n ^ exponentGCD n :=
  (primitiveBase_pow_exponentGCD hn).symm

theorem primitiveBase_pos {n : ℕ} (hn : 0 < n) : 0 < primitiveBase n := by
  exact Nat.pos_iff_ne_zero.mpr (Nat.floorRoot_ne_zero.mpr
    ⟨(exponentGCD_pos hn).ne', hn.ne'⟩)

theorem primitiveBase_support_eq {n : ℕ} (hn : 1 < n) :
    (primitiveBase n).factorization.support = n.factorization.support := by
  have hnpos : 0 < n := lt_trans Nat.zero_lt_one hn
  rw [primitiveBase_factorization n]
  apply Finset.Subset.antisymm Finsupp.support_floorDiv_subset
  intro p hp
  rw [Finsupp.mem_support_iff] at hp ⊢
  simp only [Finsupp.floorDiv_apply, Nat.floorDiv_eq_div]
  have hgdvd := exponentGCD_dvd_factorization (n := n) (p := p)
  exact (Nat.div_pos
    (Nat.le_of_dvd (Nat.zero_lt_of_ne_zero hp) hgdvd)
    (exponentGCD_pos hnpos)).ne'

theorem primitiveBase_exponent_gcd_one {n : ℕ} (hn : 1 < n) :
    (primitiveBase n).factorization.support.gcd
      (primitiveBase n).factorization = 1 := by
  have hnpos : 0 < n := lt_trans Nat.zero_lt_one hn
  obtain ⟨p, hp, hp0⟩ := exists_factorization_support_of_one_lt hn
  rw [primitiveBase_support_eq hn, primitiveBase_factorization n,
    exponentGCD, if_neg hn.ne']
  calc
    n.factorization.support.gcd
          (n.factorization ⌊/⌋ rawExponentGCD n) =
        n.factorization.support.gcd
          (fun j => n.factorization j / rawExponentGCD n) := by
      apply Finset.gcd_congr rfl
      intro j _
      rfl
    _ = 1 := by
      simpa only [rawExponentGCD] using
        (Finset.gcd_div_eq_one (s := n.factorization.support)
          (f := n.factorization) hp hp0)

theorem primitiveBase_radical_eq {n : ℕ} (hn : 0 < n) :
    abcRadical (primitiveBase n) = abcRadical n := by
  by_cases h1 : n = 1
  · simp [h1]
  · rw [abcRadical_eq_natRadical, abcRadical_eq_natRadical]
    have hsupp := primitiveBase_support_eq
      (Nat.one_lt_iff_ne_zero_and_ne_one.mpr ⟨hn.ne', h1⟩)
    have hprimeFactors : (primitiveBase n).primeFactors = n.primeFactors := by
      simpa only [Nat.support_factorization] using hsupp
    rw [Nat.radical_eq_prod_primeFactors, Nat.radical_eq_prod_primeFactors,
      hprimeFactors]

/-- Logarithmic height of the canonical primitive base. -/
def primitiveBaseHeight (n : ℕ) : ℝ := legHeight (primitiveBase n)

/-- Coherent thickness along the common-exponent (Veronese) ray. -/
def coherentThickness (n : ℕ) : ℝ :=
  ((exponentGCD n : ℝ) - 1) * primitiveBaseHeight n

/-- Residual thickness left in the exponent-gcd-one primitive base. -/
def primitiveResidualThickness (n : ℕ) : ℝ :=
  primitiveBaseHeight n - legRadicalMass n

@[simp] theorem primitiveBaseHeight_one : primitiveBaseHeight 1 = 0 := by
  simp [primitiveBaseHeight, legHeight]

@[simp] theorem coherentThickness_one : coherentThickness 1 = 0 := by
  simp [coherentThickness]

@[simp] theorem primitiveResidualThickness_one : primitiveResidualThickness 1 = 0 := by
  simp [primitiveResidualThickness, legRadicalMass, abcRadical]

theorem legHeight_eq_exponentGCD_mul_primitiveBaseHeight
    {n : ℕ} (hn : 0 < n) :
    legHeight n = (exponentGCD n : ℝ) * primitiveBaseHeight n := by
  unfold legHeight primitiveBaseHeight
  calc
    Real.log (n : ℝ) =
        Real.log (((primitiveBase n ^ exponentGCD n : ℕ) : ℝ)) := by
      rw [primitiveBase_pow_exponentGCD hn]
    _ = Real.log ((primitiveBase n : ℝ) ^ exponentGCD n) := by
      norm_cast
    _ = (exponentGCD n : ℝ) * Real.log (primitiveBase n : ℝ) := by
      rw [Real.log_pow]

theorem primitiveBaseHeight_eq_height_div_exponentGCD
    {n : ℕ} (hn : 0 < n) :
    primitiveBaseHeight n = legHeight n / (exponentGCD n : ℝ) := by
  rw [legHeight_eq_exponentGCD_mul_primitiveBaseHeight hn]
  exact (mul_div_cancel_left₀ _ (by exact_mod_cast (exponentGCD_pos hn).ne')).symm

theorem exponentDefect_integer_veronese_residual
    {n : ℕ} (hn : 0 < n) :
    legHeight n - legRadicalMass n =
      coherentThickness n + primitiveResidualThickness n := by
  rw [legHeight_eq_exponentGCD_mul_primitiveBaseHeight hn]
  unfold coherentThickness primitiveResidualThickness
  ring

theorem primitiveBaseHeight_nonneg {n : ℕ} (hn : 0 < n) :
    0 ≤ primitiveBaseHeight n :=
  legHeight_nonneg (primitiveBase_pos hn)

theorem coherentThickness_nonneg {n : ℕ} (hn : 0 < n) :
    0 ≤ coherentThickness n := by
  unfold coherentThickness
  have hg : (1 : ℝ) ≤ exponentGCD n := by
    exact_mod_cast Nat.one_le_iff_ne_zero.mpr (exponentGCD_pos hn).ne'
  exact mul_nonneg (sub_nonneg.mpr hg) (primitiveBaseHeight_nonneg hn)

theorem primitiveResidualThickness_nonneg {n : ℕ} (hn : 0 < n) :
    0 ≤ primitiveResidualThickness n := by
  unfold primitiveResidualThickness primitiveBaseHeight
  apply sub_nonneg.mpr
  rw [show legRadicalMass n = legRadicalMass (primitiveBase n) by
    unfold legRadicalMass
    rw [primitiveBase_radical_eq hn]]
  exact legRadicalMass_le_legHeight (primitiveBase_pos hn)

/-! ## Actual finite-support divisor and exterior-coordinate objects -/

/-- The integral finite-prime divisor lattice. -/
abbrev FiniteDivisor := ℕ →₀ ℤ

/-- Ordered-pair coordinates for an alternating two-vector.  Storing both
orders makes finite support and signed-chain addition completely explicit;
the norm below divides the ordered sum by two. -/
abbrev ExteriorCoordinate := ℕ × ℕ

/-- Integral finite-support two-vectors. -/
abbrev FiniteExteriorSurface := ExteriorCoordinate →₀ ℤ

/-- Tensor product in the finitely supported coordinate model. -/
def finiteTensor (X Y : FiniteDivisor) : FiniteExteriorSurface :=
  Finsupp.onFinset (X.support ×ˢ Y.support)
    (fun pq => X pq.1 * Y pq.2) (by
      intro pq hpq
      by_contra hmem
      simp only [Finset.mem_product, not_and_or] at hmem
      rcases hmem with hp | hq
      · rw [Finsupp.notMem_support_iff.mp hp, zero_mul] at hpq
        exact hpq rfl
      · rw [Finsupp.notMem_support_iff.mp hq, mul_zero] at hpq
        exact hpq rfl)

@[simp] theorem finiteTensor_apply (X Y : FiniteDivisor) (p q : ℕ) :
    finiteTensor X Y (p, q) = X p * Y q := by
  rfl

/-- Exterior product in the actual finite-support divisor lattice. -/
def finiteWedge (X Y : FiniteDivisor) : FiniteExteriorSurface :=
  finiteTensor X Y - finiteTensor Y X

@[simp] theorem finiteWedge_apply (X Y : FiniteDivisor) (p q : ℕ) :
    finiteWedge X Y (p, q) = X p * Y q - X q * Y p := by
  simp [finiteWedge]
  ring

/-- Affine contact surface of three finitely supported divisor vertices. -/
def finiteContact (A B C : FiniteDivisor) : FiniteExteriorSurface :=
  finiteWedge (A - C) (B - C)

@[simp] theorem finiteContact_apply (A B C : FiniteDivisor) (p q : ℕ) :
    finiteContact A B C (p, q) =
      (A p - C p) * (B q - C q) - (A q - C q) * (B p - C p) := by
  simp [finiteContact]

/-- A natural number's integral divisor as an actual `Finsupp`. -/
def finiteValuationDivisor (n : ℕ) : FiniteDivisor :=
  n.factorization.mapRange (fun k : ℕ => (k : ℤ)) (by simp)

@[simp] theorem finiteValuationDivisor_apply (n p : ℕ) :
    finiteValuationDivisor n p = (n.factorization p : ℤ) := by
  simp [finiteValuationDivisor]

/-- A concrete positive reduced rational cell `left / total`, with
`middle = total-left` recorded as a positive natural number. -/
structure PositiveRationalCell where
  left : ℕ
  middle : ℕ
  total : ℕ
  left_pos : 0 < left
  middle_pos : 0 < middle
  sum_eq : left + middle = total
  reduced : Nat.Coprime left middle

namespace PositiveRationalCell

theorem total_pos (P : PositiveRationalCell) : 0 < P.total := by
  rw [← P.sum_eq]
  exact Nat.add_pos_left P.left_pos P.middle

theorem left_coprime_total (P : PositiveRationalCell) :
    Nat.Coprime P.left P.total := by
  rw [← P.sum_eq]
  exact Nat.coprime_self_add_right.mpr P.reduced

theorem middle_coprime_total (P : PositiveRationalCell) :
    Nat.Coprime P.middle P.total := by
  rw [← P.sum_eq]
  exact Nat.coprime_add_self_right.mpr P.reduced.symm

/-- The canonical rational number represented by the cell. -/
def value (P : PositiveRationalCell) : ℚ := P.left / P.total

theorem value_pos (P : PositiveRationalCell) : 0 < P.value := by
  exact div_pos (by exact_mod_cast P.left_pos) (by exact_mod_cast P.total_pos)

theorem value_lt_one (P : PositiveRationalCell) : P.value < 1 := by
  unfold value
  rw [div_lt_one (by exact_mod_cast P.total_pos)]
  exact_mod_cast (show P.left < P.total by
    rw [← P.sum_eq]
    exact Nat.lt_add_of_pos_right P.middle_pos)

/-- Its exact global finite-support divisor contact surface. -/
def surface (P : PositiveRationalCell) : FiniteExteriorSurface :=
  finiteContact (finiteValuationDivisor P.left)
    (finiteValuationDivisor P.middle) (finiteValuationDivisor P.total)

end PositiveRationalCell

/-- Pairwise disjoint supports, the finite-support form of primitive legs. -/
def PairwiseDisjointSupports (A B C : FiniteDivisor) : Prop :=
  Disjoint A.support B.support ∧ Disjoint B.support C.support ∧
    Disjoint C.support A.support

theorem positiveRationalCell_pairwiseDisjoint (P : PositiveRationalCell) :
    PairwiseDisjointSupports (finiteValuationDivisor P.left)
      (finiteValuationDivisor P.middle) (finiteValuationDivisor P.total) := by
  have hleft0 : P.left ≠ 0 := P.left_pos.ne'
  have hmiddle0 : P.middle ≠ 0 := P.middle_pos.ne'
  have htotal0 : P.total ≠ 0 := P.total_pos.ne'
  have hsupp (n : ℕ) :
      (finiteValuationDivisor n).support = n.primeFactors := by
    unfold finiteValuationDivisor
    rw [Finsupp.support_mapRange_of_injective]
    · exact Nat.support_factorization n
    · exact Int.ofNat_injective
  unfold PairwiseDisjointSupports
  rw [hsupp, hsupp, hsupp]
  exact
    And.intro
      ((Nat.disjoint_primeFactors hleft0 hmiddle0).mpr P.reduced)
      (And.intro
        ((Nat.disjoint_primeFactors hmiddle0 htotal0).mpr P.middle_coprime_total)
        ((Nat.disjoint_primeFactors htotal0 hleft0).mpr P.left_coprime_total.symm))

/-! ## Exact weighted norm of a primitive finite-support cell -/

/-- Effective finite divisors, used before embedding coefficients in `ℤ`. -/
abbrev EffectiveDivisor := ℕ →₀ ℕ

/-- Coefficientwise embedding of an effective divisor into the integral
divisor lattice. -/
def integralize (A : EffectiveDivisor) : FiniteDivisor :=
  A.mapRange (fun k : ℕ => (k : ℤ)) (by simp)

@[simp] theorem integralize_apply (A : EffectiveDivisor) (p : ℕ) :
    integralize A p = (A p : ℤ) := by
  simp [integralize]

/-- The actual finite-support surface of three effective divisor legs. -/
def effectiveContactSurface (A B C : EffectiveDivisor) :
    FiniteExteriorSurface := finiteContact (integralize A) (integralize B)
      (integralize C)

@[simp] theorem effectiveContactSurface_apply
    (A B C : EffectiveDivisor) (p q : ℕ) :
    effectiveContactSurface A B C (p, q) =
      ((A p : ℤ) - C p) * ((B q : ℤ) - C q) -
        ((A q : ℤ) - C q) * ((B p : ℤ) - C p) := by
  simp [effectiveContactSurface]

theorem effectiveContactSurface_threeLeg_apply
    (A B C : EffectiveDivisor) (p q : ℕ) :
    effectiveContactSurface A B C (p, q) =
      (A p : ℤ) * B q - (A q : ℤ) * B p +
      ((B p : ℤ) * C q - (B q : ℤ) * C p) +
      ((C p : ℤ) * A q - (C q : ℤ) * A p) := by
  rw [effectiveContactSurface_apply]
  ring

def EffectivePairwiseDisjoint (A B C : EffectiveDivisor) : Prop :=
  Disjoint A.support B.support ∧ Disjoint B.support C.support ∧
    Disjoint C.support A.support

theorem apply_eq_zero_of_disjoint_support_right
    {A B : EffectiveDivisor} (h : Disjoint A.support B.support)
    {p : ℕ} (hp : A p ≠ 0) : B p = 0 := by
  by_contra hBp
  exact Finset.disjoint_left.mp h
    (Finsupp.mem_support_iff.mpr hp) (Finsupp.mem_support_iff.mpr hBp)

theorem effective_coordinate_cases
    {A B C : EffectiveDivisor} (h : EffectivePairwiseDisjoint A B C)
    (p : ℕ) :
    (B p = 0 ∧ C p = 0) ∨ (A p = 0 ∧ C p = 0) ∨
      (A p = 0 ∧ B p = 0) := by
  by_cases hA : A p = 0
  · by_cases hB : B p = 0
    · exact Or.inr (Or.inr ⟨hA, hB⟩)
    · exact Or.inr (Or.inl ⟨hA,
        apply_eq_zero_of_disjoint_support_right h.2.1 hB⟩)
  · exact Or.inl
      ⟨apply_eq_zero_of_disjoint_support_right h.1 hA,
        apply_eq_zero_of_disjoint_support_right h.2.2.symm hA⟩

@[simp] theorem int_natAbs_natCast_mul (a b : ℕ) :
    ((a : ℤ) * (b : ℤ)).natAbs = a * b := by
  rw [Int.natAbs_mul]
  simp

/-- At every ordered prime pair the absolute coefficient is the sum of the
six directed rectangular-block products. -/
theorem effectiveContactSurface_natAbs
    {A B C : EffectiveDivisor} (h : EffectivePairwiseDisjoint A B C)
    (p q : ℕ) :
    (effectiveContactSurface A B C (p, q)).natAbs =
      A p * B q + B p * A q + B p * C q + C p * B q +
        C p * A q + A p * C q := by
  obtain hp | hp | hp := effective_coordinate_cases h p <;>
    obtain hq | hq | hq := effective_coordinate_cases h q <;>
    simp [hp.1, hp.2, hq.1, hq.2] <;> ring

/-- Weighted mass of one effective divisor on a finite coordinate set. -/
def weightedMassOn (S : Finset ℕ) (w : ℕ → ℝ)
    (A : EffectiveDivisor) : ℝ :=
  ∑ p ∈ S, (A p : ℝ) * w p

/-- The weighted `ell^1` norm of an effective contact surface, computed on
the finite ordered coordinate square and divided by two for alternation. -/
def weightedContactNormOn (S : Finset ℕ) (w : ℕ → ℝ)
    (A B C : EffectiveDivisor) : ℝ :=
  (1 / 2 : ℝ) *
    ∑ p ∈ S, ∑ q ∈ S,
      ((effectiveContactSurface A B C (p, q)).natAbs : ℝ) * w p * w q

/-- Exact finite-support mixed-area identity.  No convergence claim is
hidden: every sum is over the displayed finite set `S`. -/
theorem weightedContactNormOn_eq_mixedArea
    {A B C : EffectiveDivisor} (h : EffectivePairwiseDisjoint A B C)
    (S : Finset ℕ) (w : ℕ → ℝ) :
    weightedContactNormOn S w A B C =
      weightedMassOn S w A * weightedMassOn S w B +
      weightedMassOn S w B * weightedMassOn S w C +
      weightedMassOn S w C * weightedMassOn S w A := by
  classical
  unfold weightedContactNormOn weightedMassOn
  simp_rw [effectiveContactSurface_natAbs h, Nat.cast_add, Nat.cast_mul]
  ring_nf
  simp_rw [Finset.sum_add_distrib]
  have hdouble (D E : EffectiveDivisor) :
      (∑ x ∈ S, ∑ y ∈ S,
          (D x : ℝ) * (E y : ℝ) * w x * w y) =
        (∑ x ∈ S, (D x : ℝ) * w x) *
          ∑ y ∈ S, (E y : ℝ) * w y := by
    rw [Finset.sum_mul_sum]
    apply Finset.sum_congr rfl
    intro x _
    apply Finset.sum_congr rfl
    intro y _
    ring
  have hdouble' (D E : EffectiveDivisor) :
      (∑ x ∈ S, ∑ y ∈ S,
          (E y : ℝ) * (D x : ℝ) * w x * w y) =
        (∑ x ∈ S, (D x : ℝ) * w x) *
          ∑ y ∈ S, (E y : ℝ) * w y := by
    rw [Finset.sum_mul_sum]
    apply Finset.sum_congr rfl
    intro x _
    apply Finset.sum_congr rfl
    intro y _
    ring
  rw [hdouble A B, hdouble A C, hdouble' C B, hdouble B A,
    hdouble B C, hdouble' C A]
  ring

theorem weightedMassOn_factorization_eq_legHeight
    (n : ℕ) (S : Finset ℕ) (hsub : n.factorization.support ⊆ S) :
    weightedMassOn S (fun p => Real.log (p : ℝ)) n.factorization =
      legHeight n := by
  unfold weightedMassOn legHeight
  rw [Real.log_nat_eq_sum_factorization]
  change (∑ p ∈ S, (n.factorization p : ℝ) * Real.log (p : ℝ)) =
    ∑ p ∈ n.factorization.support,
      (n.factorization p : ℝ) * Real.log (p : ℝ)
  symm
  apply Finset.sum_subset hsub
  intro p _ hp
  rw [Finsupp.notMem_support_iff.mp hp]
  simp

namespace PositiveRationalCell

/-- The finite union of the three actual prime supports of a rational cell. -/
def primeSupport (P : PositiveRationalCell) : Finset ℕ :=
  P.left.factorization.support ∪ P.middle.factorization.support ∪
    P.total.factorization.support

theorem left_support_subset (P : PositiveRationalCell) :
    P.left.factorization.support ⊆ P.primeSupport := by
  intro p hp
  exact Finset.mem_union_left _ (Finset.mem_union_left _ hp)

theorem middle_support_subset (P : PositiveRationalCell) :
    P.middle.factorization.support ⊆ P.primeSupport := by
  intro p hp
  exact Finset.mem_union_left _ (Finset.mem_union_right _ hp)

theorem total_support_subset (P : PositiveRationalCell) :
    P.total.factorization.support ⊆ P.primeSupport := by
  intro p hp
  exact Finset.mem_union_right _ hp

theorem effectivePairwiseDisjoint (P : PositiveRationalCell) :
    EffectivePairwiseDisjoint P.left.factorization P.middle.factorization
      P.total.factorization := by
  have hleft0 : P.left ≠ 0 := P.left_pos.ne'
  have hmiddle0 : P.middle ≠ 0 := P.middle_pos.ne'
  have htotal0 : P.total ≠ 0 := P.total_pos.ne'
  unfold EffectivePairwiseDisjoint
  simpa only [Nat.support_factorization] using
    And.intro
      ((Nat.disjoint_primeFactors hleft0 hmiddle0).mpr P.reduced)
      (And.intro
        ((Nat.disjoint_primeFactors hmiddle0 htotal0).mpr P.middle_coprime_total)
        ((Nat.disjoint_primeFactors htotal0 hleft0).mpr P.left_coprime_total.symm))

/-- The exact logarithmically weighted norm of the actual divisor surface. -/
def logWeightedNorm (P : PositiveRationalCell) : ℝ :=
  weightedContactNormOn P.primeSupport (fun p => Real.log (p : ℝ))
    P.left.factorization P.middle.factorization P.total.factorization

theorem logWeightedNorm_eq_fullContactArea (P : PositiveRationalCell) :
    P.logWeightedNorm =
      fullContactArea (legHeight P.left) (legHeight P.middle)
        (legHeight P.total) := by
  rw [logWeightedNorm, weightedContactNormOn_eq_mixedArea
    P.effectivePairwiseDisjoint]
  rw [weightedMassOn_factorization_eq_legHeight _ _ P.left_support_subset,
    weightedMassOn_factorization_eq_legHeight _ _ P.middle_support_subset,
    weightedMassOn_factorization_eq_legHeight _ _ P.total_support_subset]
  rfl

/-- The one-sided radical polarization of a canonical rational cell. -/
def mixedCost (P : PositiveRationalCell) : ℝ :=
  mixedRadicalContactArea (legHeight P.left) (legHeight P.middle)
    (legHeight P.total) (legRadicalMass P.left)
    (legRadicalMass P.middle) (legRadicalMass P.total)

/-- The coherent common-exponent contribution to the contact loss. -/
def coherentCost (P : PositiveRationalCell) : ℝ :=
  contactLossFromDefects (coherentThickness P.left)
    (coherentThickness P.middle) (coherentThickness P.total)
    (legHeight P.left) (legHeight P.middle) (legHeight P.total)

/-- The primitive-base residual contribution to the contact loss. -/
def residualCost (P : PositiveRationalCell) : ℝ :=
  contactLossFromDefects (primitiveResidualThickness P.left)
    (primitiveResidualThickness P.middle)
    (primitiveResidualThickness P.total) (legHeight P.left)
    (legHeight P.middle) (legHeight P.total)

/-- Arithmetic cell identity `2 Phi = M + V + R`, now with `Phi` the
weighted norm of the concrete finite-support divisor surface and with `V,R`
coming from the canonical integer exponent decomposition. -/
theorem two_logWeightedNorm_eq_mixed_coherent_residual
    (P : PositiveRationalCell) :
    2 * P.logWeightedNorm = P.mixedCost + P.coherentCost + P.residualCost := by
  rw [P.logWeightedNorm_eq_fullContactArea]
  have hleft := exponentDefect_integer_veronese_residual P.left_pos
  have hmiddle := exponentDefect_integer_veronese_residual P.middle_pos
  have htotal := exponentDefect_integer_veronese_residual P.total_pos
  have hpolar := two_fullContactArea_sub_mixedRadicalContactArea
    (legHeight P.left) (legHeight P.middle) (legHeight P.total)
    (legRadicalMass P.left) (legRadicalMass P.middle)
    (legRadicalMass P.total)
  unfold mixedCost coherentCost residualCost at ⊢
  unfold contactLossFromDefects at hpolar ⊢
  rw [hleft, hmiddle, htotal] at hpolar
  linarith

end PositiveRationalCell

/-! ## A finite rational chain and the concrete filling instantiation -/

/-- A finite signed chain of canonical positive reduced rational cells.  The
boundary equation is an equality in the actual integral finite-support
exterior coordinate module.  This is exactly the hypothesis used by the
automatic boundary estimate. -/
structure FiniteRationalCellChain (I : Type*) [Fintype I] where
  target : PositiveRationalCell
  cell : I → PositiveRationalCell
  coefficient : I → ℤ
  boundary : target.surface =
    ∑ j, coefficient j • (cell j).surface

/-- A weighted real coordinate on the finite square `S × S`, obtained
from an integral exterior surface.  The factor `1/2` compensates for storing
both orientations. -/
def restrictedWeightedCoordinate (S : Finset ℕ) (w : ℕ → ℝ)
    (omega : FiniteExteriorSurface) (pq : S × S) : ℝ :=
  (1 / 2 : ℝ) * (omega (pq.1.1, pq.2.1) : ℝ) * w pq.1.1 * w pq.2.1

/-- The finite coordinate sum is exactly the ordered-pair weighted norm.
This lemma is the bridge from actual `Finsupp` surfaces to the `Fintype`
interface of `finiteFilling_boundary_le_calibratedCost`. -/
theorem sum_abs_restrictedWeightedCoordinate
    (S : Finset ℕ) (w : ℕ → ℝ) (omega : FiniteExteriorSurface)
    (hw : ∀ p ∈ S, 0 ≤ w p) :
    (∑ pq : S × S, |restrictedWeightedCoordinate S w omega pq|) =
      (1 / 2 : ℝ) *
        ∑ p ∈ S, ∑ q ∈ S,
          ((omega (p, q)).natAbs : ℝ) * w p * w q := by
  classical
  rw [Fintype.sum_prod_type]
  unfold restrictedWeightedCoordinate
  let F : ℕ → ℕ → ℝ := fun p q =>
    |(1 / 2 : ℝ) * (omega (p, q) : ℝ) * w p * w q|
  change (∑ p : S, ∑ q : S, F p.1 q.1) = _
  calc
    (∑ p : S, ∑ q : S, F p.1 q.1) =
        ∑ p ∈ S, ∑ q ∈ S, F p q := by
      rw [Finset.sum_coe_sort S (fun p => ∑ q : S, F p q.1)]
      apply Finset.sum_congr rfl
      intro p _
      exact Finset.sum_coe_sort S (F p)
    _ = ∑ p ∈ S, ∑ q ∈ S,
          (1 / 2 : ℝ) * ((omega (p, q)).natAbs : ℝ) * w p * w q := by
      apply Finset.sum_congr rfl
      intro p hp
      apply Finset.sum_congr rfl
      intro q hq
      dsimp [F]
      rw [abs_mul, abs_mul, abs_mul]
      simp only [abs_of_nonneg (show (0 : ℝ) ≤ 1 / 2 by norm_num),
        abs_of_nonneg (hw p hp), abs_of_nonneg (hw q hq)]
      simp
    _ = (1 / 2 : ℝ) *
        ∑ p ∈ S, ∑ q ∈ S,
          ((omega (p, q)).natAbs : ℝ) * w p * w q := by
      simp_rw [Finset.mul_sum]
      ring_nf

namespace PositiveRationalCell

theorem surface_eq_effectiveContactSurface (P : PositiveRationalCell) :
    P.surface = effectiveContactSurface P.left.factorization
      P.middle.factorization P.total.factorization := by
  rfl

theorem prime_of_mem_primeSupport (P : PositiveRationalCell) {p : ℕ}
    (hp : p ∈ P.primeSupport) : p.Prime := by
  unfold primeSupport at hp
  rcases Finset.mem_union.mp hp with hpLM | hpT
  · rcases Finset.mem_union.mp hpLM with hpL | hpM
    · exact Nat.prime_of_mem_primeFactors (by
        simpa only [Nat.support_factorization] using hpL)
    · exact Nat.prime_of_mem_primeFactors (by
        simpa only [Nat.support_factorization] using hpM)
  · exact Nat.prime_of_mem_primeFactors (by
      simpa only [Nat.support_factorization] using hpT)

theorem weightedContactNormOn_eq_logWeightedNorm_of_subset
    (P : PositiveRationalCell) (S : Finset ℕ)
    (hPS : P.primeSupport ⊆ S) :
    weightedContactNormOn S (fun p => Real.log (p : ℝ))
        P.left.factorization P.middle.factorization P.total.factorization =
      P.logWeightedNorm := by
  rw [weightedContactNormOn_eq_mixedArea P.effectivePairwiseDisjoint]
  rw [weightedMassOn_factorization_eq_legHeight _ _
      (P.left_support_subset.trans hPS),
    weightedMassOn_factorization_eq_legHeight _ _
      (P.middle_support_subset.trans hPS),
    weightedMassOn_factorization_eq_legHeight _ _
      (P.total_support_subset.trans hPS),
    P.logWeightedNorm_eq_fullContactArea]
  rfl

end PositiveRationalCell

namespace FiniteRationalCellChain

variable {I : Type*} [Fintype I]

/-- The finite union of every prime support occurring in the target and
chain cells. -/
def primeSupport (Gamma : FiniteRationalCellChain I) : Finset ℕ :=
  Gamma.target.primeSupport ∪
    Finset.univ.biUnion fun j => (Gamma.cell j).primeSupport

theorem target_primeSupport_subset (Gamma : FiniteRationalCellChain I) :
    Gamma.target.primeSupport ⊆ Gamma.primeSupport := by
  intro p hp
  exact Finset.mem_union_left _ hp

theorem cell_primeSupport_subset (Gamma : FiniteRationalCellChain I)
    (j : I) : (Gamma.cell j).primeSupport ⊆ Gamma.primeSupport := by
  classical
  intro p hp
  apply Finset.mem_union_right
  exact Finset.mem_biUnion.mpr ⟨j, Finset.mem_univ _, hp⟩

theorem log_nonneg_on_primeSupport (Gamma : FiniteRationalCellChain I)
    {p : ℕ} (hp : p ∈ Gamma.primeSupport) :
    0 ≤ Real.log (p : ℝ) := by
  classical
  rw [primeSupport, Finset.mem_union] at hp
  have hprime : p.Prime := by
    rcases hp with hp | hp
    · exact Gamma.target.prime_of_mem_primeSupport hp
    · obtain ⟨j, _, hpj⟩ := Finset.mem_biUnion.mp hp
      exact (Gamma.cell j).prime_of_mem_primeSupport hpj
  exact Real.log_nonneg (by exact_mod_cast hprime.one_le)

theorem coordinateNorm_eq_cellNorm
    (Gamma : FiniteRationalCellChain I) (P : PositiveRationalCell)
    (hP : P.primeSupport ⊆ Gamma.primeSupport) :
    (∑ pq : Gamma.primeSupport × Gamma.primeSupport,
      |restrictedWeightedCoordinate Gamma.primeSupport
        (fun p => Real.log (p : ℝ)) P.surface pq|) = P.logWeightedNorm := by
  rw [sum_abs_restrictedWeightedCoordinate]
  · rw [P.surface_eq_effectiveContactSurface]
    exact P.weightedContactNormOn_eq_logWeightedNorm_of_subset _ hP
  · intro p hp
    exact Gamma.log_nonneg_on_primeSupport hp

theorem coordinate_boundary (Gamma : FiniteRationalCellChain I) :
    ∀ pq : Gamma.primeSupport × Gamma.primeSupport,
      restrictedWeightedCoordinate Gamma.primeSupport
          (fun p => Real.log (p : ℝ)) Gamma.target.surface pq =
        ∑ j, (Gamma.coefficient j : ℝ) *
          restrictedWeightedCoordinate Gamma.primeSupport
            (fun p => Real.log (p : ℝ)) (Gamma.cell j).surface pq := by
  classical
  intro pq
  let ev : FiniteExteriorSurface →+ ℤ :=
    { toFun := fun omega => omega (pq.1.1, pq.2.1)
      map_zero' := by simp
      map_add' := by intro x y; simp }
  have hcoord : Gamma.target.surface (pq.1.1, pq.2.1) =
      ∑ j, Gamma.coefficient j *
        (Gamma.cell j).surface (pq.1.1, pq.2.1) := by
    calc
      Gamma.target.surface (pq.1.1, pq.2.1) = ev Gamma.target.surface := rfl
      _ = ev (∑ j, Gamma.coefficient j • (Gamma.cell j).surface) :=
        congrArg ev Gamma.boundary
      _ = ∑ j ∈ Finset.univ,
          ev (Gamma.coefficient j • (Gamma.cell j).surface) := by
        apply map_sum
      _ = ∑ j, Gamma.coefficient j *
          (Gamma.cell j).surface (pq.1.1, pq.2.1) := by
        simp [ev]
  unfold restrictedWeightedCoordinate
  have hcoordReal :
      (Gamma.target.surface (pq.1.1, pq.2.1) : ℝ) =
        ∑ j, (Gamma.coefficient j : ℝ) *
          (Gamma.cell j).surface (pq.1.1, pq.2.1) := by
    exact_mod_cast hcoord
  rw [hcoordReal]
  let lp := Real.log (pq.1.1 : ℝ)
  let lq := Real.log (pq.2.1 : ℝ)
  change (1 / 2 : ℝ) *
      (∑ j, (Gamma.coefficient j : ℝ) *
        (Gamma.cell j).surface (pq.1.1, pq.2.1)) * lp * lq =
    ∑ j, (Gamma.coefficient j : ℝ) *
      ((1 / 2 : ℝ) *
        ((Gamma.cell j).surface (pq.1.1, pq.2.1) : ℝ) * lp * lq)
  rw [Finset.mul_sum, Finset.sum_mul, Finset.sum_mul]
  apply Finset.sum_congr rfl
  intro j _
  ring

/-- Concrete instantiation of
`finiteFilling_boundary_le_calibratedCost` for a signed finite chain of
canonical reduced positive rational cells and their actual finite-support
divisor surfaces. -/
theorem boundary_le_calibratedCost (Gamma : FiniteRationalCellChain I) :
    Gamma.target.logWeightedNorm ≤
      (1 / 2 : ℝ) *
        ((∑ j, |(Gamma.coefficient j : ℝ)| *
            ((Gamma.cell j).mixedCost + (Gamma.cell j).coherentCost)) +
          ∑ j, |(Gamma.coefficient j : ℝ)| *
            (Gamma.cell j).residualCost) := by
  let omega := fun j (pq : Gamma.primeSupport × Gamma.primeSupport) =>
    restrictedWeightedCoordinate Gamma.primeSupport
      (fun p => Real.log (p : ℝ)) (Gamma.cell j).surface pq
  let omega0 := fun pq : Gamma.primeSupport × Gamma.primeSupport =>
    restrictedWeightedCoordinate Gamma.primeSupport
      (fun p => Real.log (p : ℝ)) Gamma.target.surface pq
  have hcell : ∀ j,
      2 * (∑ pq, |omega j pq|) =
        (Gamma.cell j).mixedCost + (Gamma.cell j).coherentCost +
          (Gamma.cell j).residualCost := by
    intro j
    rw [show (∑ pq, |omega j pq|) = (Gamma.cell j).logWeightedNorm by
      exact Gamma.coordinateNorm_eq_cellNorm (Gamma.cell j)
        (Gamma.cell_primeSupport_subset j)]
    exact (Gamma.cell j).two_logWeightedNorm_eq_mixed_coherent_residual
  have h := finiteFilling_boundary_le_calibratedCost
    (n := fun j => (Gamma.coefficient j : ℝ)) (omega := omega)
    (omega0 := omega0) (mixed := fun j => (Gamma.cell j).mixedCost)
    (coherent := fun j => (Gamma.cell j).coherentCost)
    (residual := fun j => (Gamma.cell j).residualCost)
    Gamma.coordinate_boundary hcell
  rw [show (∑ pq, |omega0 pq|) = Gamma.target.logWeightedNorm by
    exact Gamma.coordinateNorm_eq_cellNorm Gamma.target
      Gamma.target_primeSupport_subset] at h
  exact h

end FiniteRationalCellChain

end
end SteinbergIntegerFiniteChain20260902
end IUTThreeClosures
