/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.TateThetaOddGraphDescent
import Mathlib.GroupTheory.GroupAction.Basic

/-!
# The free integer action generated by odd graph-period descent

For the odd theta-root self-equivalence constructed in
`TateThetaOddGraphDescent`, this file forms its integral iterates and proves
that they define a free `ℤ`-action.  The proof is geometric in the minimal
sense that it uses the actual base coordinate: the `n`-th iterate multiplies
that coordinate by `(q^(2*k+1))^n`, and a Tate parameter has infinite order.

No quotient topology, proper-discontinuity statement, analytic structure, or
tempered fundamental group is asserted here.
-/

namespace IUTThreeClosures

open TateCurvesTheta

universe u

variable {K : Type u} [NormedField K] [CompleteSpace K]

namespace TateThetaRootPoint

/-- The `n`-th integral iterate of the odd graph-period equivalence. -/
noncomputable def oddPeriodShiftIterate
    (t : TateParameter K) (k : ℕ) (n : ℤ) :
    TateThetaRootPoint t (2 * k + 1) ≃
      TateThetaRootPoint t (2 * k + 1) :=
  (oddPeriodShiftEquiv t k) ^ n

@[simp]
theorem oddPeriodShiftIterate_zero
    (t : TateParameter K) (k : ℕ)
    (z : TateThetaRootPoint t (2 * k + 1)) :
    oddPeriodShiftIterate t k 0 z = z := by
  simp [oddPeriodShiftIterate]

@[simp]
theorem oddPeriodShiftIterate_one
    (t : TateParameter K) (k : ℕ)
    (z : TateThetaRootPoint t (2 * k + 1)) :
    oddPeriodShiftIterate t k 1 z = oddPeriodShift t k z := by
  rfl

/-- Integral iterates obey the addition law in the order appropriate to a
left action. -/
theorem oddPeriodShiftIterate_add
    (t : TateParameter K) (k : ℕ) (m n : ℤ)
    (z : TateThetaRootPoint t (2 * k + 1)) :
    oddPeriodShiftIterate t k (m + n) z =
      oddPeriodShiftIterate t k m (oddPeriodShiftIterate t k n z) := by
  simp only [oddPeriodShiftIterate, zpow_add, Equiv.Perm.mul_apply]

/-- The inverse graph-period equivalence multiplies the base coordinate by
`(q^(2*k+1))⁻¹`. -/
@[simp]
theorem oddPeriodShiftEquiv_inv_base
    (t : TateParameter K) (k : ℕ)
    (z : TateThetaRootPoint t (2 * k + 1)) :
    (((oddPeriodShiftEquiv t k) ⁻¹)
        z).base =
      (t.q ^ (2 * k + 1))⁻¹ * z.base :=
  rfl

/-- Exact base-coordinate formula for every positive or negative graph
iterate. -/
theorem oddPeriodShiftIterate_base
    (t : TateParameter K) (k : ℕ) (n : ℤ)
    (z : TateThetaRootPoint t (2 * k + 1)) :
    (oddPeriodShiftIterate t k n z).base =
      (t.q ^ (2 * k + 1)) ^ n * z.base := by
  induction n using Int.induction_on generalizing z with
  | zero => simp
  | succ n ih =>
      rw [oddPeriodShiftIterate, zpow_add_one, Equiv.Perm.mul_apply]
      change
        (oddPeriodShiftIterate t k (n : ℤ)
          (oddPeriodShiftEquiv t k z)).base = _
      rw [ih, oddPeriodShiftEquiv_base, zpow_add_one]
      group
  | pred n ih =>
      rw [oddPeriodShiftIterate, zpow_sub_one, Equiv.Perm.mul_apply]
      change
        (oddPeriodShiftIterate t k (-(n : ℤ))
          ((oddPeriodShiftEquiv t k) ⁻¹ z)).base = _
      rw [ih, oddPeriodShiftEquiv_inv_base, zpow_sub_one]
      group

omit [CompleteSpace K] in
/-- A Tate parameter, regarded as a unit, has infinite multiplicative order. -/
theorem tateParameter_q_not_isOfFinOrder (t : TateParameter K) :
    ¬ IsOfFinOrder t.q := by
  intro hfinite
  obtain ⟨n, hn, hpow⟩ := hfinite.exists_pow_eq_one
  have hpowK : (t.q : K) ^ n = 1 := by
    simpa using congrArg (fun w : Kˣ => (w : K)) hpow
  exact t.pow_ne_one hn hpowK

/-- No nonzero integral iterate fixes a point of the theta-root locus.  This
is the pointwise freeness statement, before packaging it as an action class. -/
theorem oddPeriodShiftIterate_eq_self_iff
    (t : TateParameter K) (k : ℕ) (n : ℤ)
    (z : TateThetaRootPoint t (2 * k + 1)) :
    oddPeriodShiftIterate t k n z = z ↔ n = 0 := by
  constructor
  · intro hfixed
    have hbase := congrArg TateThetaRootPoint.base hfixed
    rw [oddPeriodShiftIterate_base] at hbase
    have hperiod : (t.q ^ (2 * k + 1)) ^ n = 1 := by
      apply mul_right_cancel (b := z.base)
      simpa using hbase
    have hperiodInfinite : ¬ IsOfFinOrder (t.q ^ (2 * k + 1)) := by
      intro hfinite
      exact tateParameter_q_not_isOfFinOrder t
        (hfinite.of_pow (by omega))
    apply (injective_zpow_iff_not_isOfFinOrder.mpr hperiodInfinite)
    simpa using hperiod
  · rintro rfl
    exact oddPeriodShiftIterate_zero t k z

/-- The additive action of `ℤ` generated by the odd graph-period
self-equivalence. -/
@[reducible]
noncomputable def oddPeriodShiftAddAction
    (t : TateParameter K) (k : ℕ) :
    AddAction ℤ (TateThetaRootPoint t (2 * k + 1)) where
  vadd n z := oddPeriodShiftIterate t k n z
  zero_vadd := oddPeriodShiftIterate_zero t k
  add_vadd := oddPeriodShiftIterate_add t k

/-- The packaged integer action is free in Mathlib's standard sense: its
point stabilizers are trivial. -/
theorem oddPeriodShiftAddAction_isCancelVAdd
    (t : TateParameter K) (k : ℕ) :
    letI := oddPeriodShiftAddAction t k
    IsCancelVAdd ℤ (TateThetaRootPoint t (2 * k + 1)) := by
  letI := oddPeriodShiftAddAction t k
  rw [isCancelVAdd_iff_eq_zero_of_vadd_eq]
  intro n z hfixed
  exact (oddPeriodShiftIterate_eq_self_iff t k n z).mp hfixed

end TateThetaRootPoint

end IUTThreeClosures
