/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.TateThetaRootZAction
import Mathlib.Topology.Instances.AddCircle.Real

/-!
# The quotient tower `shift^(ell Z) -> shift^Z`

Let `T` be the corrected theta-root deck generator.  There are two distinct
orbit quotients of the pulled-back analytic locus:

* quotient by `T^(ell Z)`, corresponding to the `ell`-sheeted theta-root cover;
* quotient by `T^Z`, corresponding to the base Tate cycle.

The first orbit relation refines the second, so the identity on the pulled-back
locus descends to a canonical map from the cover quotient to the base quotient.

The normalized radial coordinate descends on the two quotients as

`rho / ell mod Z` and `rho mod Z`.

The quotient map intertwines these coordinates by multiplication by `ell` on
the unit additive circle.  Thus the finite-degree skeleton map is constructed
from the genuine deck action rather than postulated.

No claim is made here that the set-theoretic quotient already carries the full
Berkovich analytic structure; topology and covering-space properties are
separate subsequent theorems.
-/

namespace IUTThreeClosures

open TateCurvesTheta

universe u

variable {K : Type u} [NormedField K] [CompleteSpace K]

namespace TateThetaRootRadialSkeleton

variable (t : TateParameter K) (ell : ℕ)
variable (r : Kˣ) (hr : r ^ ell = t.q)

/-- Full integer-orbit relation for the corrected deck generator. -/
def IntegerOrbitRelated
    (x y : TateThetaRootPullbackPoint t ell) : Prop :=
  ∃ n : ℤ, deckZ t ell r hr n x = y

/-- Orbit relation for the subgroup generated by the original Tate period
`T^ell`. -/
def EllPeriodOrbitRelated
    (x y : TateThetaRootPullbackPoint t ell) : Prop :=
  ∃ n : ℤ, deckZ t ell r hr ((ell : ℤ) * n) x = y

/-- Full integer-orbit relation is reflexive. -/
theorem integerOrbitRelated_refl
    (x : TateThetaRootPullbackPoint t ell) :
    IntegerOrbitRelated t ell r hr x x := by
  exact ⟨0, by simp⟩

/-- Full integer-orbit relation is symmetric. -/
theorem integerOrbitRelated_symm
    {x y : TateThetaRootPullbackPoint t ell}
    (h : IntegerOrbitRelated t ell r hr x y) :
    IntegerOrbitRelated t ell r hr y x := by
  rcases h with ⟨n, rfl⟩
  refine ⟨-n, ?_⟩
  calc
    deckZ t ell r hr (-n)
        (deckZ t ell r hr n x) =
      deckZ t ell r hr (-n + n) x := by
        symm
        exact deckZ_add t ell r hr (-n) n x
    _ = x := by simp

/-- Full integer-orbit relation is transitive. -/
theorem integerOrbitRelated_trans
    {x y z : TateThetaRootPullbackPoint t ell}
    (hxy : IntegerOrbitRelated t ell r hr x y)
    (hyz : IntegerOrbitRelated t ell r hr y z) :
    IntegerOrbitRelated t ell r hr x z := by
  rcases hxy with ⟨n, rfl⟩
  rcases hyz with ⟨m, rfl⟩
  refine ⟨m + n, ?_⟩
  exact deckZ_add t ell r hr m n x

/-- Setoid for the full corrected deck action. -/
def integerOrbitSetoid :
    Setoid (TateThetaRootPullbackPoint t ell) where
  r := IntegerOrbitRelated t ell r hr
  iseqv := {
    refl := integerOrbitRelated_refl t ell r hr
    symm := integerOrbitRelated_symm t ell r hr
    trans := integerOrbitRelated_trans t ell r hr
  }

/-- `ell`-period orbit relation is reflexive. -/
theorem ellPeriodOrbitRelated_refl
    (x : TateThetaRootPullbackPoint t ell) :
    EllPeriodOrbitRelated t ell r hr x x := by
  exact ⟨0, by simp⟩

/-- `ell`-period orbit relation is symmetric. -/
theorem ellPeriodOrbitRelated_symm
    {x y : TateThetaRootPullbackPoint t ell}
    (h : EllPeriodOrbitRelated t ell r hr x y) :
    EllPeriodOrbitRelated t ell r hr y x := by
  rcases h with ⟨n, rfl⟩
  refine ⟨-n, ?_⟩
  have hsum :
      ((ell : ℤ) * (-n)) + ((ell : ℤ) * n) = 0 := by
    ring
  calc
    deckZ t ell r hr ((ell : ℤ) * (-n))
        (deckZ t ell r hr ((ell : ℤ) * n) x) =
      deckZ t ell r hr
        (((ell : ℤ) * (-n)) + ((ell : ℤ) * n)) x := by
          symm
          exact deckZ_add t ell r hr
            ((ell : ℤ) * (-n)) ((ell : ℤ) * n) x
    _ = x := by simp [hsum]

/-- `ell`-period orbit relation is transitive. -/
theorem ellPeriodOrbitRelated_trans
    {x y z : TateThetaRootPullbackPoint t ell}
    (hxy : EllPeriodOrbitRelated t ell r hr x y)
    (hyz : EllPeriodOrbitRelated t ell r hr y z) :
    EllPeriodOrbitRelated t ell r hr x z := by
  rcases hxy with ⟨n, rfl⟩
  rcases hyz with ⟨m, rfl⟩
  refine ⟨m + n, ?_⟩
  have hexponent :
      (ell : ℤ) * (m + n) =
        (ell : ℤ) * m + (ell : ℤ) * n := by ring
  rw [hexponent]
  exact deckZ_add t ell r hr
    ((ell : ℤ) * m) ((ell : ℤ) * n) x

/-- Setoid for the original Tate-period subgroup. -/
def ellPeriodOrbitSetoid :
    Setoid (TateThetaRootPullbackPoint t ell) where
  r := EllPeriodOrbitRelated t ell r hr
  iseqv := {
    refl := ellPeriodOrbitRelated_refl t ell r hr
    symm := ellPeriodOrbitRelated_symm t ell r hr
    trans := ellPeriodOrbitRelated_trans t ell r hr
  }

/-- Every `ell`-period orbit is contained in a full integer orbit. -/
theorem ellPeriodRelated_implies_integerRelated
    {x y : TateThetaRootPullbackPoint t ell}
    (h : EllPeriodOrbitRelated t ell r hr x y) :
    IntegerOrbitRelated t ell r hr x y := by
  rcases h with ⟨n, hn⟩
  exact ⟨(ell : ℤ) * n, hn⟩

/-- Set-theoretic quotient representing the `ell`-sheeted theta-root cover. -/
abbrev ThetaCoverOrbitQuotient :=
  Quotient (ellPeriodOrbitSetoid t ell r hr)

/-- Set-theoretic quotient representing the base Tate cycle. -/
abbrev ThetaBaseOrbitQuotient :=
  Quotient (integerOrbitSetoid t ell r hr)

/-- Natural projection from the theta-root cover quotient to the base quotient. -/
noncomputable def coverToBase :
    ThetaCoverOrbitQuotient t ell r hr →
      ThetaBaseOrbitQuotient t ell r hr :=
  Quotient.map id fun _ _ h =>
    ellPeriodRelated_implies_integerRelated t ell r hr h

/-- The cover-to-base projection is surjective. -/
theorem coverToBase_surjective :
    Function.Surjective (coverToBase t ell r hr) := by
  intro q
  refine Quotient.inductionOn q ?_
  intro x
  refine ⟨Quotient.mk (ellPeriodOrbitSetoid t ell r hr) x, ?_⟩
  rfl

/-- Full-orbit radial coordinate `rho mod Z` on the base quotient. -/
noncomputable def baseCycleCoordinate :
    ThetaBaseOrbitQuotient t ell r hr → UnitAddCircle :=
  Quotient.lift
    (fun z => ((coordinate t ell r z : ℝ) : UnitAddCircle))
    (by
      intro x y hxy
      rcases hxy with ⟨n, rfl⟩
      rw [coordinate_deckZ]
      have hnzero : ((n : ℝ) : UnitAddCircle) = 0 := by
        rw [AddCircle.coe_eq_zero_iff]
        exact ⟨n, by simp⟩
      simpa only [AddCircle.coe_add, hnzero, add_zero])

/-- `ell`-period radial coordinate `rho/ell mod Z` on the cover quotient. -/
noncomputable def coverCycleCoordinate [NeZero ell] :
    ThetaCoverOrbitQuotient t ell r hr → UnitAddCircle :=
  Quotient.lift
    (fun z =>
      ((coordinate t ell r z / (ell : ℝ) : ℝ) : UnitAddCircle))
    (by
      intro x y hxy
      rcases hxy with ⟨n, rfl⟩
      rw [coordinate_deckZ]
      have hell : (ell : ℝ) ≠ 0 := by
        exact_mod_cast (NeZero.ne ell)
      have hreal :
          (coordinate t ell r x +
              (((ell : ℤ) * n : ℤ) : ℝ)) / (ell : ℝ) =
            coordinate t ell r x / (ell : ℝ) + (n : ℝ) := by
        push_cast
        field_simp [hell]
      rw [hreal]
      have hnzero : ((n : ℝ) : UnitAddCircle) = 0 := by
        rw [AddCircle.coe_eq_zero_iff]
        exact ⟨n, by simp⟩
      simpa only [AddCircle.coe_add, hnzero, add_zero])

/-- On radial skeleton coordinates, the cover-to-base map is multiplication
by `ell` on the unit additive circle. -/
theorem baseCycleCoordinate_coverToBase [NeZero ell]
    (q : ThetaCoverOrbitQuotient t ell r hr) :
    baseCycleCoordinate t ell r hr (coverToBase t ell r hr q) =
      ell • coverCycleCoordinate t ell r hr q := by
  refine Quotient.inductionOn q ?_
  intro x
  change
    ((coordinate t ell r x : ℝ) : UnitAddCircle) =
      ell •
        ((coordinate t ell r x / (ell : ℝ) : ℝ) : UnitAddCircle)
  have hell : (ell : ℝ) ≠ 0 := by
    exact_mod_cast (NeZero.ne ell)
  have hreal :
      ell • (coordinate t ell r x / (ell : ℝ)) =
        coordinate t ell r x := by
    change
      (ell : ℝ) * (coordinate t ell r x / (ell : ℝ)) =
        coordinate t ell r x
    exact mul_div_cancel₀ _ hell
  calc
    ((coordinate t ell r x : ℝ) : UnitAddCircle) =
        ((ell • (coordinate t ell r x / (ell : ℝ)) : ℝ) :
          UnitAddCircle) := by rw [hreal]
    _ = ell •
        ((coordinate t ell r x / (ell : ℝ) : ℝ) : UnitAddCircle) :=
      AddCircle.coe_nsmul (p := (1 : ℝ))
        (n := ell) (x := coordinate t ell r x / (ell : ℝ))

/-- One corrected deck step acts nontrivially on the cover quotient but is
trivial after projection to the base quotient. -/
noncomputable def residualDeckTranslate
    (j : ℤ) :
    ThetaCoverOrbitQuotient t ell r hr →
      ThetaCoverOrbitQuotient t ell r hr :=
  Quotient.map (deckZ t ell r hr j) (by
    intro x y hxy
    rcases hxy with ⟨n, rfl⟩
    refine ⟨n, ?_⟩
    calc
      deckZ t ell r hr ((ell : ℤ) * n)
          (deckZ t ell r hr j x) =
        deckZ t ell r hr (((ell : ℤ) * n) + j) x := by
          symm
          exact deckZ_add t ell r hr ((ell : ℤ) * n) j x
      _ = deckZ t ell r hr (j + (ell : ℤ) * n) x := by
          rw [add_comm]
      _ = deckZ t ell r hr j
          (deckZ t ell r hr ((ell : ℤ) * n) x) :=
        deckZ_add t ell r hr j ((ell : ℤ) * n) x)

/-- Residual integer translation is invisible after projection to the base. -/
theorem coverToBase_residualDeckTranslate
    (j : ℤ)
    (q : ThetaCoverOrbitQuotient t ell r hr) :
    coverToBase t ell r hr
        (residualDeckTranslate t ell r hr j q) =
      coverToBase t ell r hr q := by
  refine Quotient.inductionOn q ?_
  intro x
  apply Quotient.sound
  exact integerOrbitRelated_symm t ell r hr ⟨j, rfl⟩

/-- On cover radial coordinates, residual integer translation adds `j/ell`. -/
theorem coverCycleCoordinate_residualDeckTranslate
    [NeZero ell]
    (j : ℤ)
    (q : ThetaCoverOrbitQuotient t ell r hr) :
    coverCycleCoordinate t ell r hr
        (residualDeckTranslate t ell r hr j q) =
      coverCycleCoordinate t ell r hr q +
        (((j : ℝ) / (ell : ℝ) : ℝ) : UnitAddCircle) := by
  refine Quotient.inductionOn q ?_
  intro x
  change
    (((coordinate t ell r
        (deckZ t ell r hr j x) / (ell : ℝ) : ℝ)) :
      UnitAddCircle) =
      ((coordinate t ell r x / (ell : ℝ) : ℝ) : UnitAddCircle) +
        (((j : ℝ) / (ell : ℝ) : ℝ) : UnitAddCircle)
  rw [coordinate_deckZ, add_div]
  exact AddCircle.coe_add (1 : ℝ)
    (coordinate t ell r x / (ell : ℝ))
    ((j : ℝ) / (ell : ℝ))

end TateThetaRootRadialSkeleton

end IUTThreeClosures
