import IUTThreeClosures.OuterMeasurePossibleImageSandwich
import IUTThreeClosures.TateParameterPowerRegions
import Mathlib.MeasureTheory.Measure.Haar.DistribChar

/-!
# Actual Haar-measured Tate q-pilot regions

The consistent pilot-volume layer should be built from an actual measure, not
from a total real-valued function on arbitrary sets.  This module constructs
that measure locally.

For a proper normed field `K`, the norm-unit ball `O = {x | ‖x‖ ≤ 1}` is a
compact set with nonempty interior.  We normalize additive Haar measure by
`μ(O) = 1`.  Every nonzero scalar image `a O` is again a positive compact and
therefore gives a genuine finite-positive measured region.  Applying this to
`a = q^n` constructs the local regions generated by an actual Tate parameter.

No abstract volume or scaling axiom is introduced.  The remaining arithmetic
calibration is the concrete theorem identifying the additive-Haar modulus of
`q` with the normalized valuation/order used by the global q-pilot.
-/

namespace TateCurvesTheta

open MeasureTheory
open TopologicalSpace

universe u

variable {K : Type u} [NormedField K]

/-- The norm-unit-ball presentation used by the Tate region is the metric
closed unit ball. -/
theorem normIntegralRegion_eq_closedBall :
    normIntegralRegion (K := K) = Metric.closedBall (0 : K) 1 := by
  ext x
  simp [normIntegralRegion, Metric.mem_closedBall]

/-- The norm-unit ball is a positive compact in a proper normed field. -/
noncomputable def normIntegralPositiveCompacts
    (K : Type u) [NormedField K] [ProperSpace K] : PositiveCompacts K where
  carrier := normIntegralRegion (K := K)
  isCompact' := by
    rw [normIntegralRegion_eq_closedBall]
    exact isCompact_closedBall (0 : K) 1
  interior_nonempty' := by
    rw [normIntegralRegion_eq_closedBall]
    have hsub :
        Metric.ball (0 : K) 1 ⊆ interior (Metric.closedBall (0 : K) 1) :=
      Metric.isOpen_ball.subset_interior Metric.ball_subset_closedBall
    exact ⟨0, hsub (by simp)⟩

variable [ProperSpace K] [MeasurableSpace K] [BorelSpace K]

/-- Additive Haar measure normalized so that the norm-unit ball has measure
one. -/
noncomputable def normIntegralHaar (K : Type u)
    [NormedField K] [ProperSpace K] [MeasurableSpace K] [BorelSpace K] :
    Measure K :=
  Measure.addHaarMeasure (normIntegralPositiveCompacts K)

/-- The chosen normalization is literal: `μ(O) = 1`. -/
@[simp]
theorem normIntegralHaar_apply_normIntegralRegion :
    normIntegralHaar K (normIntegralRegion (K := K)) = 1 := by
  change Measure.addHaarMeasure (normIntegralPositiveCompacts K)
      (normIntegralPositiveCompacts K : Set K) = 1
  exact Measure.addHaarMeasure_self

/-- The unit ball as a genuine finite-positive measured region. -/
noncomputable def normIntegralFinitePositiveRegion :
    IUTThreeClosures.FinitePositiveRegion K (normIntegralHaar K) where
  carrier := normIntegralRegion (K := K)
  measurable := by
    rw [normIntegralRegion_eq_closedBall]
    exact Metric.isClosed_closedBall.measurableSet
  measure_ne_zero := by simp
  measure_ne_top := by simp

@[simp]
theorem normIntegralFinitePositiveRegion_logVolume :
    (normIntegralFinitePositiveRegion (K := K)).logVolume = 0 := by
  rw [IUTThreeClosures.FinitePositiveRegion.logVolume]
  simp

/-- Multiplication by a nonzero scalar sends the unit ball to another positive
compact. -/
noncomputable def scaledPositiveCompacts (a : K) (ha : a ≠ 0) :
    PositiveCompacts K :=
  (normIntegralPositiveCompacts K).map
    (fun x : K => a * x)
    (Homeomorph.mulLeft₀ a ha).continuous
    (Homeomorph.mulLeft₀ a ha).isOpenMap

@[simp]
theorem coe_scaledPositiveCompacts (a : K) (ha : a ≠ 0) :
    (scaledPositiveCompacts a ha : Set K) =
      scaledRegion a (normIntegralRegion (K := K)) := by
  rfl

/-- Every nonzero scalar image of the unit ball is an actual finite-positive
Haar-measured region. -/
noncomputable def scaledFinitePositiveRegion (a : K) (ha : a ≠ 0) :
    IUTThreeClosures.FinitePositiveRegion K (normIntegralHaar K) where
  carrier := scaledPositiveCompacts a ha
  measurable := (scaledPositiveCompacts a ha).isCompact.isClosed.measurableSet
  measure_ne_zero :=
    (measure_pos_of_nonempty_interior (normIntegralHaar K)
      (scaledPositiveCompacts a ha).interior_nonempty).ne'
  measure_ne_top := (scaledPositiveCompacts a ha).isCompact.measure_ne_top

@[simp]
theorem coe_scaledFinitePositiveRegion (a : K) (ha : a ≠ 0) :
    (scaledFinitePositiveRegion a ha : Set K) =
      scaledRegion a (normIntegralRegion (K := K)) := by
  exact coe_scaledPositiveCompacts a ha

namespace TateParameter

/-- The `q^n O` region generated by an actual Tate parameter, equipped with
normalized additive Haar measure and proofs of finite positivity. -/
noncomputable def qPowerFinitePositiveRegion
    (t : TateParameter K) (n : ℕ) :
    IUTThreeClosures.FinitePositiveRegion K (normIntegralHaar K) :=
  scaledFinitePositiveRegion ((t.q : K) ^ n)
    (pow_ne_zero n t.q.ne_zero)

@[simp]
theorem coe_qPowerFinitePositiveRegion
    (t : TateParameter K) (n : ℕ) :
    (t.qPowerFinitePositiveRegion n : Set K) = t.qPowerRegion n := by
  rfl

/-- The Haar-measured Tate-power regions inherit the actual antitone nesting
of the underlying q-power regions. -/
theorem qPowerFinitePositiveRegion_antitone
    (t : TateParameter K) {m n : ℕ} (hmn : m ≤ n) :
    (t.qPowerFinitePositiveRegion n : Set K) ⊆
      (t.qPowerFinitePositiveRegion m : Set K) := by
  simpa using t.qPowerRegion_antitone hmn

/-- Consequently their canonical log-volumes are antitone in the exponent. -/
theorem qPowerFinitePositiveRegion_logVolume_antitone
    (t : TateParameter K) {m n : ℕ} (hmn : m ≤ n) :
    (t.qPowerFinitePositiveRegion n).logVolume ≤
      (t.qPowerFinitePositiveRegion m).logVolume :=
  IUTThreeClosures.FinitePositiveRegion.logVolume_mono
    (t.qPowerFinitePositiveRegion_antitone hmn)

end TateParameter

end TateCurvesTheta
