/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# The abstract graph-period quotient

Let `q` be an element of infinite order in a group `G`.  Inside the cyclic
subgroup `q ^ ℤ`, let `graphPeriodSubgroup q ell` be the subgroup generated
by `q ^ ell`.  This file proves the purely group-theoretic equivalence

`(q ^ ℤ) / ((q ^ ell) ^ ℤ) ≃ Multiplicative (ZMod ell)`.

The construction is explicit at the level relevant to the paper proof: first
identify `q ^ ℤ` with `Multiplicative ℤ` by the exponent map, transport the
period subgroup to `ell * ℤ`, and then use the standard quotient description
of `ZMod ell`.

This is only an abstract quotient-group theorem.  It makes no assertion about
an analytic Tate-curve quotient, a deck action, an orbicurve, or a tempered
fundamental group.
-/

namespace IUTThreeClosures.TateGraphPeriodQuotient

open Subgroup

universe u

variable {G : Type u} [Group G]

/-- The distinguished generator, regarded as an element of its own cyclic
subgroup. -/
def graphGenerator (q : G) : Subgroup.zpowers q :=
  ⟨q, Subgroup.mem_zpowers q⟩

@[simp]
theorem graphGenerator_coe (q : G) :
    (graphGenerator q : G) = q :=
  rfl

/-- The subgroup generated by the `ell`-step period, formed inside the cyclic
group generated by `q`. -/
def graphPeriodSubgroup (q : G) (ell : ℕ) :
    Subgroup (Subgroup.zpowers q) :=
  Subgroup.zpowers ((graphGenerator q) ^ ell)

/-- Membership in the internal period subgroup is exactly being an integral
power of `q ^ ell` in the ambient group. -/
theorem mem_graphPeriodSubgroup_iff
    (q : G) (ell : ℕ) (x : Subgroup.zpowers q) :
    x ∈ graphPeriodSubgroup q ell ↔
      ∃ n : ℤ, (q ^ ell) ^ n = (x : G) := by
  constructor
  · rintro ⟨n, hn⟩
    exact ⟨n, congrArg Subtype.val hn⟩
  · rintro ⟨n, hn⟩
    exact ⟨n, Subtype.ext hn⟩

/-- Infinite order makes the integral exponent map into `q ^ ℤ` a genuine
group equivalence. -/
noncomputable def integerPowersEquiv
    (q : G) (hq : ¬ IsOfFinOrder q) :
    Multiplicative ℤ ≃* Subgroup.zpowers q := by
  let f : Multiplicative ℤ →* Subgroup.zpowers q :=
    zpowersHom (Subgroup.zpowers q) (graphGenerator q)
  apply MulEquiv.ofBijective f
  constructor
  · intro m n hmn
    change m.toAdd = n.toAdd
    apply (injective_zpow_iff_not_isOfFinOrder.mpr hq)
    simpa [f, graphGenerator] using congrArg Subtype.val hmn
  · intro x
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp x.property
    refine ⟨Multiplicative.ofAdd n, ?_⟩
    apply Subtype.ext
    simpa [f, graphGenerator] using hn

@[simp]
theorem integerPowersEquiv_apply
    (q : G) (hq : ¬ IsOfFinOrder q) (n : ℤ) :
    integerPowersEquiv q hq (Multiplicative.ofAdd n) =
      (graphGenerator q) ^ n :=
  rfl

@[simp]
theorem integerPowersEquiv_symm_graphGenerator
    (q : G) (hq : ¬ IsOfFinOrder q) :
    (integerPowersEquiv q hq).symm (graphGenerator q) =
      Multiplicative.ofAdd 1 := by
  rw [MulEquiv.symm_apply_eq]
  simp

/-- Under the inverse exponent equivalence, the internal subgroup generated
by `q ^ ell` becomes the standard subgroup `ell * ℤ`. -/
theorem map_graphPeriodSubgroup_integerPowersEquiv_symm
    (q : G) (hq : ¬ IsOfFinOrder q) (ell : ℕ) :
    (graphPeriodSubgroup q ell).map
        (integerPowersEquiv q hq).symm.toMonoidHom =
      AddSubgroup.toSubgroup (AddSubgroup.zmultiples (ell : ℤ)) := by
  rw [graphPeriodSubgroup, MonoidHom.map_zpowers]
  change Subgroup.zpowers
      ((integerPowersEquiv q hq).symm ((graphGenerator q) ^ ell)) = _
  rw [map_pow, integerPowersEquiv_symm_graphGenerator]
  rw [← ofAdd_nsmul]
  simp only [nsmul_eq_mul, mul_one]
  rfl

/-- The exact abstract group isomorphism
`<q> / <q^ell> ≃ Multiplicative (ZMod ell)`.

It is valid also for `ell = 0`, when both sides are infinite cyclic.  The graph
cover application uses `0 < ell`. -/
noncomputable def graphPeriodQuotientEquivZMod
    (q : G) (hq : ¬ IsOfFinOrder q) (ell : ℕ) :
    (Subgroup.zpowers q ⧸ graphPeriodSubgroup q ell) ≃*
      Multiplicative (ZMod ell) :=
  (QuotientGroup.congr
      (graphPeriodSubgroup q ell)
      (AddSubgroup.toSubgroup (AddSubgroup.zmultiples (ell : ℤ)))
      (integerPowersEquiv q hq).symm
      (map_graphPeriodSubgroup_integerPowersEquiv_symm q hq ell)).trans
    (Int.quotientZMultiplesNatEquivZMod ell).toMultiplicative

end IUTThreeClosures.TateGraphPeriodQuotient
