import IUTThreeClosures.TateHaarQPilotRegion

/-!
# Exact Haar modulus of Tate q-pilot regions

The preceding module constructs the regions `q^n O` as genuine finite-positive
subsets of a normalized additive Haar space.  This module computes their
measure and log-volume.  The computation uses Mathlib's distributive Haar
character, so no freely specified scaling law is introduced.

For a nonzero scalar `a`, normalized Haar measure satisfies

`μ(a O) = Δ_K(a)`.

Consequently an actual Tate parameter satisfies

`μ(q^n O) = Δ_K(q)^n`

and the canonical log-volume is

`n * log Δ_K(q)`.

The remaining local arithmetic theorem is therefore no longer an abstract
volume calibration: it is the concrete identification of `Δ_K` on a chosen
uniformizer with the normalized residue-field/valuation convention.
-/

namespace TateCurvesTheta

open MeasureTheory
open scoped Pointwise ENNReal

universe u

variable {K : Type u} [NormedField K] [ProperSpace K]
variable [MeasurableSpace K] [BorelSpace K]

/-- The pointwise action of the unit represented by `a` on the norm-unit ball
is the scalar-image region used by the Tate construction. -/
theorem units_smul_normIntegralRegion_eq_scaledRegion
    (a : K) (ha : a ≠ 0) :
    (Units.mk0 a ha) • normIntegralRegion (K := K) =
      scaledRegion a (normIntegralRegion (K := K)) := by
  ext x
  constructor
  · rintro ⟨y, hy, hxy⟩
    exact ⟨y, hy, by simpa [smul_eq_mul] using hxy⟩
  · rintro ⟨y, hy, rfl⟩
    exact ⟨y, hy, by simp [smul_eq_mul]⟩

/-- Exact normalized additive-Haar measure of a nonzero scalar image of the
unit ball. -/
theorem normIntegralHaar_apply_scaledRegion
    (a : K) (ha : a ≠ 0) :
    normIntegralHaar K
        (scaledRegion a (normIntegralRegion (K := K))) =
      (MeasureTheory.distribHaarChar K (Units.mk0 a ha) : ℝ≥0∞) := by
  have h := MeasureTheory.distribHaarChar_mul
    (normIntegralHaar K) (Units.mk0 a ha)
      (normIntegralRegion (K := K))
  rw [normIntegralHaar_apply_normIntegralRegion, mul_one,
    units_smul_normIntegralRegion_eq_scaledRegion] at h
  exact h.symm

/-- Canonical log-volume of a nonzero scalar image, expressed without any
abstract volume axiom. -/
theorem scaledFinitePositiveRegion_logVolume
    (a : K) (ha : a ≠ 0) :
    (scaledFinitePositiveRegion a ha).logVolume =
      Real.log (MeasureTheory.distribHaarChar K (Units.mk0 a ha) : ℝ) := by
  rw [IUTThreeClosures.FinitePositiveRegion.logVolume]
  change
    Real.log
        ((normIntegralHaar K
          (scaledRegion a (normIntegralRegion (K := K)))).toReal) = _
  rw [normIntegralHaar_apply_scaledRegion]
  simp

namespace TateParameter

/-- Exact Haar measure of the `n`-th region generated by an actual Tate
parameter. -/
theorem normIntegralHaar_apply_qPowerRegion
    (t : TateParameter K) (n : ℕ) :
    normIntegralHaar K (t.qPowerRegion n) =
      (MeasureTheory.distribHaarChar K (t.q ^ n) : ℝ≥0∞) := by
  have h := normIntegralHaar_apply_scaledRegion
    (K := K) ((t.q : K) ^ n) (pow_ne_zero n t.q.ne_zero)
  have hu :
      Units.mk0 ((t.q : K) ^ n) (pow_ne_zero n t.q.ne_zero) =
        t.q ^ n := by
    ext
    rfl
  simpa [qPowerRegion, hu] using h

/-- The actual Haar measure is multiplicative in the Tate power. -/
theorem normIntegralHaar_apply_qPowerRegion_eq_pow
    (t : TateParameter K) (n : ℕ) :
    normIntegralHaar K (t.qPowerRegion n) =
      ((MeasureTheory.distribHaarChar K t.q : ℝ≥0∞) ^ n) := by
  rw [t.normIntegralHaar_apply_qPowerRegion]
  simp

/-- Exact canonical log-volume of an actual `q^n O` region. -/
theorem qPowerFinitePositiveRegion_logVolume_eq_distribHaarChar
    (t : TateParameter K) (n : ℕ) :
    (t.qPowerFinitePositiveRegion n).logVolume =
      (n : ℝ) *
        Real.log (MeasureTheory.distribHaarChar K t.q : ℝ) := by
  rw [IUTThreeClosures.FinitePositiveRegion.logVolume]
  change
    Real.log ((normIntegralHaar K (t.qPowerRegion n)).toReal) = _
  rw [t.normIntegralHaar_apply_qPowerRegion_eq_pow]
  simp [Real.log_pow]

end TateParameter

end TateCurvesTheta
