/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import Mathlib.RingTheory.PiTensorProduct

/-!
# Tensor integral orders and factorwise integral inclusion

The integral structure on a tensor packet is generated by the label-wise
integral structures under the canonical maps into the n-ary tensor algebra.
It must not be identified by definition with the product of the integral
closures of the primitive field factors.

This module defines the generated tensor order and proves the universal
factor-inclusion theorem. If a ring map from the tensor algebra to a target
factor sends every label-wise integral generator into a chosen target order,
then it sends the entire generated tensor order into that target order. The
proof is the minimality of `Subring.closure`.

Applied to every primitive finite-etale factor, the generator condition follows
from preservation of integrality. The remaining arithmetic theorem is that
the resulting inclusion has finite index and that its index is controlled by
(or identified with) the local different/discriminant correction.
-/

namespace IUTThreeClosures

open PiTensorProduct TensorProduct

universe u v w

variable (R : Type u) [CommRing R]
variable (ι : Type v) [Fintype ι] [DecidableEq ι]
variable (A : ι → Type w)
variable [∀ i, CommRing (A i)] [∀ i, Algebra R (A i)]

/-- The set of label-wise integral generators inside the n-ary tensor
algebra. -/
def tensorIntegralGenerators
    (O : ∀ i, Subring (A i)) :
    Set (⨂[R] i, A i) :=
  {x | ∃ i a, a ∈ O i ∧ x = singleAlgHom (R := R) (A := A) i a}

/-- The integral order generated by all label-wise integral subrings. -/
def tensorIntegralOrder
    (O : ∀ i, Subring (A i)) :
    Subring (⨂[R] i, A i) :=
  Subring.closure (tensorIntegralGenerators R ι A O)

/-- Every label-wise integral element belongs to the generated tensor order. -/
theorem singleAlgHom_mem_tensorIntegralOrder
    (O : ∀ i, Subring (A i)) (i : ι) (a : A i)
    (ha : a ∈ O i) :
    singleAlgHom (R := R) (A := A) i a ∈
      tensorIntegralOrder R ι A O := by
  apply Subring.subset_closure
  exact ⟨i, a, ha, rfl⟩

section Factor

variable {B : Type*} [CommRing B]

/-- Universal factorwise inclusion: it is enough to check the actual factor
map on the label-wise integral generators. -/
theorem tensorIntegralOrder_le_comap
    (O : ∀ i, Subring (A i))
    (BOrder : Subring B)
    (f : (⨂[R] i, A i) →+* B)
    (hgen : ∀ i a, a ∈ O i →
      f (singleAlgHom (R := R) (A := A) i a) ∈ BOrder) :
    tensorIntegralOrder R ι A O ≤ BOrder.comap f := by
  apply Subring.closure_le.mpr
  rintro x ⟨i, a, ha, rfl⟩
  exact hgen i a ha

/-- Elementwise form of the factorwise inclusion theorem. -/
theorem map_mem_of_mem_tensorIntegralOrder
    (O : ∀ i, Subring (A i))
    (BOrder : Subring B)
    (f : (⨂[R] i, A i) →+* B)
    (hgen : ∀ i a, a ∈ O i →
      f (singleAlgHom (R := R) (A := A) i a) ∈ BOrder)
    {x : ⨂[R] i, A i}
    (hx : x ∈ tensorIntegralOrder R ι A O) :
    f x ∈ BOrder :=
  tensorIntegralOrder_le_comap R ι A O BOrder f hgen hx

/-- The componentwise product of a family of subrings.  This explicit
construction is used instead of a nonexistent `Subring.pi` API. -/
def productSubring
    {κ : Type*} (Bκ : κ → Type*) [∀ k, CommRing (Bκ k)]
    (BOrder : ∀ k, Subring (Bκ k)) :
    Subring (∀ k, Bκ k) where
  carrier := {x | ∀ k, x k ∈ BOrder k}
  zero_mem' := fun k => (BOrder k).zero_mem
  one_mem' := fun k => (BOrder k).one_mem
  add_mem' := by
    intro x y hx hy k
    exact (BOrder k).add_mem (hx k) (hy k)
  neg_mem' := by
    intro x hx k
    exact (BOrder k).neg_mem (hx k)
  mul_mem' := by
    intro x y hx hy k
    exact (BOrder k).mul_mem (hx k) (hy k)

@[simp]
theorem mem_productSubring
    {κ : Type*} (Bκ : κ → Type*) [∀ k, CommRing (Bκ k)]
    (BOrder : ∀ k, Subring (Bκ k)) (x : ∀ k, Bκ k) :
    x ∈ productSubring Bκ BOrder ↔ ∀ k, x k ∈ BOrder k :=
  Iff.rfl

/-- Simultaneous inclusion in a product of primitive factor orders. -/
theorem tensorIntegralOrder_le_pi_comap
    {κ : Type*} (O : ∀ i, Subring (A i))
    (Bκ : κ → Type*) [∀ k, CommRing (Bκ k)]
    (BOrder : ∀ k, Subring (Bκ k))
    (f : (⨂[R] i, A i) →+* ∀ k, Bκ k)
    (hgen : ∀ i a, a ∈ O i →
      ∀ k, f (singleAlgHom (R := R) (A := A) i a) k ∈ BOrder k) :
    tensorIntegralOrder R ι A O ≤
      (productSubring Bκ BOrder).comap f := by
  apply tensorIntegralOrder_le_comap R ι A O
  intro i a ha
  exact fun k => hgen i a ha k

end Factor

end IUTThreeClosures
