/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.TateParameterPowerRegions
import Mathlib.Algebra.BigOperators.Group.Finset.Basic

/-!
# Exact norm formula for the theta-pilot generators

The theta values that generate the local IUT theta-pilot splitting monoid are
`q^(j^2)`.  Their norm formula is therefore algebraic, not an identity theorem
for an arbitrary analytic theta function.  This module proves the formula for
one generator, for arbitrary finite products of generator powers, and after a
norm-one Kummer/unit ambiguity.  It also identifies the corresponding
principal regions with the actual Tate `q`-power regions.
-/

namespace TateCurvesTheta

open scoped BigOperators

variable {K : Type*} [NormedField K]

namespace TateParameter

/-- The primitive theta-pilot value with label `j`. -/
def thetaPilotValue (t : TateParameter K) (j : ℕ) : K :=
  (t.q : K) ^ (j ^ 2)

/-- The primitive theta-pilot value has exactly the expected Tate-power norm. -/
@[simp]
theorem norm_thetaPilotValue (t : TateParameter K) (j : ℕ) :
    ‖t.thetaPilotValue j‖ = ‖(t.q : K)‖ ^ (j ^ 2) := by
  simp [thetaPilotValue, norm_pow]

/-- Primitive theta-pilot values are nonzero. -/
@[simp]
theorem thetaPilotValue_ne_zero (t : TateParameter K) (j : ℕ) :
    t.thetaPilotValue j ≠ 0 := by
  exact pow_ne_zero _ t.q.ne_zero

/-- Every primitive theta-pilot value belongs to the norm unit ball. -/
theorem thetaPilotValue_mem_normIntegral
    (t : TateParameter K) (j : ℕ) :
    t.thetaPilotValue j ∈ normIntegralRegion (K := K) := by
  change ‖t.thetaPilotValue j‖ ≤ 1
  rw [t.norm_thetaPilotValue j]
  exact pow_le_one₀ (norm_nonneg _) t.norm_lt_one.le

/-- The principal region of a primitive theta-pilot generator is literally the
corresponding Tate-power region. -/
theorem scaledRegion_thetaPilotValue_eq_qPowerRegion
    (t : TateParameter K) (j : ℕ) :
    scaledRegion (t.thetaPilotValue j) (normIntegralRegion (K := K)) =
      t.qPowerRegion (j ^ 2) := by
  rfl

/-- A finite product of powers of theta-pilot generators is a single power of
`q`; its exponent is the corresponding finite sum of squares with
multiplicities. -/
theorem prod_thetaPilotValue_pow_eq_q_pow
    {ι : Type*} (t : TateParameter K)
    (s : Finset ι) (j m : ι → ℕ) :
    (∏ k ∈ s, (t.thetaPilotValue (j k)) ^ (m k)) =
      (t.q : K) ^ (∑ k ∈ s, (j k) ^ 2 * m k) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      rw [Finset.prod_insert ha, Finset.sum_insert ha, ih]
      simp only [thetaPilotValue]
      rw [← pow_mul, ← pow_add]

/-- Exact norm formula for every finite theta-pilot monoid word. -/
theorem norm_prod_thetaPilotValue_pow
    {ι : Type*} (t : TateParameter K)
    (s : Finset ι) (j m : ι → ℕ) :
    ‖∏ k ∈ s, (t.thetaPilotValue (j k)) ^ (m k)‖ =
      ‖(t.q : K)‖ ^ (∑ k ∈ s, (j k) ^ 2 * m k) := by
  rw [t.prod_thetaPilotValue_pow_eq_q_pow s j m, norm_pow]

/-- The region generated by every finite theta-pilot monoid word is the actual
Tate-power region at the sum-of-squares exponent. -/
theorem scaledRegion_prod_thetaPilotValue_pow_eq_qPowerRegion
    {ι : Type*} (t : TateParameter K)
    (s : Finset ι) (j m : ι → ℕ) :
    scaledRegion
        (∏ k ∈ s, (t.thetaPilotValue (j k)) ^ (m k))
        (normIntegralRegion (K := K)) =
      t.qPowerRegion (∑ k ∈ s, (j k) ^ 2 * m k) := by
  rw [t.prod_thetaPilotValue_pow_eq_q_pow s j m]
  rfl

/-- A norm-one Kummer ambiguity does not change the exact norm formula. -/
theorem norm_unit_mul_prod_thetaPilotValue_pow
    {ι : Type*} (t : TateParameter K)
    (s : Finset ι) (j m : ι → ℕ)
    (u : K) (hu : ‖u‖ = 1) :
    ‖u * ∏ k ∈ s, (t.thetaPilotValue (j k)) ^ (m k)‖ =
      ‖(t.q : K)‖ ^ (∑ k ∈ s, (j k) ^ 2 * m k) := by
  rw [norm_mul, hu, one_mul, t.norm_prod_thetaPilotValue_pow s j m]

/-- A norm-one Kummer ambiguity also leaves the generated principal region
unchanged. -/
theorem scaledRegion_unit_mul_prod_thetaPilotValue_pow_eq_qPowerRegion
    {ι : Type*} (t : TateParameter K)
    (s : Finset ι) (j m : ι → ℕ)
    (u : K) (hu : ‖u‖ = 1) :
    scaledRegion
        (u * ∏ k ∈ s, (t.thetaPilotValue (j k)) ^ (m k))
        (normIntegralRegion (K := K)) =
      t.qPowerRegion (∑ k ∈ s, (j k) ^ 2 * m k) := by
  let v : K := ∏ k ∈ s, (t.thetaPilotValue (j k)) ^ (m k)
  calc
    scaledRegion (u * v) (normIntegralRegion (K := K)) =
        scaledRegion (v * u) (normIntegralRegion (K := K)) := by
      rw [mul_comm]
    _ = scaledRegion v
        (scaledRegion u (normIntegralRegion (K := K))) := by
      exact scaledRegion_mul v u (normIntegralRegion (K := K))
    _ = scaledRegion v (normIntegralRegion (K := K)) := by
      rw [scaledRegion_normIntegral_of_norm_eq_one u hu]
    _ = t.qPowerRegion (∑ k ∈ s, (j k) ^ 2 * m k) := by
      dsimp [v]
      exact t.scaledRegion_prod_thetaPilotValue_pow_eq_qPowerRegion s j m

/-- Source adapter: once a concrete Kummer output is identified with a
norm-one multiple of a finite theta-pilot monoid word, its requested exact norm
formula follows with no further analytic hypothesis. -/
theorem actual_theta_kummer_norm_of_eq_unit_mul_word
    {ι : Type*} (t : TateParameter K)
    (s : Finset ι) (j m : ι → ℕ)
    (value u : K) (hu : ‖u‖ = 1)
    (hvalue : value =
      u * ∏ k ∈ s, (t.thetaPilotValue (j k)) ^ (m k)) :
    ‖value‖ = ‖(t.q : K)‖ ^
      (∑ k ∈ s, (j k) ^ 2 * m k) := by
  rw [hvalue]
  exact t.norm_unit_mul_prod_thetaPilotValue_pow s j m u hu

end TateParameter

end TateCurvesTheta
