/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import IUTThreeClosures.SL2ElementaryGeneration

/-!
# Conjugating one transvection to the opposite root subgroup

Let

`U(1) = [[1,1],[0,1]]`

and let `g = [[a,b],[c,d]]` be invertible.  The fixed line of
`g U(1) g⁻¹` is generated by the first column `(a,c)` of `g`.  If `c ≠ 0`,
then `g` moves the fixed line of `U(1)`.  Conjugating once more by
`U(-a/c)` sends this line to the second coordinate line and yields the lower
transvection

`L(-c²/det(g))`.

The parameter is nonzero.  Thus, over a prime field, irreducibility plus one
nontrivial transvection supplies both opposite elementary root subgroups:
powers of `U(1)` give every upper parameter, while powers of the resulting
nonzero lower transvection give every lower parameter.  Together with
`SL2ElementaryGeneration`, this replaces the Dickson subgroup classification
in the proposed uniform large-image proof.

This file proves the exact matrix identity.  The Galois-theoretic source still
has to provide the moving element `g` from irreducibility and identify the
Tate-inertia element with `U(1)`.
-/

namespace IUTThreeClosures

universe u

namespace SL2ElementaryGeneration
namespace Mat2

variable {F : Type u} [Field F]

/-- The adjugate-over-determinant inverse of an invertible two-by-two matrix. -/
def inv (G : Mat2 F) : Mat2 F where
  a := G.d / det G
  b := -G.b / det G
  c := -G.c / det G
  d := G.a / det G

/-- The explicit inverse is a right inverse. -/
theorem mul_inv
    (G : Mat2 F)
    (hdet : det G ≠ 0) :
    mul G (inv G) =
      { a := 1, b := 0, c := 0, d := 1 } := by
  change G.a * G.d - G.b * G.c ≠ 0 at hdet
  ext <;> simp [mul, inv, det] <;> field_simp [hdet] <;> ring

/-- The explicit inverse is a left inverse. -/
theorem inv_mul
    (G : Mat2 F)
    (hdet : det G ≠ 0) :
    mul (inv G) G =
      { a := 1, b := 0, c := 0, d := 1 } := by
  change G.a * G.d - G.b * G.c ≠ 0 at hdet
  ext <;> simp [mul, inv, det] <;> field_simp [hdet] <;> ring

/-- Conjugation of the standard upper transvection by an invertible matrix. -/
def conjugateUpper (G : Mat2 F) : Mat2 F :=
  mul (mul G (upper 1)) (inv G)

/-- Coordinate formula for the conjugated transvection. -/
theorem conjugateUpper_eq
    (G : Mat2 F)
    (hdet : det G ≠ 0) :
    conjugateUpper G =
      { a := 1 - G.a * G.c / det G
        b := G.a ^ 2 / det G
        c := -(G.c ^ 2) / det G
        d := 1 + G.a * G.c / det G } := by
  change G.a * G.d - G.b * G.c ≠ 0 at hdet
  ext <;> simp [conjugateUpper, mul, inv, upper, det] <;>
    field_simp [hdet] <;> ring

/-- Translating the moved fixed line to the second coordinate line produces a
lower transvection. -/
theorem translated_conjugateUpper_eq_lower
    (G : Mat2 F)
    (hdet : det G ≠ 0)
    (hc : G.c ≠ 0) :
    mul (mul (upper (-G.a / G.c)) (conjugateUpper G))
        (upper (G.a / G.c)) =
      lower (-(G.c ^ 2) / det G) := by
  rw [conjugateUpper_eq G hdet]
  change G.a * G.d - G.b * G.c ≠ 0 at hdet
  ext <;> simp [mul, upper, lower, det] <;>
    field_simp [hdet, hc] <;> ring

/-- The lower-transvection parameter obtained above is nonzero. -/
theorem translated_lower_parameter_ne_zero
    (G : Mat2 F)
    (hdet : det G ≠ 0)
    (hc : G.c ≠ 0) :
    -(G.c ^ 2) / det G ≠ 0 := by
  exact div_ne_zero (neg_ne_zero.mpr (pow_ne_zero 2 hc)) hdet

/-- Packaged matrix conclusion: an invertible element moving the first
coordinate line conjugates the standard upper transvection, after an upper
translation, to a nontrivial lower transvection. -/
theorem exists_nontrivial_lower_from_moving_conjugate
    (G : Mat2 F)
    (hdet : det G ≠ 0)
    (hc : G.c ≠ 0) :
    ∃ t : F, t ≠ 0 ∧
      mul (mul (upper (-G.a / G.c)) (conjugateUpper G))
          (upper (G.a / G.c)) = lower t := by
  refine ⟨-(G.c ^ 2) / det G,
    translated_lower_parameter_ne_zero G hdet hc, ?_⟩
  exact translated_conjugateUpper_eq_lower G hdet hc

end Mat2
end SL2ElementaryGeneration

end IUTThreeClosures
