/-
Copyright (c) 2026 ChatGPT. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ChatGPT
-/
import Mathlib

/-!
# Possible images generated by upper semi-compatible Ind3 steps

IUT III does not classify every Ind3 possible image as one exact `q`-power
word.  The source statement is upper semi-compatible: after the Ind1 and Ind2
isomorphism ambiguities, an Ind3 step may move from one region to any region
related to it by the log-link inclusion relation.

This module formalizes that logical shape directly.  Possible-image regions
are generated inductively from ordinary branches, deterministic Ind1/Ind2
region transformations, and a genuinely relational Ind3 step.  If ordinary
branches lie in an explicit envelope, Ind1 and Ind2 preserve that envelope,
and every Ind3-related target remains in the envelope, then every possible
image lies in the envelope.  The native ordinary branch is automatically in
the possible-image union.

Thus the two source relations needed by the honest IUT III--IV bridge are
proved without replacing upper semi-compatibility by a stronger and generally
false exact-trace classification.
-/

namespace IUTThreeClosures

universe u v w x y

/-- Regions reachable from ordinary branches by Ind1, Ind2 and relational
Ind3 operations. -/
inductive UpperSemicompatibleReachable
    {α : Type y}
    {Ordinary : Type u} {Ind1 : Type v} {Ind2 : Type w} {Ind3 : Type x}
    (ordinaryRegion : Ordinary → Set α)
    (act1 : Ind1 → Set α → Set α)
    (act2 : Ind2 → Set α → Set α)
    (step3 : Ind3 → Set α → Set α → Prop) :
    Set α → Prop
  | ordinary (o : Ordinary) :
      UpperSemicompatibleReachable ordinaryRegion act1 act2 step3
        (ordinaryRegion o)
  | ind1 (a : Ind1) {U : Set α}
      (hU : UpperSemicompatibleReachable ordinaryRegion act1 act2 step3 U) :
      UpperSemicompatibleReachable ordinaryRegion act1 act2 step3
        (act1 a U)
  | ind2 (a : Ind2) {U : Set α}
      (hU : UpperSemicompatibleReachable ordinaryRegion act1 act2 step3 U) :
      UpperSemicompatibleReachable ordinaryRegion act1 act2 step3
        (act2 a U)
  | ind3 (a : Ind3) {U V : Set α}
      (hU : UpperSemicompatibleReachable ordinaryRegion act1 act2 step3 U)
      (hUV : step3 a U V) :
      UpperSemicompatibleReachable ordinaryRegion act1 act2 step3 V

/-- A source presentation matching the upper-semicompatible form of IUT III,
Theorem 3.11. -/
structure UpperSemicompatiblePossibleImageSystem (α : Type y) :
    Type (max (u + 1) (v + 1) (w + 1) (x + 1) (y + 1)) where
  Ordinary : Type u
  Ind1 : Type v
  Ind2 : Type w
  Ind3 : Type x
  ordinaryRegion : Ordinary → Set α
  act1 : Ind1 → Set α → Set α
  act2 : Ind2 → Set α → Set α
  /-- The multivalued/log-link Ind3 relation. -/
  step3 : Ind3 → Set α → Set α → Prop
  native : Ordinary
  envelope : Set α
  ordinary_le_envelope : ∀ o, ordinaryRegion o ⊆ envelope
  ind1_preserves_envelope :
    ∀ a U, U ⊆ envelope → act1 a U ⊆ envelope
  ind2_preserves_envelope :
    ∀ a U, U ⊆ envelope → act2 a U ⊆ envelope
  ind3_preserves_envelope :
    ∀ a U V, U ⊆ envelope → step3 a U V → V ⊆ envelope

namespace UpperSemicompatiblePossibleImageSystem

variable {α : Type y}

/-- Reachability predicate determined by a source presentation. -/
abbrev Reachable
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α)
    (U : Set α) : Prop :=
  UpperSemicompatibleReachable S.ordinaryRegion S.act1 S.act2 S.step3 U

/-- Actual possible images are the reachable regions themselves. -/
abbrev Output
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α) :=
  {U : Set α // S.Reachable U}

/-- Region represented by one possible image. -/
def realization
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α)
    (o : S.Output) : Set α :=
  o.1

/-- Literal union of all source-generated possible-image regions. -/
def possibleUnion
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α) : Set α :=
  ⋃ o : S.Output, S.realization o

/-- Distinguished native q-pilot region. -/
def nativeRegion
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α) : Set α :=
  S.ordinaryRegion S.native

/-- Every reachable region remains in the explicit multiradial envelope. -/
theorem reachable_le_envelope
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α)
    {U : Set α} (hU : S.Reachable U) :
    U ⊆ S.envelope := by
  induction hU with
  | ordinary o =>
      exact S.ordinary_le_envelope o
  | ind1 a hU ih =>
      exact S.ind1_preserves_envelope a _ ih
  | ind2 a hU ih =>
      exact S.ind2_preserves_envelope a _ ih
  | ind3 a hU hUV ih =>
      exact S.ind3_preserves_envelope a _ _ ih hUV

/-- The native q-pilot branch belongs to the genuine possible-image union. -/
theorem actualNativeImage
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α) :
    S.nativeRegion ⊆ S.possibleUnion := by
  intro z hz
  let o : S.Output :=
    ⟨S.nativeRegion, UpperSemicompatibleReachable.ordinary S.native⟩
  exact Set.mem_iUnion.mpr ⟨o, hz⟩

/-- Every genuine upper-semicompatible possible image is contained in the
explicit multiradial envelope. -/
theorem realization_le_envelope
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α)
    (o : S.Output) :
    S.realization o ⊆ S.envelope :=
  S.reachable_le_envelope o.2

/-- The complete possible-image union is contained in the explicit envelope. -/
theorem actualPossibleImageEnvelope
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α) :
    S.possibleUnion ⊆ S.envelope := by
  intro z hz
  rcases Set.mem_iUnion.mp hz with ⟨o, hzo⟩
  exact S.realization_le_envelope o hzo

/-- The two source relations packaged together. -/
theorem sourceRelations
    (S : UpperSemicompatiblePossibleImageSystem.{u, v, w, x, y} α) :
    S.nativeRegion ⊆ S.possibleUnion ∧
      S.possibleUnion ⊆ S.envelope :=
  ⟨S.actualNativeImage, S.actualPossibleImageEnvelope⟩

end UpperSemicompatiblePossibleImageSystem

end IUTThreeClosures
