import IUTThreeClosures.ActualPilotWitness
import IUTThreeClosures.GeneratedSource
import IUTThreeClosures.PublicLogVolumeInconsistency
import IUTThreeClosures.HonestFinitePositiveLogVolume
import IUTThreeClosures.FiniteProductLogVolume
import IUTThreeClosures.PublicThetaHullComponentFormula
import IUTThreeClosures.PublicThetaHullUpperBound
import IUTThreeClosures.PublicIUTIVTheorem110
import IUTThreeClosures.HonestPilotWitness
import IUTThreeClosures.HonestGeneratedSource
import IUTThreeClosures.HonestContainerSource
import IUTThreeClosures.QuantifierCorrectClosure
import IUTThreeClosures.ABCStatement
import IUTThreeClosures.ABCClosure
import IUTThreeClosures.ThreeClosureTheorems
import IUTThreeClosures.InhabitationBoundary
import IUTThreeClosures.CircularityAudit
import IUTThreeClosures.NonCircularDownstream
import IUTThreeClosures.FullPolyCore
import IUTThreeClosures.WeakCompatibilityCountermodel
import IUTThreeClosures.FourOpenConstructions
import IUTThreeClosures.PublicProgramUninhabited
import IUTThreeClosures.BridgeInhabitationAudit
import IUTThreeClosures.BridgeInhabitationExact
import IUTThreeClosures.GeneratedOutputHullEnvelope

-- Canonical, source-derived replacement for the freely populated bridge.
import IUTThreeClosures.CanonicalQPilotCorridor
import IUTThreeClosures.CanonicalCorridorAudit
import IUTThreeClosures.SourceDerivedIUTIVBridge
import IUTThreeClosures.FreyCalibratedIUTIVBridge
import IUTThreeClosures.FreyConductorCalibratedIUTIVBridge
import IUTThreeClosures.PublicFreyComponentBridge
import IUTThreeClosures.PublicFreyTheorem110Bridge
import IUTThreeClosures.GlobalQPilotReconstruction
import IUTThreeClosures.CompleteGlobalJPacket
import IUTThreeClosures.TateLocalQJContribution
import IUTThreeClosures.SelectedBadPlaceGlobalReconstruction

-- Arithmetic input route: point-dependent Legendre and integral Frey curves,
-- their exact rational Weil heights and conductor arithmetic, an explicit
-- fixed comparison curve, a nonintegral shifted-j family, and preservation of
-- perfect mod-ell image after solvable base change.
import IUTThreeClosures.ABCPointLegendreCurve
import IUTThreeClosures.LegendreArithmetic
import IUTThreeClosures.ABCFreyCurve
import IUTThreeClosures.TripodWeilHeight
import IUTThreeClosures.LegendreHeightCorridor
import IUTThreeClosures.FreyJReducedData
import IUTThreeClosures.FreyJHeightCorridor
import IUTThreeClosures.FreyDiscriminantConductor
import IUTThreeClosures.ShiftedJAdmissibleCurve
import IUTThreeClosures.ExplicitSemistableCurve
import IUTThreeClosures.SolvableRestrictionImage
import IUTThreeClosures.ZModSL2Perfect

import IUTThreeClosures.QPilotNormalizationAudit
import IUTThreeClosures.QPilotNormalizationFork
import IUTThreeClosures.RootQPilotDivisor
import IUTThreeClosures.ExactRootNormalization
import IUTThreeClosures.FinitePositiveLogVolumeMonotonicity
import IUTThreeClosures.RamificationCorrectedQPilot
import IUTThreeClosures.RamificationWeightCancellation
import IUTThreeClosures.ProductWeightMarginalization
import IUTThreeClosures.CanonicalLocalDegreeWeights
import IUTThreeClosures.DifferentSupportAbsorption
import IUTThreeClosures.FiniteIndexHaarCorrection
import IUTThreeClosures.PrimePowerQPilotRegion
import IUTThreeClosures.DistinguishedLabelQPilot
import IUTThreeClosures.NativeQPilotCalibration
import IUTThreeClosures.GeneratedUnionCompactness
import IUTThreeClosures.AdmissiblePrimeSelection
import IUTThreeClosures.FiniteExceptionalSet
import IUTThreeClosures.StatementIIOutsideFinite
import IUTThreeClosures.TateParameterUnitBallRegion
import IUTThreeClosures.TateParameterPowerRegions
import IUTThreeClosures.ActualHodgeTheaterOutput
import IUTThreeClosures.FiniteExponentHull
import IUTThreeClosures.StandardZeroLabel
import IUTThreeClosures.BarycentricPacketReading
import IUTThreeClosures.ZeroLabelBarycentric
import IUTThreeClosures.DiagonalPacketNoGo
import IUTThreeClosures.Cor312CoefficientAlgebra
import IUTThreeClosures.IUTIVAbsorption
import IUTThreeClosures.PublicNormalizationObstruction
import IUTThreeClosures.CorrectedQPilotDivisor
