import IUTThreeClosures.ActualPilotWitness
import IUTThreeClosures.GeneratedSource
import IUTThreeClosures.QuantifierCorrectClosure
import IUTThreeClosures.ABCStatement
import IUTThreeClosures.ABCClosure
import IUTThreeClosures.ThreeClosureTheorems
import IUTThreeClosures.InhabitationBoundary
import IUTThreeClosures.CircularityAudit
import IUTThreeClosures.NonCircularDownstream
import IUTThreeClosures.FullPolyCore
import IUTThreeClosures.WeakCompatibilityCountermodel
import IUTThreeClosures.FourOpenConstructions
import IUTThreeClosures.BridgeInhabitationAudit
import IUTThreeClosures.BridgeInhabitationExact

-- Canonical, source-derived replacement for the freely populated bridge.
import IUTThreeClosures.CanonicalQPilotCorridor
import IUTThreeClosures.CanonicalCorridorAudit
import IUTThreeClosures.SourceDerivedIUTIVBridge

-- Arithmetic input route: point-dependent Legendre curves, an explicit fixed
-- comparison curve, and preservation of perfect mod-ℓ image after solvable
-- auxiliary base change.
import IUTThreeClosures.ABCPointLegendreCurve
import IUTThreeClosures.ExplicitSemistableCurve
import IUTThreeClosures.SolvableRestrictionImage
import IUTThreeClosures.ZModSL2Perfect

import IUTThreeClosures.QPilotNormalizationAudit
import IUTThreeClosures.QPilotNormalizationFork
import IUTThreeClosures.RootQPilotDivisor
import IUTThreeClosures.FinitePositiveLogVolumeMonotonicity
import IUTThreeClosures.RamificationCorrectedQPilot
import IUTThreeClosures.ProductWeightMarginalization
import IUTThreeClosures.PrimePowerQPilotRegion
import IUTThreeClosures.DistinguishedLabelQPilot
import IUTThreeClosures.NativeQPilotCalibration
import IUTThreeClosures.GeneratedUnionCompactness
import IUTThreeClosures.AdmissiblePrimeSelection
import IUTThreeClosures.FiniteExceptionalSet
import IUTThreeClosures.StatementIIOutsideFinite
import IUTThreeClosures.TateParameterUnitBallRegion
import IUTThreeClosures.FiniteExponentHull
import IUTThreeClosures.StandardZeroLabel
import IUTThreeClosures.BarycentricPacketReading
import IUTThreeClosures.ZeroLabelBarycentric
import IUTThreeClosures.DiagonalPacketNoGo
import IUTThreeClosures.Cor312CoefficientAlgebra
import IUTThreeClosures.IUTIVAbsorption
import IUTThreeClosures.PublicNormalizationObstruction
import IUTThreeClosures.CorrectedQPilotDivisor